/**
 * The control plane. Blueprint, "Subsystem three": customers, licences,
 * usage counts — never customer content. This binding is intentionally
 * named CONTROL_DB rather than DB, so a reviewer scanning for the
 * `no-restricted-properties` lint rule's banned names doesn't mistake
 * this Worker for one that needs the resolveTenant discipline — it has
 * no tenant to resolve. There is exactly one of this Worker, not one
 * per customer.
 *
 * Customers, licences and the signed token are implemented here.
 * Idempotent usage-period ingestion and the payment webhook — Blueprint
 * build order: "Payments last — the webhook is the easy part" — remain
 * a later build step.
 */

import { handleCreateCustomer } from "./customers-route.js";
import { handleUpsertLicence } from "./licences-route.js";
import { handleIssueToken } from "./token-route.js";

export interface Env {
  CONTROL_DB?: D1Database;
  /**
   * A JWK-format ECDSA P-256 private key, as JSON. Set via
   * `wrangler secret put LICENCE_SIGNING_PRIVATE_KEY`, generated by
   * scripts/generate-licence-keypair.mjs — never committed, never
   * passed as a plain CLI argument (the script prints it for piping
   * into `wrangler secret put`, which reads from stdin).
   */
  LICENCE_SIGNING_PRIVATE_KEY?: string;
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function parsePrivateKey(env: Env): { ok: true; key: JsonWebKey } | { ok: false; response: Response } {
  if (!env.LICENCE_SIGNING_PRIVATE_KEY) {
    return { ok: false, response: json({ error: "LICENCE_SIGNING_PRIVATE_KEY not configured" }, 500) };
  }
  try {
    return { ok: true, key: JSON.parse(env.LICENCE_SIGNING_PRIVATE_KEY) as JsonWebKey };
  } catch {
    return {
      ok: false,
      response: json({ error: "LICENCE_SIGNING_PRIVATE_KEY is not valid JSON" }, 500),
    };
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      if (!env.CONTROL_DB) {
        return json({ status: "error", detail: "CONTROL_DB binding missing" }, 500);
      }
      // Confirms the binding is live, not just declared.
      await env.CONTROL_DB.prepare("SELECT 1").first();
      return json({ status: "ok" });
    }

    if (!env.CONTROL_DB) {
      return json({ error: "CONTROL_DB binding not configured" }, 500);
    }

    if (url.pathname === "/customers" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleCreateCustomer(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (url.pathname === "/licences" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleUpsertLicence(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    const tokenMatch = url.pathname.match(/^\/licences\/([^/]+)\/token$/);
    if (tokenMatch && request.method === "GET") {
      const keyResult = parsePrivateKey(env);
      if (!keyResult.ok) return keyResult.response;
      const result = await handleIssueToken(env.CONTROL_DB, keyResult.key, tokenMatch[1]);
      return json(result.body, result.status);
    }

    return json({ error: "not found" }, 404);
  },
};
