/**
 * The control plane. Blueprint, "Subsystem three": customers, licences,
 * usage counts — never customer content. This binding is intentionally
 * named CONTROL_DB rather than DB, so a reviewer scanning for the
 * `no-restricted-properties` lint rule's banned names doesn't mistake
 * this Worker for one that needs the resolveTenant discipline — it has
 * no tenant to resolve. There is exactly one of this Worker, not one
 * per customer.
 *
 * Customers, licences and the signed token are implemented here.
 * Idempotent usage-period ingestion (see usage-route.ts) is also
 * implemented — the payment webhook alone remains a later build step,
 * per the Blueprint's own build order: "Payments last — the webhook is
 * the easy part."
 */

import { handleCreateCustomer } from "./customers-route.js";
import { handleUpsertLicence } from "./licences-route.js";
import { handleIssueToken } from "./token-route.js";
import { handleReportUsage } from "./usage-route.js";
import { handleRotateKey } from "./rotate-key-route.js";
import { handleListCustomers, handleSetFleetMetadata } from "./fleet-route.js";
import { extractBearerToken, isValidAdminKey, isValidCustomerKey } from "./auth.js";

export interface Env {
  CONTROL_DB?: D1Database;
  /**
   * A JWK-format ECDSA P-256 private key, as JSON. Set via
   * `wrangler secret put LICENCE_SIGNING_PRIVATE_KEY`, generated by
   * scripts/generate-licence-keypair.mjs — never committed, never
   * passed as a plain CLI argument (the script prints it for piping
   * into `wrangler secret put`, which reads from stdin).
   */
  LICENCE_SIGNING_PRIVATE_KEY?: string;
  /**
   * A single shared secret protecting provisioning (POST /customers,
   * POST /licences, key rotation). Set via
   * `wrangler secret put ADMIN_API_KEY`, generated by
   * scripts/generate-admin-key.mjs — same never-committed,
   * never-a-CLI-argument discipline as the signing key. See
   * docs/decisions/0006-endpoint-authentication.md.
   */
  ADMIN_API_KEY?: string;
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function parsePrivateKey(env: Env): { ok: true; key: JsonWebKey } | { ok: false; response: Response } {
  if (!env.LICENCE_SIGNING_PRIVATE_KEY) {
    return { ok: false, response: json({ error: "LICENCE_SIGNING_PRIVATE_KEY not configured" }, 500) };
  }
  try {
    return { ok: true, key: JSON.parse(env.LICENCE_SIGNING_PRIVATE_KEY) as JsonWebKey };
  } catch {
    return {
      ok: false,
      response: json({ error: "LICENCE_SIGNING_PRIVATE_KEY is not valid JSON" }, 500),
    };
  }
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      if (!env.CONTROL_DB) {
        return json({ status: "error", detail: "CONTROL_DB binding missing" }, 500);
      }
      // Confirms the binding is live, not just declared.
      await env.CONTROL_DB.prepare("SELECT 1").first();
      return json({ status: "ok" });
    }

    if (!env.CONTROL_DB) {
      return json({ error: "CONTROL_DB binding not configured" }, 500);
    }

    // Admin-only routes: provisioning, key management, and the fleet
    // manifest (Blueprint build order step 5 — see
    // docs/decisions/0011-fleet-tooling.md). A single shared secret,
    // not per-customer — see Env.ADMIN_API_KEY's own comment and
    // docs/decisions/0006-endpoint-authentication.md. The fleet
    // manifest is admin-only for the same reason provisioning is: it
    // is cross-customer administrative data, not something any single
    // customer's own credential should be able to read or change.
    const rotateMatch = url.pathname.match(/^\/customers\/([^/]+)\/rotate-key$/);
    const fleetMetadataMatch = url.pathname.match(/^\/customers\/([^/]+)\/fleet-metadata$/);
    const isAdminRoute =
      (url.pathname === "/customers" && (request.method === "POST" || request.method === "GET")) ||
      (url.pathname === "/licences" && request.method === "POST") ||
      (rotateMatch !== null && request.method === "POST") ||
      (fleetMetadataMatch !== null && request.method === "PATCH");
    if (isAdminRoute) {
      const providedKey = extractBearerToken(request);
      if (!isValidAdminKey(providedKey, env.ADMIN_API_KEY)) {
        return json({ error: "unauthorized" }, 401);
      }
    }

    if (url.pathname === "/customers" && request.method === "GET") {
      const result = await handleListCustomers(env.CONTROL_DB);
      return json(result.body, result.status);
    }

    if (url.pathname === "/customers" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleCreateCustomer(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (fleetMetadataMatch && request.method === "PATCH") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleSetFleetMetadata(
        env.CONTROL_DB,
        fleetMetadataMatch[1],
        (body ?? {}) as Record<string, unknown>
      );
      return json(result.body, result.status);
    }

    if (url.pathname === "/licences" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleUpsertLicence(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (rotateMatch && request.method === "POST") {
      const result = await handleRotateKey(env.CONTROL_DB, rotateMatch[1]);
      return json(result.body, result.status);
    }

    // Per-customer routes: the machine-to-machine calls each
    // customer's own vf-app instance makes. Authenticated against that
    // specific customer's key, not the admin secret — a customer's
    // instance must never be able to act as, or be authenticated by,
    // credentials belonging to a different customer or to the admin.
    const tokenMatch = url.pathname.match(/^\/licences\/([^/]+)\/token$/);
    if (tokenMatch && request.method === "GET") {
      const customerId = tokenMatch[1];
      const providedKey = extractBearerToken(request);
      if (!(await isValidCustomerKey(env.CONTROL_DB, customerId, providedKey))) {
        return json({ error: "unauthorized" }, 401);
      }
      const keyResult = parsePrivateKey(env);
      if (!keyResult.ok) return keyResult.response;
      const result = await handleIssueToken(env.CONTROL_DB, keyResult.key, customerId);
      return json(result.body, result.status);
    }

    if (url.pathname === "/usage" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const parsedBody = (body ?? {}) as Record<string, unknown>;
      const customerId = typeof parsedBody.customerId === "string" ? parsedBody.customerId : null;
      const providedKey = extractBearerToken(request);
      if (!customerId || !(await isValidCustomerKey(env.CONTROL_DB, customerId, providedKey))) {
        return json({ error: "unauthorized" }, 401);
      }
      const result = await handleReportUsage(env.CONTROL_DB, parsedBody);
      return json(result.body, result.status);
    }

    return json({ error: "not found" }, 404);
  },
};
