/**
 * The control plane. Blueprint, "Subsystem three": customers, licences,
 * usage counts — never customer content. This binding is intentionally
 * named CONTROL_DB rather than DB, so a reviewer scanning for the
 * `no-restricted-properties` lint rule's banned names doesn't mistake
 * this Worker for one that needs the resolveTenant discipline — it has
 * no tenant to resolve. There is exactly one of this Worker, not one
 * per customer.
 *
 * Customers, licences and the signed token are implemented here.
 * Idempotent usage-period ingestion (see usage-route.ts) is also
 * implemented — the payment webhook alone remains a later build step,
 * per the Blueprint's own build order: "Payments last — the webhook is
 * the easy part."
 */

import { handleCreateCustomer } from "./customers-route.js";
import { handleCreateEnvironment, handleDeleteEnvironment } from "./environment-route.js";
import { handleDevLogin } from "./dev-login-route.js";
import { handleLogin, handleListMyEnvironments, setCredential } from "./login-route.js";
import { grantAccess, revokeAccess } from "./credentials.js";
import { setBranding, handleBrandingStylesheet } from "./branding.js";
import {
  handleUiStrings,
  handleSetUiString,
  handleListUiStrings,
  handleBulkUiStrings,
} from "./ui-strings.js";
import { handleUpsertLicence } from "./licences-route.js";
import { handleIssueToken } from "./token-route.js";
import { handleReportUsage } from "./usage-route.js";
import { handleRotateKey } from "./rotate-key-route.js";
import { handleListEnvironments, handleSetFleetMetadata } from "./fleet-route.js";
import {
  handleSubmitSignupRequest,
  handleListSignupRequests,
  handleApproveSignupRequest,
  handleRejectSignupRequest,
  handleRecordProvisioning,
} from "./signup-route.js";
import { handleProvisionTrial, expireOverdueLicences, warnExpiringLicences , handleEnvironmentConfig } from "./provision-route.js";
import { recordAdminAction, handleListAdminActions } from "./admin-audit.js";
import { extractBearerToken, isValidAdminKey, isValidEnvironmentKey } from "./auth.js";
import { handlePreflight, withCors } from "@vibefinance/shared";

export interface Env {
  /**
   * Which web origins may read this Worker's responses (decision
   * 0098). Unset means none, which is how it behaved before this
   * existed — CORS is a browser mechanism, so no page can read a
   * response and every curl is unaffected.
   */
  ALLOWED_ORIGINS?: string;

  CONTROL_DB?: D1Database;
  /**
   * A JWK-format ECDSA P-256 private key, as JSON. Set via
   * `wrangler secret put LICENCE_SIGNING_PRIVATE_KEY`, generated by
   * scripts/generate-licence-keypair.mjs — never committed, never
   * passed as a plain CLI argument (the script prints it for piping
   * into `wrangler secret put`, which reads from stdin).
   */
  LICENCE_SIGNING_PRIVATE_KEY?: string;
  /**
   * Enables the development login stub (decision 0087). Absent means
   * the route does not exist. Never set in production — and the stub
   * refuses to mint a production token even if it is, because a flag
   * somebody forgot is exactly the failure this guards against.
   */
  ALLOW_DEV_LOGIN?: string;
  /**
   * A single shared secret protecting provisioning (POST /customers,
   * POST /licences, key rotation). Set via
   * `wrangler secret put ADMIN_API_KEY`, generated by
   * scripts/generate-admin-key.mjs — same never-committed,
   * never-a-CLI-argument discipline as the signing key. See
   * docs/decisions/0006-endpoint-authentication.md.
   */
  ADMIN_API_KEY?: string;
}

function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "content-type": "application/json" },
  });
}

function parsePrivateKey(env: Env): { ok: true; key: JsonWebKey } | { ok: false; response: Response } {
  if (!env.LICENCE_SIGNING_PRIVATE_KEY) {
    return { ok: false, response: json({ error: "LICENCE_SIGNING_PRIVATE_KEY not configured" }, 500) };
  }
  try {
    return { ok: true, key: JSON.parse(env.LICENCE_SIGNING_PRIVATE_KEY) as JsonWebKey };
  } catch {
    return {
      ok: false,
      response: json({ error: "LICENCE_SIGNING_PRIVATE_KEY is not valid JSON" }, 500),
    };
  }
}

/**
 * Which requests are privileged — decision 0140.
 *
 * **Extracted so the gate and the audit ask the same question.** They
 * were one expression inside the router; the audit needed it too, and a
 * second copy is a second thing to keep in step — the divergence this
 * project finds most often.
 */
export function isPrivileged(method: string, pathname: string): boolean {
  const matches = (pattern: RegExp) => pattern.test(pathname);

  return (
    (pathname === "/customers" && method === "POST") ||
    (pathname === "/environments" && (method === "POST" || method === "GET")) ||
    (pathname === "/licences" && method === "POST") ||
    (pathname === "/credentials" && method === "POST") ||
    (pathname.startsWith("/branding/") && method === "PUT") ||
    (pathname === "/ui-strings" && (method === "PUT" || method === "POST")) ||
    (pathname === "/ui-strings/keys" && method === "GET") ||
    // The manifest names every binding a customer's Worker runs with
    // (decision 0136), so reading it is the operator's alone.
    (matches(/^\/environments\/[^/]+\/config$/) && method === "GET") ||
    (pathname === "/access" && (method === "POST" || method === "DELETE")) ||
    (pathname === "/signup-requests" && method === "GET") ||
    (matches(/^\/signup-requests\/[^/]+\/approve$/) && method === "POST") ||
    (matches(/^\/signup-requests\/[^/]+\/reject$/) && method === "POST") ||
    (matches(/^\/signup-requests\/[^/]+\/provisioned$/) && method === "POST") ||
    (matches(/^\/signup-requests\/[^/]+\/provision$/) && method === "POST") ||
    (matches(/^\/environments\/[^/]+\/rotate-key$/) && method === "POST") ||
    (matches(/^\/environments\/[^/]+$/) && method === "DELETE") ||
    (matches(/^\/environments\/[^/]+\/fleet-metadata$/) && method === "PATCH") ||
    // The log itself. Reading who did what is a privileged act.
    (pathname === "/admin-actions" && method === "GET")
  );
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Answered before anything else: a preflight carries no credentials
    // and asks only whether the real request would be permitted.
    const preflight = handlePreflight(request, env.ALLOWED_ORIGINS);
    if (preflight) return preflight;

    // Applied at the edge to whatever the router produced, so no
    // individual route has to remember. A route that forgot would work
    // from curl and fail from a browser — the kind of divergence this
    // project keeps finding.
    const response = await this._routed(request, env);

    /**
     * Every privileged action, recorded — decision 0140.
     *
     * **At the edge, so no individual route has to remember.** Seven
     * route groups are admin-gated and two recorded who acted; a
     * convention asking each to log itself would have the same shape,
     * and the eighth would be the one that forgot.
     *
     * The gate already computes which requests are privileged, so this
     * asks the same question rather than a second one that could
     * disagree with it.
     */
    if (env.CONTROL_DB && isPrivileged(request.method, new URL(request.url).pathname)) {
      /**
       * A refusal's reason is read from a **clone**, because reading a
       * response body consumes it and the caller still needs theirs.
       *
       * Only refusals: a successful body may carry a freshly minted API
       * key (decision 0006) or a credential, and decision 0009 is this
       * project's own record of key material reaching somewhere nobody
       * expected. A log is exactly such a place.
       */
      const body =
        response.status >= 400
          ? ((await response.clone().json().catch(() => ({}))) as Record<string, unknown>)
          : {};

      await recordAdminAction(
        env.CONTROL_DB,
        request,
        `${request.method} ${new URL(request.url).pathname}`,
        { status: response.status, body }
      );
    }

    return withCors(response, request, env.ALLOWED_ORIGINS);
  },

  async _routed(request: Request, env: Env): Promise<Response> {
    const url = new URL(request.url);

    if (url.pathname === "/health") {
      if (!env.CONTROL_DB) {
        return json({ status: "error", detail: "CONTROL_DB binding missing" }, 500);
      }
      // Confirms the binding is live, not just declared.
      await env.CONTROL_DB.prepare("SELECT 1").first();
      return json({ status: "ok" });
    }

    if (!env.CONTROL_DB) {
      return json({ error: "CONTROL_DB binding not configured" }, 500);
    }

    // The one deliberately unauthenticated write endpoint on this
    // Worker — decision 0038. A prospective customer filling in the
    // website's trial-request form has no credential yet, by
    // definition. Placed before the admin gate below for exactly that
    // reason. Nothing is provisioned and nothing is promised: a real
    // person reviews every request.
    if (url.pathname === "/signup-requests" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleSubmitSignupRequest(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    // Admin-only routes: provisioning, key management, and the fleet
    // manifest (Blueprint build order step 5 — see
    // docs/decisions/0011-fleet-tooling.md). A single shared secret,
    // not per-environment — see Env.ADMIN_API_KEY's own comment and
    // docs/decisions/0006-endpoint-authentication.md. The fleet
    // manifest is admin-only for the same reason provisioning is: it
    // is cross-customer administrative data, not something any single
    // environment's own credential should be able to read or change.
    // The stylesheet the shared UI fetches. **Unauthenticated**,
    // because the login screen needs a livery before anybody has signed
    // in — and it discloses four colours and a name, which a customer
    // puts on their letterhead anyway.
    const brandingCssMatch = url.pathname.match(/^\/branding\/([^/]+)\/tokens\.css$/);
    if (brandingCssMatch && request.method === "GET") {
      return handleBrandingStylesheet(env.CONTROL_DB, decodeURIComponent(brandingCssMatch[1]));
    }
    // The interface's words — decision 0107. Unauthenticated for the
    // same reason branding is: the login screen needs them before
    // anybody has signed in, and they are the words on a public login
    // page.
    if (url.pathname === "/ui-strings" && request.method === "GET") {
      return handleUiStrings(
        env.CONTROL_DB,
        url.searchParams.get("locale") ?? request.headers.get("Accept-Language")
      );
    }

    if (url.pathname === "/branding/tokens.css" && request.method === "GET") {
      // No customer named yet — the very first paint of a login screen.
      return handleBrandingStylesheet(env.CONTROL_DB, null);
    }

    // **Setting** branding is admin-only and lives BELOW the admin gate
    // — see the provisioning surface further down. It was first written
    // here beside its GET, which returned before `isAdminRoute` was
    // even computed, so the admin entry was dead code and anybody could
    // rebrand any customer. Reading is public; writing is not, and the
    // two therefore cannot sit together.

    // Signing in, and asking which instances you may reach. Neither is
    // an admin route: they are what a person does BEFORE holding any
    // credential, so this is deliberately not an admin route. Its
    // protection is the two guards inside it, not a key.
    if ((url.pathname === "/login" || url.pathname === "/my-environments") && request.method === "POST") {
      if (!env.LICENCE_SIGNING_PRIVATE_KEY) {
        return json({ error: "LICENCE_SIGNING_PRIVATE_KEY not configured" }, 500);
      }
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result =
        url.pathname === "/login"
          ? await handleLogin(
              env.CONTROL_DB,
              (body ?? {}) as Record<string, unknown>,
              JSON.parse(env.LICENCE_SIGNING_PRIVATE_KEY) as JsonWebKey,
              request.headers.get("CF-Connecting-IP")
            )
          : await handleListMyEnvironments(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (url.pathname === "/dev-login" && request.method === "POST") {
      if (!env.LICENCE_SIGNING_PRIVATE_KEY) {
        return json({ error: "LICENCE_SIGNING_PRIVATE_KEY not configured" }, 500);
      }
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleDevLogin(
        env.CONTROL_DB,
        (body ?? {}) as Record<string, unknown>,
        JSON.parse(env.LICENCE_SIGNING_PRIVATE_KEY) as JsonWebKey,
        { allowDevLogin: env.ALLOW_DEV_LOGIN === "true" }
      );
      return json(result.body, result.status);
    }

    const rotateMatch = url.pathname.match(/^\/environments\/([^/]+)\/rotate-key$/);
    // Deleting an environment created in error — decision 0085. Admin
    // only, for the same reason creating one is: it is cross-customer
    // administrative data, not something an environment's own
    // credential should be able to remove.
    const deleteEnvMatch = url.pathname.match(/^\/environments\/([^/]+)$/);
    const fleetMetadataMatch = url.pathname.match(/^\/environments\/([^/]+)\/fleet-metadata$/);
    const approveMatch = url.pathname.match(/^\/signup-requests\/([^/]+)\/approve$/);
    const rejectMatch = url.pathname.match(/^\/signup-requests\/([^/]+)\/reject$/);
    const provisionedMatch = url.pathname.match(/^\/signup-requests\/([^/]+)\/provisioned$/);
    const provisionMatch = url.pathname.match(/^\/signup-requests\/([^/]+)\/provision$/);
    const isAdminRoute = isPrivileged(request.method, url.pathname);
    if (isAdminRoute) {
      const providedKey = extractBearerToken(request);
      if (!isValidAdminKey(providedKey, env.ADMIN_API_KEY)) {
        return json({ error: "unauthorized" }, 401);
      }
    }

    // The operator's own review queue, and the decisions taken from
    // it. Approval deliberately does not provision — see
    // signup-route.ts's own comment and decision 0038.
    if (url.pathname === "/signup-requests" && request.method === "GET") {
      const result = await handleListSignupRequests(env.CONTROL_DB, url.searchParams.get("status"));
      return json(result.body, result.status);
    }

    if (approveMatch && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleApproveSignupRequest(env.CONTROL_DB, approveMatch[1], (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (rejectMatch && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleRejectSignupRequest(env.CONTROL_DB, rejectMatch[1], (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    // Control-plane provisioning (decision 0039) — creates the
    // customer, sandbox environment and 30-day trial licence for an
    // approved request. Deliberately does NOT create the real
    // Cloudflare D1 database, R2 bucket or Worker; see
    // provision-route.ts's own comment.
    if (provisionMatch && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleProvisionTrial(env.CONTROL_DB, provisionMatch[1], (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (provisionedMatch && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleRecordProvisioning(env.CONTROL_DB, provisionedMatch[1], (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (url.pathname === "/environments" && request.method === "GET") {
      const result = await handleListEnvironments(env.CONTROL_DB);
      return json(result.body, result.status);
    }

    // Every key with its translations and its gaps — what a translator
    // needs, and admin only because it is the whole fleet's wording.
    // What a deploy needs, from the manifest — decision 0136.
    const configMatch = url.pathname.match(/^\/environments\/([^/]+)\/config$/);
    if (configMatch && request.method === "GET") {
      const result = await handleEnvironmentConfig(env.CONTROL_DB, configMatch[1]);
      return json(result.body, result.status);
    }

    /**
     * The log — decision 0140. Privileged itself: reading who did what
     * is an operator's business alone.
     */
    if (url.pathname === "/admin-actions" && request.method === "GET") {
      const limit = Number(url.searchParams.get("limit") ?? "100");
      const result = await handleListAdminActions(
        env.CONTROL_DB,
        Number.isFinite(limit) ? limit : 100
      );
      return json(result.body, result.status);
    }

    if (url.pathname === "/ui-strings/keys" && request.method === "GET") {
      const result = await handleListUiStrings(env.CONTROL_DB);
      return json(result.body, result.status);
    }

    // A whole language at once. Translating a PUT at a time is tedious
    // enough that nobody would, which would make the framework
    // theoretical.
    if (url.pathname === "/ui-strings" && request.method === "POST") {
      let bulkBody: unknown;
      try {
        bulkBody = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleBulkUiStrings(env.CONTROL_DB, (bulkBody ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    // Setting a word — admin only. The words on every customer's
    // screens are not one customer's to change.
    if (url.pathname === "/ui-strings" && request.method === "PUT") {
      let stringBody: unknown;
      try {
        stringBody = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleSetUiString(env.CONTROL_DB, (stringBody ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    // Setting a customer's livery — admin only (decision 0083 section
    // 3: the operator sets branding, never the customer).
    const brandingSetMatch = url.pathname.match(/^\/branding\/([^/]+)$/);
    if (brandingSetMatch && request.method === "PUT") {
      let brandingBody: unknown;
      try {
        brandingBody = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await setBranding(
        env.CONTROL_DB,
        decodeURIComponent(brandingSetMatch[1]),
        (brandingBody ?? {}) as Record<string, unknown>,
        "operator"
      );
      return json(result.body, result.status);
    }

    // The provisioning surface — admin only, for the same reason
    // creating an environment is: it decides who may reach a customer's
    // data at all.
    if (url.pathname === "/credentials" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const { email, customerId, password } = (body ?? {}) as Record<string, unknown>;
      if (typeof email !== "string" || typeof customerId !== "string" || typeof password !== "string") {
        return json({ error: "email, customerId and password are required" }, 400);
      }
      const result = await setCredential(env.CONTROL_DB, email, customerId, password);
      return json(result.body, result.status);
    }

    if (url.pathname === "/access" && (request.method === "POST" || request.method === "DELETE")) {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const { email, environmentId, grantedBy } = (body ?? {}) as Record<string, unknown>;
      if (typeof email !== "string" || typeof environmentId !== "string") {
        return json({ error: "email and environmentId are required" }, 400);
      }
      const result =
        request.method === "POST"
          ? await grantAccess(env.CONTROL_DB, email, environmentId, typeof grantedBy === "string" ? grantedBy : null)
          : await revokeAccess(env.CONTROL_DB, email, environmentId);
      return json(result.body, result.status);
    }

    if (url.pathname === "/customers" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleCreateCustomer(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (url.pathname === "/environments" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleCreateEnvironment(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (fleetMetadataMatch && request.method === "PATCH") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleSetFleetMetadata(
        env.CONTROL_DB,
        fleetMetadataMatch[1],
        (body ?? {}) as Record<string, unknown>
      );
      return json(result.body, result.status);
    }

    if (url.pathname === "/licences" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const result = await handleUpsertLicence(env.CONTROL_DB, (body ?? {}) as Record<string, unknown>);
      return json(result.body, result.status);
    }

    if (deleteEnvMatch && request.method === "DELETE") {
      const result = await handleDeleteEnvironment(env.CONTROL_DB, decodeURIComponent(deleteEnvMatch[1]));
      return json(result.body, result.status);
    }

    if (rotateMatch && request.method === "POST") {
      const result = await handleRotateKey(env.CONTROL_DB, rotateMatch[1]);
      return json(result.body, result.status);
    }

    // Per-environment routes: the machine-to-machine calls each
    // environment's own vf-app instance makes. Authenticated against
    // that specific environment's key, not the admin secret — an
    // environment's instance must never be able to act as, or be
    // authenticated by, credentials belonging to a different
    // environment (including a different environment of the same
    // customer) or to the admin.
    const tokenMatch = url.pathname.match(/^\/licences\/([^/]+)\/token$/);
    if (tokenMatch && request.method === "GET") {
      const environmentId = tokenMatch[1];
      const providedKey = extractBearerToken(request);
      if (!(await isValidEnvironmentKey(env.CONTROL_DB, environmentId, providedKey))) {
        return json({ error: "unauthorized" }, 401);
      }
      const keyResult = parsePrivateKey(env);
      if (!keyResult.ok) return keyResult.response;
      const result = await handleIssueToken(env.CONTROL_DB, keyResult.key, environmentId);
      return json(result.body, result.status);
    }

    if (url.pathname === "/usage" && request.method === "POST") {
      let body: unknown;
      try {
        body = await request.json();
      } catch {
        return json({ error: "invalid JSON body" }, 400);
      }
      const parsedBody = (body ?? {}) as Record<string, unknown>;
      const environmentId = typeof parsedBody.environmentId === "string" ? parsedBody.environmentId : null;
      const providedKey = extractBearerToken(request);
      if (!environmentId || !(await isValidEnvironmentKey(env.CONTROL_DB, environmentId, providedKey))) {
        return json({ error: "unauthorized" }, 401);
      }
      const result = await handleReportUsage(env.CONTROL_DB, parsedBody);
      return json(result.body, result.status);
    }

    return json({ error: "not found" }, 404);
  },

  /**
   * vf-licence's first scheduled handler (decision 0039). Blocks
   * every licence whose valid_to has passed — without it, an expired
   * trial keeps working indefinitely, since vf-app's licence cache
   * fails open at its last known good state (decision 0003) and a
   * licence that merely stops being renewable never actually stops
   * anything.
   *
   * Deliberately thin: all the real logic is expireOverdueLicences,
   * a plain function over the database, so it is testable without
   * simulating a scheduled event.
   */
  async scheduled(_event: ScheduledController, env: Env): Promise<void> {
    if (!env.CONTROL_DB) return;
    try {
      // Warn first, then expire — deliberately in that order. A
      // licence crossing its expiry in the same run should be
      // blocked, not warned about an expiry that has already
      // happened; warnExpiringLicences ignores anything already past
      // valid_to, and expireOverdueLicences then blocks it.
      await warnExpiringLicences(env.CONTROL_DB);
      await expireOverdueLicences(env.CONTROL_DB);
    } catch {
      // Deliberately silent, matching vf-app's own scheduled handler:
      // retried next cron cycle. An expiry sweep that fails once has
      // not let anything through permanently — the same overdue rows
      // are still overdue an hour later.
    }
  },
};
