-- 0068_purchase_order_org.sql
-- Decision 0374 — which legal entity a purchase order belongs to.
--
-- The exact question decision 0111 already answered for invoices,
-- asked again for orders: does a buyer tax reference name the org
-- explicitly, or get matched against one? Matched, for the same
-- reason — a VAT number already uniquely identifies a legal entity,
-- and asking for both would be two sources of truth that could
-- disagree. Reuses org_units.vat_id (kind = 'legal_entity'), the exact
-- column and matching discipline decision 0226 already settled for
-- invoices' own BT-48.
--
-- Unlike invoices, unmatched is not stored as a null and left for a
-- person to notice later: the operator's own words were "this should
-- always be known," since a purchase order is generated by the
-- customer's own purchasing system, about itself — not a document
-- from a third party that could genuinely misaddress it the way an
-- inbound invoice might. So a purchase order whose buyer tax reference
-- is missing or unmatched is refused at load, never stored with a
-- null org — see purchase-order-route.ts's own two new refusal
-- reasons. This column being NOT NULL is therefore the real invariant,
-- not merely nullable-for-now the way invoice_headers.org_unit_id is.
ALTER TABLE purchase_orders ADD COLUMN org_unit_id TEXT REFERENCES org_units(id);

CREATE INDEX idx_purchase_orders_org ON purchase_orders(org_unit_id);

-- Point-in-time: nothing has an org yet — every purchase order loaded
-- before this migration predates the check that would have required
-- one.
-- ASSERT: SELECT count(*) FROM purchase_orders WHERE org_unit_id IS NOT NULL == 0

-- Standing invariant: an org, if set, is a real legal entity — the
-- foreign key enforces existence; this enforces which kind.
-- ASSERT ALWAYS: SELECT count(*) FROM purchase_orders po JOIN org_units u ON u.id = po.org_unit_id WHERE u.kind != 'legal_entity' == 0
