-- 0068_dashboard_strings.sql
-- Decision 0242 — the dashboard's words.
--
-- **"On my clock", not "My items".** The card exists to say what is
-- under time pressure, and decision 0239 chose to show two clocks at
-- once because they disagree: how long I have held something is my
-- responsiveness, and `BT-9` is the supplier's expectation.
--
-- **And "Needs somebody", not "Errors".** An unplaced document and a
-- supplier awaiting the ERP are work waiting for a person, not faults —
-- decision 0231's distinction, in a heading.
INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.dashboard', 'en', 'My work'),
 ('dash.heading', 'en', 'My work'),
 ('dash.sub', 'en', 'What is waiting, and what is on the clock'),
 ('dash.waiting', 'en', 'Waiting for me'),
 ('dash.waitingsub', 'en', 'Mine, and work my teams own'),
 ('dash.acrossstages', 'en', 'across {n} stages'),
 ('dash.myclock', 'en', 'On my clock'),
 ('dash.myclocksub', 'en', 'Assigned to me or claimed by me — not a team queue'),
 ('dash.nothingmine', 'en', 'Nothing is assigned to you or claimed by you.'),
 ('dash.supplier', 'en', 'Supplier'),
 ('dash.held', 'en', 'Held'),
 ('dash.due', 'en', 'Payment due'),
 ('dash.value', 'en', 'Value'),
 ('dash.today', 'en', 'today'),
 ('dash.overdue', 'en', '{n}d overdue'),
 ('dash.duein', 'en', 'due in {n}d'),
 ('dash.sort.held', 'en', 'Longest held'),
 ('dash.sort.due', 'en', 'Soonest due'),
 ('dash.sort.value', 'en', 'Highest value'),
 ('dash.wherethings', 'en', 'Where things are'),
 ('dash.bystage', 'en', 'Count by stage'),
 ('dash.nothinginflight', 'en', 'Nothing is in progress.'),
 ('dash.astage', 'en', 'A stage'),
 ('dash.stagegone', 'en', 'This stage no longer exists. Choose another, or remove this card.'),
 ('dash.waitinghere', 'en', 'waiting here'),
 ('dash.ageing', 'en', 'How long they have waited'),
 ('dash.ageingsub', 'en', 'All open work'),
 ('dash.done', 'en', 'Done'),
 ('dash.todaylabel', 'en', 'today'),
 ('dash.weeklabel', 'en', 'this week'),
 ('dash.minelabel', 'en', 'by me this week'),
 ('dash.received', 'en', 'Received'),
 ('dash.receivedsub', 'en', 'This week, by day'),
 ('dash.nonereceived', 'en', 'Nothing has arrived this week.'),
 ('dash.exceptions', 'en', 'Exceptions by supplier'),
 ('dash.exceptionssub', 'en', 'Last 30 days'),
 ('dash.noexceptions', 'en', 'No validation failures in the last 30 days.'),
 ('dash.needssomebody', 'en', 'Needs somebody'),
 ('dash.needssomebodysub', 'en', 'Nothing else surfaces these'),
 ('dash.unplaced', 'en', 'Unplaced documents'),
 ('dash.awaitingerp', 'en', 'Suppliers awaiting the ERP'),
 ('dash.duplicates', 'en', 'Possible duplicates'),
 ('dash.allclear', 'en', 'Nothing is stuck.');

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.dashboard', 'de', 'Meine Arbeit'),
 ('dash.heading', 'de', 'Meine Arbeit'),
 ('dash.sub', 'de', 'Was wartet und was unter Zeitdruck steht'),
 ('dash.waiting', 'de', 'Wartet auf mich'),
 ('dash.waitingsub', 'de', 'Meine und die meiner Teams'),
 ('dash.acrossstages', 'de', 'über {n} Stufen'),
 ('dash.myclock', 'de', 'Unter meiner Verantwortung'),
 ('dash.myclocksub', 'de', 'Mir zugewiesen oder von mir übernommen — keine Teamwarteschlange'),
 ('dash.nothingmine', 'de', 'Ihnen ist nichts zugewiesen und Sie haben nichts übernommen.'),
 ('dash.supplier', 'de', 'Lieferant'),
 ('dash.held', 'de', 'Liegt seit'),
 ('dash.due', 'de', 'Fällig'),
 ('dash.value', 'de', 'Betrag'),
 ('dash.today', 'de', 'heute'),
 ('dash.overdue', 'de', '{n} T überfällig'),
 ('dash.duein', 'de', 'fällig in {n} T'),
 ('dash.sort.held', 'de', 'Längste Liegezeit'),
 ('dash.sort.due', 'de', 'Bald fällig'),
 ('dash.sort.value', 'de', 'Höchster Betrag'),
 ('dash.wherethings', 'de', 'Wo die Belege stehen'),
 ('dash.bystage', 'de', 'Anzahl je Stufe'),
 ('dash.nothinginflight', 'de', 'Es ist nichts in Bearbeitung.'),
 ('dash.astage', 'de', 'Eine Stufe'),
 ('dash.stagegone', 'de', 'Diese Stufe existiert nicht mehr. Wählen Sie eine andere oder entfernen Sie diese Karte.'),
 ('dash.waitinghere', 'de', 'wartet hier'),
 ('dash.ageing', 'de', 'Wie lange sie warten'),
 ('dash.ageingsub', 'de', 'Alle offenen Aufgaben'),
 ('dash.done', 'de', 'Erledigt'),
 ('dash.todaylabel', 'de', 'heute'),
 ('dash.weeklabel', 'de', 'diese Woche'),
 ('dash.minelabel', 'de', 'von mir diese Woche'),
 ('dash.received', 'de', 'Eingegangen'),
 ('dash.receivedsub', 'de', 'Diese Woche, nach Tag'),
 ('dash.nonereceived', 'de', 'Diese Woche ist nichts eingegangen.'),
 ('dash.exceptions', 'de', 'Ausnahmen nach Lieferant'),
 ('dash.exceptionssub', 'de', 'Letzte 30 Tage'),
 ('dash.noexceptions', 'de', 'Keine Prüffehler in den letzten 30 Tagen.'),
 ('dash.needssomebody', 'de', 'Braucht jemanden'),
 ('dash.needssomebodysub', 'de', 'Nichts anderes zeigt diese an'),
 ('dash.unplaced', 'de', 'Nicht zugeordnete Belege'),
 ('dash.awaitingerp', 'de', 'Lieferanten ohne ERP-Kennung'),
 ('dash.duplicates', 'de', 'Mögliche Doppelbelege'),
 ('dash.allclear', 'de', 'Nichts hängt fest.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key LIKE 'dash.%' OR key = 'nav.dashboard' == 86
