-- 0093_role_management_strings.sql
-- Decision 0319 — the read-only role-management screen's own strings.
INSERT INTO ui_strings (key, locale, value) VALUES
  ('column.role', 'en', 'Role'),
  ('column.person', 'en', 'Person'),
  ('nav.roles', 'en', 'Roles'),
  ('roles.subtitle', 'en', 'Who can do what, where, and up to how much'),
  ('roles.units', 'en', 'Org units'),
  ('roles.nounits', 'en', 'No org units configured yet.'),
  ('roles.kind', 'en', 'Kind'),
  ('roles.roles', 'en', 'Roles'),
  ('roles.norolesconfigured', 'en', 'No roles configured yet.'),
  ('roles.permissions', 'en', 'Permissions'),
  ('roles.nopermissions', 'en', 'No permissions granted.'),
  ('roles.people', 'en', 'People'),
  ('roles.nopeople', 'en', 'No people configured yet.'),
  ('roles.assignments', 'en', 'Roles held'),
  ('roles.limits', 'en', 'Approval limits'),
  ('roles.noassignments', 'en', 'Holds no role.'),
  ('roles.nolimits', 'en', 'No limit set.'),
  ('roles.everywhere', 'en', 'everywhere'),
  ('column.role', 'de', 'Rolle'),
  ('column.person', 'de', 'Person'),
  ('nav.roles', 'de', 'Rollen'),
  ('roles.subtitle', 'de', 'Wer was tun darf, wo, und bis zu welchem Betrag'),
  ('roles.units', 'de', 'Organisationseinheiten'),
  ('roles.nounits', 'de', 'Noch keine Organisationseinheiten konfiguriert.'),
  ('roles.kind', 'de', 'Art'),
  ('roles.roles', 'de', 'Rollen'),
  ('roles.norolesconfigured', 'de', 'Noch keine Rollen konfiguriert.'),
  ('roles.permissions', 'de', 'Berechtigungen'),
  ('roles.nopermissions', 'de', 'Keine Berechtigungen erteilt.'),
  ('roles.people', 'de', 'Personen'),
  ('roles.nopeople', 'de', 'Noch keine Personen konfiguriert.'),
  ('roles.assignments', 'de', 'Innehabende Rollen'),
  ('roles.limits', 'de', 'Freigabelimits'),
  ('roles.noassignments', 'de', 'Hat keine Rolle.'),
  ('roles.nolimits', 'de', 'Kein Limit festgelegt.'),
  ('roles.everywhere', 'de', 'überall');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key LIKE 'roles.%' AND locale = 'en' == 15
