-- 0106_process_management_strings.sql
-- Decision 0349 — a new Process management screen: adding stages to
-- a process, and real version control (a draft, published as a new
-- version, never touching an in-flight instance's own version).
INSERT INTO ui_strings (key, locale, value) VALUES
  ('nav.processes', 'en', 'Processes'),
  ('processes.title', 'en', 'Processes'),
  ('processes.subtitle', 'en', 'Stages, in order, and how a process changes shape'),
  ('processes.new', 'en', 'New process'),
  ('processes.name', 'en', 'Name'),
  ('processes.id', 'en', 'ID'),
  ('processes.version', 'en', 'Version'),
  ('processes.stages', 'en', 'stages'),
  ('processes.empty', 'en', 'No processes configured.'),
  ('processes.v', 'en', 'v'),
  ('processes.live', 'en', 'live'),
  ('processes.draft', 'en', 'Draft'),
  ('processes.draftnote', 'en', 'In-flight invoices stay on the live version. Only new ones start on the draft once it is published.'),
  ('processes.addstage', 'en', 'Add stage'),
  ('processes.removestage', 'en', 'Remove from draft'),
  ('processes.scope', 'en', 'Evaluated'),
  ('processes.scopeheader', 'en', 'Once per invoice'),
  ('processes.scopeline', 'en', 'Once per line'),
  ('processes.automatic', 'en', 'Automatic'),
  ('processes.needidandname', 'en', 'Give it an ID and a name.'),
  ('processes.savefailed', 'en', 'Could not save. Please try again.'),
  ('action.newprocess', 'en', 'New process'),
  ('action.addstage', 'en', 'Add stage'),
  ('action.publish', 'en', 'Publish'),
  ('nav.processes', 'de', 'Prozesse'),
  ('processes.title', 'de', 'Prozesse'),
  ('processes.subtitle', 'de', 'Stufen, in Reihenfolge, und wie sich ein Prozess ändert'),
  ('processes.new', 'de', 'Neuer Prozess'),
  ('processes.name', 'de', 'Name'),
  ('processes.id', 'de', 'ID'),
  ('processes.version', 'de', 'Version'),
  ('processes.stages', 'de', 'Stufen'),
  ('processes.empty', 'de', 'Keine Prozesse konfiguriert.'),
  ('processes.v', 'de', 'v'),
  ('processes.live', 'de', 'live'),
  ('processes.draft', 'de', 'Entwurf'),
  ('processes.draftnote', 'de', 'Laufende Rechnungen bleiben auf der aktiven Version. Neue starten erst auf dem Entwurf, sobald er veröffentlicht ist.'),
  ('processes.addstage', 'de', 'Stufe hinzufügen'),
  ('processes.removestage', 'de', 'Aus Entwurf entfernen'),
  ('processes.scope', 'de', 'Ausgewertet'),
  ('processes.scopeheader', 'de', 'Einmal pro Rechnung'),
  ('processes.scopeline', 'de', 'Einmal pro Zeile'),
  ('processes.automatic', 'de', 'Automatisch'),
  ('processes.needidandname', 'de', 'Bitte ID und Name angeben.'),
  ('processes.savefailed', 'de', 'Konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.'),
  ('action.newprocess', 'de', 'Neuer Prozess'),
  ('action.addstage', 'de', 'Stufe hinzufügen'),
  ('action.publish', 'de', 'Veröffentlichen');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.processes','processes.title','processes.subtitle','processes.new','processes.name','processes.id','processes.version','processes.stages','processes.empty','processes.v','processes.live','processes.draft','processes.draftnote','processes.addstage','processes.removestage','processes.scope','processes.scopeheader','processes.scopeline','processes.automatic','processes.needidandname','processes.savefailed','action.newprocess','action.addstage','action.publish') AND locale = 'en' == 24
