-- 0188_po_matching_panel_strings.sql
-- Decision 0530. The Matching stage's PO matching panel, phase 1: the
-- button, the panel itself, and the Timeline line a re-link records.
-- PO statuses reuse the Purchase Orders screen's own words
-- (purchaseorders.status.*, 0377).

INSERT INTO ui_strings (key, locale, value) VALUES
 ('action.po_matching', 'en', 'PO matching'),
 ('activity.polinked', 'en', '{who} linked this to purchase order {po}'),
 ('pomatch.title', 'en', 'Purchase order matching'),
 ('pomatch.loading', 'en', 'Loading…'),
 ('pomatch.loadfailed', 'en', 'The matching could not be loaded.'),
 ('pomatch.linked', 'en', 'Linked purchase order'),
 ('pomatch.how', 'en', 'Linked by the order number on the invoice ({po})'),
 ('pomatch.none', 'en', 'No purchase order is linked. The invoice has no order number.'),
 ('pomatch.notheld', 'en', 'The invoice names purchase order {po}, which is not held in VibeFinance.'),
 ('pomatch.ponumber', 'en', 'PO number'),
 ('pomatch.supplier', 'en', 'Supplier'),
 ('pomatch.buyer', 'en', 'Buyer'),
 ('pomatch.issued', 'en', 'Issued'),
 ('pomatch.status', 'en', 'Status'),
 ('pomatch.used', 'en', 'How much of this PO is used'),
 ('pomatch.usedpct', 'en', '{pct}% used once this invoice is paid'),
 ('pomatch.over', 'en', 'Over by {amount}'),
 ('pomatch.already', 'en', 'Already invoiced'),
 ('pomatch.thisinvoice', 'en', 'This invoice'),
 ('pomatch.left', 'en', 'Left'),
 ('pomatch.of', 'en', 'of {total}'),
 ('pomatch.lines', 'en', 'Invoice lines against the PO'),
 ('pomatch.clear', 'en', '{n} of {total} lines clear'),
 ('pomatch.tolerance', 'en', 'price tolerance {pct}'),
 ('pomatch.invoiceline', 'en', 'Invoice line'),
 ('pomatch.poline', 'en', 'PO line'),
 ('pomatch.result', 'en', 'Result'),
 ('pomatch.byref', 'en', 'By line reference {ref}'),
 ('pomatch.noref', 'en', 'No line reference on the invoice'),
 ('pomatch.refnotfound', 'en', 'The PO has no line {ref}'),
 ('pomatch.r.matched', 'en', 'Matched'),
 ('pomatch.r.price', 'en', 'Amount differs {pct}'),
 ('pomatch.r.qty', 'en', 'Quantity differs {pct}'),
 ('pomatch.r.unit', 'en', 'Unit differs'),
 ('pomatch.r.nopoline', 'en', 'No PO line'),
 ('pomatch.r.nocompare', 'en', 'Cannot compare'),
 ('pomatch.unused', 'en', 'PO lines this invoice does not use:'),
 ('pomatch.search.title', 'en', 'Find a different purchase order'),
 ('pomatch.search.titlenone', 'en', 'Find the purchase order'),
 ('pomatch.search.placeholder', 'en', 'PO number, supplier VAT or item'),
 ('pomatch.f.supplier', 'en', 'This supplier only'),
 ('pomatch.f.active', 'en', 'Active POs only'),
 ('pomatch.f.covers', 'en', 'Enough left to cover this invoice'),
 ('pomatch.col.po', 'en', 'PO number'),
 ('pomatch.col.supplier', 'en', 'Supplier'),
 ('pomatch.col.issued', 'en', 'Issued'),
 ('pomatch.col.total', 'en', 'PO total'),
 ('pomatch.col.used', 'en', 'Used'),
 ('pomatch.col.left', 'en', 'Left'),
 ('pomatch.col.status', 'en', 'Status'),
 ('pomatch.col.why', 'en', 'Why it fits'),
 ('pomatch.why.supplier', 'en', 'Same supplier'),
 ('pomatch.why.covers', 'en', 'Enough left'),
 ('pomatch.why.currency', 'en', 'Same currency'),
 ('pomatch.use', 'en', 'Use this PO'),
 ('pomatch.current', 'en', 'Linked'),
 ('pomatch.noresults', 'en', 'No purchase orders match. Try clearing a filter.'),
 ('pomatch.relinkhint', 'en', 'Only the person whose task this is can link a different purchase order.'),
 ('pomatch.linkfailed', 'en', 'The purchase order could not be linked.'),
 ('pomatch.foot', 'en', 'Linking a different purchase order is recorded in the Timeline. The Matching rules check again when you complete the task.');

INSERT INTO ui_strings (key, locale, value) VALUES
 ('action.po_matching', 'de', 'PO-Abgleich'),
 ('activity.polinked', 'de', '{who} hat dies mit Bestellung {po} verknüpft'),
 ('pomatch.title', 'de', 'Bestellabgleich'),
 ('pomatch.loading', 'de', 'Wird geladen…'),
 ('pomatch.loadfailed', 'de', 'Der Abgleich konnte nicht geladen werden.'),
 ('pomatch.linked', 'de', 'Verknüpfte Bestellung'),
 ('pomatch.how', 'de', 'Verknüpft über die Bestellnummer auf der Rechnung ({po})'),
 ('pomatch.none', 'de', 'Keine Bestellung verknüpft. Die Rechnung enthält keine Bestellnummer.'),
 ('pomatch.notheld', 'de', 'Die Rechnung nennt Bestellung {po}, die in VibeFinance nicht vorliegt.'),
 ('pomatch.ponumber', 'de', 'Bestellnummer'),
 ('pomatch.supplier', 'de', 'Lieferant'),
 ('pomatch.buyer', 'de', 'Einkäufer'),
 ('pomatch.issued', 'de', 'Ausgestellt'),
 ('pomatch.status', 'de', 'Status'),
 ('pomatch.used', 'de', 'Wie viel dieser Bestellung verbraucht ist'),
 ('pomatch.usedpct', 'de', '{pct} % verbraucht, sobald diese Rechnung bezahlt ist'),
 ('pomatch.over', 'de', 'Überschritten um {amount}'),
 ('pomatch.already', 'de', 'Bereits berechnet'),
 ('pomatch.thisinvoice', 'de', 'Diese Rechnung'),
 ('pomatch.left', 'de', 'Verbleibend'),
 ('pomatch.of', 'de', 'von {total}'),
 ('pomatch.lines', 'de', 'Rechnungspositionen gegen die Bestellung'),
 ('pomatch.clear', 'de', '{n} von {total} Positionen in Ordnung'),
 ('pomatch.tolerance', 'de', 'Preistoleranz {pct}'),
 ('pomatch.invoiceline', 'de', 'Rechnungsposition'),
 ('pomatch.poline', 'de', 'Bestellposition'),
 ('pomatch.result', 'de', 'Ergebnis'),
 ('pomatch.byref', 'de', 'Über Positionsreferenz {ref}'),
 ('pomatch.noref', 'de', 'Keine Positionsreferenz auf der Rechnung'),
 ('pomatch.refnotfound', 'de', 'Die Bestellung hat keine Position {ref}'),
 ('pomatch.r.matched', 'de', 'Abgeglichen'),
 ('pomatch.r.price', 'de', 'Betrag weicht ab {pct}'),
 ('pomatch.r.qty', 'de', 'Menge weicht ab {pct}'),
 ('pomatch.r.unit', 'de', 'Einheit weicht ab'),
 ('pomatch.r.nopoline', 'de', 'Keine Bestellposition'),
 ('pomatch.r.nocompare', 'de', 'Nicht vergleichbar'),
 ('pomatch.unused', 'de', 'Bestellpositionen, die diese Rechnung nicht nutzt:'),
 ('pomatch.search.title', 'de', 'Andere Bestellung suchen'),
 ('pomatch.search.titlenone', 'de', 'Bestellung suchen'),
 ('pomatch.search.placeholder', 'de', 'Bestellnummer, USt-IdNr. des Lieferanten oder Artikel'),
 ('pomatch.f.supplier', 'de', 'Nur dieser Lieferant'),
 ('pomatch.f.active', 'de', 'Nur aktive Bestellungen'),
 ('pomatch.f.covers', 'de', 'Genug übrig für diese Rechnung'),
 ('pomatch.col.po', 'de', 'Bestellnummer'),
 ('pomatch.col.supplier', 'de', 'Lieferant'),
 ('pomatch.col.issued', 'de', 'Ausgestellt'),
 ('pomatch.col.total', 'de', 'Bestellsumme'),
 ('pomatch.col.used', 'de', 'Verbraucht'),
 ('pomatch.col.left', 'de', 'Verbleibend'),
 ('pomatch.col.status', 'de', 'Status'),
 ('pomatch.col.why', 'de', 'Warum sie passt'),
 ('pomatch.why.supplier', 'de', 'Gleicher Lieferant'),
 ('pomatch.why.covers', 'de', 'Genug übrig'),
 ('pomatch.why.currency', 'de', 'Gleiche Währung'),
 ('pomatch.use', 'de', 'Diese Bestellung verwenden'),
 ('pomatch.current', 'de', 'Verknüpft'),
 ('pomatch.noresults', 'de', 'Keine passenden Bestellungen. Versuchen Sie, einen Filter zu entfernen.'),
 ('pomatch.relinkhint', 'de', 'Nur die Person, deren Aufgabe dies ist, kann eine andere Bestellung verknüpfen.'),
 ('pomatch.linkfailed', 'de', 'Die Bestellung konnte nicht verknüpft werden.'),
 ('pomatch.foot', 'de', 'Das Verknüpfen einer anderen Bestellung wird in der Zeitleiste festgehalten. Die Abgleichsregeln prüfen erneut, wenn Sie die Aufgabe abschließen.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key LIKE 'pomatch.%' == 116
-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('action.po_matching', 'activity.polinked') == 4
