-- 0203_split_coding_strings.sql
-- Decision 0548. Split coding: the Coding pop-out's split rows, the
-- line table's chip, "Split like last time", and why a split was not
-- saved or a coding task not completed.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('viewer.coding.split.start', 'en', 'Split this line'),
 ('viewer.coding.split.start', 'de', 'Diese Position aufteilen'),
 ('viewer.coding.split.title', 'en', 'Split across'),
 ('viewer.coding.split.title', 'de', 'Aufteilen auf'),
 ('viewer.coding.split.bypct', 'en', 'By %'),
 ('viewer.coding.split.bypct', 'de', 'Nach %'),
 ('viewer.coding.split.byamount', 'en', 'By amount'),
 ('viewer.coding.split.byamount', 'de', 'Nach Betrag'),
 ('viewer.coding.split.share', 'en', 'Share'),
 ('viewer.coding.split.share', 'de', 'Anteil'),
 ('viewer.coding.split.amount', 'en', 'Amount'),
 ('viewer.coding.split.amount', 'de', 'Betrag'),
 ('viewer.coding.split.row', 'en', 'Split {n}'),
 ('viewer.coding.split.row', 'de', 'Aufteilung {n}'),
 ('viewer.coding.split.wholeline', 'en', 'whole line'),
 ('viewer.coding.split.wholeline', 'de', 'ganze Position'),
 ('viewer.coding.split.add', 'en', '+ Add a split'),
 ('viewer.coding.split.add', 'de', '+ Aufteilung hinzufügen'),
 ('viewer.coding.split.stop', 'en', 'Stop splitting (keep the first row)'),
 ('viewer.coding.split.stop', 'de', 'Nicht mehr aufteilen (erste Zeile behalten)'),
 ('viewer.coding.split.remove', 'en', 'Remove this split'),
 ('viewer.coding.split.remove', 'de', 'Diese Aufteilung entfernen'),
 ('viewer.coding.split.fill', 'en', 'Put it on the last row'),
 ('viewer.coding.split.fill', 'de', 'Auf die letzte Zeile buchen'),
 ('viewer.coding.split.balanced', 'en', '{pct}% allocated · {done} of {total}'),
 ('viewer.coding.split.balanced', 'de', '{pct} % verteilt · {done} von {total}'),
 ('viewer.coding.split.left', 'en', '{pct}% allocated · {left} still to allocate'),
 ('viewer.coding.split.left', 'de', '{pct} % verteilt · {left} noch zu verteilen'),
 ('viewer.coding.split.over', 'en', '{pct}% allocated · {left} more than the line'),
 ('viewer.coding.split.over', 'de', '{pct} % verteilt · {left} mehr als die Position'),
 ('viewer.coding.split.rounding', 'en', 'Pennies left by rounding go to the last row.'),
 ('viewer.coding.split.rounding', 'de', 'Rundungscent gehen auf die letzte Zeile.'),
 ('viewer.coding.split.waits', 'en', 'Done waits until the split adds up to the line.'),
 ('viewer.coding.split.waits', 'de', 'Fertig ist möglich, sobald die Aufteilung die Position ergibt.'),
 ('viewer.coding.split.budget', 'en', 'Budget: {pct}% used once this invoice is paid'),
 ('viewer.coding.split.budget', 'de', 'Budget: {pct} % verbraucht, sobald diese Rechnung bezahlt ist'),
 ('viewer.coding.split.chip', 'en', 'Split · {n}'),
 ('viewer.coding.split.chip', 'de', 'Aufgeteilt · {n}'),
 ('viewer.coding.split.last', 'en', 'Split like last time'),
 ('viewer.coding.split.last', 'de', 'Wie beim letzten Mal aufteilen'),
 ('viewer.coding.split.lastwhy', 'en', '{invoice} from this supplier was split {shares}'),
 ('viewer.coding.split.lastwhy', 'de', '{invoice} dieses Lieferanten wurde {shares} aufgeteilt'),
 ('viewer.coding.split.refused.unbalanced', 'en', 'Not saved. The split on line {line} does not add up to the line''s net amount.'),
 ('viewer.coding.split.refused.unbalanced', 'de', 'Nicht gespeichert. Die Aufteilung in Position {line} ergibt nicht den Nettobetrag der Position.'),
 ('viewer.coding.split.refused.too_few', 'en', 'Not saved. A split needs at least two rows (line {line}).'),
 ('viewer.coding.split.refused.too_few', 'de', 'Nicht gespeichert. Eine Aufteilung braucht mindestens zwei Zeilen (Position {line}).'),
 ('viewer.coding.split.refused.too_many', 'en', 'Not saved. A line can be split ten ways at most (line {line}).'),
 ('viewer.coding.split.refused.too_many', 'de', 'Nicht gespeichert. Eine Position lässt sich höchstens zehnmal aufteilen (Position {line}).'),
 ('viewer.coding.split.refused.not_positive', 'en', 'Not saved. Every split on line {line} needs an amount.'),
 ('viewer.coding.split.refused.not_positive', 'de', 'Nicht gespeichert. Jede Aufteilung in Position {line} braucht einen Betrag.'),
 ('viewer.coding.split.refused.no_net', 'en', 'Not saved. Line {line} has no net amount to split.'),
 ('viewer.coding.split.refused.no_net', 'de', 'Nicht gespeichert. Position {line} hat keinen Nettobetrag zum Aufteilen.'),
 ('viewer.coding.split.cell', 'en', 'Split'),
 ('viewer.coding.split.cell', 'de', 'Aufgeteilt'),
 ('viewer.onsplit', 'en', 'split'),
 ('viewer.onsplit', 'de', 'Aufteilung'),
 ('field.coding.split', 'en', 'Split coding'),
 ('field.coding.split', 'de', 'Aufgeteilte Kontierung');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key LIKE 'viewer.coding.split.%' OR key IN ('viewer.onsplit', 'field.coding.split') == 58
