-- 0204_split_rules_approval_erp_export_strings.sql
-- Decisions 0551 and 0552. An approver's share of a split line, and the
-- ERP export screen with its place in the menu.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('viewer.coding.split.yourshare', 'en', 'Your task covers line {line}: {amount} of {total}'),
 ('viewer.coding.split.yourshare', 'de', 'Ihre Aufgabe betrifft Position {line}: {amount} von {total}'),
 ('nav.erpexport', 'en', 'ERP export'),
 ('nav.erpexport', 'de', 'ERP-Export'),
 ('nav.group.integration', 'en', 'Integration'),
 ('nav.group.integration', 'de', 'Integration'),
 ('nav.groupshort.integration', 'en', 'INT'),
 ('nav.groupshort.integration', 'de', 'INT'),
 ('erpexport.heading', 'en', 'ERP export'),
 ('erpexport.heading', 'de', 'ERP-Export'),
 ('erpexport.subtitle', 'en', 'Payment-eligible invoices, each exported once, as a CSV file for your ERP to import.'),
 ('erpexport.subtitle', 'de', 'Zahlungsbereite Rechnungen, jede genau einmal exportiert, als CSV-Datei für den Import in Ihr ERP.'),
 ('erpexport.ready', 'en', 'Ready to export'),
 ('erpexport.ready', 'de', 'Bereit zum Export'),
 ('erpexport.readycount', 'en', '{n} payment-eligible invoices not yet exported'),
 ('erpexport.readycount', 'de', '{n} zahlungsbereite Rechnungen, noch nicht exportiert'),
 ('erpexport.none', 'en', 'Nothing is waiting: every payment-eligible invoice has been exported.'),
 ('erpexport.none', 'de', 'Nichts offen: Alle zahlungsbereiten Rechnungen sind exportiert.'),
 ('erpexport.exportnow', 'en', 'Export {n} invoices'),
 ('erpexport.exportnow', 'de', '{n} Rechnungen exportieren'),
 ('erpexport.more', 'en', '… and {n} more, all included in the export.'),
 ('erpexport.more', 'de', '… und {n} weitere, alle im Export enthalten.'),
 ('erpexport.history', 'en', 'Past exports'),
 ('erpexport.history', 'de', 'Bisherige Exporte'),
 ('erpexport.nohistory', 'en', 'No exports yet.'),
 ('erpexport.nohistory', 'de', 'Noch keine Exporte.'),
 ('erpexport.col.invoice', 'en', 'Invoice'),
 ('erpexport.col.invoice', 'de', 'Rechnung'),
 ('erpexport.col.supplier', 'en', 'Supplier'),
 ('erpexport.col.supplier', 'de', 'Lieferant'),
 ('erpexport.col.issued', 'en', 'Issued'),
 ('erpexport.col.issued', 'de', 'Ausgestellt'),
 ('erpexport.col.total', 'en', 'Total'),
 ('erpexport.col.total', 'de', 'Gesamt'),
 ('erpexport.col.when', 'en', 'Exported'),
 ('erpexport.col.when', 'de', 'Exportiert'),
 ('erpexport.col.by', 'en', 'By'),
 ('erpexport.col.by', 'de', 'Von'),
 ('erpexport.col.invoices', 'en', 'Invoices'),
 ('erpexport.col.invoices', 'de', 'Rechnungen'),
 ('erpexport.col.rows', 'en', 'Rows'),
 ('erpexport.col.rows', 'de', 'Zeilen'),
 ('erpexport.done', 'en', 'Exported {invoices} invoices as {rows} rows. The file is downloading.'),
 ('erpexport.done', 'de', '{invoices} Rechnungen als {rows} Zeilen exportiert. Die Datei wird heruntergeladen.'),
 ('erpexport.nothing', 'en', 'There is nothing to export.'),
 ('erpexport.nothing', 'de', 'Es gibt nichts zu exportieren.'),
 ('erpexport.conflict', 'en', 'Another export took some of these invoices just now. Try again.'),
 ('erpexport.conflict', 'de', 'Ein anderer Export hat soeben einige dieser Rechnungen übernommen. Bitte erneut versuchen.'),
 ('erpexport.failed', 'en', 'The export could not be loaded or made. Try again.'),
 ('erpexport.failed', 'de', 'Der Export konnte nicht geladen oder erstellt werden. Bitte erneut versuchen.'),
 ('erpexport.downloadfailed', 'en', 'The file could not be downloaded. Try again.'),
 ('erpexport.downloadfailed', 'de', 'Die Datei konnte nicht heruntergeladen werden. Bitte erneut versuchen.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key LIKE 'erpexport.%' OR key IN ('viewer.coding.split.yourshare', 'nav.erpexport', 'nav.group.integration', 'nav.groupshort.integration') == 52
