-- 0207_route_monitor_strings.sql
-- Decision 0556. The Route monitor: its menu entry and page help, the four
-- counts, filters, columns, statuses, the route's five parts, an
-- explanation and a fix for each error code the server sends, and the
-- names of the events in a message's history.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.routemonitor', 'en', 'Route monitor'),
 ('nav.routemonitor', 'de', 'Routen-Monitor'),
 ('help.screen.routemonitor', 'en', 'Every message your routes received: what arrived, from whom, and what became of it. Open one to see where it failed and why, the invoices it made, and its original files as they arrived.'),
 ('help.screen.routemonitor', 'de', 'Jede Nachricht, die Ihre Routen empfangen haben: was ankam, von wem und was daraus wurde. Öffnen Sie eine, um zu sehen, wo und warum sie scheiterte, welche Rechnungen entstanden und die Originaldateien, wie sie ankamen.'),
 ('routemonitor.heading', 'en', 'Route monitor'),
 ('routemonitor.heading', 'de', 'Routen-Monitor'),
 ('routemonitor.subtitle', 'en', 'Every message through your routes: what arrived, what became of it, and what went wrong.'),
 ('routemonitor.subtitle', 'de', 'Jede Nachricht über Ihre Routen: was ankam, was daraus wurde und was schiefging.'),
 ('routemonitor.failed', 'en', 'The messages could not be loaded.'),
 ('routemonitor.failed', 'de', 'Die Nachrichten konnten nicht geladen werden.'),
 ('routemonitor.messages', 'en', 'Messages'),
 ('routemonitor.messages', 'de', 'Nachrichten'),
 ('routemonitor.nomessages', 'en', 'No messages in this period.'),
 ('routemonitor.nomessages', 'de', 'Keine Nachrichten in diesem Zeitraum.'),
 ('routemonitor.pick', 'en', 'Choose a message to see where it got to, what went wrong and its original files.'),
 ('routemonitor.pick', 'de', 'Wählen Sie eine Nachricht, um zu sehen, wie weit sie kam, was schiefging und ihre Originaldateien.'),
 ('routemonitor.tile.received', 'en', 'Received today'),
 ('routemonitor.tile.received', 'de', 'Heute empfangen'),
 ('routemonitor.tile.delivered', 'en', 'Delivered today'),
 ('routemonitor.tile.delivered', 'de', 'Heute zugestellt'),
 ('routemonitor.tile.failed', 'en', 'Failed, not yet fixed'),
 ('routemonitor.tile.failed', 'de', 'Fehlgeschlagen, noch offen'),
 ('routemonitor.tile.waiting', 'en', 'Waiting over an hour'),
 ('routemonitor.tile.waiting', 'de', 'Wartet über eine Stunde'),
 ('routemonitor.filter.allsources', 'en', 'All routes'),
 ('routemonitor.filter.allsources', 'de', 'Alle Routen'),
 ('routemonitor.filter.unclaimed', 'en', 'Unknown address'),
 ('routemonitor.filter.unclaimed', 'de', 'Unbekannte Adresse'),
 ('routemonitor.filter.failedonly', 'en', 'Failed only'),
 ('routemonitor.filter.failedonly', 'de', 'Nur fehlgeschlagene'),
 ('routemonitor.period.today', 'en', 'Today'),
 ('routemonitor.period.today', 'de', 'Heute'),
 ('routemonitor.period.7d', 'en', '7 days'),
 ('routemonitor.period.7d', 'de', '7 Tage'),
 ('routemonitor.period.30d', 'en', '30 days'),
 ('routemonitor.period.30d', 'de', '30 Tage'),
 ('routemonitor.col.time', 'en', 'Time'),
 ('routemonitor.col.time', 'de', 'Zeit'),
 ('routemonitor.col.route', 'en', 'Route'),
 ('routemonitor.col.route', 'de', 'Route'),
 ('routemonitor.col.message', 'en', 'Message'),
 ('routemonitor.col.message', 'de', 'Nachricht'),
 ('routemonitor.col.status', 'en', 'Status'),
 ('routemonitor.col.status', 'de', 'Status'),
 ('routemonitor.status.delivered', 'en', 'Delivered'),
 ('routemonitor.status.delivered', 'de', 'Zugestellt'),
 ('routemonitor.status.partial', 'en', 'Partly delivered'),
 ('routemonitor.status.partial', 'de', 'Teilweise zugestellt'),
 ('routemonitor.status.failed', 'en', 'Failed'),
 ('routemonitor.status.failed', 'de', 'Fehlgeschlagen'),
 ('routemonitor.status.received', 'en', 'In progress'),
 ('routemonitor.status.received', 'de', 'In Bearbeitung'),
 ('routemonitor.status.dismissed', 'en', 'Dismissed'),
 ('routemonitor.status.dismissed', 'de', 'Verworfen'),
 ('routemonitor.at.gateway', 'en', 'at the gateway'),
 ('routemonitor.at.gateway', 'de', 'am Eingang'),
 ('routemonitor.at.format', 'en', 'at the format'),
 ('routemonitor.at.format', 'de', 'beim Format'),
 ('routemonitor.at.translation', 'en', 'at translation'),
 ('routemonitor.at.translation', 'de', 'bei der Übersetzung'),
 ('routemonitor.at.delivery', 'en', 'at delivery'),
 ('routemonitor.at.delivery', 'de', 'bei der Zustellung'),
 ('routemonitor.made.one', 'en', '→ invoice {number}'),
 ('routemonitor.made.one', 'de', '→ Rechnung {number}'),
 ('routemonitor.made.many', 'en', '→ {n} invoices'),
 ('routemonitor.made.many', 'de', '→ {n} Rechnungen'),
 ('routemonitor.made.none', 'en', 'no invoice made'),
 ('routemonitor.made.none', 'de', 'keine Rechnung erstellt'),
 ('routemonitor.from', 'en', 'from {who}'),
 ('routemonitor.from', 'de', 'von {who}'),
 ('routemonitor.unclaimed', 'en', 'Unknown address'),
 ('routemonitor.unclaimed', 'de', 'Unbekannte Adresse'),
 ('routemonitor.nosubject', 'en', '(no subject)'),
 ('routemonitor.nosubject', 'de', '(kein Betreff)'),
 ('routemonitor.part.gateway', 'en', 'Gateway'),
 ('routemonitor.part.gateway', 'de', 'Eingang'),
 ('routemonitor.part.format', 'en', 'Format'),
 ('routemonitor.part.format', 'de', 'Format'),
 ('routemonitor.part.translation', 'en', 'Translation'),
 ('routemonitor.part.translation', 'de', 'Übersetzung'),
 ('routemonitor.part.model', 'en', 'EN 16931'),
 ('routemonitor.part.model', 'de', 'EN 16931'),
 ('routemonitor.part.process', 'en', 'Process'),
 ('routemonitor.part.process', 'de', 'Prozess'),
 ('routemonitor.state.ok', 'en', 'Done'),
 ('routemonitor.state.ok', 'de', 'Erledigt'),
 ('routemonitor.state.warn', 'en', 'Partly'),
 ('routemonitor.state.warn', 'de', 'Teilweise'),
 ('routemonitor.state.bad', 'en', 'Failed'),
 ('routemonitor.state.bad', 'de', 'Fehlgeschlagen'),
 ('routemonitor.state.idle', 'en', 'Not reached'),
 ('routemonitor.state.idle', 'de', 'Nicht erreicht'),
 ('routemonitor.tofix', 'en', 'To fix:'),
 ('routemonitor.tofix', 'de', 'Zur Behebung:'),
 ('routemonitor.error.no_such_address.title', 'en', 'Nothing receives mail at this address'),
 ('routemonitor.error.no_such_address.title', 'de', 'Für diese Adresse ist kein Empfang eingerichtet'),
 ('routemonitor.error.no_such_address.body', 'en', 'No route is set up for the address the message was sent to, so it was refused and the sender was told. Such mail is recorded but not kept.'),
 ('routemonitor.error.no_such_address.body', 'de', 'Für die Adresse, an die die Nachricht ging, ist keine Route eingerichtet. Sie wurde abgelehnt und der Absender benachrichtigt. Solche E-Mails werden erfasst, aber nicht aufbewahrt.'),
 ('routemonitor.error.no_such_address.fix', 'en', 'if this address should receive invoices, set up a route for it. Otherwise ask the sender to use your invoice address.'),
 ('routemonitor.error.no_such_address.fix', 'de', 'Soll diese Adresse Rechnungen empfangen, richten Sie eine Route dafür ein. Andernfalls bitten Sie den Absender, Ihre Rechnungsadresse zu verwenden.'),
 ('routemonitor.error.source_retired.title', 'en', 'This route is retired'),
 ('routemonitor.error.source_retired.title', 'de', 'Diese Route ist stillgelegt'),
 ('routemonitor.error.source_retired.body', 'en', 'The message reached a route that no longer receives invoices, so it was refused and the sender was told. The message is kept.'),
 ('routemonitor.error.source_retired.body', 'de', 'Die Nachricht erreichte eine Route, die keine Rechnungen mehr empfängt. Sie wurde abgelehnt und der Absender benachrichtigt. Die Nachricht wird aufbewahrt.'),
 ('routemonitor.error.source_retired.fix', 'en', 'ask the sender to use your current invoice address, or remove the old address from your mail routing.'),
 ('routemonitor.error.source_retired.fix', 'de', 'Bitten Sie den Absender, Ihre aktuelle Rechnungsadresse zu verwenden, oder entfernen Sie die alte Adresse aus Ihrer E-Mail-Weiterleitung.'),
 ('routemonitor.error.no_attachment.title', 'en', 'Nothing was attached'),
 ('routemonitor.error.no_attachment.title', 'de', 'Nichts war angehängt'),
 ('routemonitor.error.no_attachment.body', 'en', 'The message carried no PDF, XML or image, so there was no invoice to read. The sender was asked to attach one. The email itself is kept, so its text can be read below.'),
 ('routemonitor.error.no_attachment.body', 'de', 'Die Nachricht enthielt kein PDF, XML oder Bild, also gab es keine Rechnung zu lesen. Der Absender wurde gebeten, eine anzuhängen. Die E-Mail selbst wird aufbewahrt und kann unten gelesen werden.'),
 ('routemonitor.error.no_attachment.fix', 'en', 'if the invoice is in the email text or a link, ask the supplier to send it as an attachment.'),
 ('routemonitor.error.no_attachment.fix', 'de', 'Steht die Rechnung im E-Mail-Text oder hinter einem Link, bitten Sie den Lieferanten, sie als Anhang zu senden.'),
 ('routemonitor.error.unreadable.title', 'en', 'No attachment could be read as an invoice'),
 ('routemonitor.error.unreadable.title', 'de', 'Kein Anhang konnte als Rechnung gelesen werden'),
 ('routemonitor.error.unreadable.body', 'en', 'Every attachment was received and kept, but none could be turned into an invoice. The sender was told. Each file and the reason it could not be read are below.'),
 ('routemonitor.error.unreadable.body', 'de', 'Jeder Anhang wurde empfangen und aufbewahrt, aber keiner konnte in eine Rechnung umgewandelt werden. Der Absender wurde benachrichtigt. Jede Datei und der Grund stehen unten.'),
 ('routemonitor.error.unreadable.fix', 'en', 'open the file to check it is an invoice and is legible. A photograph or scan may need to be sent again more clearly.'),
 ('routemonitor.error.unreadable.fix', 'de', 'Öffnen Sie die Datei und prüfen Sie, ob es eine lesbare Rechnung ist. Ein Foto oder Scan muss eventuell deutlicher erneut gesendet werden.'),
 ('routemonitor.error.partial.title', 'en', 'Some attachments were not read'),
 ('routemonitor.error.partial.title', 'de', 'Einige Anhänge wurden nicht gelesen'),
 ('routemonitor.error.partial.body', 'en', 'At least one attachment became an invoice, so the message was accepted. The others could not be read and are listed below with their reasons.'),
 ('routemonitor.error.partial.body', 'de', 'Mindestens ein Anhang wurde zur Rechnung, daher wurde die Nachricht angenommen. Die anderen konnten nicht gelesen werden und stehen unten mit ihren Gründen.'),
 ('routemonitor.error.partial.fix', 'en', 'check whether the unread files are invoices. A logo or signature image can be ignored.'),
 ('routemonitor.error.partial.fix', 'de', 'Prüfen Sie, ob die nicht gelesenen Dateien Rechnungen sind. Ein Logo oder Signaturbild kann ignoriert werden.'),
 ('routemonitor.error.unknown.title', 'en', 'The message could not be processed'),
 ('routemonitor.error.unknown.title', 'de', 'Die Nachricht konnte nicht verarbeitet werden'),
 ('routemonitor.error.unknown.body', 'en', 'Something went wrong while this message was being processed. The technical detail below says what.'),
 ('routemonitor.error.unknown.body', 'de', 'Bei der Verarbeitung dieser Nachricht ging etwas schief. Die technischen Details unten sagen, was.'),
 ('routemonitor.error.unknown.fix', 'en', 'pass the reference and the technical detail to whoever supports VibeFinance for you.'),
 ('routemonitor.error.unknown.fix', 'de', 'Geben Sie die Referenz und die technischen Details an Ihren VibeFinance-Support weiter.'),
 ('routemonitor.invoices', 'en', 'Invoices it made'),
 ('routemonitor.invoices', 'de', 'Erstellte Rechnungen'),
 ('routemonitor.originals', 'en', 'Original, as received'),
 ('routemonitor.originals', 'de', 'Original, wie empfangen'),
 ('routemonitor.nooriginals', 'en', 'Nothing was kept for this message.'),
 ('routemonitor.nooriginals', 'de', 'Für diese Nachricht wurde nichts aufbewahrt.'),
 ('routemonitor.theemail', 'en', 'The email'),
 ('routemonitor.theemail', 'de', 'Die E-Mail'),
 ('routemonitor.download', 'en', 'Download'),
 ('routemonitor.download', 'de', 'Herunterladen'),
 ('routemonitor.history', 'en', 'History'),
 ('routemonitor.history', 'de', 'Verlauf'),
 ('routemonitor.partn', 'en', 'file {n}'),
 ('routemonitor.partn', 'de', 'Datei {n}'),
 ('routemonitor.event.received', 'en', 'Received'),
 ('routemonitor.event.received', 'de', 'Empfangen'),
 ('routemonitor.event.original_stored', 'en', 'Email kept'),
 ('routemonitor.event.original_stored', 'de', 'E-Mail aufbewahrt'),
 ('routemonitor.event.original_not_stored', 'en', 'Email not kept'),
 ('routemonitor.event.original_not_stored', 'de', 'E-Mail nicht aufbewahrt'),
 ('routemonitor.event.attachment_not_stored', 'en', 'Attachment not kept'),
 ('routemonitor.event.attachment_not_stored', 'de', 'Anhang nicht aufbewahrt'),
 ('routemonitor.event.captured', 'en', 'Invoice made'),
 ('routemonitor.event.captured', 'de', 'Rechnung erstellt'),
 ('routemonitor.event.capture_failed', 'en', 'Could not be read'),
 ('routemonitor.event.capture_failed', 'de', 'Konnte nicht gelesen werden'),
 ('routemonitor.event.delivered', 'en', 'Delivered'),
 ('routemonitor.event.delivered', 'de', 'Zugestellt'),
 ('routemonitor.event.partial', 'en', 'Partly delivered'),
 ('routemonitor.event.partial', 'de', 'Teilweise zugestellt'),
 ('routemonitor.event.failed', 'en', 'Failed'),
 ('routemonitor.event.failed', 'de', 'Fehlgeschlagen');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.routemonitor','help.screen.routemonitor','routemonitor.heading','routemonitor.subtitle','routemonitor.failed','routemonitor.messages','routemonitor.nomessages','routemonitor.pick','routemonitor.tile.received','routemonitor.tile.delivered','routemonitor.tile.failed','routemonitor.tile.waiting','routemonitor.filter.allsources','routemonitor.filter.unclaimed','routemonitor.filter.failedonly','routemonitor.period.today','routemonitor.period.7d','routemonitor.period.30d','routemonitor.col.time','routemonitor.col.route','routemonitor.col.message','routemonitor.col.status','routemonitor.status.delivered','routemonitor.status.partial','routemonitor.status.failed','routemonitor.status.received','routemonitor.status.dismissed','routemonitor.at.gateway','routemonitor.at.format','routemonitor.at.translation','routemonitor.at.delivery','routemonitor.made.one','routemonitor.made.many','routemonitor.made.none','routemonitor.from','routemonitor.unclaimed','routemonitor.nosubject','routemonitor.part.gateway','routemonitor.part.format','routemonitor.part.translation','routemonitor.part.model','routemonitor.part.process','routemonitor.state.ok','routemonitor.state.warn','routemonitor.state.bad','routemonitor.state.idle','routemonitor.tofix','routemonitor.error.no_such_address.title','routemonitor.error.no_such_address.body','routemonitor.error.no_such_address.fix','routemonitor.error.source_retired.title','routemonitor.error.source_retired.body','routemonitor.error.source_retired.fix','routemonitor.error.no_attachment.title','routemonitor.error.no_attachment.body','routemonitor.error.no_attachment.fix','routemonitor.error.unreadable.title','routemonitor.error.unreadable.body','routemonitor.error.unreadable.fix','routemonitor.error.partial.title','routemonitor.error.partial.body','routemonitor.error.partial.fix','routemonitor.error.unknown.title','routemonitor.error.unknown.body','routemonitor.error.unknown.fix','routemonitor.invoices','routemonitor.originals','routemonitor.nooriginals','routemonitor.theemail','routemonitor.download','routemonitor.history','routemonitor.partn','routemonitor.event.received','routemonitor.event.original_stored','routemonitor.event.original_not_stored','routemonitor.event.attachment_not_stored','routemonitor.event.captured','routemonitor.event.capture_failed','routemonitor.event.delivered','routemonitor.event.partial','routemonitor.event.failed') == 162
