-- 0208_routes_and_process_routes_strings.sql
-- Decision 0557. The Routes and Process routes screens: their menu entries
-- and page help, the words for each of a route's five parts and their
-- values, and Process routes' cards, panels and Add a source pop-out.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.routes', 'en', 'Routes'),
 ('nav.routes', 'de', 'Routen'),
 ('nav.processroutes', 'en', 'Process routes'),
 ('nav.processroutes', 'de', 'Prozessrouten'),
 ('help.screen.routes', 'en', 'Every route: the ways information comes into VibeFinance (Sources) and goes out of it (Destinations). Choose one to see its five parts. These are the standard routes VibeFinance supplies.'),
 ('help.screen.routes', 'de', 'Jede Route: die Wege, auf denen Informationen in VibeFinance hineinkommen (Quellen) und hinausgehen (Ziele). Wählen Sie eine, um ihre fünf Teile zu sehen. Dies sind die Standardrouten von VibeFinance.'),
 ('help.screen.processroutes', 'en', 'Where each process takes information in and sends it out. Sources deliver to the process''s first stage, Destinations read from its last. Choose a source to give it an address, set its org, rename or retire it, or add a new one.'),
 ('help.screen.processroutes', 'de', 'Wo jeder Prozess Informationen aufnimmt und abgibt. Quellen liefern an die erste Stufe des Prozesses, Ziele lesen aus der letzten. Wählen Sie eine Quelle, um ihr eine Adresse zu geben, ihre Organisation festzulegen, sie umzubenennen oder stillzulegen, oder fügen Sie eine neue hinzu.'),
 ('routes.heading', 'en', 'Routes'),
 ('routes.heading', 'de', 'Routen'),
 ('routes.subtitle', 'en', 'Ways information comes into VibeFinance and goes out of it. Each route is defined once, then placed in a process.'),
 ('routes.subtitle', 'de', 'Wege, auf denen Informationen in VibeFinance hineinkommen und hinausgehen. Jede Route wird einmal definiert und dann in einem Prozess platziert.'),
 ('routes.failed', 'en', 'The routes could not be loaded.'),
 ('routes.failed', 'de', 'Die Routen konnten nicht geladen werden.'),
 ('routes.sources', 'en', 'Sources'),
 ('routes.sources', 'de', 'Quellen'),
 ('routes.sourcessub', 'en', 'Bring information in: invoices, receipts and replies.'),
 ('routes.sourcessub', 'de', 'Bringen Informationen herein: Rechnungen, Belege und Antworten.'),
 ('routes.destinations', 'en', 'Destinations'),
 ('routes.destinations', 'de', 'Ziele'),
 ('routes.destinationssub', 'en', 'Send information out: to your ERP, your customers or other organisations.'),
 ('routes.destinationssub', 'de', 'Senden Informationen hinaus: an Ihr ERP, Ihre Kunden oder andere Organisationen.'),
 ('routes.col.route', 'en', 'Route'),
 ('routes.col.route', 'de', 'Route'),
 ('routes.col.inout', 'en', 'In → out'),
 ('routes.col.inout', 'de', 'Ein → aus'),
 ('routes.col.placed', 'en', 'Placed in'),
 ('routes.col.placed', 'de', 'Platziert in'),
 ('routes.col.version', 'en', 'Version'),
 ('routes.col.version', 'de', 'Version'),
 ('routes.standard', 'en', 'Standard'),
 ('routes.standard', 'de', 'Standard'),
 ('routes.copied', 'en', 'Copied from Standard'),
 ('routes.copied', 'de', 'Kopie einer Standardroute'),
 ('routes.live', 'en', 'Live'),
 ('routes.live', 'de', 'Aktiv'),
 ('routes.draft', 'en', 'Draft'),
 ('routes.draft', 'de', 'Entwurf'),
 ('routes.notplaced', 'en', 'Not placed'),
 ('routes.notplaced', 'de', 'Nicht platziert'),
 ('routes.placedn', 'en', '{n} processes'),
 ('routes.placedn', 'de', '{n} Prozesse'),
 ('routes.placedinlist', 'en', 'placed in {list}'),
 ('routes.placedinlist', 'de', 'platziert in {list}'),
 ('routes.dir.source', 'en', 'Source'),
 ('routes.dir.source', 'de', 'Quelle'),
 ('routes.dir.destination', 'en', 'Destination'),
 ('routes.dir.destination', 'de', 'Ziel'),
 ('routes.standardroute', 'en', 'standard route'),
 ('routes.standardroute', 'de', 'Standardroute'),
 ('routes.copiedroute', 'en', 'copied route'),
 ('routes.copiedroute', 'de', 'kopierte Route'),
 ('routes.versionn', 'en', 'version {n}'),
 ('routes.versionn', 'de', 'Version {n}'),
 ('routes.part.1', 'en', 'Receiving gateway'),
 ('routes.part.1', 'de', 'Eingangskanal'),
 ('routes.part.2', 'en', 'Receiving format'),
 ('routes.part.2', 'de', 'Eingangsformat'),
 ('routes.part.3', 'en', 'Translation'),
 ('routes.part.3', 'de', 'Übersetzung'),
 ('routes.part.4', 'en', 'Delivery format'),
 ('routes.part.4', 'de', 'Ausgabeformat'),
 ('routes.part.5', 'en', 'Delivery gateway'),
 ('routes.part.5', 'de', 'Ausgabekanal'),
 ('routes.keeporiginal', 'en', 'Every message on this route keeps its original (the email and each attachment), stored as it arrived.'),
 ('routes.keeporiginal', 'de', 'Jede Nachricht auf dieser Route behält ihr Original (die E-Mail und jeden Anhang), gespeichert wie empfangen.'),
 ('routes.readsfrom', 'en', 'Reads from the process''s last stage, and sends each item once.'),
 ('routes.readsfrom', 'de', 'Liest aus der letzten Stufe des Prozesses und sendet jeden Vorgang einmal.'),
 ('routes.readonly', 'en', 'Standard routes are supplied by VibeFinance. Copying one to change it comes with the mapping editor.'),
 ('routes.readonly', 'de', 'Standardrouten werden von VibeFinance bereitgestellt. Das Kopieren zum Ändern kommt mit dem Mapping-Editor.'),
 ('routes.gw.email', 'en', 'Email address'),
 ('routes.gw.email', 'de', 'E-Mail-Adresse'),
 ('routes.gw.https', 'en', 'HTTPS (API)'),
 ('routes.gw.https', 'de', 'HTTPS (API)'),
 ('routes.gw.sftp', 'en', 'SFTP'),
 ('routes.gw.sftp', 'de', 'SFTP'),
 ('routes.gw.file_import', 'en', 'File import'),
 ('routes.gw.file_import', 'de', 'Dateiimport'),
 ('routes.gw.edi', 'en', 'EDI'),
 ('routes.gw.edi', 'de', 'EDI'),
 ('routes.gw.peppol', 'en', 'Peppol'),
 ('routes.gw.peppol', 'de', 'Peppol'),
 ('routes.gw.process', 'en', 'A VibeFinance process'),
 ('routes.gw.process', 'de', 'Ein VibeFinance-Prozess'),
 ('routes.gw.file_download', 'en', 'File download'),
 ('routes.gw.file_download', 'de', 'Dateidownload'),
 ('routes.gwd.email', 'en', 'Each process gets its own address when the route is placed'),
 ('routes.gwd.email', 'de', 'Jeder Prozess erhält seine eigene Adresse, wenn die Route platziert wird'),
 ('routes.gwd.https', 'en', 'Sent by your systems to the capture API'),
 ('routes.gwd.https', 'de', 'Von Ihren Systemen an die Erfassungs-API gesendet'),
 ('routes.gwd.sftp', 'en', 'Not available yet'),
 ('routes.gwd.sftp', 'de', 'Noch nicht verfügbar'),
 ('routes.gwd.file_import', 'en', 'Not available yet'),
 ('routes.gwd.file_import', 'de', 'Noch nicht verfügbar'),
 ('routes.gwd.edi', 'en', 'Not available yet'),
 ('routes.gwd.edi', 'de', 'Noch nicht verfügbar'),
 ('routes.gwd.peppol', 'en', 'Through an access point provider'),
 ('routes.gwd.peppol', 'de', 'Über einen Access-Point-Anbieter'),
 ('routes.gwd.process', 'en', 'Chosen when the route is placed'),
 ('routes.gwd.process', 'de', 'Wird beim Platzieren der Route gewählt'),
 ('routes.gwd.file_download', 'en', 'Downloaded from the ERP export screen, each export kept'),
 ('routes.gwd.file_download', 'de', 'Über die Seite ERP-Export heruntergeladen, jeder Export bleibt erhalten'),
 ('routes.fmt.detected', 'en', 'PDF, image or XML'),
 ('routes.fmt.detected', 'de', 'PDF, Bild oder XML'),
 ('routes.fmt.ubl', 'en', 'UBL'),
 ('routes.fmt.ubl', 'de', 'UBL'),
 ('routes.fmt.cii', 'en', 'CII'),
 ('routes.fmt.cii', 'de', 'CII'),
 ('routes.fmt.factur_x', 'en', 'Factur-X / ZUGFeRD'),
 ('routes.fmt.factur_x', 'de', 'Factur-X / ZUGFeRD'),
 ('routes.fmt.supplier_xml', 'en', 'Supplier''s own XML'),
 ('routes.fmt.supplier_xml', 'de', 'Eigenes XML des Lieferanten'),
 ('routes.fmt.en16931', 'en', 'EN 16931 invoice'),
 ('routes.fmt.en16931', 'de', 'EN-16931-Rechnung'),
 ('routes.fmt.edifact', 'en', 'EDIFACT'),
 ('routes.fmt.edifact', 'de', 'EDIFACT'),
 ('routes.fmt.csv', 'en', 'CSV file'),
 ('routes.fmt.csv', 'de', 'CSV-Datei'),
 ('routes.fmt.idoc', 'en', 'SAP IDoc'),
 ('routes.fmt.idoc', 'de', 'SAP IDoc'),
 ('routes.fmtd.detected', 'en', 'Detected per document: UBL, CII, Factur-X / ZUGFeRD, PDF or image'),
 ('routes.fmtd.detected', 'de', 'Je Dokument erkannt: UBL, CII, Factur-X / ZUGFeRD, PDF oder Bild'),
 ('routes.fmtd.en16931', 'en', 'The model in the middle, with the original attached'),
 ('routes.fmtd.en16931', 'de', 'Das Modell in der Mitte, mit angehängtem Original'),
 ('routes.fmtd.csv', 'en', 'One row per distribution: a line, or each row of a split line'),
 ('routes.fmtd.csv', 'de', 'Eine Zeile je Kontierung: eine Position oder jede Zeile einer aufgeteilten Position'),
 ('routes.fmtd.edifact', 'en', 'EDIFACT INVOIC messages'),
 ('routes.fmtd.edifact', 'de', 'EDIFACT-INVOIC-Nachrichten'),
 ('routes.fmtd.ubl', 'en', 'Peppol BIS Billing 3.0'),
 ('routes.fmtd.ubl', 'de', 'Peppol BIS Billing 3.0'),
 ('routes.fmtd.cii', 'en', 'UN/CEFACT Cross Industry Invoice'),
 ('routes.fmtd.cii', 'de', 'UN/CEFACT Cross Industry Invoice'),
 ('routes.fmtd.factur_x', 'en', 'A PDF carrying its invoice as XML'),
 ('routes.fmtd.factur_x', 'de', 'Ein PDF, das seine Rechnung als XML enthält'),
 ('routes.fmtd.supplier_xml', 'en', 'Mapped field by field'),
 ('routes.fmtd.supplier_xml', 'de', 'Feld für Feld abgebildet'),
 ('routes.fmtd.idoc', 'en', 'INVOIC for SAP'),
 ('routes.fmtd.idoc', 'de', 'INVOIC für SAP'),
 ('routes.tr.standard_intake', 'en', 'Standard intake mapping'),
 ('routes.tr.standard_intake', 'de', 'Standard-Eingangsabbildung'),
 ('routes.tr.erp_csv_v1', 'en', 'ERP CSV layout'),
 ('routes.tr.erp_csv_v1', 'de', 'ERP-CSV-Layout'),
 ('routes.trd.standard_intake', 'en', 'Structured data read directly, AI reading for PDFs and images'),
 ('routes.trd.standard_intake', 'de', 'Strukturierte Daten direkt gelesen, KI-Lesen für PDFs und Bilder'),
 ('routes.trd.erp_csv_v1', 'en', 'Supplier, amounts and account coding for each distribution'),
 ('routes.trd.erp_csv_v1', 'de', 'Lieferant, Beträge und Kontierung je Kontierungszeile'),
 ('processroutes.heading', 'en', 'Process routes'),
 ('processroutes.heading', 'de', 'Prozessrouten'),
 ('processroutes.subtitle', 'en', 'Where each process takes information in, and where it sends it out.'),
 ('processroutes.subtitle', 'de', 'Wo jeder Prozess Informationen aufnimmt und wohin er sie sendet.'),
 ('processroutes.failed', 'en', 'The process routes could not be loaded.'),
 ('processroutes.failed', 'de', 'Die Prozessrouten konnten nicht geladen werden.'),
 ('processroutes.source', 'en', 'SOURCE'),
 ('processroutes.source', 'de', 'QUELLE'),
 ('processroutes.destination', 'en', 'DESTINATION'),
 ('processroutes.destination', 'de', 'ZIEL'),
 ('processroutes.sources', 'en', 'Sources'),
 ('processroutes.sources', 'de', 'Quellen'),
 ('processroutes.destinations', 'en', 'Destinations'),
 ('processroutes.destinations', 'de', 'Ziele'),
 ('processroutes.deliverto', 'en', 'deliver to {stage}'),
 ('processroutes.deliverto', 'de', 'liefern an {stage}'),
 ('processroutes.readfrom', 'en', 'read from {stage}'),
 ('processroutes.readfrom', 'de', 'lesen aus {stage}'),
 ('processroutes.nosources', 'en', 'No source delivers to this process yet.'),
 ('processroutes.nosources', 'de', 'Noch liefert keine Quelle an diesen Prozess.'),
 ('processroutes.nodestinations', 'en', 'No destination reads from this process yet.'),
 ('processroutes.nodestinations', 'de', 'Noch liest kein Ziel aus diesem Prozess.'),
 ('processroutes.notlive', 'en', 'Not yet available'),
 ('processroutes.notlive', 'de', 'Noch nicht verfügbar'),
 ('processroutes.noaddress', 'en', 'No address yet'),
 ('processroutes.noaddress', 'de', 'Noch keine Adresse'),
 ('processroutes.thisweek', 'en', '{n} this week'),
 ('processroutes.thisweek', 'de', '{n} diese Woche'),
 ('processroutes.failedn', 'en', '{n} failed'),
 ('processroutes.failedn', 'de', '{n} fehlgeschlagen'),
 ('processroutes.waiting', 'en', '{n} waiting'),
 ('processroutes.waiting', 'de', '{n} wartend'),
 ('processroutes.sourcesdeliver', 'en', 'Sources deliver here'),
 ('processroutes.sourcesdeliver', 'de', 'Quellen liefern hierhin'),
 ('processroutes.destsread', 'en', 'Destinations read from here'),
 ('processroutes.destsread', 'de', 'Ziele lesen von hier'),
 ('processroutes.nostages', 'en', 'This process has no stages yet, so nothing can arrive in it.'),
 ('processroutes.nostages', 'de', 'Dieser Prozess hat noch keine Stufen, daher kann nichts in ihm ankommen.'),
 ('processroutes.sourcetitle', 'en', 'Source'),
 ('processroutes.sourcetitle', 'de', 'Quelle'),
 ('processroutes.sourcesub', 'en', 'An instance of the {route} route, in {process}'),
 ('processroutes.sourcesub', 'de', 'Eine Instanz der Route {route} in {process}'),
 ('processroutes.destinationtitle', 'en', 'Destination'),
 ('processroutes.destinationtitle', 'de', 'Ziel'),
 ('processroutes.destsub', 'en', 'An instance of the {route} route, in {process}'),
 ('processroutes.destsub', 'de', 'Eine Instanz der Route {route} in {process}'),
 ('processroutes.field.route', 'en', 'Route'),
 ('processroutes.field.route', 'de', 'Route'),
 ('processroutes.field.deliversto', 'en', 'Delivers to stage'),
 ('processroutes.field.deliversto', 'de', 'Liefert an Stufe'),
 ('processroutes.field.readsfrom', 'en', 'Reads from stage'),
 ('processroutes.field.readsfrom', 'de', 'Liest aus Stufe'),
 ('processroutes.field.gateway', 'en', 'Gateway'),
 ('processroutes.field.gateway', 'de', 'Kanal'),
 ('processroutes.field.status', 'en', 'Status'),
 ('processroutes.field.status', 'de', 'Status'),
 ('processroutes.readsfromhint', 'en', 'approved, coded and matched'),
 ('processroutes.readsfromhint', 'de', 'genehmigt, kontiert und abgeglichen'),
 ('processroutes.status.active', 'en', 'Active'),
 ('processroutes.status.active', 'de', 'Aktiv'),
 ('processroutes.status.paused', 'en', 'Paused'),
 ('processroutes.status.paused', 'de', 'Pausiert'),
 ('processroutes.status.retired', 'en', 'Retired'),
 ('processroutes.status.retired', 'de', 'Stillgelegt'),
 ('processroutes.openexport', 'en', 'Open ERP export'),
 ('processroutes.openexport', 'de', 'ERP-Export öffnen'),
 ('processroutes.erpnote', 'en', 'The ERP export works as before, from its own screen: each payment-eligible invoice exported once, as a CSV file.'),
 ('processroutes.erpnote', 'de', 'Der ERP-Export funktioniert wie bisher über seine eigene Seite: jede zahlungsreife Rechnung wird einmal als CSV-Datei exportiert.'),
 ('processroutes.addsource', 'en', 'Add a source'),
 ('processroutes.addsource', 'de', 'Quelle hinzufügen'),
 ('processroutes.addsourcesub', 'en', 'A new way in to {process}, delivering to {stage}. An email source gets its address once it is created.'),
 ('processroutes.addsourcesub', 'de', 'Ein neuer Eingang in {process}, der an {stage} liefert. Eine E-Mail-Quelle erhält ihre Adresse, sobald sie angelegt ist.'),
 ('processroutes.howarrives', 'en', 'How it arrives'),
 ('processroutes.howarrives', 'de', 'Wie es ankommt');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.routes','nav.processroutes','help.screen.routes','help.screen.processroutes','routes.heading','routes.subtitle','routes.failed','routes.sources','routes.sourcessub','routes.destinations','routes.destinationssub','routes.col.route','routes.col.inout','routes.col.placed','routes.col.version','routes.standard','routes.copied','routes.live','routes.draft','routes.notplaced','routes.placedn','routes.placedinlist','routes.dir.source','routes.dir.destination','routes.standardroute','routes.copiedroute','routes.versionn','routes.part.1','routes.part.2','routes.part.3','routes.part.4','routes.part.5','routes.keeporiginal','routes.readsfrom','routes.readonly','routes.gw.email','routes.gw.https','routes.gw.sftp','routes.gw.file_import','routes.gw.edi','routes.gw.peppol','routes.gw.process','routes.gw.file_download','routes.gwd.email','routes.gwd.https','routes.gwd.sftp','routes.gwd.file_import','routes.gwd.edi','routes.gwd.peppol','routes.gwd.process','routes.gwd.file_download','routes.fmt.detected','routes.fmt.ubl','routes.fmt.cii','routes.fmt.factur_x','routes.fmt.supplier_xml','routes.fmt.en16931','routes.fmt.edifact','routes.fmt.csv','routes.fmt.idoc','routes.fmtd.detected','routes.fmtd.en16931','routes.fmtd.csv','routes.fmtd.edifact','routes.fmtd.ubl','routes.fmtd.cii','routes.fmtd.factur_x','routes.fmtd.supplier_xml','routes.fmtd.idoc','routes.tr.standard_intake','routes.tr.erp_csv_v1','routes.trd.standard_intake','routes.trd.erp_csv_v1','processroutes.heading','processroutes.subtitle','processroutes.failed','processroutes.source','processroutes.destination','processroutes.sources','processroutes.destinations','processroutes.deliverto','processroutes.readfrom','processroutes.nosources','processroutes.nodestinations','processroutes.notlive','processroutes.noaddress','processroutes.thisweek','processroutes.failedn','processroutes.waiting','processroutes.sourcesdeliver','processroutes.destsread','processroutes.nostages','processroutes.sourcetitle','processroutes.sourcesub','processroutes.destinationtitle','processroutes.destsub','processroutes.field.route','processroutes.field.deliversto','processroutes.field.readsfrom','processroutes.field.gateway','processroutes.field.status','processroutes.readsfromhint','processroutes.status.active','processroutes.status.paused','processroutes.status.retired','processroutes.openexport','processroutes.erpnote','processroutes.addsource','processroutes.addsourcesub','processroutes.howarrives') == 220
