-- 0210_route_fix_and_tell_strings.sql
-- Decision 0559. Reprocess, dismiss and alerts in the Route monitor: the
-- buttons, the dismiss pop-out, why a message cannot be run again, the
-- history's new events, and the Alerts pop-out with its refusals.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('routemonitor.alerts', 'en', 'Alerts'),
 ('routemonitor.alerts', 'de', 'Benachrichtigungen'),
 ('routemonitor.reprocess', 'en', 'Reprocess'),
 ('routemonitor.reprocess', 'de', 'Erneut verarbeiten'),
 ('routemonitor.reprocessall', 'en', 'Reprocess {n} like it'),
 ('routemonitor.reprocessall', 'de', '{n} ähnliche erneut verarbeiten'),
 ('routemonitor.dismiss', 'en', 'Dismiss'),
 ('routemonitor.dismiss', 'de', 'Verwerfen'),
 ('routemonitor.reprocessfailed', 'en', 'It could not be run again. Try again.'),
 ('routemonitor.reprocessfailed', 'de', 'Sie konnte nicht erneut verarbeitet werden. Bitte erneut versuchen.'),
 ('routemonitor.reprocessed', 'en', '{n} run again: {d} delivered.'),
 ('routemonitor.reprocessed', 'de', '{n} erneut verarbeitet: {d} zugestellt.'),
 ('routemonitor.dismisstitle', 'en', 'Dismiss this message'),
 ('routemonitor.dismisstitle', 'de', 'Diese Nachricht verwerfen'),
 ('routemonitor.dismissexplain', 'en', 'It stays on the record, with what failed and why, and stops counting as waiting to be fixed.'),
 ('routemonitor.dismissexplain', 'de', 'Sie bleibt erfasst, mit dem Fehler und seinem Grund, zählt aber nicht mehr als offen.'),
 ('routemonitor.dismisslabel', 'en', 'Why is it being dismissed?'),
 ('routemonitor.dismisslabel', 'de', 'Warum wird sie verworfen?'),
 ('routemonitor.dismissplaceholder', 'en', 'For example: a portal notification, not an invoice'),
 ('routemonitor.dismissplaceholder', 'de', 'Zum Beispiel: eine Portal-Benachrichtigung, keine Rechnung'),
 ('routemonitor.dismissneedsreason', 'en', 'Give a reason. It shows in the message''s history.'),
 ('routemonitor.dismissneedsreason', 'de', 'Bitte einen Grund angeben. Er erscheint im Verlauf der Nachricht.'),
 ('routemonitor.dismissfailed', 'en', 'It could not be dismissed. Try again.'),
 ('routemonitor.dismissfailed', 'de', 'Sie konnte nicht verworfen werden. Bitte erneut versuchen.'),
 ('routemonitor.cannot.outbound', 'en', 'Sent out: to send it again, export again from the ERP export screen.'),
 ('routemonitor.cannot.outbound', 'de', 'Ausgehend: Zum erneuten Senden über die Seite ERP-Export erneut exportieren.'),
 ('routemonitor.cannot.no_original', 'en', 'Its original was not kept, so it cannot be run again.'),
 ('routemonitor.cannot.no_original', 'de', 'Ihr Original wurde nicht aufbewahrt, daher kann sie nicht erneut verarbeitet werden.'),
 ('routemonitor.cannot.source_retired', 'en', 'Its route is retired, so it cannot be run again.'),
 ('routemonitor.cannot.source_retired', 'de', 'Ihre Route ist stillgelegt, daher kann sie nicht erneut verarbeitet werden.'),
 ('routemonitor.cannot.not_failed', 'en', 'There is nothing to run again.'),
 ('routemonitor.cannot.not_failed', 'de', 'Es gibt nichts erneut zu verarbeiten.'),
 ('routemonitor.cannot.no_bucket', 'en', 'Stored documents cannot be read here, so it cannot be run again.'),
 ('routemonitor.cannot.no_bucket', 'de', 'Gespeicherte Dokumente können hier nicht gelesen werden, daher ist keine erneute Verarbeitung möglich.'),
 ('routemonitor.cannot.no_model', 'en', 'Reading invoices is not set up here, so it cannot be run again.'),
 ('routemonitor.cannot.no_model', 'de', 'Das Lesen von Rechnungen ist hier nicht eingerichtet, daher ist keine erneute Verarbeitung möglich.'),
 ('routemonitor.event.reprocessed', 'en', 'Run again'),
 ('routemonitor.event.reprocessed', 'de', 'Erneut verarbeitet'),
 ('routemonitor.event.dismissed', 'en', 'Dismissed'),
 ('routemonitor.event.dismissed', 'de', 'Verworfen'),
 ('routemonitor.alert.explain', 'en', 'Tell your IT team when a route needs them: by email, or by a signed webhook to your own monitoring. Routes gone quiet are checked every six hours.'),
 ('routemonitor.alert.explain', 'de', 'Benachrichtigen Sie Ihr IT-Team, wenn eine Route es braucht: per E-Mail oder per signiertem Webhook an Ihr eigenes Monitoring. Stille Routen werden alle sechs Stunden geprüft.'),
 ('routemonitor.alert.allroutes', 'en', 'All routes'),
 ('routemonitor.alert.allroutes', 'de', 'Alle Routen'),
 ('routemonitor.alert.eachfailure', 'en', 'Each message that fails'),
 ('routemonitor.alert.eachfailure', 'de', 'Jede fehlgeschlagene Nachricht'),
 ('routemonitor.alert.perday', 'en', 'When a day''s failures reach {n}'),
 ('routemonitor.alert.perday', 'de', 'Wenn die Fehler eines Tages {n} erreichen'),
 ('routemonitor.alert.silent', 'en', 'When nothing arrives for {n} hours'),
 ('routemonitor.alert.silent', 'de', 'Wenn {n} Stunden lang nichts ankommt'),
 ('routemonitor.alert.perdayform', 'en', 'A day''s failures reach'),
 ('routemonitor.alert.perdayform', 'de', 'Die Fehler eines Tages erreichen'),
 ('routemonitor.alert.silentform', 'en', 'Nothing arrives for (hours)'),
 ('routemonitor.alert.silentform', 'de', 'Nichts kommt an für (Stunden)'),
 ('routemonitor.alert.none', 'en', 'No alerts yet. Add one below.'),
 ('routemonitor.alert.none', 'de', 'Noch keine Benachrichtigungen. Fügen Sie unten eine hinzu.'),
 ('routemonitor.alert.test', 'en', 'Test'),
 ('routemonitor.alert.test', 'de', 'Testen'),
 ('routemonitor.alert.change', 'en', 'Change'),
 ('routemonitor.alert.change', 'de', 'Ändern'),
 ('routemonitor.alert.delete', 'en', 'Delete'),
 ('routemonitor.alert.delete', 'de', 'Löschen'),
 ('routemonitor.alert.tested', 'en', 'Test sent: {outcome}'),
 ('routemonitor.alert.tested', 'de', 'Test gesendet: {outcome}'),
 ('routemonitor.alert.failed', 'en', 'The alert could not be saved. Try again.'),
 ('routemonitor.alert.failed', 'de', 'Die Benachrichtigung konnte nicht gespeichert werden. Bitte erneut versuchen.'),
 ('routemonitor.alert.secret', 'en', 'Webhook calls are signed with {secret} (header X-VibeFinance-Signature)'),
 ('routemonitor.alert.secret', 'de', 'Webhook-Aufrufe werden mit {secret} signiert (Header X-VibeFinance-Signature)'),
 ('routemonitor.alert.lastsent', 'en', 'Last sent {when}: {outcome}'),
 ('routemonitor.alert.lastsent', 'de', 'Zuletzt gesendet {when}: {outcome}'),
 ('routemonitor.alert.save', 'en', 'Save'),
 ('routemonitor.alert.save', 'de', 'Speichern'),
 ('routemonitor.alert.add', 'en', 'Add alert'),
 ('routemonitor.alert.add', 'de', 'Benachrichtigung hinzufügen'),
 ('routemonitor.alert.new', 'en', 'A new alert'),
 ('routemonitor.alert.new', 'de', 'Eine neue Benachrichtigung'),
 ('routemonitor.alert.changetitle', 'en', 'Change this alert'),
 ('routemonitor.alert.changetitle', 'de', 'Diese Benachrichtigung ändern'),
 ('routemonitor.alert.route', 'en', 'Route'),
 ('routemonitor.alert.route', 'de', 'Route'),
 ('routemonitor.alert.when', 'en', 'Tell when'),
 ('routemonitor.alert.when', 'de', 'Benachrichtigen, wenn'),
 ('routemonitor.alert.emails', 'en', 'Email to (a comma between addresses)'),
 ('routemonitor.alert.emails', 'de', 'E-Mail an (Adressen mit Komma trennen)'),
 ('routemonitor.alert.webhook', 'en', 'Webhook (https)'),
 ('routemonitor.alert.webhook', 'de', 'Webhook (https)'),
 ('routemonitor.alert.cancel', 'en', 'Cancel'),
 ('routemonitor.alert.cancel', 'de', 'Abbrechen'),
 ('routemonitor.alert.refused.nothing_to_alert', 'en', 'Choose when to tell someone.'),
 ('routemonitor.alert.refused.nothing_to_alert', 'de', 'Wählen Sie, wann benachrichtigt werden soll.'),
 ('routemonitor.alert.refused.no_recipient', 'en', 'Give an email address or a webhook.'),
 ('routemonitor.alert.refused.no_recipient', 'de', 'Geben Sie eine E-Mail-Adresse oder einen Webhook an.'),
 ('routemonitor.alert.refused.invalid_email', 'en', 'One of the email addresses is not an address.'),
 ('routemonitor.alert.refused.invalid_email', 'de', 'Eine der E-Mail-Adressen ist keine gültige Adresse.'),
 ('routemonitor.alert.refused.invalid_webhook', 'en', 'The webhook must be an https address.'),
 ('routemonitor.alert.refused.invalid_webhook', 'de', 'Der Webhook muss eine https-Adresse sein.'),
 ('routemonitor.alert.refused.invalid_threshold', 'en', 'The daily number must be a whole number from 1.'),
 ('routemonitor.alert.refused.invalid_threshold', 'de', 'Die Tageszahl muss eine ganze Zahl ab 1 sein.'),
 ('routemonitor.alert.refused.invalid_silence', 'en', 'The hours must be a whole number from 1 to 720.'),
 ('routemonitor.alert.refused.invalid_silence', 'de', 'Die Stunden müssen eine ganze Zahl von 1 bis 720 sein.'),
 ('routemonitor.alert.refused.silence_needs_source', 'en', 'Only a Source can go quiet: choose a Source, or leave that unticked.'),
 ('routemonitor.alert.refused.silence_needs_source', 'de', 'Nur eine Quelle kann still werden: Wählen Sie eine Quelle oder lassen Sie dies leer.'),
 ('routemonitor.alert.refused.unknown_route', 'en', 'That route no longer exists.'),
 ('routemonitor.alert.refused.unknown_route', 'de', 'Diese Route gibt es nicht mehr.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('routemonitor.alerts','routemonitor.reprocess','routemonitor.reprocessall','routemonitor.dismiss','routemonitor.reprocessfailed','routemonitor.reprocessed','routemonitor.dismisstitle','routemonitor.dismissexplain','routemonitor.dismisslabel','routemonitor.dismissplaceholder','routemonitor.dismissneedsreason','routemonitor.dismissfailed','routemonitor.cannot.outbound','routemonitor.cannot.no_original','routemonitor.cannot.source_retired','routemonitor.cannot.not_failed','routemonitor.cannot.no_bucket','routemonitor.cannot.no_model','routemonitor.event.reprocessed','routemonitor.event.dismissed','routemonitor.alert.explain','routemonitor.alert.allroutes','routemonitor.alert.eachfailure','routemonitor.alert.perday','routemonitor.alert.silent','routemonitor.alert.perdayform','routemonitor.alert.silentform','routemonitor.alert.none','routemonitor.alert.test','routemonitor.alert.change','routemonitor.alert.delete','routemonitor.alert.tested','routemonitor.alert.failed','routemonitor.alert.secret','routemonitor.alert.lastsent','routemonitor.alert.save','routemonitor.alert.add','routemonitor.alert.new','routemonitor.alert.changetitle','routemonitor.alert.route','routemonitor.alert.when','routemonitor.alert.emails','routemonitor.alert.webhook','routemonitor.alert.cancel','routemonitor.alert.refused.nothing_to_alert','routemonitor.alert.refused.no_recipient','routemonitor.alert.refused.invalid_email','routemonitor.alert.refused.invalid_webhook','routemonitor.alert.refused.invalid_threshold','routemonitor.alert.refused.invalid_silence','routemonitor.alert.refused.silence_needs_source','routemonitor.alert.refused.unknown_route') == 104
