-- 0211_formats_and_en16931_strings.sql
-- Decision 0560. Routes, phase 2 slice 1: structured formats in. The
-- Routes screen's receiving-formats panel, the format and syntax names, the
-- Route monitor's e-invoice checks, and each EN 16931 business rule we check
-- in words (the rule identifiers are the official ones).

INSERT INTO ui_strings (key, locale, value) VALUES
 ('routes.formats.heading', 'en', 'Receiving formats'),
 ('routes.formats.heading', 'de', 'Empfangsformate'),
 ('routes.formats.sub', 'en', 'Recognised for each attachment, in this order. An invoice sent as data is read as data, never from its picture.'),
 ('routes.formats.sub', 'de', 'Für jeden Anhang in dieser Reihenfolge erkannt. Eine Rechnung, die als Daten kommt, wird als Daten gelesen, nie von ihrem Bild.'),
 ('routes.formats.col.format', 'en', 'Format'),
 ('routes.formats.col.format', 'de', 'Format'),
 ('routes.formats.col.how', 'en', 'How it is read'),
 ('routes.formats.col.how', 'de', 'Wie es gelesen wird'),
 ('routes.formats.col.checked', 'en', 'Checked on arrival against'),
 ('routes.formats.col.checked', 'de', 'Beim Eingang geprüft gegen'),
 ('routes.formats.col.days', 'en', 'Last 30 days'),
 ('routes.formats.col.days', 'de', 'Letzte 30 Tage'),
 ('routes.formats.xrechnung', 'en', 'XRechnung'),
 ('routes.formats.xrechnung', 'de', 'XRechnung'),
 ('routes.formats.xrechnung.syntax', 'en', 'UBL or CII'),
 ('routes.formats.xrechnung.syntax', 'de', 'UBL oder CII'),
 ('routes.formats.xrechnung.how', 'en', 'As data'),
 ('routes.formats.xrechnung.how', 'de', 'Als Daten'),
 ('routes.formats.xrechnung.checked', 'en', 'EN 16931, and the buyer reference XRechnung requires (BR-DE-15)'),
 ('routes.formats.xrechnung.checked', 'de', 'EN 16931 und die von XRechnung verlangte Käuferreferenz (BR-DE-15)'),
 ('routes.formats.peppol_bis_3', 'en', 'Peppol BIS Billing 3.0'),
 ('routes.formats.peppol_bis_3', 'de', 'Peppol BIS Billing 3.0'),
 ('routes.formats.peppol_bis_3.syntax', 'en', 'UBL'),
 ('routes.formats.peppol_bis_3.syntax', 'de', 'UBL'),
 ('routes.formats.peppol_bis_3.how', 'en', 'As data'),
 ('routes.formats.peppol_bis_3.how', 'de', 'Als Daten'),
 ('routes.formats.peppol_bis_3.checked', 'en', 'EN 16931'),
 ('routes.formats.peppol_bis_3.checked', 'de', 'EN 16931'),
 ('routes.formats.en16931', 'en', 'EN 16931'),
 ('routes.formats.en16931', 'de', 'EN 16931'),
 ('routes.formats.en16931.syntax', 'en', 'UBL or CII, with no national rules'),
 ('routes.formats.en16931.syntax', 'de', 'UBL oder CII, ohne nationale Regeln'),
 ('routes.formats.en16931.how', 'en', 'As data'),
 ('routes.formats.en16931.how', 'de', 'Als Daten'),
 ('routes.formats.en16931.checked', 'en', 'EN 16931'),
 ('routes.formats.en16931.checked', 'de', 'EN 16931'),
 ('routes.formats.factur_x', 'en', 'ZUGFeRD / Factur-X'),
 ('routes.formats.factur_x', 'de', 'ZUGFeRD / Factur-X'),
 ('routes.formats.factur_x.syntax', 'en', 'A PDF with the XML inside'),
 ('routes.formats.factur_x.syntax', 'de', 'Ein PDF mit dem XML darin'),
 ('routes.formats.factur_x.how', 'en', 'The XML inside, as data. The PDF is kept as the picture people see'),
 ('routes.formats.factur_x.how', 'de', 'Das XML darin, als Daten. Das PDF bleibt als das Bild, das Menschen sehen'),
 ('routes.formats.factur_x.checked', 'en', 'EN 16931, from the BASIC profile up. MINIMUM and BASIC WL are recognised and not checked: they are not full invoices'),
 ('routes.formats.factur_x.checked', 'de', 'EN 16931, ab dem Profil BASIC. MINIMUM und BASIC WL werden erkannt und nicht geprüft: Sie sind keine vollständigen Rechnungen'),
 ('routes.formats.other', 'en', 'Another UBL or CII invoice'),
 ('routes.formats.other', 'de', 'Eine andere UBL- oder CII-Rechnung'),
 ('routes.formats.other.syntax', 'en', 'Declaring another specification'),
 ('routes.formats.other.syntax', 'de', 'Mit Angabe einer anderen Spezifikation'),
 ('routes.formats.other.how', 'en', 'As data'),
 ('routes.formats.other.how', 'de', 'Als Daten'),
 ('routes.formats.other.checked', 'en', 'EN 16931'),
 ('routes.formats.other.checked', 'de', 'EN 16931'),
 ('routes.formats.picture', 'en', 'PDF or image'),
 ('routes.formats.picture', 'de', 'PDF oder Bild'),
 ('routes.formats.picture.syntax', 'en', 'No data inside'),
 ('routes.formats.picture.syntax', 'de', 'Keine Daten darin'),
 ('routes.formats.picture.how', 'en', 'AI reading, as before'),
 ('routes.formats.picture.how', 'de', 'KI-Lesung, wie bisher'),
 ('routes.formats.picture.checked', 'en', 'The usual intake checks'),
 ('routes.formats.picture.checked', 'de', 'Die üblichen Eingangsprüfungen'),
 ('routes.formats.failing', 'en', '{n} broke a rule'),
 ('routes.formats.failing', 'de', '{n} mit Regelverstoß'),
 ('routes.formats.unread', 'en', '{n} attachments in the last 30 days could not be read at all. The Route monitor says why.'),
 ('routes.formats.unread', 'de', '{n} Anhänge der letzten 30 Tage konnten gar nicht gelesen werden. Der Routen-Monitor sagt, warum.'),
 ('routes.formats.notstopped.h', 'en', 'A broken rule does not stop an invoice'),
 ('routes.formats.notstopped.h', 'de', 'Ein Regelverstoß hält keine Rechnung auf'),
 ('routes.formats.notstopped', 'en', 'It carries on to the process with the rules it broke recorded, so a rule of yours can route it: for example, en16931.failures contains BR-CO-16.'),
 ('routes.formats.notstopped', 'de', 'Sie geht mit den verletzten Regeln in den Prozess weiter, damit eine Ihrer Regeln sie leiten kann: zum Beispiel en16931.failures contains BR-CO-16.'),
 ('routes.format.peppol_bis_3', 'en', 'Peppol BIS Billing 3.0'),
 ('routes.format.peppol_bis_3', 'de', 'Peppol BIS Billing 3.0'),
 ('routes.format.xrechnung', 'en', 'XRechnung'),
 ('routes.format.xrechnung', 'de', 'XRechnung'),
 ('routes.format.en16931', 'en', 'EN 16931'),
 ('routes.format.en16931', 'de', 'EN 16931'),
 ('routes.format.factur_x_extended', 'en', 'Factur-X / ZUGFeRD EXTENDED'),
 ('routes.format.factur_x_extended', 'de', 'Factur-X / ZUGFeRD EXTENDED'),
 ('routes.format.factur_x_basic', 'en', 'Factur-X / ZUGFeRD BASIC'),
 ('routes.format.factur_x_basic', 'de', 'Factur-X / ZUGFeRD BASIC'),
 ('routes.format.factur_x_basic_wl', 'en', 'Factur-X / ZUGFeRD BASIC WL'),
 ('routes.format.factur_x_basic_wl', 'de', 'Factur-X / ZUGFeRD BASIC WL'),
 ('routes.format.factur_x_minimum', 'en', 'Factur-X / ZUGFeRD MINIMUM'),
 ('routes.format.factur_x_minimum', 'de', 'Factur-X / ZUGFeRD MINIMUM'),
 ('routes.format.ubl_other', 'en', 'UBL invoice'),
 ('routes.format.ubl_other', 'de', 'UBL-Rechnung'),
 ('routes.format.cii_other', 'en', 'CII invoice'),
 ('routes.format.cii_other', 'de', 'CII-Rechnung'),
 ('routes.syntax.ubl', 'en', 'UBL'),
 ('routes.syntax.ubl', 'de', 'UBL'),
 ('routes.syntax.cii', 'en', 'CII'),
 ('routes.syntax.cii', 'de', 'CII'),
 ('routemonitor.checks', 'en', 'E-invoice checks'),
 ('routemonitor.checks', 'de', 'E-Rechnungs-Prüfungen'),
 ('routemonitor.passed', 'en', 'Passed EN 16931'),
 ('routemonitor.passed', 'de', 'EN 16931 bestanden'),
 ('routemonitor.notchecked', 'en', 'Not checked'),
 ('routemonitor.notchecked', 'de', 'Nicht geprüft'),
 ('routemonitor.notcheckedwhy', 'en', 'A MINIMUM or BASIC WL profile is not a full invoice, so it is not checked against EN 16931.'),
 ('routemonitor.notcheckedwhy', 'de', 'Ein Profil MINIMUM oder BASIC WL ist keine vollständige Rechnung und wird daher nicht gegen EN 16931 geprüft.'),
 ('routemonitor.brokenn', 'en', '{n} rules broken'),
 ('routemonitor.brokenn', 'de', '{n} Regeln verletzt'),
 ('routemonitor.notstopped', 'en', 'The invoice was still delivered to the process. A rule on en16931.failures can route invoices like it.'),
 ('routemonitor.notstopped', 'de', 'Die Rechnung wurde trotzdem an den Prozess übergeben. Eine Regel auf en16931.failures kann solche Rechnungen leiten.'),
 ('routemonitor.event.en16931_failed', 'en', 'EN 16931 rules broken'),
 ('routemonitor.event.en16931_failed', 'de', 'EN-16931-Regeln verletzt'),
 ('en16931.rule.br-01', 'en', 'The specification identifier (BT-24) is missing.'),
 ('en16931.rule.br-01', 'de', 'Die Spezifikationskennung (BT-24) fehlt.'),
 ('en16931.rule.br-02', 'en', 'The invoice number (BT-1) is missing.'),
 ('en16931.rule.br-02', 'de', 'Die Rechnungsnummer (BT-1) fehlt.'),
 ('en16931.rule.br-03', 'en', 'The issue date (BT-2) is missing.'),
 ('en16931.rule.br-03', 'de', 'Das Rechnungsdatum (BT-2) fehlt.'),
 ('en16931.rule.br-04', 'en', 'The invoice type code (BT-3) is missing.'),
 ('en16931.rule.br-04', 'de', 'Der Rechnungsartcode (BT-3) fehlt.'),
 ('en16931.rule.br-05', 'en', 'The invoice currency (BT-5) is missing.'),
 ('en16931.rule.br-05', 'de', 'Die Rechnungswährung (BT-5) fehlt.'),
 ('en16931.rule.br-06', 'en', 'The seller''s name (BT-27) is missing.'),
 ('en16931.rule.br-06', 'de', 'Der Name des Verkäufers (BT-27) fehlt.'),
 ('en16931.rule.br-07', 'en', 'The buyer''s name (BT-44) is missing.'),
 ('en16931.rule.br-07', 'de', 'Der Name des Käufers (BT-44) fehlt.'),
 ('en16931.rule.br-08', 'en', 'The seller''s postal address is missing.'),
 ('en16931.rule.br-08', 'de', 'Die Anschrift des Verkäufers fehlt.'),
 ('en16931.rule.br-09', 'en', 'The seller''s country code (BT-40) is missing.'),
 ('en16931.rule.br-09', 'de', 'Der Ländercode des Verkäufers (BT-40) fehlt.'),
 ('en16931.rule.br-10', 'en', 'The buyer''s postal address is missing.'),
 ('en16931.rule.br-10', 'de', 'Die Anschrift des Käufers fehlt.'),
 ('en16931.rule.br-11', 'en', 'The buyer''s country code (BT-55) is missing.'),
 ('en16931.rule.br-11', 'de', 'Der Ländercode des Käufers (BT-55) fehlt.'),
 ('en16931.rule.br-12', 'en', 'The sum of line net amounts (BT-106) is missing.'),
 ('en16931.rule.br-12', 'de', 'Die Summe der Nettobeträge der Positionen (BT-106) fehlt.'),
 ('en16931.rule.br-13', 'en', 'The total without VAT (BT-109) is missing.'),
 ('en16931.rule.br-13', 'de', 'Der Gesamtbetrag ohne Umsatzsteuer (BT-109) fehlt.'),
 ('en16931.rule.br-14', 'en', 'The total with VAT (BT-112) is missing.'),
 ('en16931.rule.br-14', 'de', 'Der Gesamtbetrag mit Umsatzsteuer (BT-112) fehlt.'),
 ('en16931.rule.br-15', 'en', 'The amount due (BT-115) is missing.'),
 ('en16931.rule.br-15', 'de', 'Der fällige Betrag (BT-115) fehlt.'),
 ('en16931.rule.br-16', 'en', 'The invoice has no lines.'),
 ('en16931.rule.br-16', 'de', 'Die Rechnung hat keine Positionen.'),
 ('en16931.rule.br-21', 'en', 'A line has no line identifier (BT-126).'),
 ('en16931.rule.br-21', 'de', 'Einer Position fehlt die Positionsnummer (BT-126).'),
 ('en16931.rule.br-22', 'en', 'A line has no quantity (BT-129).'),
 ('en16931.rule.br-22', 'de', 'Einer Position fehlt die Menge (BT-129).'),
 ('en16931.rule.br-23', 'en', 'A line''s quantity has no unit of measure (BT-130).'),
 ('en16931.rule.br-23', 'de', 'Der Menge einer Position fehlt die Einheit (BT-130).'),
 ('en16931.rule.br-24', 'en', 'A line has no net amount (BT-131).'),
 ('en16931.rule.br-24', 'de', 'Einer Position fehlt der Nettobetrag (BT-131).'),
 ('en16931.rule.br-25', 'en', 'A line has no item name (BT-153).'),
 ('en16931.rule.br-25', 'de', 'Einer Position fehlt die Artikelbezeichnung (BT-153).'),
 ('en16931.rule.br-26', 'en', 'A line has no net price (BT-146).'),
 ('en16931.rule.br-26', 'de', 'Einer Position fehlt der Nettopreis (BT-146).'),
 ('en16931.rule.br-27', 'en', 'A line''s net price is negative.'),
 ('en16931.rule.br-27', 'de', 'Der Nettopreis einer Position ist negativ.'),
 ('en16931.rule.br-co-9', 'en', 'A VAT identifier does not start with a country code.'),
 ('en16931.rule.br-co-9', 'de', 'Eine Umsatzsteuer-ID beginnt nicht mit einem Ländercode.'),
 ('en16931.rule.br-co-10', 'en', 'The line amounts do not add up to the sum of lines (BT-106).'),
 ('en16931.rule.br-co-10', 'de', 'Die Positionsbeträge ergeben nicht die Summe der Positionen (BT-106).'),
 ('en16931.rule.br-co-13', 'en', 'The total without VAT (BT-109) is not the sum of lines less allowances plus charges.'),
 ('en16931.rule.br-co-13', 'de', 'Der Gesamtbetrag ohne Umsatzsteuer (BT-109) ist nicht die Positionssumme abzüglich Nachlässen zuzüglich Zuschlägen.'),
 ('en16931.rule.br-co-15', 'en', 'The total with VAT (BT-112) is not the total without VAT plus the VAT.'),
 ('en16931.rule.br-co-15', 'de', 'Der Gesamtbetrag mit Umsatzsteuer (BT-112) ist nicht der Betrag ohne Umsatzsteuer plus Umsatzsteuer.'),
 ('en16931.rule.br-co-16', 'en', 'The amount due (BT-115) does not follow from the total, the amount paid and rounding.'),
 ('en16931.rule.br-co-16', 'de', 'Der fällige Betrag (BT-115) ergibt sich nicht aus Gesamtbetrag, gezahltem Betrag und Rundung.'),
 ('en16931.rule.br-co-25', 'en', 'An amount is due but there is no due date (BT-9) and no payment terms (BT-20).'),
 ('en16931.rule.br-co-25', 'de', 'Ein Betrag ist fällig, aber es gibt weder Fälligkeitsdatum (BT-9) noch Zahlungsbedingungen (BT-20).'),
 ('en16931.rule.br-de-15', 'en', 'An XRechnung must give the buyer reference (BT-10), such as a Leitweg-ID.'),
 ('en16931.rule.br-de-15', 'de', 'Eine XRechnung muss die Käuferreferenz (BT-10) enthalten, etwa eine Leitweg-ID.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('routes.formats.heading','routes.formats.sub','routes.formats.col.format','routes.formats.col.how','routes.formats.col.checked','routes.formats.col.days','routes.formats.xrechnung','routes.formats.xrechnung.syntax','routes.formats.xrechnung.how','routes.formats.xrechnung.checked','routes.formats.peppol_bis_3','routes.formats.peppol_bis_3.syntax','routes.formats.peppol_bis_3.how','routes.formats.peppol_bis_3.checked','routes.formats.en16931','routes.formats.en16931.syntax','routes.formats.en16931.how','routes.formats.en16931.checked','routes.formats.factur_x','routes.formats.factur_x.syntax','routes.formats.factur_x.how','routes.formats.factur_x.checked','routes.formats.other','routes.formats.other.syntax','routes.formats.other.how','routes.formats.other.checked','routes.formats.picture','routes.formats.picture.syntax','routes.formats.picture.how','routes.formats.picture.checked','routes.formats.failing','routes.formats.unread','routes.formats.notstopped.h','routes.formats.notstopped','routes.format.peppol_bis_3','routes.format.xrechnung','routes.format.en16931','routes.format.factur_x_extended','routes.format.factur_x_basic','routes.format.factur_x_basic_wl','routes.format.factur_x_minimum','routes.format.ubl_other','routes.format.cii_other','routes.syntax.ubl','routes.syntax.cii','routemonitor.checks','routemonitor.passed','routemonitor.notchecked','routemonitor.notcheckedwhy','routemonitor.brokenn','routemonitor.notstopped','routemonitor.event.en16931_failed','en16931.rule.br-01','en16931.rule.br-02','en16931.rule.br-03','en16931.rule.br-04','en16931.rule.br-05','en16931.rule.br-06','en16931.rule.br-07','en16931.rule.br-08','en16931.rule.br-09','en16931.rule.br-10','en16931.rule.br-11','en16931.rule.br-12','en16931.rule.br-13','en16931.rule.br-14','en16931.rule.br-15','en16931.rule.br-16','en16931.rule.br-21','en16931.rule.br-22','en16931.rule.br-23','en16931.rule.br-24','en16931.rule.br-25','en16931.rule.br-26','en16931.rule.br-27','en16931.rule.br-co-9','en16931.rule.br-co-10','en16931.rule.br-co-13','en16931.rule.br-co-15','en16931.rule.br-co-16','en16931.rule.br-co-25','en16931.rule.br-de-15') == 164
