-- 0212_supplier_mapping_strings.sql
-- Decision 0561. Supplier mappings: the mapping editor, the functions and
-- Business Terms by name, the Route monitor's way into the editor, and the
-- Routes screen's Supplier mappings panel and format row.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('mapping.title', 'en', 'Mapping: {name}'),
 ('mapping.title', 'de', 'Zuordnung: {name}'),
 ('mapping.subtitle', 'en', 'Translation'),
 ('mapping.subtitle', 'de', 'Übersetzung'),
 ('mapping.draftn', 'en', 'draft version {n}, not live'),
 ('mapping.draftn', 'de', 'Entwurf Version {n}, nicht aktiv'),
 ('mapping.liven', 'en', 'live version {n}'),
 ('mapping.liven', 'de', 'aktive Version {n}'),
 ('mapping.livebeside', 'en', 'live: version {n}'),
 ('mapping.livebeside', 'de', 'aktiv: Version {n}'),
 ('mapping.samplefrom', 'en', 'drawn from {file}'),
 ('mapping.samplefrom', 'de', 'erstellt aus {file}'),
 ('mapping.heading', 'en', '<{root}> → EN 16931 invoice'),
 ('mapping.heading', 'de', '<{root}> → EN-16931-Rechnung'),
 ('mapping.counts', 'en', 'Mapped: {m}, with a function: {f}. Required terms still needing a source: {r}.'),
 ('mapping.counts', 'de', 'Zugeordnet: {m}, mit Funktion: {f}. Pflichtangaben ohne Quelle: {r}.'),
 ('mapping.legend.line', 'en', 'Mapped'),
 ('mapping.legend.line', 'de', 'Zugeordnet'),
 ('mapping.legend.fx', 'en', 'a function changes the value on the way'),
 ('mapping.legend.fx', 'de', 'eine Funktion ändert den Wert unterwegs'),
 ('mapping.legend.required', 'en', 'required by EN 16931'),
 ('mapping.legend.required', 'de', 'Pflicht nach EN 16931'),
 ('mapping.receiving', 'en', 'Receiving format'),
 ('mapping.receiving', 'de', 'Empfangsformat'),
 ('mapping.receivingsub', 'en', 'The supplier''s own <{root}> · element and sample value'),
 ('mapping.receivingsub', 'de', 'Das eigene <{root}> des Lieferanten · Element und Beispielwert'),
 ('mapping.eachline', 'en', 'each line'),
 ('mapping.eachline', 'de', 'jede Position'),
 ('mapping.delivery', 'en', 'Delivery format'),
 ('mapping.delivery', 'de', 'Zielformat'),
 ('mapping.deliverysub', 'en', 'EN 16931 invoice · the model in the middle'),
 ('mapping.deliverysub', 'de', 'EN-16931-Rechnung · das Modell in der Mitte'),
 ('mapping.invoice', 'en', 'Invoice'),
 ('mapping.invoice', 'de', 'Rechnung'),
 ('mapping.invoiceline', 'en', 'Invoice line'),
 ('mapping.invoiceline', 'de', 'Rechnungsposition'),
 ('mapping.fixed', 'en', 'A fixed value'),
 ('mapping.fixed', 'de', 'Ein fester Wert'),
 ('mapping.needed', 'en', 'Needs a source'),
 ('mapping.needed', 'de', 'Braucht eine Quelle'),
 ('mapping.howto', 'en', 'How to map'),
 ('mapping.howto', 'de', 'So ordnen Sie zu'),
 ('mapping.howtotext', 'en', 'Choose an element on the left, then the term it becomes on the right, or the other way round. Choose a mapped term to give it a function, in your own words.'),
 ('mapping.howtotext', 'de', 'Wählen Sie links ein Element und rechts die Angabe, die daraus wird, oder umgekehrt. Wählen Sie eine zugeordnete Angabe, um ihr in Ihren eigenen Worten eine Funktion zu geben.'),
 ('mapping.required', 'en', 'Required on every invoice.'),
 ('mapping.required', 'de', 'Auf jeder Rechnung Pflicht.'),
 ('mapping.optional', 'en', 'Not required, but used where the document gives it.'),
 ('mapping.optional', 'de', 'Keine Pflicht, wird aber genutzt, wo das Dokument sie enthält.'),
 ('mapping.choosesource', 'en', 'Choose the element on the left that holds it.'),
 ('mapping.choosesource', 'de', 'Wählen Sie links das Element, das sie enthält.'),
 ('mapping.orfixed', 'en', 'Or, where the document never gives it, a fixed value:'),
 ('mapping.orfixed', 'de', 'Oder, wo das Dokument sie nie enthält, ein fester Wert:'),
 ('mapping.fixedplaceholder', 'en', 'For example 380, a commercial invoice'),
 ('mapping.fixedplaceholder', 'de', 'Zum Beispiel 380, eine Handelsrechnung'),
 ('mapping.usefixed', 'en', 'Use this value'),
 ('mapping.usefixed', 'de', 'Diesen Wert verwenden'),
 ('mapping.from', 'en', 'From'),
 ('mapping.from', 'de', 'Aus'),
 ('mapping.sample', 'en', 'Sample'),
 ('mapping.sample', 'de', 'Beispiel'),
 ('mapping.function', 'en', 'Function'),
 ('mapping.function', 'de', 'Funktion'),
 ('mapping.nofunction', 'en', 'The value is used as it is written. Say what should happen to it, if anything.'),
 ('mapping.nofunction', 'de', 'Der Wert wird so verwendet, wie er geschrieben ist. Sagen Sie, was damit geschehen soll, falls nötig.'),
 ('mapping.sayplaceholder', 'en', 'For example: read it as day.month.year'),
 ('mapping.sayplaceholder', 'de', 'Zum Beispiel: als Tag.Monat.Jahr lesen'),
 ('mapping.understand', 'en', 'Understand'),
 ('mapping.understand', 'de', 'Verstehen'),
 ('mapping.understood', 'en', 'Understood as'),
 ('mapping.understood', 'de', 'Verstanden als'),
 ('mapping.examples', 'en', 'Worked examples, from this sample''s own values'),
 ('mapping.examples', 'de', 'Durchgerechnete Beispiele aus den Werten dieses Beispiels'),
 ('mapping.none', 'en', '(nothing)'),
 ('mapping.none', 'de', '(nichts)'),
 ('mapping.accept', 'en', 'Accept'),
 ('mapping.accept', 'de', 'Übernehmen'),
 ('mapping.compilefailed', 'en', 'It could not be understood. Try again.'),
 ('mapping.compilefailed', 'de', 'Es konnte nicht verstanden werden. Bitte erneut versuchen.'),
 ('mapping.removefunction', 'en', 'Remove function'),
 ('mapping.removefunction', 'de', 'Funktion entfernen'),
 ('mapping.removeline', 'en', 'Remove line'),
 ('mapping.removeline', 'de', 'Zuordnung entfernen'),
 ('mapping.try', 'en', 'Try on the sample'),
 ('mapping.try', 'de', 'Am Beispiel testen'),
 ('mapping.tryfailed', 'en', 'It could not be tried. Try again.'),
 ('mapping.tryfailed', 'de', 'Der Test war nicht möglich. Bitte erneut versuchen.'),
 ('mapping.tried', 'en', 'What it makes of {file}'),
 ('mapping.tried', 'de', 'Was daraus aus {file} wird'),
 ('mapping.triedsummary', 'en', 'Values read: {v}. Lines: {l}.'),
 ('mapping.triedsummary', 'de', 'Gelesene Werte: {v}. Positionen: {l}.'),
 ('mapping.problems', 'en', 'Values it could not read'),
 ('mapping.problems', 'de', 'Werte, die nicht gelesen werden konnten'),
 ('mapping.noproblems', 'en', 'Every mapped value was read.'),
 ('mapping.noproblems', 'de', 'Jeder zugeordnete Wert wurde gelesen.'),
 ('mapping.linen', 'en', 'line {n}'),
 ('mapping.linen', 'de', 'Position {n}'),
 ('mapping.publish', 'en', 'Publish'),
 ('mapping.publish', 'de', 'Veröffentlichen'),
 ('mapping.publishrefused', 'en', 'It cannot be published while it cannot read its own sample. The values are listed below.'),
 ('mapping.publishrefused', 'de', 'Sie kann nicht veröffentlicht werden, solange sie ihr eigenes Beispiel nicht lesen kann. Die Werte stehen unten.'),
 ('mapping.publishfailed', 'en', 'It could not be published. Try again.'),
 ('mapping.publishfailed', 'de', 'Sie konnte nicht veröffentlicht werden. Bitte erneut versuchen.'),
 ('mapping.published', 'en', 'Version {n} is live'),
 ('mapping.published', 'de', 'Version {n} ist aktiv'),
 ('mapping.waiting', 'en', '{n} failed messages on this route may now be read.'),
 ('mapping.waiting', 'de', '{n} fehlgeschlagene Nachrichten dieser Route können jetzt gelesen werden.'),
 ('mapping.nowaiting', 'en', 'The next invoice from this supplier will be read with it.'),
 ('mapping.nowaiting', 'de', 'Die nächste Rechnung dieses Lieferanten wird damit gelesen.'),
 ('mapping.reprocess', 'en', 'Reprocess {n} messages'),
 ('mapping.reprocess', 'de', '{n} Nachrichten erneut verarbeiten'),
 ('mapping.reprocessed', 'en', '{n} run again: {d} delivered.'),
 ('mapping.reprocessed', 'de', '{n} erneut verarbeitet: {d} zugestellt.'),
 ('mapping.reprocessforbidden', 'en', 'Reprocessing needs the Integration.Monitor permission. The Route monitor can run them again.'),
 ('mapping.reprocessforbidden', 'de', 'Erneutes Verarbeiten braucht die Berechtigung Integration.Monitor. Der Routen-Monitor kann sie erneut verarbeiten.'),
 ('mapping.reprocessfailed', 'en', 'They could not be run again. Try again from the Route monitor.'),
 ('mapping.reprocessfailed', 'de', 'Sie konnten nicht erneut verarbeitet werden. Bitte im Routen-Monitor erneut versuchen.'),
 ('mapping.back', 'en', 'Back to Routes'),
 ('mapping.back', 'de', 'Zurück zu Routen'),
 ('mapping.settings', 'en', 'Mapping'),
 ('mapping.settings', 'de', 'Zuordnung'),
 ('mapping.name', 'en', 'Name'),
 ('mapping.name', 'de', 'Name'),
 ('mapping.senders', 'en', 'Who it is for'),
 ('mapping.senders', 'de', 'Für wen'),
 ('mapping.sendersplaceholder', 'en', '@munch.de, or an address. Empty is anyone'),
 ('mapping.sendersplaceholder', 'de', '@munch.de oder eine Adresse. Leer heißt alle'),
 ('mapping.linesat', 'en', 'Lines repeat at'),
 ('mapping.linesat', 'de', 'Positionen wiederholen sich bei'),
 ('mapping.nolines', 'en', 'No lines'),
 ('mapping.nolines', 'de', 'Keine Positionen'),
 ('mapping.linesreset', 'en', '{n} line mappings were removed, because the lines are now read from elsewhere.'),
 ('mapping.linesreset', 'de', '{n} Positionszuordnungen wurden entfernt, weil die Positionen jetzt anderswo gelesen werden.'),
 ('mapping.saved', 'en', 'Saved.'),
 ('mapping.saved', 'de', 'Gespeichert.'),
 ('mapping.savefailed', 'en', 'It could not be saved. Try again.'),
 ('mapping.savefailed', 'de', 'Speichern war nicht möglich. Bitte erneut versuchen.'),
 ('mapping.scope.line', 'en', 'That term belongs to each line: choose an element inside the lines.'),
 ('mapping.scope.line', 'de', 'Diese Angabe gehört zu jeder Position: Wählen Sie ein Element innerhalb der Positionen.'),
 ('mapping.scope.header', 'en', 'That term belongs to the whole invoice: choose an element outside the lines.'),
 ('mapping.scope.header', 'de', 'Diese Angabe gehört zur ganzen Rechnung: Wählen Sie ein Element außerhalb der Positionen.'),
 ('mapping.nosample', 'en', 'The sample this mapping was drawn from is no longer kept.'),
 ('mapping.nosample', 'de', 'Das Beispiel, aus dem diese Zuordnung erstellt wurde, ist nicht mehr gespeichert.'),
 ('mapping.loadfailed', 'en', 'The mapping could not be opened. Try again.'),
 ('mapping.loadfailed', 'de', 'Die Zuordnung konnte nicht geöffnet werden. Bitte erneut versuchen.'),
 ('mapping.fn.read_date', 'en', 'read date'),
 ('mapping.fn.read_date', 'de', 'Datum lesen'),
 ('mapping.fn.write_date', 'en', 'write date'),
 ('mapping.fn.write_date', 'de', 'Datum schreiben'),
 ('mapping.fn.decimal_comma', 'en', 'decimal comma'),
 ('mapping.fn.decimal_comma', 'de', 'Dezimalkomma'),
 ('mapping.fn.number', 'en', 'number'),
 ('mapping.fn.number', 'de', 'Zahl'),
 ('mapping.fn.round', 'en', 'round'),
 ('mapping.fn.round', 'de', 'runden'),
 ('mapping.fn.multiply', 'en', 'multiply'),
 ('mapping.fn.multiply', 'de', 'multiplizieren'),
 ('mapping.fn.trim', 'en', 'trim'),
 ('mapping.fn.trim', 'de', 'Leerzeichen entfernen'),
 ('mapping.fn.upper', 'en', 'upper case'),
 ('mapping.fn.upper', 'de', 'Großbuchstaben'),
 ('mapping.fn.lower', 'en', 'lower case'),
 ('mapping.fn.lower', 'de', 'Kleinbuchstaben'),
 ('mapping.fn.first_letters', 'en', 'first letters'),
 ('mapping.fn.first_letters', 'de', 'erste Zeichen'),
 ('mapping.fn.last_letters', 'en', 'last letters'),
 ('mapping.fn.last_letters', 'de', 'letzte Zeichen'),
 ('mapping.fn.remove_prefix', 'en', 'remove prefix'),
 ('mapping.fn.remove_prefix', 'de', 'Präfix entfernen'),
 ('mapping.fn.replace', 'en', 'replace'),
 ('mapping.fn.replace', 'de', 'ersetzen'),
 ('mapping.fn.remove_spaces', 'en', 'remove spaces'),
 ('mapping.fn.remove_spaces', 'de', 'Leerzeichen streichen'),
 ('mapping.fn.country_to_code', 'en', 'country to code'),
 ('mapping.fn.country_to_code', 'de', 'Land zu Code'),
 ('mapping.fn.code_to_country', 'en', 'code to country'),
 ('mapping.fn.code_to_country', 'de', 'Code zu Land'),
 ('mapping.fn.unit_code', 'en', 'unit of measure'),
 ('mapping.fn.unit_code', 'de', 'Mengeneinheit'),
 ('mapping.fn.if_empty', 'en', 'if empty, use'),
 ('mapping.fn.if_empty', 'de', 'wenn leer, verwende'),
 ('mapping.fn.always', 'en', 'always'),
 ('mapping.fn.always', 'de', 'immer'),
 ('mapping.bt.bt-1', 'en', 'Invoice number'),
 ('mapping.bt.bt-1', 'de', 'Rechnungsnummer'),
 ('mapping.bt.bt-2', 'en', 'Issue date'),
 ('mapping.bt.bt-2', 'de', 'Rechnungsdatum'),
 ('mapping.bt.bt-3', 'en', 'Invoice type code'),
 ('mapping.bt.bt-3', 'de', 'Rechnungsart'),
 ('mapping.bt.bt-5', 'en', 'Currency'),
 ('mapping.bt.bt-5', 'de', 'Währung'),
 ('mapping.bt.bt-9', 'en', 'Payment due date'),
 ('mapping.bt.bt-9', 'de', 'Fälligkeitsdatum'),
 ('mapping.bt.bt-10', 'en', 'Buyer reference'),
 ('mapping.bt.bt-10', 'de', 'Käuferreferenz'),
 ('mapping.bt.bt-11', 'en', 'Project reference'),
 ('mapping.bt.bt-11', 'de', 'Projektreferenz'),
 ('mapping.bt.bt-13', 'en', 'Purchase order reference'),
 ('mapping.bt.bt-13', 'de', 'Bestellreferenz'),
 ('mapping.bt.bt-20', 'en', 'Payment terms'),
 ('mapping.bt.bt-20', 'de', 'Zahlungsbedingungen'),
 ('mapping.bt.bt-27', 'en', 'Seller name'),
 ('mapping.bt.bt-27', 'de', 'Name des Verkäufers'),
 ('mapping.bt.bt-31', 'en', 'Seller VAT identifier'),
 ('mapping.bt.bt-31', 'de', 'USt-IdNr. des Verkäufers'),
 ('mapping.bt.bt-34', 'en', 'Seller electronic address'),
 ('mapping.bt.bt-34', 'de', 'Elektronische Adresse des Verkäufers'),
 ('mapping.bt.bt-40', 'en', 'Seller country code'),
 ('mapping.bt.bt-40', 'de', 'Ländercode des Verkäufers'),
 ('mapping.bt.bt-44', 'en', 'Buyer name'),
 ('mapping.bt.bt-44', 'de', 'Name des Käufers'),
 ('mapping.bt.bt-48', 'en', 'Buyer VAT identifier'),
 ('mapping.bt.bt-48', 'de', 'USt-IdNr. des Käufers'),
 ('mapping.bt.bt-49', 'en', 'Buyer electronic address'),
 ('mapping.bt.bt-49', 'de', 'Elektronische Adresse des Käufers'),
 ('mapping.bt.bt-55', 'en', 'Buyer country code'),
 ('mapping.bt.bt-55', 'de', 'Ländercode des Käufers'),
 ('mapping.bt.bt-106', 'en', 'Sum of line net amounts'),
 ('mapping.bt.bt-106', 'de', 'Summe der Positionsnettobeträge'),
 ('mapping.bt.bt-109', 'en', 'Total without VAT'),
 ('mapping.bt.bt-109', 'de', 'Gesamtbetrag ohne Umsatzsteuer'),
 ('mapping.bt.bt-110', 'en', 'Total VAT amount'),
 ('mapping.bt.bt-110', 'de', 'Umsatzsteuerbetrag'),
 ('mapping.bt.bt-112', 'en', 'Total with VAT'),
 ('mapping.bt.bt-112', 'de', 'Gesamtbetrag mit Umsatzsteuer'),
 ('mapping.bt.bt-115', 'en', 'Amount due for payment'),
 ('mapping.bt.bt-115', 'de', 'Fälliger Betrag'),
 ('mapping.bt.bt-126', 'en', 'Line identifier'),
 ('mapping.bt.bt-126', 'de', 'Positionsnummer'),
 ('mapping.bt.bt-127', 'en', 'Line note'),
 ('mapping.bt.bt-127', 'de', 'Positionshinweis'),
 ('mapping.bt.bt-129', 'en', 'Invoiced quantity'),
 ('mapping.bt.bt-129', 'de', 'Menge'),
 ('mapping.bt.bt-130', 'en', 'Unit of measure'),
 ('mapping.bt.bt-130', 'de', 'Mengeneinheit'),
 ('mapping.bt.bt-131', 'en', 'Line net amount'),
 ('mapping.bt.bt-131', 'de', 'Nettobetrag der Position'),
 ('mapping.bt.bt-132', 'en', 'Order line reference'),
 ('mapping.bt.bt-132', 'de', 'Bestellpositionsreferenz'),
 ('mapping.bt.bt-133', 'en', 'Buyer accounting reference'),
 ('mapping.bt.bt-133', 'de', 'Buchungsreferenz des Käufers'),
 ('mapping.bt.bt-146', 'en', 'Item net price'),
 ('mapping.bt.bt-146', 'de', 'Nettopreis'),
 ('mapping.bt.bt-151', 'en', 'VAT category code'),
 ('mapping.bt.bt-151', 'de', 'Umsatzsteuerkategorie'),
 ('mapping.bt.bt-152', 'en', 'Line VAT rate'),
 ('mapping.bt.bt-152', 'de', 'Umsatzsteuersatz der Position'),
 ('mapping.bt.bt-153', 'en', 'Item name'),
 ('mapping.bt.bt-153', 'de', 'Artikelbezeichnung'),
 ('mapping.bt.bt-154', 'en', 'Item description'),
 ('mapping.bt.bt-154', 'de', 'Artikelbeschreibung'),
 ('routemonitor.error.no_mapping.title', 'en', 'A supplier''s own XML, and no mapping reads it yet'),
 ('routemonitor.error.no_mapping.title', 'de', 'Eigenes XML eines Lieferanten, noch ohne Zuordnung'),
 ('routemonitor.error.no_mapping.body', 'en', 'The file is well-formed XML, but neither UBL nor CII: the supplier''s own format. It is kept, and nothing is lost.'),
 ('routemonitor.error.no_mapping.body', 'de', 'Die Datei ist gültiges XML, aber weder UBL noch CII: das eigene Format des Lieferanten. Sie ist gespeichert, nichts geht verloren.'),
 ('routemonitor.error.no_mapping.fix', 'en', 'Map this format from the file below, publish the mapping, then reprocess. Every invoice like it is then read as data.'),
 ('routemonitor.error.no_mapping.fix', 'de', 'Ordnen Sie das Format aus der Datei unten zu, veröffentlichen Sie die Zuordnung und verarbeiten Sie erneut. Jede solche Rechnung wird dann als Daten gelesen.'),
 ('routemonitor.error.mapping_failed.title', 'en', 'The supplier''s mapping could not read a value'),
 ('routemonitor.error.mapping_failed.title', 'de', 'Die Zuordnung des Lieferanten konnte einen Wert nicht lesen'),
 ('routemonitor.error.mapping_failed.body', 'en', 'The file is the supplier''s own XML, and its mapping ran, but one or more values were not in the form it expects. Which, where and why is shown below.'),
 ('routemonitor.error.mapping_failed.body', 'de', 'Die Datei ist das eigene XML des Lieferanten und seine Zuordnung lief, aber ein oder mehrere Werte hatten nicht die erwartete Form. Welche, wo und warum steht unten.'),
 ('routemonitor.error.mapping_failed.fix', 'en', 'Open the mapping, change the line or its function, publish, then reprocess.'),
 ('routemonitor.error.mapping_failed.fix', 'de', 'Öffnen Sie die Zuordnung, ändern Sie die Zeile oder ihre Funktion, veröffentlichen Sie und verarbeiten Sie erneut.'),
 ('routemonitor.mapthis', 'en', 'Map this format'),
 ('routemonitor.mapthis', 'de', 'Dieses Format zuordnen'),
 ('routemonitor.openmapping', 'en', 'Open the mapping'),
 ('routemonitor.openmapping', 'de', 'Zuordnung öffnen'),
 ('routemonitor.nomapping', 'en', 'No mapping yet'),
 ('routemonitor.nomapping', 'de', 'Noch keine Zuordnung'),
 ('routemonitor.mappingfailed', 'en', 'Mapping could not read it'),
 ('routemonitor.mappingfailed', 'de', 'Zuordnung konnte sie nicht lesen'),
 ('routemonitor.nomappingwhy', 'en', 'This supplier sends its own XML. Map it once, from this file, and every invoice like it is read as data.'),
 ('routemonitor.nomappingwhy', 'de', 'Dieser Lieferant sendet sein eigenes XML. Ordnen Sie es einmal aus dieser Datei zu, dann wird jede solche Rechnung als Daten gelesen.'),
 ('routemonitor.readwith', 'en', 'Read with {name}, version {n}.'),
 ('routemonitor.readwith', 'de', 'Gelesen mit {name}, Version {n}.'),
 ('routemonitor.mapforbidden', 'en', 'Drawing a mapping needs the Admin.Configure permission.'),
 ('routemonitor.mapforbidden', 'de', 'Eine Zuordnung zu erstellen braucht die Berechtigung Admin.Configure.'),
 ('routemonitor.mapfailed', 'en', 'A mapping could not be drawn from it. Try again.'),
 ('routemonitor.mapfailed', 'de', 'Daraus konnte keine Zuordnung erstellt werden. Bitte erneut versuchen.'),
 ('routes.format.supplier_xml', 'en', 'A supplier''s own XML'),
 ('routes.format.supplier_xml', 'de', 'Eigenes XML eines Lieferanten'),
 ('routes.formats.supplier_xml', 'en', 'A supplier''s own XML'),
 ('routes.formats.supplier_xml', 'de', 'Eigenes XML eines Lieferanten'),
 ('routes.formats.supplier_xml.syntax', 'en', 'Neither UBL nor CII'),
 ('routes.formats.supplier_xml.syntax', 'de', 'Weder UBL noch CII'),
 ('routes.formats.supplier_xml.how', 'en', 'As data, with that supplier''s mapping'),
 ('routes.formats.supplier_xml.how', 'de', 'Als Daten, mit der Zuordnung dieses Lieferanten'),
 ('routes.formats.supplier_xml.checked', 'en', 'EN 16931, after translation'),
 ('routes.formats.supplier_xml.checked', 'de', 'EN 16931, nach der Übersetzung'),
 ('routes.mappings.heading', 'en', 'Supplier mappings'),
 ('routes.mappings.heading', 'de', 'Lieferantenzuordnungen'),
 ('routes.mappings.sub', 'en', 'For suppliers who send their own XML. Draw one from a kept message in the Route monitor with Map this format.'),
 ('routes.mappings.sub', 'de', 'Für Lieferanten mit eigenem XML. Erstellen Sie eine aus einer gespeicherten Nachricht im Routen-Monitor mit Dieses Format zuordnen.'),
 ('routes.mappings.none', 'en', 'None yet. A supplier''s own XML that no mapping reads fails in the Route monitor, with Map this format.'),
 ('routes.mappings.none', 'de', 'Noch keine. Eigenes XML eines Lieferanten ohne Zuordnung schlägt im Routen-Monitor fehl, mit Dieses Format zuordnen.'),
 ('routes.mappings.failed', 'en', 'The mappings could not be read. Try again.'),
 ('routes.mappings.failed', 'de', 'Die Zuordnungen konnten nicht gelesen werden. Bitte erneut versuchen.'),
 ('routes.mappings.col.mapping', 'en', 'Mapping'),
 ('routes.mappings.col.mapping', 'de', 'Zuordnung'),
 ('routes.mappings.col.version', 'en', 'Version'),
 ('routes.mappings.col.version', 'de', 'Version'),
 ('routes.mappings.anyone', 'en', 'anyone'),
 ('routes.mappings.anyone', 'de', 'alle'),
 ('routes.mappings.read', 'en', '{n} read'),
 ('routes.mappings.read', 'de', '{n} gelesen'),
 ('routes.mappings.waiting', 'en', '{n} failed, waiting'),
 ('routes.mappings.waiting', 'de', '{n} fehlgeschlagen, wartend'),
 ('routes.mappings.open', 'en', 'Open'),
 ('routes.mappings.open', 'de', 'Öffnen');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('mapping.title','mapping.subtitle','mapping.draftn','mapping.liven','mapping.livebeside','mapping.samplefrom','mapping.heading','mapping.counts','mapping.legend.line','mapping.legend.fx','mapping.legend.required','mapping.receiving','mapping.receivingsub','mapping.eachline','mapping.delivery','mapping.deliverysub','mapping.invoice','mapping.invoiceline','mapping.fixed','mapping.needed','mapping.howto','mapping.howtotext','mapping.required','mapping.optional','mapping.choosesource','mapping.orfixed','mapping.fixedplaceholder','mapping.usefixed','mapping.from','mapping.sample','mapping.function','mapping.nofunction','mapping.sayplaceholder','mapping.understand','mapping.understood','mapping.examples','mapping.none','mapping.accept','mapping.compilefailed','mapping.removefunction','mapping.removeline','mapping.try','mapping.tryfailed','mapping.tried','mapping.triedsummary','mapping.problems','mapping.noproblems','mapping.linen','mapping.publish','mapping.publishrefused','mapping.publishfailed','mapping.published','mapping.waiting','mapping.nowaiting','mapping.reprocess','mapping.reprocessed','mapping.reprocessforbidden','mapping.reprocessfailed','mapping.back','mapping.settings','mapping.name','mapping.senders','mapping.sendersplaceholder','mapping.linesat','mapping.nolines','mapping.linesreset','mapping.saved','mapping.savefailed','mapping.scope.line','mapping.scope.header','mapping.nosample','mapping.loadfailed','mapping.fn.read_date','mapping.fn.write_date','mapping.fn.decimal_comma','mapping.fn.number','mapping.fn.round','mapping.fn.multiply','mapping.fn.trim','mapping.fn.upper','mapping.fn.lower','mapping.fn.first_letters','mapping.fn.last_letters','mapping.fn.remove_prefix','mapping.fn.replace','mapping.fn.remove_spaces','mapping.fn.country_to_code','mapping.fn.code_to_country','mapping.fn.unit_code','mapping.fn.if_empty','mapping.fn.always','mapping.bt.bt-1','mapping.bt.bt-2','mapping.bt.bt-3','mapping.bt.bt-5','mapping.bt.bt-9','mapping.bt.bt-10','mapping.bt.bt-11','mapping.bt.bt-13','mapping.bt.bt-20','mapping.bt.bt-27','mapping.bt.bt-31','mapping.bt.bt-34','mapping.bt.bt-40','mapping.bt.bt-44','mapping.bt.bt-48','mapping.bt.bt-49','mapping.bt.bt-55','mapping.bt.bt-106','mapping.bt.bt-109','mapping.bt.bt-110','mapping.bt.bt-112','mapping.bt.bt-115','mapping.bt.bt-126','mapping.bt.bt-127','mapping.bt.bt-129','mapping.bt.bt-130','mapping.bt.bt-131','mapping.bt.bt-132','mapping.bt.bt-133','mapping.bt.bt-146','mapping.bt.bt-151','mapping.bt.bt-152','mapping.bt.bt-153','mapping.bt.bt-154','routemonitor.error.no_mapping.title','routemonitor.error.no_mapping.body','routemonitor.error.no_mapping.fix','routemonitor.error.mapping_failed.title','routemonitor.error.mapping_failed.body','routemonitor.error.mapping_failed.fix','routemonitor.mapthis','routemonitor.openmapping','routemonitor.nomapping','routemonitor.mappingfailed','routemonitor.nomappingwhy','routemonitor.readwith','routemonitor.mapforbidden','routemonitor.mapfailed','routes.format.supplier_xml','routes.formats.supplier_xml','routes.formats.supplier_xml.syntax','routes.formats.supplier_xml.how','routes.formats.supplier_xml.checked','routes.mappings.heading','routes.mappings.sub','routes.mappings.none','routes.mappings.failed','routes.mappings.col.mapping','routes.mappings.col.version','routes.mappings.anyone','routes.mappings.read','routes.mappings.waiting','routes.mappings.open') == 308
