-- 0213_mapping_help_strings.sql
-- Decision 0562. Help written at length: the mapping editor's own help, and
-- the Routes and Route monitor help extended with formats, checks and
-- supplier mappings.
--
-- A screen's help is its key, then any numbered keys after it
-- (help.screen.mapping.2, .3, ...), one line each: a line starting "## " is
-- a heading, one starting "- " a list item, anything else a paragraph. One
-- line per key rather than line breaks in one value, because stored words
-- hold no escape sequences (0546), and a translator works line by line.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('help.screen.mapping', 'en', 'A mapping teaches VibeFinance to read a supplier who sends invoices in its own XML layout, rather than UBL or CII. Once it is published, every invoice in that layout from that supplier is read as data: nothing is retyped, and no picture is read by AI.'),
 ('help.screen.mapping', 'de', 'Eine Zuordnung bringt VibeFinance bei, einen Lieferanten zu lesen, der Rechnungen in seinem eigenen XML-Aufbau statt in UBL oder CII sendet. Sobald sie veröffentlicht ist, wird jede Rechnung in diesem Aufbau von diesem Lieferanten als Daten gelesen: Nichts wird abgetippt, und kein Bild wird von KI gelesen.'),
 ('help.screen.mapping.2', 'en', '## The two columns'),
 ('help.screen.mapping.2', 'de', '## Die zwei Spalten'),
 ('help.screen.mapping.3', 'en', '- Left: the supplier''s own file, drawn from the kept email it arrived in. Each element shows the value it holds in that sample. Dimmed elements are not used yet.'),
 ('help.screen.mapping.3', 'de', '- Links: die eigene Datei des Lieferanten, aus der gespeicherten E-Mail, mit der sie ankam. Jedes Element zeigt seinen Wert in diesem Beispiel. Abgeblendete Elemente werden noch nicht verwendet.'),
 ('help.screen.mapping.4', 'en', '- Right: the EN 16931 invoice, the model in the middle that every route delivers. A red asterisk marks a term every invoice must have, and Needs a source marks a required term with nothing mapped yet.'),
 ('help.screen.mapping.4', 'de', '- Rechts: die EN-16931-Rechnung, das Modell in der Mitte, das jede Route liefert. Ein rotes Sternchen markiert eine Angabe, die jede Rechnung haben muss, und Braucht eine Quelle eine Pflichtangabe ohne Zuordnung.'),
 ('help.screen.mapping.5', 'en', '- Invoice terms belong to the whole invoice. Invoice line terms repeat for each line.'),
 ('help.screen.mapping.5', 'de', '- Rechnungsangaben gehören zur ganzen Rechnung. Positionsangaben wiederholen sich für jede Position.'),
 ('help.screen.mapping.6', 'en', '## Drawing a line'),
 ('help.screen.mapping.6', 'de', '## Eine Linie ziehen'),
 ('help.screen.mapping.7', 'en', '- Choose an element on the left, then the term it becomes on the right, or the other way round.'),
 ('help.screen.mapping.7', 'de', '- Wählen Sie links ein Element und rechts die Angabe, die daraus wird, oder umgekehrt.'),
 ('help.screen.mapping.8', 'en', '- A line''s term needs an element from inside the lines, and a whole-invoice term needs one from outside them. The editor says so if they do not match.'),
 ('help.screen.mapping.8', 'de', '- Eine Positionsangabe braucht ein Element innerhalb der Positionen, eine Rechnungsangabe eines außerhalb. Passt das nicht, sagt der Editor es.'),
 ('help.screen.mapping.9', 'en', '- One element can feed several terms: the net total can be both the sum of lines (BT-106) and the total without VAT (BT-109). Each term takes one element, so to reuse an element choose the term first.'),
 ('help.screen.mapping.9', 'de', '- Ein Element kann mehrere Angaben speisen: Der Nettobetrag kann die Positionssumme (BT-106) und der Betrag ohne Umsatzsteuer (BT-109) sein. Jede Angabe hat ein Element, wählen Sie also zuerst die Angabe, um ein Element erneut zu verwenden.'),
 ('help.screen.mapping.10', 'en', '- A term the document never carries, such as the invoice type (380 for a commercial invoice), takes a fixed value instead.'),
 ('help.screen.mapping.10', 'de', '- Eine Angabe, die das Dokument nie enthält, etwa die Rechnungsart (380 für eine Handelsrechnung), bekommt stattdessen einen festen Wert.'),
 ('help.screen.mapping.11', 'en', '- Every change saves the draft at once. Nothing is used on real invoices until you publish.'),
 ('help.screen.mapping.11', 'de', '- Jede Änderung speichert den Entwurf sofort. Für echte Rechnungen gilt nichts, bevor Sie veröffentlichen.'),
 ('help.screen.mapping.12', 'en', '## Functions (Fx)'),
 ('help.screen.mapping.12', 'de', '## Funktionen (Fx)'),
 ('help.screen.mapping.13', 'en', '- Choose a mapped term, then say in your own words what should happen to its value, for example: read it as day.month.year, or: amounts use a decimal comma.'),
 ('help.screen.mapping.13', 'de', '- Wählen Sie eine zugeordnete Angabe und sagen Sie in Ihren Worten, was mit ihrem Wert geschehen soll, zum Beispiel: als Tag.Monat.Jahr lesen, oder: Beträge mit Dezimalkomma.'),
 ('help.screen.mapping.14', 'en', '- Understand turns what you said into steps from a fixed list of functions: dates, amounts, text, country and unit codes, and fixed values. Anything the list cannot do is refused, with the reason.'),
 ('help.screen.mapping.14', 'de', '- Verstehen macht daraus Schritte aus einer festen Liste von Funktionen: Datumsangaben, Beträge, Text, Länder- und Einheitencodes und feste Werte. Was die Liste nicht kann, wird mit Begründung abgelehnt.'),
 ('help.screen.mapping.15', 'en', '- The worked examples show what each of the sample''s values becomes. VibeFinance calculates them, so they show exactly what will happen. Check them, then Accept.'),
 ('help.screen.mapping.15', 'de', '- Die durchgerechneten Beispiele zeigen, was aus jedem Wert des Beispiels wird. VibeFinance rechnet sie selbst, sie zeigen also genau, was geschehen wird. Prüfen Sie sie und übernehmen Sie dann.'),
 ('help.screen.mapping.16', 'en', '- Fx on a line shows that a function changes the value on the way.'),
 ('help.screen.mapping.16', 'de', '- Fx auf einer Linie zeigt, dass eine Funktion den Wert unterwegs ändert.'),
 ('help.screen.mapping.17', 'en', '## The Mapping card'),
 ('help.screen.mapping.17', 'de', '## Die Karte Zuordnung'),
 ('help.screen.mapping.18', 'en', '- Name: what the mapping is called on the Routes screen and in the Route monitor.'),
 ('help.screen.mapping.18', 'de', '- Name: wie die Zuordnung auf der Seite Routen und im Routen-Monitor heißt.'),
 ('help.screen.mapping.19', 'en', '- Who it is for: which senders'' invoices this mapping reads. A mapping is recognised by the top element of the file, such as <Rechnung>, and different suppliers can use the same one with different layouts. This field stops one supplier''s invoices being read with another''s mapping.'),
 ('help.screen.mapping.19', 'de', '- Für wen: Rechnungen welcher Absender diese Zuordnung liest. Eine Zuordnung wird am obersten Element der Datei erkannt, etwa <Rechnung>, und verschiedene Lieferanten können dasselbe mit unterschiedlichem Aufbau verwenden. Dieses Feld verhindert, dass Rechnungen eines Lieferanten mit der Zuordnung eines anderen gelesen werden.'),
 ('help.screen.mapping.20', 'en', '- Write a domain such as @munch.de for anyone at that company, or a full address for one sender only. Separate several with commas. Leave it empty for anyone, but only where the layout really is unique to one supplier.'),
 ('help.screen.mapping.20', 'de', '- Schreiben Sie eine Domain wie @munch.de für alle bei dieser Firma oder eine vollständige Adresse für nur einen Absender. Mehrere trennen Sie mit Kommas. Leer heißt alle, aber nur, wo der Aufbau wirklich nur zu einem Lieferanten gehört.'),
 ('help.screen.mapping.21', 'en', '- A new mapping is for the domain of the email it was drawn from. Where two mappings match, the one that names the sender is used.'),
 ('help.screen.mapping.21', 'de', '- Eine neue Zuordnung gilt für die Domain der E-Mail, aus der sie erstellt wurde. Passen zwei Zuordnungen, wird die verwendet, die den Absender nennt.'),
 ('help.screen.mapping.22', 'en', '- Lines repeat at: the group in the file that holds one invoice line. Changing it removes the line mappings, which are then drawn again.'),
 ('help.screen.mapping.22', 'de', '- Positionen wiederholen sich bei: die Gruppe in der Datei, die eine Rechnungsposition enthält. Eine Änderung entfernt die Positionszuordnungen, die dann neu gezogen werden.'),
 ('help.screen.mapping.23', 'en', '- Save keeps the name and who it is for.'),
 ('help.screen.mapping.23', 'de', '- Speichern sichert den Namen und für wen sie gilt.'),
 ('help.screen.mapping.24', 'en', '## Try, publish, reprocess'),
 ('help.screen.mapping.24', 'de', '## Testen, veröffentlichen, erneut verarbeiten'),
 ('help.screen.mapping.25', 'en', '- Try on the sample shows what the draft makes of its sample: the values read, the lines, any value it could not read and why, and the EN 16931 checks.'),
 ('help.screen.mapping.25', 'de', '- Am Beispiel testen zeigt, was der Entwurf aus seinem Beispiel macht: die gelesenen Werte, die Positionen, jeden Wert, der nicht gelesen werden konnte, und warum, sowie die EN-16931-Prüfungen.'),
 ('help.screen.mapping.26', 'en', '- Publish makes the draft the live version. It is refused while the draft cannot read its own sample. The version before stays in the history.'),
 ('help.screen.mapping.26', 'de', '- Veröffentlichen macht den Entwurf zur aktiven Version. Das wird abgelehnt, solange der Entwurf sein eigenes Beispiel nicht lesen kann. Die vorherige Version bleibt im Verlauf.'),
 ('help.screen.mapping.27', 'en', '- After publishing, reprocess the messages that failed while waiting for this mapping. The next invoice from this supplier is read with it automatically.'),
 ('help.screen.mapping.27', 'de', '- Verarbeiten Sie nach dem Veröffentlichen die Nachrichten erneut, die auf diese Zuordnung gewartet haben. Die nächste Rechnung dieses Lieferanten wird automatisch damit gelesen.'),
 ('help.screen.mapping.28', 'en', '- Editing a live mapping starts a new draft. The live version keeps reading invoices until the draft is published.'),
 ('help.screen.mapping.28', 'de', '- Wer eine aktive Zuordnung ändert, beginnt einen neuen Entwurf. Die aktive Version liest weiter Rechnungen, bis der Entwurf veröffentlicht ist.'),
 ('help.screen.mapping.29', 'en', '## When an invoice fails'),
 ('help.screen.mapping.29', 'de', '## Wenn eine Rechnung scheitert'),
 ('help.screen.mapping.30', 'en', '- A supplier''s own XML with no mapping yet fails in the Route monitor, with Map this format.'),
 ('help.screen.mapping.30', 'de', '- Eigenes XML eines Lieferanten ohne Zuordnung scheitert im Routen-Monitor, mit Dieses Format zuordnen.'),
 ('help.screen.mapping.31', 'en', '- An invoice the mapping cannot read fails with the term, where it is in the file, the value, and why, and with Open the mapping. Fix the line or its function, publish, then reprocess.'),
 ('help.screen.mapping.31', 'de', '- Eine Rechnung, die die Zuordnung nicht lesen kann, scheitert mit Angabe, Stelle in der Datei, Wert und Grund, und mit Zuordnung öffnen. Korrigieren Sie die Linie oder ihre Funktion, veröffentlichen Sie und verarbeiten Sie erneut.'),
 ('help.screen.mapping.32', 'en', '- An EN 16931 rule the invoice breaks never stops it: it is delivered, and the rule is recorded for your own rules to act on.'),
 ('help.screen.mapping.32', 'de', '- Eine verletzte EN-16931-Regel hält eine Rechnung nie auf: Sie wird zugestellt, und die Regel wird für Ihre eigenen Regeln festgehalten.'),
 ('help.screen.mapping.33', 'en', '## Who can use it'),
 ('help.screen.mapping.33', 'de', '## Wer sie nutzen kann'),
 ('help.screen.mapping.34', 'en', '- Changing mappings needs the Admin.Configure permission. Reprocessing needs Integration.Monitor.'),
 ('help.screen.mapping.34', 'de', '- Zuordnungen zu ändern braucht die Berechtigung Admin.Configure. Erneutes Verarbeiten braucht Integration.Monitor.'),
 ('help.screen.routes.2', 'en', '## Receiving formats'),
 ('help.screen.routes.2', 'de', '## Empfangsformate'),
 ('help.screen.routes.3', 'en', '- For a Source, every format it recognises, in the order it tries them, how each is read, and what it is checked against on arrival, with the last 30 days'' count.'),
 ('help.screen.routes.3', 'de', '- Für eine Quelle jedes Format, das sie erkennt, in der Reihenfolge, in der sie es versucht, wie es gelesen und wogegen es beim Eingang geprüft wird, mit der Anzahl der letzten 30 Tage.'),
 ('help.screen.routes.4', 'en', '- XRechnung, Peppol BIS, UBL, CII and the XML inside a ZUGFeRD or Factur-X PDF are read as data and checked against EN 16931. A picture or plain PDF is read by AI, as before.'),
 ('help.screen.routes.4', 'de', '- XRechnung, Peppol BIS, UBL, CII und das XML in einem ZUGFeRD- oder Factur-X-PDF werden als Daten gelesen und gegen EN 16931 geprüft. Ein Bild oder ein einfaches PDF liest KI, wie bisher.'),
 ('help.screen.routes.5', 'en', '- A broken EN 16931 rule never stops an invoice. It is recorded, so a rule of yours can route it: for example, en16931.failures contains BR-CO-16.'),
 ('help.screen.routes.5', 'de', '- Eine verletzte EN-16931-Regel hält keine Rechnung auf. Sie wird festgehalten, damit eine Ihrer Regeln die Rechnung leiten kann: zum Beispiel en16931.failures contains BR-CO-16.'),
 ('help.screen.routes.6', 'en', '## Supplier mappings'),
 ('help.screen.routes.6', 'de', '## Lieferantenzuordnungen'),
 ('help.screen.routes.7', 'en', '- For suppliers who send their own XML. Each mapping shows its live and draft versions, how many invoices it read in the last 30 days, and the failed messages waiting for it.'),
 ('help.screen.routes.7', 'de', '- Für Lieferanten mit eigenem XML. Jede Zuordnung zeigt ihre aktive und ihre Entwurfsversion, wie viele Rechnungen sie in den letzten 30 Tagen gelesen hat und die fehlgeschlagenen Nachrichten, die auf sie warten.'),
 ('help.screen.routes.8', 'en', '- Open one in the mapping editor. A new one is drawn from a kept message in the Route monitor, with Map this format.'),
 ('help.screen.routes.8', 'de', '- Öffnen Sie eine im Zuordnungseditor. Eine neue entsteht aus einer gespeicherten Nachricht im Routen-Monitor, mit Dieses Format zuordnen.'),
 ('help.screen.routemonitor.2', 'en', '## E-invoice checks'),
 ('help.screen.routemonitor.2', 'de', '## E-Rechnungs-Prüfungen'),
 ('help.screen.routemonitor.3', 'en', '- For each attachment read as data: its format, and either that it passed EN 16931, or each rule it broke, in words, with the figures the check found. A broken rule never stops the invoice.'),
 ('help.screen.routemonitor.3', 'de', '- Für jeden als Daten gelesenen Anhang: sein Format und entweder, dass er EN 16931 bestanden hat, oder jede verletzte Regel in Worten, mit den gefundenen Zahlen. Eine verletzte Regel hält die Rechnung nie auf.'),
 ('help.screen.routemonitor.4', 'en', '## A supplier''s own XML'),
 ('help.screen.routemonitor.4', 'de', '## Eigenes XML eines Lieferanten'),
 ('help.screen.routemonitor.5', 'en', '- With no mapping yet, it fails with Map this format, which opens the mapping editor on that very file.'),
 ('help.screen.routemonitor.5', 'de', '- Ohne Zuordnung scheitert es mit Dieses Format zuordnen, was den Zuordnungseditor mit genau dieser Datei öffnet.'),
 ('help.screen.routemonitor.6', 'en', '- Where its mapping could not read a value, it says which, and offers Open the mapping. Fix it, publish, then Reprocess.'),
 ('help.screen.routemonitor.6', 'de', '- Konnte die Zuordnung einen Wert nicht lesen, sagt sie welchen und bietet Zuordnung öffnen an. Korrigieren, veröffentlichen, dann erneut verarbeiten.'),
 ('help.screen.routemonitor.7', 'en', '## Fix and tell'),
 ('help.screen.routemonitor.7', 'de', '## Beheben und benachrichtigen'),
 ('help.screen.routemonitor.8', 'en', '- Reprocess runs a failed message again from its kept original, never making an invoice twice. Dismiss closes one that needs no fixing, with a reason. Alerts tell your IT team by email or webhook.'),
 ('help.screen.routemonitor.8', 'de', '- Erneut verarbeiten führt eine fehlgeschlagene Nachricht aus ihrem gespeicherten Original erneut aus, ohne je eine Rechnung doppelt zu erzeugen. Verwerfen schließt eine, die keine Korrektur braucht, mit Begründung. Benachrichtigungen informieren Ihr IT-Team per E-Mail oder Webhook.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('help.screen.mapping','help.screen.mapping.2','help.screen.mapping.3','help.screen.mapping.4','help.screen.mapping.5','help.screen.mapping.6','help.screen.mapping.7','help.screen.mapping.8','help.screen.mapping.9','help.screen.mapping.10','help.screen.mapping.11','help.screen.mapping.12','help.screen.mapping.13','help.screen.mapping.14','help.screen.mapping.15','help.screen.mapping.16','help.screen.mapping.17','help.screen.mapping.18','help.screen.mapping.19','help.screen.mapping.20','help.screen.mapping.21','help.screen.mapping.22','help.screen.mapping.23','help.screen.mapping.24','help.screen.mapping.25','help.screen.mapping.26','help.screen.mapping.27','help.screen.mapping.28','help.screen.mapping.29','help.screen.mapping.30','help.screen.mapping.31','help.screen.mapping.32','help.screen.mapping.33','help.screen.mapping.34','help.screen.routes.2','help.screen.routes.3','help.screen.routes.4','help.screen.routes.5','help.screen.routes.6','help.screen.routes.7','help.screen.routes.8','help.screen.routemonitor.2','help.screen.routemonitor.3','help.screen.routemonitor.4','help.screen.routemonitor.5','help.screen.routemonitor.6','help.screen.routemonitor.7','help.screen.routemonitor.8') == 96
