-- 0218_lookup_list_strings.sql
-- Decision 0568. Look-up lists: the Routes screen's panel and a list's
-- pop-out, the look_up function's name and words, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('lookup.heading', 'en', 'Look-up lists'),
 ('lookup.heading', 'de', 'Nachschlagelisten'),
 ('lookup.sub', 'en', 'Your own lists that a supplier mapping can look a value up in: a supplier''s unit word to a standard code, or their article number to yours. Kept once here, and used by any mapping.'),
 ('lookup.sub', 'de', 'Ihre eigenen Listen, in denen eine Lieferantenzuordnung einen Wert nachschlagen kann: das Einheitenwort eines Lieferanten zu einem Standardcode oder seine Artikelnummer zu Ihrer. Einmal hier gepflegt und von jeder Zuordnung nutzbar.'),
 ('lookup.none', 'en', 'No look-up lists yet.'),
 ('lookup.none', 'de', 'Noch keine Nachschlagelisten.'),
 ('lookup.loadfailed', 'en', 'The look-up lists could not be loaded.'),
 ('lookup.loadfailed', 'de', 'Die Nachschlagelisten konnten nicht geladen werden.'),
 ('lookup.col.list', 'en', 'List'),
 ('lookup.col.list', 'de', 'Liste'),
 ('lookup.col.entries', 'en', 'Entries'),
 ('lookup.col.entries', 'de', 'Einträge'),
 ('lookup.col.usedby', 'en', 'Used by'),
 ('lookup.col.usedby', 'de', 'Verwendet von'),
 ('lookup.unused', 'en', 'Not used by any mapping yet'),
 ('lookup.unused', 'de', 'Noch von keiner Zuordnung verwendet'),
 ('lookup.usedbyn', 'en', 'Used by {list}'),
 ('lookup.usedbyn', 'de', 'Verwendet von {list}'),
 ('lookup.open', 'en', 'Open'),
 ('lookup.open', 'de', 'Öffnen'),
 ('lookup.newname', 'en', 'New list name'),
 ('lookup.newname', 'de', 'Name der neuen Liste'),
 ('lookup.newplaceholder', 'en', 'A name, such as Units'),
 ('lookup.newplaceholder', 'de', 'Ein Name, etwa Einheiten'),
 ('lookup.create', 'en', 'New list'),
 ('lookup.create', 'de', 'Neue Liste'),
 ('lookup.failed', 'en', 'That could not be done.'),
 ('lookup.failed', 'de', 'Das konnte nicht ausgeführt werden.'),
 ('lookup.title', 'en', 'Look-up list: {name}'),
 ('lookup.title', 'de', 'Nachschlageliste: {name}'),
 ('lookup.name', 'en', 'Name'),
 ('lookup.name', 'de', 'Name'),
 ('lookup.from', 'en', 'From (as the supplier writes it)'),
 ('lookup.from', 'de', 'Von (wie der Lieferant es schreibt)'),
 ('lookup.to', 'en', 'To (what it becomes)'),
 ('lookup.to', 'de', 'Zu (was daraus wird)'),
 ('lookup.empty', 'en', 'No entries yet. Add a row, or paste several.'),
 ('lookup.empty', 'de', 'Noch keine Einträge. Fügen Sie eine Zeile hinzu oder mehrere per Einfügen.'),
 ('lookup.addrow', 'en', 'Add a row'),
 ('lookup.addrow', 'de', 'Zeile hinzufügen'),
 ('lookup.removerow', 'en', 'Remove'),
 ('lookup.removerow', 'de', 'Entfernen'),
 ('lookup.paste', 'en', 'Paste rows, one per line, with a tab, semicolon or comma between From and To'),
 ('lookup.paste', 'de', 'Zeilen einfügen, eine je Zeile, mit Tabulator, Semikolon oder Komma zwischen Von und Zu'),
 ('lookup.pasteplaceholder', 'en', 'For example: Rolle, RO'),
 ('lookup.pasteplaceholder', 'de', 'Zum Beispiel: Rolle, RO'),
 ('lookup.pasteadd', 'en', 'Add the pasted rows'),
 ('lookup.pasteadd', 'de', 'Eingefügte Zeilen hinzufügen'),
 ('lookup.saved', 'en', 'Saved, with {n} entries.'),
 ('lookup.saved', 'de', 'Gespeichert, mit {n} Einträgen.'),
 ('lookup.retire', 'en', 'Retire this list'),
 ('lookup.retire', 'de', 'Diese Liste stilllegen'),
 ('lookup.retireconfirm', 'en', 'Retire this list? No mapping uses it. Its entries are kept.'),
 ('lookup.retireconfirm', 'de', 'Diese Liste stilllegen? Keine Zuordnung verwendet sie. Ihre Einträge bleiben erhalten.'),
 ('lookup.retireconfirm.used', 'en', 'Retire this list? {list} still use it, and will not read a value through it until they use another list. Its entries are kept.'),
 ('lookup.retireconfirm.used', 'de', 'Diese Liste stilllegen? {list} verwenden sie noch und lesen darüber keinen Wert mehr, bis sie eine andere Liste verwenden. Ihre Einträge bleiben erhalten.'),
 ('lookup.retireyes', 'en', 'Retire list'),
 ('lookup.retireyes', 'de', 'Liste stilllegen'),
 ('lookup.retireno', 'en', 'Cancel'),
 ('lookup.retireno', 'de', 'Abbrechen'),
 ('mapping.fn.look_up', 'en', 'look up in'),
 ('mapping.fn.look_up', 'de', 'nachschlagen in'),
 ('mapping.lookup.keep', 'en', '(otherwise keep it)'),
 ('mapping.lookup.keep', 'de', '(sonst beibehalten)'),
 ('mapping.lookup.refuse', 'en', '(otherwise a problem)'),
 ('mapping.lookup.refuse', 'de', '(sonst ein Problem)'),
 ('help.screen.mapping.44', 'en', '## Look-up lists'),
 ('help.screen.mapping.44', 'de', '## Nachschlagelisten'),
 ('help.screen.mapping.45', 'en', '- A function can look a value up in one of your own lists, kept on the Routes screen: say, for example, look the unit up in Units.'),
 ('help.screen.mapping.45', 'de', '- Eine Funktion kann einen Wert in einer Ihrer eigenen Listen nachschlagen, die auf der Seite Routen gepflegt werden. Sagen Sie zum Beispiel: die Einheit in Einheiten nachschlagen.'),
 ('help.screen.mapping.46', 'en', '- A value not in the list is a problem, or, if you say so, kept for the next step. Look the unit up in Units, otherwise keep it, then turn it into a unit code reads units from the list first and the usual ones after.'),
 ('help.screen.mapping.46', 'de', '- Ein Wert, der nicht in der Liste steht, ist ein Problem oder wird, wenn Sie es sagen, für den nächsten Schritt beibehalten. Einheit in Einheiten nachschlagen, sonst beibehalten, dann in einen Einheitencode umwandeln liest zuerst die Einheiten der Liste, danach die üblichen.'),
 ('help.screen.mapping.47', 'en', '- A list is read as it is when an invoice is read. Changing a list changes what every mapping using it reads from then on.'),
 ('help.screen.mapping.47', 'de', '- Eine Liste wird so gelesen, wie sie beim Lesen einer Rechnung ist. Eine Änderung der Liste ändert ab dann, was jede Zuordnung liest, die sie verwendet.'),
 ('help.screen.routes.10', 'en', '## Look-up lists'),
 ('help.screen.routes.10', 'de', '## Nachschlagelisten'),
 ('help.screen.routes.11', 'en', '- Your own lists, From and To, that any supplier mapping can look a value up in. Open one to edit its rows, paste many at once from a spreadsheet, or retire it. Case and spaces do not matter when a value is found.'),
 ('help.screen.routes.11', 'de', '- Ihre eigenen Listen mit Von und Zu, in denen jede Lieferantenzuordnung einen Wert nachschlagen kann. Öffnen Sie eine, um Zeilen zu bearbeiten, viele auf einmal aus einer Tabelle einzufügen oder sie stillzulegen. Groß- und Kleinschreibung und Leerzeichen spielen beim Finden keine Rolle.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('lookup.heading','lookup.sub','lookup.none','lookup.loadfailed','lookup.col.list','lookup.col.entries','lookup.col.usedby','lookup.unused','lookup.usedbyn','lookup.open','lookup.newname','lookup.newplaceholder','lookup.create','lookup.failed','lookup.title','lookup.name','lookup.from','lookup.to','lookup.empty','lookup.addrow','lookup.removerow','lookup.paste','lookup.pasteplaceholder','lookup.pasteadd','lookup.saved','lookup.retire','lookup.retireconfirm','lookup.retireconfirm.used','lookup.retireyes','lookup.retireno','mapping.fn.look_up','mapping.lookup.keep','mapping.lookup.refuse','help.screen.mapping.44','help.screen.mapping.45','help.screen.mapping.46','help.screen.mapping.47','help.screen.routes.10','help.screen.routes.11') == 78
