-- 0220_ai_proposal_strings.sql
-- Decision 0570. Routes phase 2, slice 4: AI proposals in the mapping editor,
-- with a confidence VibeFinance works out, a threshold, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('mapping.ai.propose', 'en', 'Propose with AI'),
 ('mapping.ai.propose', 'de', 'Mit KI vorschlagen'),
 ('mapping.ai.working', 'en', 'Proposing…'),
 ('mapping.ai.working', 'de', 'Wird vorgeschlagen…'),
 ('mapping.ai.failed', 'en', 'The proposals could not be made. Try again, or map the lines by hand.'),
 ('mapping.ai.failed', 'de', 'Die Vorschläge konnten nicht erstellt werden. Versuchen Sie es erneut oder ordnen Sie die Zeilen von Hand zu.'),
 ('mapping.ai.nothing', 'en', 'The AI proposed nothing that could be checked. Map the lines by hand.'),
 ('mapping.ai.nothing', 'de', 'Die KI hat nichts vorgeschlagen, das geprüft werden konnte. Ordnen Sie die Zeilen von Hand zu.'),
 ('mapping.ai.applied', 'en', '{n} lines applied. Try on the sample to check them.'),
 ('mapping.ai.applied', 'de', '{n} Zeilen übernommen. Testen Sie sie am Beispiel.'),
 ('mapping.ai.heading', 'en', 'AI proposals'),
 ('mapping.ai.heading', 'de', 'KI-Vorschläge'),
 ('mapping.ai.sub', 'en', 'Proposed by AI for the terms not yet mapped. The confidence is worked out by VibeFinance, from names, values and whether the invoice adds up.'),
 ('mapping.ai.sub', 'de', 'Von der KI für die noch nicht zugeordneten Angaben vorgeschlagen. Die Sicherheit berechnet VibeFinance aus Namen, Werten und daraus, ob die Rechnung aufgeht.'),
 ('mapping.ai.threshold', 'en', 'Threshold'),
 ('mapping.ai.threshold', 'de', 'Schwelle'),
 ('mapping.ai.thresholdn', 'en', 'Apply at or above {n}%'),
 ('mapping.ai.thresholdn', 'de', 'Übernehmen ab {n}%'),
 ('mapping.ai.applyall', 'en', 'Apply {k} at or above {n}%'),
 ('mapping.ai.applyall', 'de', '{k} ab {n}% übernehmen'),
 ('mapping.ai.ready', 'en', 'Ready, {n}% or more'),
 ('mapping.ai.ready', 'de', 'Bereit, {n}% oder mehr'),
 ('mapping.ai.check', 'en', 'You check'),
 ('mapping.ai.check', 'de', 'Bitte prüfen'),
 ('mapping.ai.weak', 'en', 'Weak guesses'),
 ('mapping.ai.weak', 'de', 'Unsichere Vermutungen'),
 ('mapping.ai.missing', 'en', 'Required, nothing found'),
 ('mapping.ai.missing', 'de', 'Pflichtangabe, nichts gefunden'),
 ('mapping.ai.missinghow', 'en', 'Map these by hand, give them a fixed value, or add a rule for the whole invoice.'),
 ('mapping.ai.missinghow', 'de', 'Ordnen Sie diese von Hand zu, geben Sie einen festen Wert an oder fügen Sie eine Regel für die ganze Rechnung hinzu.'),
 ('mapping.ai.apply', 'en', 'Apply'),
 ('mapping.ai.apply', 'de', 'Übernehmen'),
 ('mapping.ai.dismiss', 'en', 'Dismiss'),
 ('mapping.ai.dismiss', 'de', 'Verwerfen'),
 ('mapping.ai.tag', 'en', 'Proposed by AI'),
 ('mapping.ai.tag', 'de', 'Von der KI vorgeschlagen'),
 ('mapping.ai.hint', 'en', 'No lines yet. Propose with AI to start, or draw them by hand.'),
 ('mapping.ai.hint', 'de', 'Noch keine Zeilen. Beginnen Sie mit KI-Vorschlägen oder ziehen Sie sie von Hand.'),
 ('help.screen.mapping.52', 'en', '## AI proposals'),
 ('help.screen.mapping.52', 'de', '## KI-Vorschläge'),
 ('help.screen.mapping.53', 'en', '- Propose with AI asks the AI which element becomes which term, for every term not yet mapped, with the functions each needs.'),
 ('help.screen.mapping.53', 'de', '- Mit KI vorschlagen fragt die KI, welches Element zu welcher Angabe wird, für jede noch nicht zugeordnete Angabe, mit den nötigen Funktionen.'),
 ('help.screen.mapping.54', 'en', '- Each proposal has a confidence, worked out by VibeFinance and not by the AI: does the element''s name match the term, is the value the right kind (a date, an amount, a currency code), and does the invoice add up with it (lines to the net total, net plus VAT to the total, quantity times price to each line).'),
 ('help.screen.mapping.54', 'de', '- Jeder Vorschlag hat eine Sicherheit, die VibeFinance berechnet und nicht die KI: Passt der Name des Elements zur Angabe, hat der Wert die richtige Art (Datum, Betrag, Währungscode), und geht die Rechnung damit auf (Positionen zur Nettosumme, Netto plus Steuer zum Gesamtbetrag, Menge mal Preis zu jeder Position).'),
 ('help.screen.mapping.55', 'en', '- Choose a threshold and apply everything at or above it at once. Check the rest one by one: apply or dismiss each. Required terms nothing was found for are listed, to map by hand, give a fixed value, or fill with a rule.'),
 ('help.screen.mapping.55', 'de', '- Wählen Sie eine Schwelle und übernehmen Sie alles ab dieser auf einmal. Prüfen Sie den Rest einzeln: jeweils übernehmen oder verwerfen. Pflichtangaben, für die nichts gefunden wurde, werden aufgeführt, um sie von Hand zuzuordnen, fest vorzugeben oder mit einer Regel zu füllen.'),
 ('help.screen.mapping.56', 'en', '- An applied proposal is a line like any other, marked AI until you change it. Nothing is used on invoices until you try the draft and publish it.'),
 ('help.screen.mapping.56', 'de', '- Ein übernommener Vorschlag ist eine Zeile wie jede andere, mit KI markiert, bis Sie sie ändern. Nichts wird für Rechnungen verwendet, bevor Sie den Entwurf testen und veröffentlichen.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('mapping.ai.propose','mapping.ai.working','mapping.ai.failed','mapping.ai.nothing','mapping.ai.applied','mapping.ai.heading','mapping.ai.sub','mapping.ai.threshold','mapping.ai.thresholdn','mapping.ai.applyall','mapping.ai.ready','mapping.ai.check','mapping.ai.weak','mapping.ai.missing','mapping.ai.missinghow','mapping.ai.apply','mapping.ai.dismiss','mapping.ai.tag','mapping.ai.hint','help.screen.mapping.52','help.screen.mapping.53','help.screen.mapping.54','help.screen.mapping.55','help.screen.mapping.56') == 48
