-- 0222_create_upload_strings.sql
-- Decision 0573. Create, Upload documents: the screen, its menu entry, the Route
-- monitor's upload events, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.create', 'en', 'Create'),
 ('nav.create', 'de', 'Erfassen'),
 ('create.heading', 'en', 'Create'),
 ('create.heading', 'de', 'Erfassen'),
 ('create.subtitle', 'en', 'Bring invoices in yourself. They go through the process like any other.'),
 ('create.subtitle', 'de', 'Rechnungen selbst einbringen. Sie durchlaufen den Prozess wie jede andere.'),
 ('create.upload', 'en', 'Upload documents'),
 ('create.upload', 'de', 'Dokumente hochladen'),
 ('create.sendto', 'en', 'Send to'),
 ('create.sendto', 'de', 'Senden an'),
 ('create.sendtohint', 'en', 'Where these invoices start: the process''s first stage, for this company.'),
 ('create.sendtohint', 'de', 'Wo diese Rechnungen beginnen: im ersten Schritt des Prozesses, für diese Firma.'),
 ('create.notargets', 'en', 'No AP upload is set up for any process. Whoever configures routes can add one on Process routes.'),
 ('create.notargets', 'de', 'Für keinen Prozess ist ein AP-Upload eingerichtet. Wer die Routen konfiguriert, kann ihn unter Prozessrouten hinzufügen.'),
 ('create.drop', 'en', 'Drop PDFs, images, XML or CSV invoices here, or a zip of them'),
 ('create.drop', 'de', 'PDFs, Bilder, XML- oder CSV-Rechnungen hier ablegen, oder ein ZIP davon'),
 ('create.dropsub', 'en', 'Each file becomes one invoice. Up to {n} files, {mb} MB each.'),
 ('create.dropsub', 'de', 'Jede Datei wird eine Rechnung. Bis zu {n} Dateien, je {mb} MB.'),
 ('create.choose', 'en', 'Choose files'),
 ('create.choose', 'de', 'Dateien wählen'),
 ('create.thisupload', 'en', 'This upload'),
 ('create.thisupload', 'de', 'Dieser Upload'),
 ('create.meta', 'en', '{message} · {n} files · {when}'),
 ('create.meta', 'de', '{message} · {n} Dateien · {when}'),
 ('create.nothingyet', 'en', 'Files you upload are listed here, with the invoice each becomes.'),
 ('create.nothingyet', 'de', 'Hochgeladene Dateien erscheinen hier, mit der Rechnung, die daraus wird.'),
 ('create.waiting', 'en', 'Waiting'),
 ('create.waiting', 'de', 'Wartet'),
 ('create.reading', 'en', 'Reading…'),
 ('create.reading', 'de', 'Wird gelesen…'),
 ('create.created', 'en', 'Created'),
 ('create.created', 'de', 'Erstellt'),
 ('create.notread', 'en', 'Not read'),
 ('create.notread', 'de', 'Nicht gelesen'),
 ('create.ncreated', 'en', '{n} created'),
 ('create.ncreated', 'de', '{n} erstellt'),
 ('create.nreading', 'en', '{n} reading'),
 ('create.nreading', 'de', '{n} werden gelesen'),
 ('create.nwaiting', 'en', '{n} waiting'),
 ('create.nwaiting', 'de', '{n} warten'),
 ('create.nnotread', 'en', '{n} not read'),
 ('create.nnotread', 'de', '{n} nicht gelesen'),
 ('create.nonumber', 'en', 'No invoice number read'),
 ('create.nonumber', 'de', 'Keine Rechnungsnummer gelesen'),
 ('create.atstage', 'en', 'now at {stage}'),
 ('create.atstage', 'de', 'jetzt bei {stage}'),
 ('create.open', 'en', 'Open'),
 ('create.open', 'de', 'Öffnen'),
 ('create.monitor', 'en', 'Route monitor'),
 ('create.monitor', 'de', 'Routen-Monitor'),
 ('create.toolarge', 'en', 'The file is larger than {mb} MB, so it was not sent.'),
 ('create.toolarge', 'de', 'Die Datei ist größer als {mb} MB und wurde nicht gesendet.'),
 ('create.toomany', 'en', 'Only the first {n} files were taken. Upload the rest separately.'),
 ('create.toomany', 'de', 'Nur die ersten {n} Dateien wurden übernommen. Laden Sie den Rest separat hoch.'),
 ('create.zipfailed', 'en', '{name} could not be opened as a zip.'),
 ('create.zipfailed', 'de', '{name} konnte nicht als ZIP geöffnet werden.'),
 ('create.failed', 'en', 'The upload could not be sent. Try again.'),
 ('create.failed', 'de', 'Der Upload konnte nicht gesendet werden. Versuchen Sie es erneut.'),
 ('routemonitor.event.upload_opened', 'en', 'Upload started'),
 ('routemonitor.event.upload_opened', 'de', 'Upload gestartet'),
 ('routemonitor.event.upload_refused', 'en', 'File refused'),
 ('routemonitor.event.upload_refused', 'de', 'Datei abgelehnt'),
 ('routemonitor.event.upload_finished', 'en', 'Upload finished'),
 ('routemonitor.event.upload_finished', 'de', 'Upload abgeschlossen'),
 ('help.screen.create', 'en', 'Bring invoices in yourself, when they did not arrive by a route: a backlog, scanned post, or files saved from a portal.'),
 ('help.screen.create', 'de', 'Rechnungen selbst einbringen, wenn sie nicht über eine Route kamen: ein Rückstand, gescannte Post oder aus einem Portal gespeicherte Dateien.'),
 ('help.screen.create.2', 'en', '## Upload documents'),
 ('help.screen.create.2', 'de', '## Dokumente hochladen'),
 ('help.screen.create.3', 'en', '- Choose where they go under Send to: the process they start in, and the company they belong to. Usually there is only one.'),
 ('help.screen.create.3', 'de', '- Wählen Sie unter Senden an, wohin sie gehen: den Prozess, in dem sie beginnen, und die Firma, zu der sie gehören. Meist gibt es nur eine Möglichkeit.'),
 ('help.screen.create.4', 'en', '- Drop PDFs, images, XML or CSV files, or a zip of them. Each file becomes one invoice, read exactly as an emailed attachment is: e-invoices as data, a supplier''s own XML or CSV through its mapping, and a PDF or picture by AI.'),
 ('help.screen.create.4', 'de', '- Legen Sie PDFs, Bilder, XML- oder CSV-Dateien ab, oder ein ZIP davon. Jede Datei wird eine Rechnung und wird genau wie ein E-Mail-Anhang gelesen: E-Rechnungen als Daten, eigenes XML oder CSV eines Lieferanten über dessen Zuordnung, ein PDF oder Bild per KI.'),
 ('help.screen.create.5', 'en', '- Each file shows as it is read. A created invoice shows its number, supplier, total and stage, with Open. A file not read says why.'),
 ('help.screen.create.5', 'de', '- Jede Datei wird angezeigt, während sie gelesen wird. Eine erstellte Rechnung zeigt Nummer, Lieferant, Betrag und Schritt, mit Öffnen. Eine nicht gelesene Datei sagt, warum.'),
 ('help.screen.create.6', 'en', '- Invoices go through the whole process from its first stage, with every check, as any other. Each one''s Timeline says it came by AP upload from you, and its Attachments tab has the file.'),
 ('help.screen.create.6', 'de', '- Die Rechnungen durchlaufen den ganzen Prozess ab dem ersten Schritt, mit allen Prüfungen, wie jede andere. Die Zeitleiste jeder Rechnung zeigt, dass sie per AP-Upload von Ihnen kam, und der Reiter Anhänge enthält die Datei.'),
 ('help.screen.create.7', 'en', '- The whole upload is one message in the Route monitor, with its reference. Creating needs the AP.Create permission.'),
 ('help.screen.create.7', 'de', '- Der ganze Upload ist eine Nachricht im Routen-Monitor, mit ihrer Referenz. Das Erfassen braucht die Berechtigung AP.Create.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.create','create.heading','create.subtitle','create.upload','create.sendto','create.sendtohint','create.notargets','create.drop','create.dropsub','create.choose','create.thisupload','create.meta','create.nothingyet','create.waiting','create.reading','create.created','create.notread','create.ncreated','create.nreading','create.nwaiting','create.nnotread','create.nonumber','create.atstage','create.open','create.monitor','create.toolarge','create.toomany','create.zipfailed','create.failed','routemonitor.event.upload_opened','routemonitor.event.upload_refused','routemonitor.event.upload_finished','help.screen.create','help.screen.create.2','help.screen.create.3','help.screen.create.4','help.screen.create.5','help.screen.create.6','help.screen.create.7') == 78
