-- 0224_batch_upload_strings.sql
-- Decision 0576. Create, Batch upload: the layout, the preview, creating in
-- chunks, the Route monitor's batch event, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('create.batch', 'en', 'Batch upload'),
 ('create.batch', 'de', 'Stapel-Upload'),
 ('create.batchintro', 'en', 'Many invoices from one file: a CSV of invoice lines, or several XML invoices. Nothing is created until you have seen the preview.'),
 ('create.batchintro', 'de', 'Viele Rechnungen aus einer Datei: eine CSV mit Rechnungspositionen oder mehrere XML-Rechnungen. Nichts wird erstellt, bevor Sie die Vorschau gesehen haben.'),
 ('create.layout', 'en', 'Layout of the CSV'),
 ('create.layout', 'de', 'Aufbau der CSV'),
 ('create.layouttemplate', 'en', 'VibeFinance template'),
 ('create.layouttemplate', 'de', 'VibeFinance-Vorlage'),
 ('create.layoutmapping', 'en', 'A supplier''s own layout, by its mapping'),
 ('create.layoutmapping', 'de', 'Aufbau eines Lieferanten, über seine Zuordnung'),
 ('create.layouthint', 'en', 'Rows with the same invoice number become one invoice, with a line for each row. XML files need no layout.'),
 ('create.layouthint', 'de', 'Zeilen mit derselben Rechnungsnummer werden eine Rechnung, mit einer Position je Zeile. XML-Dateien brauchen keinen Aufbau.'),
 ('create.template', 'en', 'Download template'),
 ('create.template', 'de', 'Vorlage herunterladen'),
 ('create.nomappings', 'en', 'No CSV mapping is published yet'),
 ('create.nomappings', 'de', 'Noch keine CSV-Zuordnung veröffentlicht'),
 ('create.loading', 'en', 'Loading…'),
 ('create.loading', 'de', 'Wird geladen…'),
 ('create.batchdrop', 'en', 'Drop a CSV file, or XML invoices, or a zip of them'),
 ('create.batchdrop', 'de', 'Eine CSV-Datei, XML-Rechnungen oder ein ZIP davon hier ablegen'),
 ('create.batchdropsub', 'en', 'Up to 500 invoices at once.'),
 ('create.batchdropsub', 'de', 'Bis zu 500 Rechnungen auf einmal.'),
 ('create.templatewhat', 'en', 'What goes in the template'),
 ('create.templatewhat', 'de', 'Was in die Vorlage gehört'),
 ('create.templatecolumns', 'en', 'One row per invoice line. Required: invoice_number, issue_date, currency, supplier_name or supplier_vat, line_description, quantity, unit_price, vat_rate. Optional: due_date, purchase_order, buyer_reference, unit, line_net, notes. Dates as 2026-09-30, amounts with a dot. Totals and VAT are worked out from the lines.'),
 ('create.templatecolumns', 'de', 'Eine Zeile je Rechnungsposition. Pflicht: invoice_number, issue_date, currency, supplier_name oder supplier_vat, line_description, quantity, unit_price, vat_rate. Optional: due_date, purchase_order, buyer_reference, unit, line_net, notes. Datum als 2026-09-30, Beträge mit Punkt. Summen und Steuer werden aus den Positionen berechnet.'),
 ('create.preview', 'en', 'Preview'),
 ('create.preview', 'de', 'Vorschau'),
 ('create.previewmeta', 'en', '{file} · {rows} rows · {n} invoices · {layout}'),
 ('create.previewmeta', 'de', '{file} · {rows} Zeilen · {n} Rechnungen · {layout}'),
 ('create.previewxml', 'en', '{n} XML invoices'),
 ('create.previewxml', 'de', '{n} XML-Rechnungen'),
 ('create.cancel', 'en', 'Cancel'),
 ('create.cancel', 'de', 'Abbrechen'),
 ('create.nready', 'en', '{n} ready'),
 ('create.nready', 'de', '{n} bereit'),
 ('create.nduplicate', 'en', '{n} possible duplicates'),
 ('create.nduplicate', 'de', '{n} mögliche Duplikate'),
 ('create.nduplicate1', 'en', '1 possible duplicate'),
 ('create.nduplicate1', 'de', '1 mögliches Duplikat'),
 ('create.nproblem', 'en', '{n} with problems'),
 ('create.nproblem', 'de', '{n} mit Problemen'),
 ('create.ready', 'en', 'Ready'),
 ('create.ready', 'de', 'Bereit'),
 ('create.duplicate', 'en', 'Possible duplicate'),
 ('create.duplicate', 'de', 'Mögliches Duplikat'),
 ('create.problem', 'en', 'Problem'),
 ('create.problem', 'de', 'Problem'),
 ('create.duplicateof', 'en', '{number} from this supplier was received on {when}'),
 ('create.duplicateof', 'de', '{number} dieses Lieferanten ging am {when} ein'),
 ('create.rowsinone', 'en', '{n} rows in one invoice'),
 ('create.rowsinone', 'de', '{n} Zeilen in einer Rechnung'),
 ('create.colinvoice', 'en', 'Invoice'),
 ('create.colinvoice', 'de', 'Rechnung'),
 ('create.colsupplier', 'en', 'Supplier'),
 ('create.colsupplier', 'de', 'Lieferant'),
 ('create.coldate', 'en', 'Date'),
 ('create.coldate', 'de', 'Datum'),
 ('create.collines', 'en', 'Lines'),
 ('create.collines', 'de', 'Positionen'),
 ('create.coltotal', 'en', 'Total'),
 ('create.coltotal', 'de', 'Betrag'),
 ('create.includeduplicates', 'en', 'Also create the possible duplicates'),
 ('create.includeduplicates', 'de', 'Auch die möglichen Duplikate erstellen'),
 ('create.fixhint', 'en', 'Fix the problems in the file and upload those invoices again: the problems file lists each with its row.'),
 ('create.fixhint', 'de', 'Beheben Sie die Probleme in der Datei und laden Sie diese Rechnungen erneut hoch: Die Problemdatei nennt jedes mit seiner Zeile.'),
 ('create.downloadproblems', 'en', 'Download problems'),
 ('create.downloadproblems', 'de', 'Probleme herunterladen'),
 ('create.createn', 'en', 'Create {n} invoices'),
 ('create.createn', 'de', '{n} Rechnungen erstellen'),
 ('create.createone', 'en', 'Create 1 invoice'),
 ('create.createone', 'de', '1 Rechnung erstellen'),
 ('create.onecsv', 'en', 'One CSV file is read at a time: only the first was read.'),
 ('create.onecsv', 'de', 'Es wird jeweils eine CSV-Datei gelesen: Nur die erste wurde gelesen.'),
 ('create.nothingtoread', 'en', 'Choose a CSV file, or XML invoices.'),
 ('create.nothingtoread', 'de', 'Wählen Sie eine CSV-Datei oder XML-Rechnungen.'),
 ('routemonitor.event.batch_read', 'en', 'Batch file read'),
 ('routemonitor.event.batch_read', 'de', 'Stapeldatei gelesen'),
 ('help.screen.create.12', 'en', '## Batch upload'),
 ('help.screen.create.12', 'de', '## Stapel-Upload'),
 ('help.screen.create.13', 'en', '- Many invoices from one file. Choose the VibeFinance template (Download template gives you its columns) or a supplier''s own CSV layout, by its published mapping. Several XML invoices, or a zip of them, need no layout.'),
 ('help.screen.create.13', 'de', '- Viele Rechnungen aus einer Datei. Wählen Sie die VibeFinance-Vorlage (Vorlage herunterladen liefert ihre Spalten) oder den eigenen CSV-Aufbau eines Lieferanten, über seine veröffentlichte Zuordnung. Mehrere XML-Rechnungen oder ein ZIP davon brauchen keinen Aufbau.'),
 ('help.screen.create.14', 'en', '- Rows with the same invoice number become one invoice, with a line for each row, so a statement becomes one invoice. For the template, totals and VAT by rate are worked out from the lines.'),
 ('help.screen.create.14', 'de', '- Zeilen mit derselben Rechnungsnummer werden eine Rechnung, mit einer Position je Zeile, so wird ein Kontoauszug eine Rechnung. Bei der Vorlage werden Summen und Steuer je Satz aus den Positionen berechnet.'),
 ('help.screen.create.15', 'en', '- The preview shows each invoice before anything is made: Ready, Possible duplicate (one with the same number from the same supplier was already received), or Problem, with the row and what is wrong. Download problems gives them as a file to fix.'),
 ('help.screen.create.15', 'de', '- Die Vorschau zeigt jede Rechnung, bevor etwas erstellt wird: Bereit, Mögliches Duplikat (eine mit derselben Nummer vom selben Lieferanten ist schon eingegangen) oder Problem, mit Zeile und Fehler. Probleme herunterladen liefert sie als Datei zum Beheben.'),
 ('help.screen.create.16', 'en', '- Create makes the ready ones, and the possible duplicates only if you tick them in. They are made a few at a time, each shown as it is made, with Open. The whole file is one message in the Route monitor, and each invoice''s Attachments tab has it.'),
 ('help.screen.create.16', 'de', '- Erstellen legt die bereiten an, und die möglichen Duplikate nur, wenn Sie sie ankreuzen. Sie werden nach und nach erstellt, jede mit Öffnen angezeigt. Die ganze Datei ist eine Nachricht im Routen-Monitor, und der Reiter Anhänge jeder Rechnung enthält sie.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('create.batch','create.batchintro','create.layout','create.layouttemplate','create.layoutmapping','create.layouthint','create.template','create.nomappings','create.loading','create.batchdrop','create.batchdropsub','create.templatewhat','create.templatecolumns','create.preview','create.previewmeta','create.previewxml','create.cancel','create.nready','create.nduplicate','create.nduplicate1','create.nproblem','create.ready','create.duplicate','create.problem','create.duplicateof','create.rowsinone','create.colinvoice','create.colsupplier','create.coldate','create.collines','create.coltotal','create.includeduplicates','create.fixhint','create.downloadproblems','create.createn','create.createone','create.onecsv','create.nothingtoread','routemonitor.event.batch_read','help.screen.create.12','help.screen.create.13','help.screen.create.14','help.screen.create.15','help.screen.create.16') == 88
