-- 0227_shared_mappings_strings.sql
-- Decision 0579. Supplier mappings are shared by every Source route, and Who
-- it is for can name an HTTPS key: the wording no longer says "on this route".

UPDATE ui_strings SET value = 'Shared by every Source route: a mapping reads its supplier''s format however it arrives, by email, upload or HTTPS. Draw one from a kept message in the Route monitor with Map this format.' WHERE key = 'routes.mappings.sub' AND locale = 'en';
UPDATE ui_strings SET value = 'Von allen Quell-Routen gemeinsam genutzt: Eine Zuordnung liest das Format ihres Lieferanten, wie auch immer es ankommt, per E-Mail, Upload oder HTTPS. Erstellen Sie eine aus einer aufbewahrten Nachricht im Routen-Monitor mit Dieses Format zuordnen.' WHERE key = 'routes.mappings.sub' AND locale = 'de';
UPDATE ui_strings SET value = '@munch.de, an address, or an HTTPS key''s name. Empty is anyone' WHERE key = 'mapping.sendersplaceholder' AND locale = 'en';
UPDATE ui_strings SET value = '@munch.de, eine Adresse oder der Name eines HTTPS-Schlüssels. Leer ist jeder' WHERE key = 'mapping.sendersplaceholder' AND locale = 'de';
UPDATE ui_strings SET value = '{n} failed messages may now be read.' WHERE key = 'mapping.waiting' AND locale = 'en';
UPDATE ui_strings SET value = '{n} fehlgeschlagene Nachrichten können jetzt gelesen werden.' WHERE key = 'mapping.waiting' AND locale = 'de';
UPDATE ui_strings SET value = '- Write a domain such as @munch.de for anyone at that company, a full address for one sender only, or the name of an HTTPS key, such as Lager Nord ERP, for files sent with it. Separate several with commas. Leave it empty for anyone, but only where the layout really is unique to one supplier.' WHERE key = 'help.screen.mapping.20' AND locale = 'en';
UPDATE ui_strings SET value = '- Schreiben Sie eine Domain wie @munch.de für alle bei dieser Firma, eine vollständige Adresse für nur einen Absender oder den Namen eines HTTPS-Schlüssels, etwa Lager Nord ERP, für damit gesendete Dateien. Mehrere mit Kommas trennen. Leer lassen für jeden, aber nur, wo der Aufbau wirklich nur einem Lieferanten gehört.' WHERE key = 'help.screen.mapping.20' AND locale = 'de';
UPDATE ui_strings SET value = '- A mapping is shared by every Source route: one drawn from an email also reads the same file uploaded or sent over HTTPS. A new mapping is for the domain of the email it was drawn from, or the key a file sent over HTTPS came with. Where two mappings match, the one that names the sender is used.' WHERE key = 'help.screen.mapping.21' AND locale = 'en';
UPDATE ui_strings SET value = '- Eine Zuordnung gilt für alle Quell-Routen: Eine aus einer E-Mail erstellte liest dieselbe Datei auch hochgeladen oder per HTTPS gesendet. Eine neue Zuordnung gilt für die Domain der E-Mail, aus der sie erstellt wurde, oder für den Schlüssel, mit dem eine per HTTPS gesendete Datei kam. Passen zwei Zuordnungen, wird die verwendet, die den Absender nennt.' WHERE key = 'help.screen.mapping.21' AND locale = 'de';
UPDATE ui_strings SET value = 'A live mapping reads this kind of file, but Who it is for does not include who sent it: the email address, or the HTTPS key''s name. The file is kept, and nothing is lost.' WHERE key = 'routemonitor.error.not_for_sender.body' AND locale = 'en';
UPDATE ui_strings SET value = 'Eine veröffentlichte Zuordnung liest diese Art von Datei, aber Für wen enthält den Absender nicht: die E-Mail-Adresse oder den Namen des HTTPS-Schlüssels. Die Datei ist aufbewahrt, und nichts geht verloren.' WHERE key = 'routemonitor.error.not_for_sender.body' AND locale = 'de';
UPDATE ui_strings SET value = 'A mapping is for this sender and this kind of file, but it is still a draft. Drafts are never used on real invoices. The file is kept, and nothing is lost.' WHERE key = 'routemonitor.error.not_published.body' AND locale = 'en';
UPDATE ui_strings SET value = 'Eine Zuordnung gilt für diesen Absender und diese Art von Datei, ist aber noch ein Entwurf. Entwürfe werden nie für echte Rechnungen verwendet. Die Datei ist aufbewahrt, und nichts geht verloren.' WHERE key = 'routemonitor.error.not_published.body' AND locale = 'de';
UPDATE ui_strings SET value = '{name} reads this format, but is not for {sender}.' WHERE key = 'routemonitor.notforsenderwhy' AND locale = 'en';
UPDATE ui_strings SET value = '{name} liest dieses Format, gilt aber nicht für {sender}.' WHERE key = 'routemonitor.notforsenderwhy' AND locale = 'de';
UPDATE ui_strings SET value = 'The file is a CSV: columns, with a row for each invoice line. No mapping reads CSV files from this sender yet. It is kept, and nothing is lost.' WHERE key = 'routemonitor.error.no_mapping_csv.body' AND locale = 'en';
UPDATE ui_strings SET value = 'Die Datei ist eine CSV: Spalten, mit einer Zeile je Rechnungsposition. Noch keine Zuordnung liest CSV-Dateien von diesem Absender. Sie ist aufbewahrt, und nichts geht verloren.' WHERE key = 'routemonitor.error.no_mapping_csv.body' AND locale = 'de';

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key = 'routes.mappings.sub' AND locale = 'en' AND value LIKE 'Shared by every Source route%' == 1
-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('mapping.waiting','routemonitor.notforsenderwhy','routemonitor.error.not_for_sender.body','routemonitor.error.not_published.body','routemonitor.error.no_mapping_csv.body') AND value LIKE '%on this route%' == 0
