-- 0232_https_out_strings.sql
-- Decision 0585. HTTPS out: adding a Destination, its settings, a test with an
-- invoice, starting it, its deliveries, and the Route monitor's events.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('httpsout.heading', 'en', 'HTTPS out'),
 ('httpsout.heading', 'de', 'HTTPS-Ausgang'),
 ('httpsout.loading', 'en', 'Loading…'),
 ('httpsout.loading', 'de', 'Wird geladen…'),
 ('httpsout.failed', 'en', 'That did not work. Try again.'),
 ('httpsout.failed', 'de', 'Das hat nicht funktioniert. Versuchen Sie es erneut.'),
 ('httpsout.adddestination', 'en', 'Add a destination'),
 ('httpsout.adddestination', 'de', 'Ziel hinzufügen'),
 ('httpsout.adddestinationsub', 'en', 'Where this process sends each invoice that reaches {stage}. It does not send anything until you start it.'),
 ('httpsout.adddestinationsub', 'de', 'Wohin dieser Prozess jede Rechnung sendet, die {stage} erreicht. Es wird nichts gesendet, bevor Sie es starten.'),
 ('httpsout.name', 'en', 'Name'),
 ('httpsout.name', 'de', 'Name'),
 ('httpsout.nameexample', 'en', 'ERP push'),
 ('httpsout.nameexample', 'de', 'ERP-Übertragung'),
 ('httpsout.connectorlabel', 'en', 'Connector'),
 ('httpsout.connectorlabel', 'de', 'Connector'),
 ('httpsout.connector', 'en', 'HTTPS out: post each invoice to a web address'),
 ('httpsout.connector', 'de', 'HTTPS-Ausgang: jede Rechnung an eine Webadresse senden'),
 ('httpsout.notstarted', 'en', 'Not sending yet'),
 ('httpsout.notstarted', 'de', 'Sendet noch nicht'),
 ('httpsout.notstartedhint', 'en', 'Fill in where to send and how to sign in, try it with an invoice, then start.'),
 ('httpsout.notstartedhint', 'de', 'Geben Sie an, wohin gesendet wird und wie angemeldet wird, testen Sie es mit einer Rechnung, dann starten Sie.'),
 ('httpsout.sending', 'en', 'Sending'),
 ('httpsout.sending', 'de', 'Sendet'),
 ('httpsout.start', 'en', 'Start sending'),
 ('httpsout.start', 'de', 'Senden starten'),
 ('httpsout.startsub', 'en', 'From now on, each invoice that reaches payment-eligible is sent, once. Invoices already waiting are sent only if you choose to.'),
 ('httpsout.startsub', 'de', 'Ab jetzt wird jede Rechnung, die zahlungsfähig wird, einmal gesendet. Bereits wartende Rechnungen werden nur gesendet, wenn Sie es wählen.'),
 ('httpsout.startnew', 'en', 'Only invoices from now on ({n} already waiting are set aside)'),
 ('httpsout.startnew', 'de', 'Nur Rechnungen ab jetzt ({n} bereits wartende werden zurückgestellt)'),
 ('httpsout.startall', 'en', 'Also send the {n} already waiting'),
 ('httpsout.startall', 'de', 'Auch die {n} bereits wartenden senden'),
 ('httpsout.cancel', 'en', 'Cancel'),
 ('httpsout.cancel', 'de', 'Abbrechen'),
 ('httpsout.settings', 'en', 'Where and how it sends'),
 ('httpsout.settings', 'de', 'Wohin und wie gesendet wird'),
 ('httpsout.url', 'en', 'Send to'),
 ('httpsout.url', 'de', 'Senden an'),
 ('httpsout.method', 'en', 'Method'),
 ('httpsout.method', 'de', 'Methode'),
 ('httpsout.formatlabel', 'en', 'Format'),
 ('httpsout.formatlabel', 'de', 'Format'),
 ('httpsout.format.vf_json', 'en', 'VibeFinance invoice JSON'),
 ('httpsout.format.vf_json', 'de', 'VibeFinance-Rechnung als JSON'),
 ('httpsout.format.csv', 'en', 'ERP CSV layout'),
 ('httpsout.format.csv', 'de', 'ERP-CSV-Aufbau'),
 ('httpsout.formathint', 'en', 'One invoice per request: its lines, each line''s distributions with Account Coding, and the supplier''s ERP id and site.'),
 ('httpsout.formathint', 'de', 'Eine Rechnung je Anfrage: ihre Positionen, die Verteilungen jeder Position mit Kontierung, und die ERP-Kennung und der Standort des Lieferanten.'),
 ('httpsout.authlabel', 'en', 'Sign in with'),
 ('httpsout.authlabel', 'de', 'Anmelden mit'),
 ('httpsout.auth.none', 'en', 'Nothing'),
 ('httpsout.auth.none', 'de', 'Nichts'),
 ('httpsout.auth.api_key_header', 'en', 'A key in a header'),
 ('httpsout.auth.api_key_header', 'de', 'Einem Schlüssel in einem Header'),
 ('httpsout.auth.bearer', 'en', 'A bearer token'),
 ('httpsout.auth.bearer', 'de', 'Einem Bearer-Token'),
 ('httpsout.auth.basic', 'en', 'User name and password'),
 ('httpsout.auth.basic', 'de', 'Benutzername und Passwort'),
 ('httpsout.auth.oauth2_client_credentials', 'en', 'OAuth 2.0 client credentials'),
 ('httpsout.auth.oauth2_client_credentials', 'de', 'OAuth-2.0-Client-Credentials'),
 ('httpsout.header', 'en', 'Header'),
 ('httpsout.header', 'de', 'Header'),
 ('httpsout.username', 'en', 'User name'),
 ('httpsout.username', 'de', 'Benutzername'),
 ('httpsout.tokenurl', 'en', 'Token address'),
 ('httpsout.tokenurl', 'de', 'Token-Adresse'),
 ('httpsout.clientid', 'en', 'Client id'),
 ('httpsout.clientid', 'de', 'Client-ID'),
 ('httpsout.scope', 'en', 'Scope (optional)'),
 ('httpsout.scope', 'de', 'Scope (optional)'),
 ('httpsout.secret.key', 'en', 'Key'),
 ('httpsout.secret.key', 'de', 'Schlüssel'),
 ('httpsout.secret.token', 'en', 'Token'),
 ('httpsout.secret.token', 'de', 'Token'),
 ('httpsout.secret.password', 'en', 'Password'),
 ('httpsout.secret.password', 'de', 'Passwort'),
 ('httpsout.secret.client_secret', 'en', 'Client secret'),
 ('httpsout.secret.client_secret', 'de', 'Client-Secret'),
 ('httpsout.secretset', 'en', 'Set {when}. Type to replace it'),
 ('httpsout.secretset', 'de', 'Gesetzt {when}. Zum Ersetzen eingeben'),
 ('httpsout.secretnotset', 'en', 'Not set yet'),
 ('httpsout.secretnotset', 'de', 'Noch nicht gesetzt'),
 ('httpsout.secrethint', 'en', 'Kept encrypted and never shown again. Leave it empty to keep the one set.'),
 ('httpsout.secrethint', 'de', 'Verschlüsselt gespeichert und nie wieder angezeigt. Leer lassen, um den gesetzten zu behalten.'),
 ('httpsout.reference', 'en', 'Its reference back (optional)'),
 ('httpsout.reference', 'de', 'Ihre Referenz zurück (optional)'),
 ('httpsout.referencehint', 'en', 'Where the reply holds the receiving system''s own id for the invoice, such as $.id or $.data.documentId. It is kept with the delivery.'),
 ('httpsout.referencehint', 'de', 'Wo die Antwort die eigene Kennung des empfangenden Systems für die Rechnung enthält, etwa $.id oder $.data.documentId. Sie wird mit der Zustellung gespeichert.'),
 ('httpsout.saved', 'en', 'Saved.'),
 ('httpsout.saved', 'de', 'Gespeichert.'),
 ('httpsout.try', 'en', 'Try it with an invoice'),
 ('httpsout.try', 'de', 'Mit einer Rechnung testen'),
 ('httpsout.tryhint', 'en', 'Show what would be sent first. Send sends it for real, once: the receiving system makes it.'),
 ('httpsout.tryhint', 'de', 'Zeigen Sie zuerst, was gesendet würde. Senden sendet sie wirklich, einmal: Das empfangende System legt sie an.'),
 ('httpsout.invoice', 'en', 'Invoice'),
 ('httpsout.invoice', 'de', 'Rechnung'),
 ('httpsout.nocandidates', 'en', 'No invoice of this process is payment-eligible yet, so there is nothing to try it with.'),
 ('httpsout.nocandidates', 'de', 'Noch keine Rechnung dieses Prozesses ist zahlungsfähig, daher gibt es nichts zum Testen.'),
 ('httpsout.preview', 'en', 'Show what would be sent'),
 ('httpsout.preview', 'de', 'Zeigen, was gesendet würde'),
 ('httpsout.previewhint', 'en', 'Nothing has been sent. Secrets are shown as •••.'),
 ('httpsout.previewhint', 'de', 'Es wurde nichts gesendet. Geheimnisse werden als ••• angezeigt.'),
 ('httpsout.send', 'en', 'Send'),
 ('httpsout.send', 'de', 'Senden'),
 ('httpsout.check.no_supplier_erp_id', 'en', 'The supplier has no ERP id: the receiving system may not know who it is.'),
 ('httpsout.check.no_supplier_erp_id', 'de', 'Der Lieferant hat keine ERP-Kennung: Das empfangende System kennt ihn möglicherweise nicht.'),
 ('httpsout.check.line_without_gl_code', 'en', 'A line has no GL code.'),
 ('httpsout.check.line_without_gl_code', 'de', 'Eine Position hat kein Sachkonto.'),
 ('httpsout.outcome.delivered', 'en', 'Delivered: HTTP {status}.'),
 ('httpsout.outcome.delivered', 'de', 'Zugestellt: HTTP {status}.'),
 ('httpsout.outcome.reference', 'en', 'Its reference: {ref}.'),
 ('httpsout.outcome.reference', 'de', 'Ihre Referenz: {ref}.'),
 ('httpsout.outcome.retrying', 'en', 'Not delivered yet ({why}). It is tried again by itself.'),
 ('httpsout.outcome.retrying', 'de', 'Noch nicht zugestellt ({why}). Es wird selbst erneut versucht.'),
 ('httpsout.outcome.failed', 'en', 'Refused: {why}. Fix it, then send again.'),
 ('httpsout.outcome.failed', 'de', 'Abgelehnt: {why}. Beheben Sie es, dann erneut senden.'),
 ('httpsout.deliveries', 'en', 'Recent deliveries'),
 ('httpsout.deliveries', 'de', 'Letzte Zustellungen'),
 ('httpsout.nodeliveries', 'en', 'Nothing sent yet.'),
 ('httpsout.nodeliveries', 'de', 'Noch nichts gesendet.'),
 ('httpsout.deliverieshint', 'en', 'Each delivery is a message in the Route monitor, with what was sent and what came back. An invoice is never sent twice once delivered.'),
 ('httpsout.deliverieshint', 'de', 'Jede Zustellung ist eine Nachricht im Routen-Monitor, mit dem Gesendeten und der Antwort. Eine zugestellte Rechnung wird nie zweimal gesendet.'),
 ('httpsout.col.invoice', 'en', 'Invoice'),
 ('httpsout.col.invoice', 'de', 'Rechnung'),
 ('httpsout.col.supplier', 'en', 'Supplier'),
 ('httpsout.col.supplier', 'de', 'Lieferant'),
 ('httpsout.col.status', 'en', 'Status'),
 ('httpsout.col.status', 'de', 'Status'),
 ('httpsout.col.detail', 'en', 'Detail'),
 ('httpsout.col.detail', 'de', 'Details'),
 ('httpsout.status.pending', 'en', 'Waiting'),
 ('httpsout.status.pending', 'de', 'Wartet'),
 ('httpsout.status.retrying', 'en', 'Trying again'),
 ('httpsout.status.retrying', 'de', 'Neuer Versuch'),
 ('httpsout.status.delivered', 'en', 'Delivered'),
 ('httpsout.status.delivered', 'de', 'Zugestellt'),
 ('httpsout.status.failed', 'en', 'Failed'),
 ('httpsout.status.failed', 'de', 'Fehlgeschlagen'),
 ('httpsout.nexttry', 'en', 'Tried {n} times · next try {when}'),
 ('httpsout.nexttry', 'de', '{n}-mal versucht · nächster Versuch {when}'),
 ('httpsout.sendagain', 'en', 'Send again'),
 ('httpsout.sendagain', 'de', 'Erneut senden'),
 ('httpsout.error.bad_url', 'en', 'Give a full https:// address to send to.'),
 ('httpsout.error.bad_url', 'de', 'Geben Sie eine vollständige https://-Adresse an.'),
 ('httpsout.error.bad_header', 'en', 'Name the header the key goes in, such as X-API-Key.'),
 ('httpsout.error.bad_header', 'de', 'Nennen Sie den Header für den Schlüssel, etwa X-API-Key.'),
 ('httpsout.error.no_username', 'en', 'Give the user name.'),
 ('httpsout.error.no_username', 'de', 'Geben Sie den Benutzernamen an.'),
 ('httpsout.error.bad_token_url', 'en', 'Give a full https:// token address.'),
 ('httpsout.error.bad_token_url', 'de', 'Geben Sie eine vollständige https://-Token-Adresse an.'),
 ('httpsout.error.no_client_id', 'en', 'Give the client id.'),
 ('httpsout.error.no_client_id', 'de', 'Geben Sie die Client-ID an.'),
 ('httpsout.error.bad_reference_path', 'en', 'The reference must be a path such as $.id or $.data[0].documentId.'),
 ('httpsout.error.bad_reference_path', 'de', 'Die Referenz muss ein Pfad sein, etwa $.id oder $.data[0].documentId.'),
 ('httpsout.error.no_secrets_key', 'en', 'Secrets cannot be kept yet: CONNECTOR_SECRETS_KEY is not set on vf-app.'),
 ('httpsout.error.no_secrets_key', 'de', 'Geheimnisse können noch nicht gespeichert werden: CONNECTOR_SECRETS_KEY ist in vf-app nicht gesetzt.'),
 ('httpsout.error.no_url', 'en', 'Give the address to send to, and save, first.'),
 ('httpsout.error.no_url', 'de', 'Geben Sie zuerst die Zieladresse an und speichern Sie.'),
 ('httpsout.error.secret_missing', 'en', 'Set the secret for signing in, and save, first.'),
 ('httpsout.error.secret_missing', 'de', 'Setzen Sie zuerst das Geheimnis zum Anmelden und speichern Sie.'),
 ('httpsout.error.already_delivered', 'en', 'This invoice was already delivered here, and is never sent twice.'),
 ('httpsout.error.already_delivered', 'de', 'Diese Rechnung wurde hier bereits zugestellt und wird nie zweimal gesendet.'),
 ('httpsout.error.already_started', 'en', 'It has already started.'),
 ('httpsout.error.already_started', 'de', 'Es wurde bereits gestartet.'),
 ('httpsout.error.name_taken', 'en', 'This process already has a destination with that name.'),
 ('httpsout.error.name_taken', 'de', 'Dieser Prozess hat bereits ein Ziel mit diesem Namen.'),
 ('httpsout.error.retired', 'en', 'This destination is retired.'),
 ('httpsout.error.retired', 'de', 'Dieses Ziel ist stillgelegt.'),
 ('routemonitor.event.sending', 'en', 'Sending'),
 ('routemonitor.event.sending', 'de', 'Wird gesendet'),
 ('routemonitor.event.attempt', 'en', 'Attempt'),
 ('routemonitor.event.attempt', 'de', 'Versuch'),
 ('routemonitor.event.reference', 'en', 'Reference received'),
 ('routemonitor.event.reference', 'de', 'Referenz erhalten'),
 ('routes.tr.vf_invoice_json_v1', 'en', 'VibeFinance invoice JSON, v1'),
 ('routes.tr.vf_invoice_json_v1', 'de', 'VibeFinance-Rechnung als JSON, v1'),
 ('routes.gwdout.https', 'en', 'Posted to an address you give, signed in, each invoice once'),
 ('routes.gwdout.https', 'de', 'An eine von Ihnen angegebene Adresse gesendet, angemeldet, jede Rechnung einmal'),
 ('routes.trd.vf_invoice_json_v1', 'en', 'Each invoice, its lines and distributions with Account Coding'),
 ('routes.trd.vf_invoice_json_v1', 'de', 'Jede Rechnung, ihre Positionen und Verteilungen mit Kontierung');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('httpsout.heading','httpsout.loading','httpsout.failed','httpsout.adddestination','httpsout.adddestinationsub','httpsout.name','httpsout.nameexample','httpsout.connectorlabel','httpsout.connector','httpsout.notstarted','httpsout.notstartedhint','httpsout.sending','httpsout.start','httpsout.startsub','httpsout.startnew','httpsout.startall','httpsout.cancel','httpsout.settings','httpsout.url','httpsout.method','httpsout.formatlabel','httpsout.format.vf_json','httpsout.format.csv','httpsout.formathint','httpsout.authlabel','httpsout.auth.none','httpsout.auth.api_key_header','httpsout.auth.bearer','httpsout.auth.basic','httpsout.auth.oauth2_client_credentials','httpsout.header','httpsout.username','httpsout.tokenurl','httpsout.clientid','httpsout.scope','httpsout.secret.key','httpsout.secret.token','httpsout.secret.password','httpsout.secret.client_secret','httpsout.secretset','httpsout.secretnotset','httpsout.secrethint','httpsout.reference','httpsout.referencehint','httpsout.saved','httpsout.try','httpsout.tryhint','httpsout.invoice','httpsout.nocandidates','httpsout.preview','httpsout.previewhint','httpsout.send','httpsout.check.no_supplier_erp_id','httpsout.check.line_without_gl_code','httpsout.outcome.delivered','httpsout.outcome.reference','httpsout.outcome.retrying','httpsout.outcome.failed','httpsout.deliveries','httpsout.nodeliveries','httpsout.deliverieshint','httpsout.col.invoice','httpsout.col.supplier','httpsout.col.status','httpsout.col.detail','httpsout.status.pending','httpsout.status.retrying','httpsout.status.delivered','httpsout.status.failed','httpsout.nexttry','httpsout.sendagain','httpsout.error.bad_url','httpsout.error.bad_header','httpsout.error.no_username','httpsout.error.bad_token_url','httpsout.error.no_client_id','httpsout.error.bad_reference_path','httpsout.error.no_secrets_key','httpsout.error.no_url','httpsout.error.secret_missing','httpsout.error.already_delivered','httpsout.error.already_started','httpsout.error.name_taken','httpsout.error.retired','routemonitor.event.sending','routemonitor.event.attempt','routemonitor.event.reference','routes.tr.vf_invoice_json_v1','routes.gwdout.https','routes.trd.vf_invoice_json_v1') == 180
