-- 0235_route_library_strings.sql
-- Decision 0589. The Route library: its screen, every standard connector's
-- name and description, transports and formats, adding and upgrading.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.routelibrary', 'en', 'Route library'),
 ('nav.routelibrary', 'de', 'Routen-Bibliothek'),
 ('help.screen.routelibrary', 'en', 'Ready-made Sources and Destinations, called connectors. Each says what it sends or receives, how, and its version, and where it is already in use. Add to my routes puts one in a process: a destination is added paused, to be set up, tried with an invoice and started on Process routes. Planned connectors are coming. When a connector has a later version, each route made from it offers Upgrade, which applies what the connector fixes and keeps your own settings.'),
 ('help.screen.routelibrary', 'de', 'Fertige Quellen und Ziele, Connectoren genannt. Jeder zeigt, was er sendet oder empfängt, wie, seine Version und wo er schon im Einsatz ist. Zu meinen Routen hinzufügen legt einen in einem Prozess an: Ein Ziel wird pausiert hinzugefügt, um unter Prozessrouten eingerichtet, mit einer Rechnung getestet und gestartet zu werden. Geplante Connectoren folgen. Hat ein Connector eine neuere Version, bietet jede daraus erstellte Route Aktualisieren an, was festgelegte Werte übernimmt und Ihre eigenen Einstellungen behält.'),
 ('library.open', 'en', 'Route library'),
 ('library.open', 'de', 'Routen-Bibliothek'),
 ('library.heading', 'en', 'Route library'),
 ('library.heading', 'de', 'Routen-Bibliothek'),
 ('library.subtitle', 'en', 'Ready-made Sources and Destinations. Add one to a process, fill in its settings, try it, and start it.'),
 ('library.subtitle', 'de', 'Fertige Quellen und Ziele. Fügen Sie eines einem Prozess hinzu, füllen Sie die Einstellungen aus, testen und starten Sie es.'),
 ('library.note', 'en', 'Standard connectors are kept up to date by VibeFinance: a later version is offered to each route made from it. Connectors from your system integrator, and your own copies, come later.'),
 ('library.note', 'de', 'Standard-Connectoren werden von VibeFinance aktuell gehalten: Eine neuere Version wird jeder daraus erstellten Route angeboten. Connectoren Ihres Systemintegrators und eigene Kopien folgen später.'),
 ('library.failed', 'en', 'The library could not be loaded. Try again.'),
 ('library.failed', 'de', 'Die Bibliothek konnte nicht geladen werden. Versuchen Sie es erneut.'),
 ('library.filter.all', 'en', 'All'),
 ('library.filter.all', 'de', 'Alle'),
 ('library.filter.destination', 'en', 'Destinations'),
 ('library.filter.destination', 'de', 'Ziele'),
 ('library.filter.source', 'en', 'Sources'),
 ('library.filter.source', 'de', 'Quellen'),
 ('library.filter.erp', 'en', 'ERP'),
 ('library.filter.erp', 'de', 'ERP'),
 ('library.filter.automation', 'en', 'Automation'),
 ('library.filter.automation', 'de', 'Automatisierung'),
 ('library.filter.generic', 'en', 'Generic'),
 ('library.filter.generic', 'de', 'Allgemein'),
 ('library.publisher.standard', 'en', 'Standard · VibeFinance'),
 ('library.publisher.standard', 'de', 'Standard · VibeFinance'),
 ('library.available', 'en', 'Available'),
 ('library.available', 'de', 'Verfügbar'),
 ('library.planned', 'en', 'Planned'),
 ('library.planned', 'de', 'Geplant'),
 ('library.inuse', 'en', 'In use: {n}'),
 ('library.inuse', 'de', 'Im Einsatz: {n}'),
 ('library.upgrades', 'en', '{n} to upgrade'),
 ('library.upgrades', 'de', '{n} zu aktualisieren'),
 ('library.upgradeto', 'en', 'Version {n} available'),
 ('library.upgradeto', 'de', 'Version {n} verfügbar'),
 ('library.upgrade', 'en', 'Upgrade'),
 ('library.upgrade', 'de', 'Aktualisieren'),
 ('library.authchanged', 'en', 'The new version does not allow the way it signed in: set sign-in again before it sends.'),
 ('library.authchanged', 'de', 'Die neue Version erlaubt die bisherige Anmeldung nicht: Legen Sie die Anmeldung neu fest, bevor gesendet wird.'),
 ('library.connectorline', 'en', 'Connector: {name} · version {v}'),
 ('library.connectorline', 'de', 'Connector: {name} · Version {v}'),
 ('library.add', 'en', 'Add to my routes'),
 ('library.add', 'de', 'Zu meinen Routen hinzufügen'),
 ('library.addtitle', 'en', 'Add {name}'),
 ('library.addtitle', 'de', '{name} hinzufügen'),
 ('library.addsubdest', 'en', 'It is added paused. Fill in where it sends and how it signs in, try it with an invoice, then start it.'),
 ('library.addsubdest', 'de', 'Es wird pausiert hinzugefügt. Geben Sie an, wohin gesendet und wie angemeldet wird, testen Sie es mit einer Rechnung, dann starten Sie es.'),
 ('library.addsubsource', 'en', 'It is added to the process. Then give it its address or keys on Process routes.'),
 ('library.addsubsource', 'de', 'Es wird dem Prozess hinzugefügt. Geben Sie ihm dann unter Prozessrouten seine Adresse oder Schlüssel.'),
 ('library.process', 'en', 'Process'),
 ('library.process', 'de', 'Prozess'),
 ('library.error.one_per_process', 'en', 'This process already has one, and can have one only.'),
 ('library.error.one_per_process', 'de', 'Dieser Prozess hat bereits eines und kann nur eines haben.'),
 ('library.error.not_available', 'en', 'This connector is not available yet.'),
 ('library.error.not_available', 'de', 'Dieser Connector ist noch nicht verfügbar.'),
 ('library.error.name_taken', 'en', 'This process already has a destination with that name.'),
 ('library.error.name_taken', 'de', 'Dieser Prozess hat bereits ein Ziel mit diesem Namen.'),
 ('httpsout.error.fixed_setting', 'en', 'This connector keeps that setting fixed.'),
 ('httpsout.error.fixed_setting', 'de', 'Dieser Connector hält diese Einstellung fest.'),
 ('httpsout.error.auth_not_allowed', 'en', 'This connector does not sign in that way.'),
 ('httpsout.error.auth_not_allowed', 'de', 'Dieser Connector meldet sich nicht auf diese Weise an.'),
 ('library.transport.https', 'en', 'HTTPS'),
 ('library.transport.https', 'de', 'HTTPS'),
 ('library.transport.email', 'en', 'Email'),
 ('library.transport.email', 'de', 'E-Mail'),
 ('library.transport.upload', 'en', 'Upload'),
 ('library.transport.upload', 'de', 'Upload'),
 ('library.transport.sftp', 'en', 'SFTP'),
 ('library.transport.sftp', 'de', 'SFTP'),
 ('library.transport.edi', 'en', 'EDI'),
 ('library.transport.edi', 'de', 'EDI'),
 ('library.transport.file_download', 'en', 'File download'),
 ('library.transport.file_download', 'de', 'Datei-Download'),
 ('library.transport.peppol', 'en', 'Peppol'),
 ('library.transport.peppol', 'de', 'Peppol'),
 ('library.format.vf_json', 'en', 'VibeFinance JSON'),
 ('library.format.vf_json', 'de', 'VibeFinance-JSON'),
 ('library.format.csv', 'en', 'CSV'),
 ('library.format.csv', 'de', 'CSV'),
 ('library.format.ubl', 'en', 'UBL'),
 ('library.format.ubl', 'de', 'UBL'),
 ('library.format.detected', 'en', 'PDF, image, XML or CSV'),
 ('library.format.detected', 'de', 'PDF, Bild, XML oder CSV'),
 ('library.format.edifact', 'en', 'EDIFACT'),
 ('library.format.edifact', 'de', 'EDIFACT'),
 ('library.format.oracle_invoice_json', 'en', 'Oracle invoices'),
 ('library.format.oracle_invoice_json', 'de', 'Oracle-Rechnungen'),
 ('library.format.sap_supplier_invoice', 'en', 'Supplier invoice'),
 ('library.format.sap_supplier_invoice', 'de', 'Lieferantenrechnung'),
 ('library.format.sage_ap_bill', 'en', 'AP bill'),
 ('library.format.sage_ap_bill', 'de', 'Kreditorenbeleg'),
 ('library.format.bc_purchase_invoice', 'en', 'Purchase invoice'),
 ('library.format.bc_purchase_invoice', 'de', 'Einkaufsrechnung'),
 ('connector.https-out.name', 'en', 'HTTPS out'),
 ('connector.https-out.name', 'de', 'HTTPS-Ausgang'),
 ('connector.https-out.description', 'en', 'Posts each payment-eligible invoice to any web address, signed in, once. The base every API connector is built on.'),
 ('connector.https-out.description', 'de', 'Sendet jede zahlungsfähige Rechnung an eine beliebige Webadresse, angemeldet, einmal. Die Grundlage jedes API-Connectors.'),
 ('connector.automation-webhook.name', 'en', 'Automation webhook'),
 ('connector.automation-webhook.name', 'de', 'Automatisierungs-Webhook'),
 ('connector.automation-webhook.description', 'en', 'Starts a Zapier, Make or Power Automate flow with each payment-eligible invoice, as JSON.'),
 ('connector.automation-webhook.description', 'de', 'Startet einen Zapier-, Make- oder Power-Automate-Ablauf mit jeder zahlungsfähigen Rechnung, als JSON.'),
 ('connector.erp-csv.name', 'en', 'ERP CSV file'),
 ('connector.erp-csv.name', 'de', 'ERP-CSV-Datei'),
 ('connector.erp-csv.description', 'en', 'A CSV file of the invoices ready to pay, one row per distribution, downloaded from the ERP export screen. Each invoice once.'),
 ('connector.erp-csv.description', 'de', 'Eine CSV-Datei der zahlungsbereiten Rechnungen, eine Zeile je Verteilung, vom ERP-Export-Bildschirm heruntergeladen. Jede Rechnung einmal.'),
 ('connector.oracle-fusion-payables.name', 'en', 'Oracle Fusion Payables'),
 ('connector.oracle-fusion-payables.name', 'de', 'Oracle Fusion Payables'),
 ('connector.oracle-fusion-payables.description', 'en', 'Creates the invoice in Payables with its lines and distributions, by business unit and supplier site, and keeps Oracle''s invoice id.'),
 ('connector.oracle-fusion-payables.description', 'de', 'Legt die Rechnung in Payables mit Positionen und Verteilungen an, nach Geschäftseinheit und Lieferantenstandort, und behält die Oracle-Rechnungs-ID.'),
 ('connector.sap-s4hana-cloud.name', 'en', 'SAP S/4HANA Cloud'),
 ('connector.sap-s4hana-cloud.name', 'de', 'SAP S/4HANA Cloud'),
 ('connector.sap-s4hana-cloud.description', 'en', 'Posts a supplier invoice by company code, with G/L and cost centre lines or PO references, and keeps SAP''s document number.'),
 ('connector.sap-s4hana-cloud.description', 'de', 'Bucht eine Lieferantenrechnung nach Buchungskreis, mit Sachkonto- und Kostenstellenzeilen oder Bestellbezug, und behält die SAP-Belegnummer.'),
 ('connector.sage-intacct.name', 'en', 'Sage Intacct'),
 ('connector.sage-intacct.name', 'de', 'Sage Intacct'),
 ('connector.sage-intacct.description', 'en', 'Creates an AP bill per invoice, by entity, vendor and GL account, with departments and projects from Account Coding.'),
 ('connector.sage-intacct.description', 'de', 'Legt je Rechnung einen Kreditorenbeleg an, nach Einheit, Lieferant und Sachkonto, mit Abteilungen und Projekten aus der Kontierung.'),
 ('connector.dynamics-365-bc.name', 'en', 'Microsoft Dynamics 365 Business Central'),
 ('connector.dynamics-365-bc.name', 'de', 'Microsoft Dynamics 365 Business Central'),
 ('connector.dynamics-365-bc.description', 'en', 'Creates a purchase invoice draft with its lines and dimensions.'),
 ('connector.dynamics-365-bc.description', 'de', 'Legt einen Einkaufsrechnungsentwurf mit Positionen und Dimensionen an.'),
 ('connector.sftp-out.name', 'en', 'SFTP file drop'),
 ('connector.sftp-out.name', 'de', 'SFTP-Dateiablage'),
 ('connector.sftp-out.description', 'en', 'Writes each invoice, or a daily batch, to a folder on your ERP''s SFTP server.'),
 ('connector.sftp-out.description', 'de', 'Schreibt jede Rechnung oder einen täglichen Stapel in einen Ordner auf dem SFTP-Server Ihres ERP.'),
 ('connector.email-in.name', 'en', 'Email in'),
 ('connector.email-in.name', 'de', 'E-Mail-Eingang'),
 ('connector.email-in.description', 'en', 'An address suppliers send invoices to. Every attachment is read: PDF, image, XML or CSV.'),
 ('connector.email-in.description', 'de', 'Eine Adresse, an die Lieferanten Rechnungen senden. Jeder Anhang wird gelesen: PDF, Bild, XML oder CSV.'),
 ('connector.https-in.name', 'en', 'HTTPS in'),
 ('connector.https-in.name', 'de', 'HTTPS-Eingang'),
 ('connector.https-in.description', 'en', 'An address a supplier''s system or portal posts invoices to, with its own keys.'),
 ('connector.https-in.description', 'de', 'Eine Adresse, an die das System oder Portal eines Lieferanten Rechnungen sendet, mit eigenen Schlüsseln.'),
 ('connector.file-import.name', 'en', 'AP upload'),
 ('connector.file-import.name', 'de', 'AP-Upload'),
 ('connector.file-import.description', 'en', 'The AP team''s own way in: upload documents, key an invoice, or a batch. One per process.'),
 ('connector.file-import.description', 'de', 'Der eigene Weg des Kreditorenteams: Dokumente hochladen, eine Rechnung erfassen oder ein Stapel. Einer je Prozess.'),
 ('connector.sftp-in.name', 'en', 'SFTP in'),
 ('connector.sftp-in.name', 'de', 'SFTP-Eingang'),
 ('connector.sftp-in.description', 'en', 'Picks up invoice files from a folder on an SFTP server.'),
 ('connector.sftp-in.description', 'de', 'Holt Rechnungsdateien aus einem Ordner auf einem SFTP-Server ab.'),
 ('connector.edi-in.name', 'en', 'EDI in'),
 ('connector.edi-in.name', 'de', 'EDI-Eingang'),
 ('connector.edi-in.description', 'en', 'EDIFACT INVOIC messages from an EDI network.'),
 ('connector.edi-in.description', 'de', 'EDIFACT-INVOIC-Nachrichten aus einem EDI-Netz.'),
 ('connector.peppol-in.name', 'en', 'Peppol in'),
 ('connector.peppol-in.name', 'de', 'Peppol-Eingang'),
 ('connector.peppol-in.description', 'en', 'Invoices sent over the Peppol network, through an access point.'),
 ('connector.peppol-in.description', 'de', 'Über das Peppol-Netz gesendete Rechnungen, über einen Access Point.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.routelibrary','help.screen.routelibrary','library.open','library.heading','library.subtitle','library.note','library.failed','library.filter.all','library.filter.destination','library.filter.source','library.filter.erp','library.filter.automation','library.filter.generic','library.publisher.standard','library.available','library.planned','library.inuse','library.upgrades','library.upgradeto','library.upgrade','library.authchanged','library.connectorline','library.add','library.addtitle','library.addsubdest','library.addsubsource','library.process','library.error.one_per_process','library.error.not_available','library.error.name_taken','httpsout.error.fixed_setting','httpsout.error.auth_not_allowed','library.transport.https','library.transport.email','library.transport.upload','library.transport.sftp','library.transport.edi','library.transport.file_download','library.transport.peppol','library.format.vf_json','library.format.csv','library.format.ubl','library.format.detected','library.format.edifact','library.format.oracle_invoice_json','library.format.sap_supplier_invoice','library.format.sage_ap_bill','library.format.bc_purchase_invoice','connector.https-out.name','connector.https-out.description','connector.automation-webhook.name','connector.automation-webhook.description','connector.erp-csv.name','connector.erp-csv.description','connector.oracle-fusion-payables.name','connector.oracle-fusion-payables.description','connector.sap-s4hana-cloud.name','connector.sap-s4hana-cloud.description','connector.sage-intacct.name','connector.sage-intacct.description','connector.dynamics-365-bc.name','connector.dynamics-365-bc.description','connector.sftp-out.name','connector.sftp-out.description','connector.email-in.name','connector.email-in.description','connector.https-in.name','connector.https-in.description','connector.file-import.name','connector.file-import.description','connector.sftp-in.name','connector.sftp-in.description','connector.edi-in.name','connector.edi-in.description','connector.peppol-in.name','connector.peppol-in.description') == 152
