-- 0236_outbound_mapping_strings.sql
-- Decision 0591. Outbound mapping: the Destination panel's card, the editor,
-- the names of the VibeFinance invoice's fields, and the monitor's explanation.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('help.screen.outboundmapping', 'en', 'How each invoice is laid out for this Destination. The VibeFinance invoice is on the left, with the values of a real invoice ready to pay. On the right is what is sent: the invoice''s fields, then each line''s, then each distribution''s, each named as the receiving system expects. Choose a field on the left to add it, or to use it for the field you chose before. Choose a sent field to rename it, make it required, give it a fixed value, or say in plain words what should happen to its value. Every change saves the draft. Try lays out a real invoice without sending it, and Publish makes the draft what the Destination sends.'),
 ('help.screen.outboundmapping', 'de', 'Wie jede Rechnung für dieses Ziel aufgebaut wird. Links steht die VibeFinance-Rechnung mit den Werten einer echten zahlungsbereiten Rechnung. Rechts steht, was gesendet wird: die Felder der Rechnung, dann jeder Position, dann jeder Verteilung, jeweils so benannt, wie das empfangende System es erwartet. Wählen Sie links ein Feld, um es hinzuzufügen oder für das zuvor gewählte Feld zu verwenden. Wählen Sie ein gesendetes Feld, um es umzubenennen, zur Pflicht zu machen, ihm einen festen Wert zu geben oder in eigenen Worten zu sagen, was mit seinem Wert geschehen soll. Jede Änderung speichert den Entwurf. Testen baut eine echte Rechnung auf, ohne sie zu senden, und Veröffentlichen macht den Entwurf zu dem, was das Ziel sendet.'),
 ('nav.outboundmapping', 'en', 'Outbound mapping'),
 ('nav.outboundmapping', 'de', 'Ausgangs-Mapping'),
 ('httpsout.format.mapped', 'en', 'Its own mapping'),
 ('httpsout.format.mapped', 'de', 'Eigenes Mapping'),
 ('httpsout.error.no_live_mapping', 'en', 'Publish its own mapping first.'),
 ('httpsout.error.no_live_mapping', 'de', 'Veröffentlichen Sie zuerst das eigene Mapping.'),
 ('httpsout.error.format_fixed', 'en', 'This connector keeps its layout.'),
 ('httpsout.error.format_fixed', 'de', 'Dieser Connector behält sein Layout.'),
 ('httpsout.error.already_copied', 'en', 'This Destination already has its own mapping.'),
 ('httpsout.error.already_copied', 'de', 'Dieses Ziel hat bereits ein eigenes Mapping.'),
 ('httpsout.error.not_https_out', 'en', 'Only an HTTPS out Destination has an outbound mapping.'),
 ('httpsout.error.not_https_out', 'de', 'Nur ein HTTPS-Ausgang-Ziel hat ein Ausgangs-Mapping.'),
 ('outmap.card.heading', 'en', 'How each invoice is laid out'),
 ('outmap.card.heading', 'de', 'Wie jede Rechnung aufgebaut wird'),
 ('outmap.card.standard', 'en', 'The standard layout: VibeFinance invoice JSON, version 1.'),
 ('outmap.card.standard', 'de', 'Das Standard-Layout: VibeFinance-Rechnungs-JSON, Version 1.'),
 ('outmap.card.live', 'en', 'Its own mapping, version {n} live'),
 ('outmap.card.live', 'de', 'Eigenes Mapping, Version {n} aktiv'),
 ('outmap.card.draft', 'en', 'draft {n}'),
 ('outmap.card.draft', 'de', 'Entwurf {n}'),
 ('outmap.card.sending', 'en', 'sending it'),
 ('outmap.card.sending', 'de', 'wird gesendet'),
 ('outmap.card.notsending', 'en', 'sending the standard layout (choose Its own mapping as the format to send it)'),
 ('outmap.card.notsending', 'de', 'sendet das Standard-Layout (wählen Sie Eigenes Mapping als Format, um es zu senden)'),
 ('outmap.card.copy', 'en', 'Make my own copy'),
 ('outmap.card.copy', 'de', 'Eigene Kopie erstellen'),
 ('outmap.card.open', 'en', 'Open the mapping'),
 ('outmap.card.open', 'de', 'Mapping öffnen'),
 ('outmap.card.hint', 'en', 'Your own copy names each field as the receiving system expects, and can change values on the way. It is tried on a real invoice before it is published.'),
 ('outmap.card.hint', 'de', 'Ihre eigene Kopie benennt jedes Feld so, wie das empfangende System es erwartet, und kann Werte unterwegs ändern. Sie wird vor dem Veröffentlichen an einer echten Rechnung getestet.'),
 ('outmap.card.fixed', 'en', 'This connector keeps its layout.'),
 ('outmap.card.fixed', 'de', 'Dieser Connector behält sein Layout.'),
 ('outmap.notsent', 'en', 'Not sent:'),
 ('outmap.notsent', 'de', 'Nicht gesendet:'),
 ('outmap.title', 'en', 'Outbound mapping · {name}'),
 ('outmap.title', 'de', 'Ausgangs-Mapping · {name}'),
 ('outmap.heading', 'en', 'What is sent for each invoice'),
 ('outmap.heading', 'de', 'Was für jede Rechnung gesendet wird'),
 ('outmap.sendingown', 'en', 'this Destination sends its own mapping'),
 ('outmap.sendingown', 'de', 'dieses Ziel sendet sein eigenes Mapping'),
 ('outmap.sendingstandard', 'en', 'this Destination sends the standard layout until one is published'),
 ('outmap.sendingstandard', 'de', 'dieses Ziel sendet das Standard-Layout, bis eines veröffentlicht ist'),
 ('outmap.counts', 'en', '{n} fields sent · {f} with a function'),
 ('outmap.counts', 'de', '{n} gesendete Felder · {f} mit Funktion'),
 ('outmap.legend.line', 'en', 'where a value comes from'),
 ('outmap.legend.line', 'de', 'woher ein Wert kommt'),
 ('outmap.legend.required', 'en', 'required: an empty value stops the invoice being sent'),
 ('outmap.legend.required', 'de', 'Pflicht: ein leerer Wert verhindert das Senden der Rechnung'),
 ('outmap.from', 'en', 'The VibeFinance invoice'),
 ('outmap.from', 'de', 'Die VibeFinance-Rechnung'),
 ('outmap.fromsub', 'en', 'Values from invoice {n}'),
 ('outmap.fromsub', 'de', 'Werte aus Rechnung {n}'),
 ('outmap.nosample', 'en', 'No invoice is ready to pay yet, so no values are shown.'),
 ('outmap.nosample', 'de', 'Noch keine Rechnung ist zahlungsbereit, daher werden keine Werte gezeigt.'),
 ('outmap.to', 'en', 'What {name} sends'),
 ('outmap.to', 'de', 'Was {name} sendet'),
 ('outmap.tosub', 'en', 'Named as the receiving system expects. A dot nests, as supplier.id.'),
 ('outmap.tosub', 'de', 'So benannt, wie das empfangende System es erwartet. Ein Punkt verschachtelt, wie supplier.id.'),
 ('outmap.level', 'en', 'Sent'),
 ('outmap.level', 'de', 'Gesendet'),
 ('outmap.level.invoice', 'en', 'Once per invoice'),
 ('outmap.level.invoice', 'de', 'Einmal je Rechnung'),
 ('outmap.level.line', 'en', 'Each line'),
 ('outmap.level.line', 'de', 'Jede Position'),
 ('outmap.level.distribution', 'en', 'Each distribution'),
 ('outmap.level.distribution', 'de', 'Jede Verteilung'),
 ('outmap.levelhint.invoice', 'en', 'Sent once for the invoice. It can read the invoice''s own fields.'),
 ('outmap.levelhint.invoice', 'de', 'Einmal für die Rechnung gesendet. Es kann die Felder der Rechnung lesen.'),
 ('outmap.levelhint.line', 'en', 'Sent once for each line. It can read the line''s fields and the invoice''s.'),
 ('outmap.levelhint.line', 'de', 'Einmal je Position gesendet. Es kann die Felder der Position und der Rechnung lesen.'),
 ('outmap.levelhint.distribution', 'en', 'Sent once for each distribution of a line''s coding. It can read the distribution''s fields, its line''s and the invoice''s.'),
 ('outmap.levelhint.distribution', 'de', 'Einmal je Verteilung der Kontierung einer Position gesendet. Es kann die Felder der Verteilung, ihrer Position und der Rechnung lesen.'),
 ('outmap.nofields', 'en', 'Nothing sent at this level.'),
 ('outmap.nofields', 'de', 'Auf dieser Ebene wird nichts gesendet.'),
 ('outmap.place.line', 'en', 'inside each line'),
 ('outmap.place.line', 'de', 'in jeder Position'),
 ('outmap.place.invoice', 'en', 'all on the invoice'),
 ('outmap.place.invoice', 'de', 'alle auf der Rechnung'),
 ('outmap.empty.omit', 'en', 'Left out'),
 ('outmap.empty.omit', 'de', 'Weggelassen'),
 ('outmap.empty.null', 'en', 'Sent as null'),
 ('outmap.empty.null', 'de', 'Als null gesendet'),
 ('outmap.fixed', 'en', 'Fixed'),
 ('outmap.fixed', 'de', 'Fest'),
 ('outmap.howto', 'en', 'How it works'),
 ('outmap.howto', 'de', 'So funktioniert es'),
 ('outmap.howtotext', 'en', 'Choose a field of the invoice on the left to add it to what is sent. Choose a sent field on the right to rename it, make it required, give it a fixed value, or change its value with a function said in plain words. Every change saves the draft.'),
 ('outmap.howtotext', 'de', 'Wählen Sie links ein Feld der Rechnung, um es dem Gesendeten hinzuzufügen. Wählen Sie rechts ein gesendetes Feld, um es umzubenennen, zur Pflicht zu machen, ihm einen festen Wert zu geben oder seinen Wert mit einer in eigenen Worten gesagten Funktion zu ändern. Jede Änderung speichert den Entwurf.'),
 ('outmap.addfixed', 'en', 'A field with a fixed value'),
 ('outmap.addfixed', 'de', 'Ein Feld mit festem Wert'),
 ('outmap.addas', 'en', 'Add it as a field sent'),
 ('outmap.addas', 'de', 'Als gesendetes Feld hinzufügen'),
 ('outmap.add', 'en', 'Add'),
 ('outmap.add', 'de', 'Hinzufügen'),
 ('outmap.usefor', 'en', 'Use it for {target}'),
 ('outmap.usefor', 'de', 'Für {target} verwenden'),
 ('outmap.name', 'en', 'Name'),
 ('outmap.name', 'de', 'Name'),
 ('outmap.value', 'en', 'Value'),
 ('outmap.value', 'de', 'Wert'),
 ('outmap.sample', 'en', 'Value'),
 ('outmap.sample', 'de', 'Wert'),
 ('outmap.nametaken', 'en', '{name} is already sent at this level.'),
 ('outmap.nametaken', 'de', '{name} wird auf dieser Ebene bereits gesendet.'),
 ('outmap.comesfrom', 'en', 'Comes from'),
 ('outmap.comesfrom', 'de', 'Kommt aus'),
 ('outmap.orfixed', 'en', 'Or a fixed value'),
 ('outmap.orfixed', 'de', 'Oder ein fester Wert'),
 ('outmap.fixedplaceholder', 'en', 'Always send this value'),
 ('outmap.fixedplaceholder', 'de', 'Immer diesen Wert senden'),
 ('outmap.required', 'en', 'Required'),
 ('outmap.required', 'de', 'Pflicht'),
 ('outmap.requiredhint', 'en', 'Do not send the invoice when it is empty'),
 ('outmap.requiredhint', 'de', 'Die Rechnung nicht senden, wenn es leer ist'),
 ('outmap.remove', 'en', 'Remove field'),
 ('outmap.remove', 'de', 'Feld entfernen'),
 ('outmap.settings', 'en', 'Layout'),
 ('outmap.settings', 'de', 'Layout'),
 ('outmap.linesname', 'en', 'The lines are sent as'),
 ('outmap.linesname', 'de', 'Die Positionen werden gesendet als'),
 ('outmap.distsname', 'en', 'The distributions are sent as'),
 ('outmap.distsname', 'de', 'Die Verteilungen werden gesendet als'),
 ('outmap.place', 'en', 'Distributions go'),
 ('outmap.place', 'de', 'Verteilungen stehen'),
 ('outmap.empty', 'en', 'An empty value is'),
 ('outmap.empty', 'de', 'Ein leerer Wert wird'),
 ('outmap.try', 'en', 'Try it on an invoice'),
 ('outmap.try', 'de', 'An einer Rechnung testen'),
 ('outmap.trybutton', 'en', 'Try'),
 ('outmap.trybutton', 'de', 'Testen'),
 ('outmap.tryhint', 'en', 'Lays out a real invoice ready to pay, as it would be sent. Nothing is sent.'),
 ('outmap.tryhint', 'de', 'Baut eine echte zahlungsbereite Rechnung so auf, wie sie gesendet würde. Es wird nichts gesendet.'),
 ('outmap.nocandidates', 'en', 'No invoice is ready to pay yet to try it on.'),
 ('outmap.nocandidates', 'de', 'Noch keine Rechnung ist zahlungsbereit, um daran zu testen.'),
 ('outmap.problems', 'en', 'What it could not lay out'),
 ('outmap.problems', 'de', 'Was nicht aufgebaut werden konnte'),
 ('outmap.noproblems', 'en', 'Laid out with no problems.'),
 ('outmap.noproblems', 'de', 'Ohne Probleme aufgebaut.'),
 ('outmap.tryfailed', 'en', 'It could not be tried. Try again.'),
 ('outmap.tryfailed', 'de', 'Der Test war nicht möglich. Versuchen Sie es erneut.'),
 ('outmap.publish', 'en', 'Publish'),
 ('outmap.publish', 'de', 'Veröffentlichen'),
 ('outmap.published', 'en', 'Version {n} is live, and is what {name} sends.'),
 ('outmap.published', 'de', 'Version {n} ist aktiv und wird von {name} gesendet.'),
 ('outmap.publishrefused', 'en', 'Not published: the draft cannot lay out the invoice it was tried on.'),
 ('outmap.publishrefused', 'de', 'Nicht veröffentlicht: Der Entwurf kann die getestete Rechnung nicht aufbauen.'),
 ('outmap.publishfailed', 'en', 'It could not be published. Try again.'),
 ('outmap.publishfailed', 'de', 'Die Veröffentlichung war nicht möglich. Versuchen Sie es erneut.'),
 ('outmap.error.not_tried', 'en', 'Try it on an invoice first.'),
 ('outmap.error.not_tried', 'de', 'Testen Sie es zuerst an einer Rechnung.'),
 ('outmap.error.no_draft', 'en', 'There is no draft to publish.'),
 ('outmap.error.no_draft', 'de', 'Es gibt keinen Entwurf zum Veröffentlichen.'),
 ('outmap.error.retired', 'en', 'The Destination is retired.'),
 ('outmap.error.retired', 'de', 'Das Ziel ist stillgelegt.'),
 ('outmap.savefailed', 'en', 'The change could not be saved.'),
 ('outmap.savefailed', 'de', 'Die Änderung konnte nicht gespeichert werden.'),
 ('outmap.loadfailed', 'en', 'The mapping could not be loaded. Try again.'),
 ('outmap.loadfailed', 'de', 'Das Mapping konnte nicht geladen werden. Versuchen Sie es erneut.'),
 ('outmap.back', 'en', 'Back'),
 ('outmap.back', 'de', 'Zurück'),
 ('outmap.src.id', 'en', 'Invoice id'),
 ('outmap.src.id', 'de', 'Rechnungs-ID'),
 ('outmap.src.invoicenumber', 'en', 'Invoice number'),
 ('outmap.src.invoicenumber', 'de', 'Rechnungsnummer'),
 ('outmap.src.issuedate', 'en', 'Issue date'),
 ('outmap.src.issuedate', 'de', 'Rechnungsdatum'),
 ('outmap.src.duedate', 'en', 'Due date'),
 ('outmap.src.duedate', 'de', 'Fälligkeitsdatum'),
 ('outmap.src.currency', 'en', 'Currency'),
 ('outmap.src.currency', 'de', 'Währung'),
 ('outmap.src.company', 'en', 'Company'),
 ('outmap.src.company', 'de', 'Gesellschaft'),
 ('outmap.src.supplier.erpid', 'en', 'Supplier ERP id'),
 ('outmap.src.supplier.erpid', 'de', 'ERP-ID des Lieferanten'),
 ('outmap.src.supplier.site', 'en', 'Supplier site'),
 ('outmap.src.supplier.site', 'de', 'Lieferantenstandort'),
 ('outmap.src.supplier.name', 'en', 'Supplier name'),
 ('outmap.src.supplier.name', 'de', 'Lieferantenname'),
 ('outmap.src.supplier.vatid', 'en', 'Supplier VAT id'),
 ('outmap.src.supplier.vatid', 'de', 'USt-IdNr. des Lieferanten'),
 ('outmap.src.purchaseorder', 'en', 'Purchase order'),
 ('outmap.src.purchaseorder', 'de', 'Bestellung'),
 ('outmap.src.totals.net', 'en', 'Net total'),
 ('outmap.src.totals.net', 'de', 'Nettosumme'),
 ('outmap.src.totals.vat', 'en', 'VAT total'),
 ('outmap.src.totals.vat', 'de', 'Steuersumme'),
 ('outmap.src.totals.total', 'en', 'Total'),
 ('outmap.src.totals.total', 'de', 'Gesamtbetrag'),
 ('outmap.src.line.linenumber', 'en', 'Line number'),
 ('outmap.src.line.linenumber', 'de', 'Positionsnummer'),
 ('outmap.src.line.description', 'en', 'Description'),
 ('outmap.src.line.description', 'de', 'Beschreibung'),
 ('outmap.src.line.quantity', 'en', 'Quantity'),
 ('outmap.src.line.quantity', 'de', 'Menge'),
 ('outmap.src.line.unit', 'en', 'Unit'),
 ('outmap.src.line.unit', 'de', 'Einheit'),
 ('outmap.src.line.poline', 'en', 'PO line'),
 ('outmap.src.line.poline', 'de', 'Bestellposition'),
 ('outmap.src.line.vatcategory', 'en', 'VAT category'),
 ('outmap.src.line.vatcategory', 'de', 'Steuerkategorie'),
 ('outmap.src.line.vatrate', 'en', 'VAT rate'),
 ('outmap.src.line.vatrate', 'de', 'Steuersatz'),
 ('outmap.src.line.netamount', 'en', 'Line net amount'),
 ('outmap.src.line.netamount', 'de', 'Nettobetrag der Position'),
 ('outmap.src.distribution.sequence', 'en', 'Distribution number'),
 ('outmap.src.distribution.sequence', 'de', 'Verteilungsnummer'),
 ('outmap.src.distribution.splitrow', 'en', 'Split row'),
 ('outmap.src.distribution.splitrow', 'de', 'Aufteilungszeile'),
 ('outmap.src.distribution.netamount', 'en', 'Distribution amount'),
 ('outmap.src.distribution.netamount', 'de', 'Verteilungsbetrag'),
 ('outmap.src.distribution.costcentre', 'en', 'Cost centre'),
 ('outmap.src.distribution.costcentre', 'de', 'Kostenstelle'),
 ('outmap.src.distribution.project', 'en', 'Project'),
 ('outmap.src.distribution.project', 'de', 'Projekt'),
 ('outmap.src.distribution.commoditycode', 'en', 'Commodity code'),
 ('outmap.src.distribution.commoditycode', 'de', 'Warengruppe'),
 ('outmap.src.distribution.glcode', 'en', 'GL code'),
 ('outmap.src.distribution.glcode', 'de', 'Sachkonto'),
 ('routemonitor.error.outbound_mapping.title', 'en', 'Its own mapping could not lay out this invoice'),
 ('routemonitor.error.outbound_mapping.title', 'de', 'Das eigene Mapping konnte diese Rechnung nicht aufbauen'),
 ('routemonitor.error.outbound_mapping.body', 'en', 'Nothing was sent. The Destination''s outbound mapping needs a value this invoice does not have, or a function could not change the value it has. The reason names the field.'),
 ('routemonitor.error.outbound_mapping.body', 'de', 'Es wurde nichts gesendet. Das Ausgangs-Mapping des Ziels braucht einen Wert, den diese Rechnung nicht hat, oder eine Funktion konnte den vorhandenen Wert nicht ändern. Der Grund nennt das Feld.'),
 ('routemonitor.error.outbound_mapping.fix', 'en', 'Correct the invoice or its look-up list, or change the mapping and publish it, then Send again.'),
 ('routemonitor.error.outbound_mapping.fix', 'de', 'Korrigieren Sie die Rechnung oder ihre Nachschlageliste, oder ändern und veröffentlichen Sie das Mapping, dann Erneut senden.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('help.screen.outboundmapping','nav.outboundmapping','httpsout.format.mapped','httpsout.error.no_live_mapping','httpsout.error.format_fixed','httpsout.error.already_copied','httpsout.error.not_https_out','outmap.card.heading','outmap.card.standard','outmap.card.live','outmap.card.draft','outmap.card.sending','outmap.card.notsending','outmap.card.copy','outmap.card.open','outmap.card.hint','outmap.card.fixed','outmap.notsent','outmap.title','outmap.heading','outmap.sendingown','outmap.sendingstandard','outmap.counts','outmap.legend.line','outmap.legend.required','outmap.from','outmap.fromsub','outmap.nosample','outmap.to','outmap.tosub','outmap.level','outmap.level.invoice','outmap.level.line','outmap.level.distribution','outmap.levelhint.invoice','outmap.levelhint.line','outmap.levelhint.distribution','outmap.nofields','outmap.place.line','outmap.place.invoice','outmap.empty.omit','outmap.empty.null','outmap.fixed','outmap.howto','outmap.howtotext','outmap.addfixed','outmap.addas','outmap.add','outmap.usefor','outmap.name','outmap.value','outmap.sample','outmap.nametaken','outmap.comesfrom','outmap.orfixed','outmap.fixedplaceholder','outmap.required','outmap.requiredhint','outmap.remove','outmap.settings','outmap.linesname','outmap.distsname','outmap.place','outmap.empty','outmap.try','outmap.trybutton','outmap.tryhint','outmap.nocandidates','outmap.problems','outmap.noproblems','outmap.tryfailed','outmap.publish','outmap.published','outmap.publishrefused','outmap.publishfailed','outmap.error.not_tried','outmap.error.no_draft','outmap.error.retired','outmap.savefailed','outmap.loadfailed','outmap.back','outmap.src.id','outmap.src.invoicenumber','outmap.src.issuedate','outmap.src.duedate','outmap.src.currency','outmap.src.company','outmap.src.supplier.erpid','outmap.src.supplier.site','outmap.src.supplier.name','outmap.src.supplier.vatid','outmap.src.purchaseorder','outmap.src.totals.net','outmap.src.totals.vat','outmap.src.totals.total','outmap.src.line.linenumber','outmap.src.line.description','outmap.src.line.quantity','outmap.src.line.unit','outmap.src.line.poline','outmap.src.line.vatcategory','outmap.src.line.vatrate','outmap.src.line.netamount','outmap.src.distribution.sequence','outmap.src.distribution.splitrow','outmap.src.distribution.netamount','outmap.src.distribution.costcentre','outmap.src.distribution.project','outmap.src.distribution.commoditycode','outmap.src.distribution.glcode','routemonitor.error.outbound_mapping.title','routemonitor.error.outbound_mapping.body','routemonitor.error.outbound_mapping.fix') == 226
