-- 0239_invitation_strings.sql
-- Decision 0593. Accepting an invitation (the welcome page), and inviting
-- a person from the Access screen.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('welcome.title', 'en', 'Welcome to VibeFinance'),
 ('welcome.title', 'de', 'Willkommen bei VibeFinance'),
 ('welcome.for', 'en', '{email}, for {customer}. Enter the 6-digit code from your email and choose your password.'),
 ('welcome.for', 'de', '{email}, für {customer}. Geben Sie den 6-stelligen Code aus Ihrer E-Mail ein und wählen Sie Ihr Passwort.'),
 ('welcome.code', 'en', 'Code from the email'),
 ('welcome.code', 'de', 'Code aus der E-Mail'),
 ('welcome.password', 'en', 'Choose a password (at least 12 characters)'),
 ('welcome.password', 'de', 'Passwort wählen (mindestens 12 Zeichen)'),
 ('welcome.again', 'en', 'The password again'),
 ('welcome.again', 'de', 'Das Passwort noch einmal'),
 ('welcome.submit', 'en', 'Set my password'),
 ('welcome.submit', 'de', 'Mein Passwort festlegen'),
 ('welcome.done', 'en', 'Your password is set. Sign in as {email}.'),
 ('welcome.done', 'de', 'Ihr Passwort ist festgelegt. Melden Sie sich als {email} an.'),
 ('welcome.signin', 'en', 'Go to sign in'),
 ('welcome.signin', 'de', 'Zur Anmeldung'),
 ('welcome.error.not_valid', 'en', 'This invitation link is not valid. Ask for a new invitation.'),
 ('welcome.error.not_valid', 'de', 'Dieser Einladungslink ist nicht gültig. Bitten Sie um eine neue Einladung.'),
 ('welcome.error.expired', 'en', 'This invitation has expired. Ask for a new one.'),
 ('welcome.error.expired', 'de', 'Diese Einladung ist abgelaufen. Bitten Sie um eine neue.'),
 ('welcome.error.cancelled', 'en', 'This invitation was replaced or cancelled. Use the newest email, or ask for a new one.'),
 ('welcome.error.cancelled', 'de', 'Diese Einladung wurde ersetzt oder zurückgezogen. Verwenden Sie die neueste E-Mail oder bitten Sie um eine neue.'),
 ('welcome.error.spent', 'en', 'Too many wrong codes, so this invitation can no longer be used. Ask for a new one.'),
 ('welcome.error.spent', 'de', 'Zu viele falsche Codes, daher kann diese Einladung nicht mehr verwendet werden. Bitten Sie um eine neue.'),
 ('welcome.error.accepted', 'en', 'This invitation has already been used. Sign in with the password you chose.'),
 ('welcome.error.accepted', 'de', 'Diese Einladung wurde bereits verwendet. Melden Sie sich mit dem gewählten Passwort an.'),
 ('welcome.error.wrong_code', 'en', 'That code is not right. {n} tries left.'),
 ('welcome.error.wrong_code', 'de', 'Dieser Code ist nicht richtig. Noch {n} Versuche.'),
 ('welcome.error.short_password', 'en', 'The password must be at least 12 characters.'),
 ('welcome.error.short_password', 'de', 'Das Passwort muss mindestens 12 Zeichen lang sein.'),
 ('welcome.error.mismatch', 'en', 'The two passwords are not the same.'),
 ('welcome.error.mismatch', 'de', 'Die beiden Passwörter stimmen nicht überein.'),
 ('welcome.error.failed', 'en', 'That did not work. Try again.'),
 ('welcome.error.failed', 'de', 'Das hat nicht funktioniert. Versuchen Sie es erneut.'),
 ('invite.column', 'en', 'Signing in'),
 ('invite.column', 'de', 'Anmeldung'),
 ('invite.onadd', 'en', 'Email them an invitation to choose their password'),
 ('invite.onadd', 'de', 'Eine Einladung per E-Mail senden, um das Passwort zu wählen'),
 ('invite.send', 'en', 'Invite'),
 ('invite.send', 'de', 'Einladen'),
 ('invite.again', 'en', 'Invite again'),
 ('invite.again', 'de', 'Erneut einladen'),
 ('invite.sent', 'en', 'An invitation has been emailed to {email}.'),
 ('invite.sent', 'de', 'Eine Einladung wurde an {email} gesendet.'),
 ('invite.unknown', 'en', 'Could not be checked'),
 ('invite.unknown', 'de', 'Konnte nicht geprüft werden'),
 ('invite.status.none', 'en', 'Not invited'),
 ('invite.status.none', 'de', 'Nicht eingeladen'),
 ('invite.status.pending', 'en', 'Invited, until {until}'),
 ('invite.status.pending', 'de', 'Eingeladen, bis {until}'),
 ('invite.status.notsent', 'en', 'Invitation not sent'),
 ('invite.status.notsent', 'de', 'Einladung nicht gesendet'),
 ('invite.status.accepted', 'en', 'Can sign in'),
 ('invite.status.accepted', 'de', 'Kann sich anmelden'),
 ('invite.status.expired', 'en', 'Invitation expired'),
 ('invite.status.expired', 'de', 'Einladung abgelaufen'),
 ('invite.status.spent', 'en', 'Invitation spent'),
 ('invite.status.spent', 'de', 'Einladung verbraucht'),
 ('invite.status.cancelled', 'en', 'Invitation cancelled'),
 ('invite.status.cancelled', 'de', 'Einladung zurückgezogen'),
 ('invite.error.not_sent', 'en', 'The invitation was made, but its email could not be sent. Ask VibeFinance to check invitation email.'),
 ('invite.error.not_sent', 'de', 'Die Einladung wurde erstellt, aber die E-Mail konnte nicht gesendet werden. Bitten Sie VibeFinance, den Einladungsversand zu prüfen.'),
 ('invite.error.unreachable', 'en', 'The control plane could not be reached. Try again.'),
 ('invite.error.unreachable', 'de', 'Die Steuerungsebene war nicht erreichbar. Versuchen Sie es erneut.'),
 ('invite.error.not_configured', 'en', 'This instance cannot invite yet: its link to the control plane is not set up.'),
 ('invite.error.not_configured', 'de', 'Diese Instanz kann noch nicht einladen: Ihre Verbindung zur Steuerungsebene ist nicht eingerichtet.'),
 ('invite.error.bad_email', 'en', 'This person''s email address cannot receive an invitation.'),
 ('invite.error.bad_email', 'de', 'An diese E-Mail-Adresse kann keine Einladung gesendet werden.'),
 ('invite.error.outside_administered_units', 'en', 'You can invite only people in the units you administer.'),
 ('invite.error.outside_administered_units', 'de', 'Sie können nur Personen in den von Ihnen verwalteten Einheiten einladen.'),
 ('invite.error.failed', 'en', 'The invitation could not be sent. Try again.'),
 ('invite.error.failed', 'de', 'Die Einladung konnte nicht gesendet werden. Versuchen Sie es erneut.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('welcome.title','welcome.for','welcome.code','welcome.password','welcome.again','welcome.submit','welcome.done','welcome.signin','welcome.error.not_valid','welcome.error.expired','welcome.error.cancelled','welcome.error.spent','welcome.error.accepted','welcome.error.wrong_code','welcome.error.short_password','welcome.error.mismatch','welcome.error.failed','invite.column','invite.onadd','invite.send','invite.again','invite.sent','invite.unknown','invite.status.none','invite.status.pending','invite.status.notsent','invite.status.accepted','invite.status.expired','invite.status.spent','invite.status.cancelled','invite.error.not_sent','invite.error.unreachable','invite.error.not_configured','invite.error.bad_email','invite.error.outside_administered_units','invite.error.failed') == 72
