-- 0242_submit_for_review_strings.sql
-- Decision 0595. Submitting a Destination for review, from a partner's sandbox.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('submit.heading', 'en', 'Share in the Route library'),
 ('submit.heading', 'de', 'In der Routen-Bibliothek teilen'),
 ('submit.hint', 'en', 'Submit this Destination as a connector for {partner}''s customers. VibeFinance reviews each version before any customer sees it. Its address and secrets are never sent: each customer gives their own.'),
 ('submit.hint', 'de', 'Reichen Sie dieses Ziel als Connector für die Kunden von {partner} ein. VibeFinance prüft jede Version, bevor ein Kunde sie sieht. Adresse und Geheimnisse werden nie übertragen: Jeder Kunde gibt eigene an.'),
 ('submit.version', 'en', 'Version'),
 ('submit.version', 'de', 'Version'),
 ('submit.status.submitted', 'en', 'Waiting for review'),
 ('submit.status.submitted', 'de', 'Wartet auf Prüfung'),
 ('submit.status.approved', 'en', 'Approved'),
 ('submit.status.approved', 'de', 'Freigegeben'),
 ('submit.status.returned', 'en', 'Sent back'),
 ('submit.status.returned', 'de', 'Zurückgegeben'),
 ('submit.status.withdrawn', 'en', 'Withdrawn'),
 ('submit.status.withdrawn', 'de', 'Zurückgezogen'),
 ('submit.withdraw', 'en', 'Withdraw'),
 ('submit.withdraw', 'de', 'Zurückziehen'),
 ('submit.withdrawn', 'en', 'Withdrawn. You can submit again.'),
 ('submit.withdrawn', 'de', 'Zurückgezogen. Sie können erneut einreichen.'),
 ('submit.name', 'en', 'Connector name'),
 ('submit.name', 'de', 'Name des Connectors'),
 ('submit.docs', 'en', 'Vendor''s API documentation (optional)'),
 ('submit.docs', 'de', 'API-Dokumentation des Herstellers (optional)'),
 ('submit.description', 'en', 'What it does'),
 ('submit.description', 'de', 'Was er tut'),
 ('submit.descriptionhint', 'en', 'Shown to customers in the Route library.'),
 ('submit.descriptionhint', 'de', 'Wird Kunden in der Routen-Bibliothek angezeigt.'),
 ('submit.notes', 'en', 'Notes for the reviewer'),
 ('submit.notes', 'de', 'Hinweise für die Prüfung'),
 ('submit.noteshint', 'en', 'What changed, and how it was tried. Only VibeFinance sees these.'),
 ('submit.noteshint', 'de', 'Was sich geändert hat und wie getestet wurde. Nur VibeFinance sieht diese.'),
 ('submit.fixed', 'en', 'Customers may not change'),
 ('submit.fixed', 'de', 'Kunden dürfen nicht ändern'),
 ('submit.fixedhint', 'en', 'Fix the format to keep your layout.'),
 ('submit.fixedhint', 'de', 'Legen Sie das Format fest, um Ihr Layout zu behalten.'),
 ('submit.auths', 'en', 'Ways customers may sign in'),
 ('submit.auths', 'de', 'Anmeldearten für Kunden'),
 ('submit.audience', 'en', 'Which customers see it'),
 ('submit.audience', 'de', 'Welche Kunden ihn sehen'),
 ('submit.audience.all', 'en', 'All the customers you serve'),
 ('submit.audience.all', 'de', 'Alle Kunden, die Sie betreuen'),
 ('submit.audience.some', 'en', 'Only these'),
 ('submit.audience.some', 'de', 'Nur diese'),
 ('submit.submit', 'en', 'Submit for review'),
 ('submit.submit', 'de', 'Zur Prüfung einreichen'),
 ('submit.again', 'en', 'Submit version {n}'),
 ('submit.again', 'de', 'Version {n} einreichen'),
 ('submit.sent', 'en', 'Version {n} is waiting for VibeFinance''s review.'),
 ('submit.sent', 'de', 'Version {n} wartet auf die Prüfung durch VibeFinance.'),
 ('submit.draftnote', 'en', 'Draft {n} of its mapping is not published: the published version is what is submitted.'),
 ('submit.draftnote', 'de', 'Entwurf {n} des Mappings ist nicht veröffentlicht: Eingereicht wird die veröffentlichte Version.'),
 ('submit.notperson', 'en', 'Only {partner}''s people can submit connectors. Ask VibeFinance to add you.'),
 ('submit.notperson', 'de', 'Nur Personen von {partner} können Connectoren einreichen. Bitten Sie VibeFinance, Sie hinzuzufügen.'),
 ('submit.suspended', 'en', '{partner} is suspended, so connectors cannot be submitted.'),
 ('submit.suspended', 'de', '{partner} ist gesperrt, daher können keine Connectoren eingereicht werden.'),
 ('submit.problem.no_live_mapping', 'en', 'It sends its own layout, but no version of its mapping is published.'),
 ('submit.problem.no_live_mapping', 'de', 'Es sendet ein eigenes Layout, aber keine Version des Mappings ist veröffentlicht.'),
 ('submit.problem.unknown_list', 'en', 'Its mapping reads a look-up list that no longer exists.'),
 ('submit.problem.unknown_list', 'de', 'Das Mapping liest eine Nachschlageliste, die es nicht mehr gibt.'),
 ('httpsout.error.not_partner_person', 'en', 'Only the partner''s people can submit connectors.'),
 ('httpsout.error.not_partner_person', 'de', 'Nur Personen des Partners können Connectoren einreichen.'),
 ('httpsout.error.partner_suspended', 'en', 'The partner is suspended.'),
 ('httpsout.error.partner_suspended', 'de', 'Der Partner ist gesperrt.'),
 ('httpsout.error.not_partner_sandbox', 'en', 'This is not a partner''s sandbox.'),
 ('httpsout.error.not_partner_sandbox', 'de', 'Dies ist keine Partner-Sandbox.'),
 ('httpsout.error.not_linked', 'en', 'That customer is not one you serve.'),
 ('httpsout.error.not_linked', 'de', 'Diesen Kunden betreuen Sie nicht.'),
 ('httpsout.error.no_audience', 'en', 'Choose at least one customer, or all.'),
 ('httpsout.error.no_audience', 'de', 'Wählen Sie mindestens einen Kunden oder alle.'),
 ('httpsout.error.bad_name', 'en', 'Give the connector a name of up to 80 characters.'),
 ('httpsout.error.bad_name', 'de', 'Geben Sie dem Connector einen Namen mit bis zu 80 Zeichen.'),
 ('httpsout.error.bad_description', 'en', 'Say what it does, in up to 600 characters.'),
 ('httpsout.error.bad_description', 'de', 'Beschreiben Sie in bis zu 600 Zeichen, was er tut.'),
 ('httpsout.error.connector_name_taken', 'en', 'You already have a connector with that name.'),
 ('httpsout.error.connector_name_taken', 'de', 'Sie haben bereits einen Connector mit diesem Namen.'),
 ('httpsout.error.already_waiting', 'en', 'A version is still waiting for review. Withdraw it first.'),
 ('httpsout.error.already_waiting', 'de', 'Eine Version wartet noch auf Prüfung. Ziehen Sie sie zuerst zurück.'),
 ('httpsout.error.invalid_definition', 'en', 'This Destination cannot be submitted as it is.'),
 ('httpsout.error.invalid_definition', 'de', 'Dieses Ziel kann so nicht eingereicht werden.'),
 ('httpsout.error.not_waiting', 'en', 'That version is no longer waiting for review.'),
 ('httpsout.error.not_waiting', 'de', 'Diese Version wartet nicht mehr auf Prüfung.'),
 ('httpsout.error.unknown_list', 'en', 'Its mapping reads a look-up list that no longer exists.'),
 ('httpsout.error.unknown_list', 'de', 'Das Mapping liest eine Nachschlageliste, die es nicht mehr gibt.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('submit.heading','submit.hint','submit.version','submit.status.submitted','submit.status.approved','submit.status.returned','submit.status.withdrawn','submit.withdraw','submit.withdrawn','submit.name','submit.docs','submit.description','submit.descriptionhint','submit.notes','submit.noteshint','submit.fixed','submit.fixedhint','submit.auths','submit.audience','submit.audience.all','submit.audience.some','submit.submit','submit.again','submit.sent','submit.draftnote','submit.notperson','submit.suspended','submit.problem.no_live_mapping','submit.problem.unknown_list','httpsout.error.not_partner_person','httpsout.error.partner_suspended','httpsout.error.not_partner_sandbox','httpsout.error.not_linked','httpsout.error.no_audience','httpsout.error.bad_name','httpsout.error.bad_description','httpsout.error.connector_name_taken','httpsout.error.already_waiting','httpsout.error.invalid_definition','httpsout.error.not_waiting','httpsout.error.unknown_list') == 82
