-- 0263_sftp_strings.sql
-- Decision 0620. The SFTP proof of concept: SFTP out and SFTP in, their settings,
-- the connection test and the server's identity, Check now, and the Route monitor's word.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('sftp.out.heading', 'en', 'SFTP out'),
 ('sftp.out.heading', 'de', 'SFTP-Ausgang'),
 ('sftp.out.sub', 'en', 'Each invoice is written as a file into a folder on your SFTP server, whole and never over another file. Test the connection to confirm the server''s identity before anything is sent.'),
 ('sftp.out.sub', 'de', 'Jede Rechnung wird als Datei in einen Ordner auf Ihrem SFTP-Server geschrieben, vollständig und nie über eine andere Datei. Testen Sie die Verbindung, um die Identität des Servers zu bestätigen, bevor etwas gesendet wird.'),
 ('sftp.in.heading', 'en', 'SFTP in'),
 ('sftp.in.heading', 'de', 'SFTP-Eingang'),
 ('sftp.in.sub', 'en', 'Files waiting in a folder on someone else''s SFTP server are collected with Check now, moved to a done folder there, and read as invoices.'),
 ('sftp.in.sub', 'de', 'Dateien in einem Ordner auf dem SFTP-Server eines anderen werden mit Jetzt prüfen abgeholt, dort in einen Erledigt-Ordner verschoben und als Rechnungen gelesen.'),
 ('sftp.settings', 'en', 'Server and folder'),
 ('sftp.settings', 'de', 'Server und Ordner'),
 ('sftp.loading', 'en', 'Loading…'),
 ('sftp.loading', 'de', 'Wird geladen…'),
 ('sftp.failed', 'en', 'This could not be done just now. Try again.'),
 ('sftp.failed', 'de', 'Das ging gerade nicht. Bitte erneut versuchen.'),
 ('sftp.host', 'en', 'Server'),
 ('sftp.host', 'de', 'Server'),
 ('sftp.hosthint', 'en', 'Its name alone, such as sftp.example.com'),
 ('sftp.hosthint', 'de', 'Nur sein Name, etwa sftp.example.com'),
 ('sftp.port', 'en', 'Port'),
 ('sftp.port', 'de', 'Port'),
 ('sftp.username', 'en', 'User'),
 ('sftp.username', 'de', 'Benutzer'),
 ('sftp.authlabel', 'en', 'Sign in with'),
 ('sftp.authlabel', 'de', 'Anmelden mit'),
 ('sftp.auth.password', 'en', 'A password'),
 ('sftp.auth.password', 'de', 'Einem Passwort'),
 ('sftp.auth.key', 'en', 'A private key'),
 ('sftp.auth.key', 'de', 'Einem privaten Schlüssel'),
 ('sftp.password', 'en', 'Password'),
 ('sftp.password', 'de', 'Passwort'),
 ('sftp.privatekey', 'en', 'Private key'),
 ('sftp.privatekey', 'de', 'Privater Schlüssel'),
 ('sftp.privatekeyhint', 'en', 'The whole key, as OpenSSH writes it. One without a passphrase.'),
 ('sftp.privatekeyhint', 'de', 'Der ganze Schlüssel, wie OpenSSH ihn schreibt. Einer ohne Passphrase.'),
 ('sftp.secretset', 'en', 'Set {when}. Leave empty to keep it.'),
 ('sftp.secretset', 'de', 'Gesetzt {when}. Leer lassen, um ihn zu behalten.'),
 ('sftp.secretnotset', 'en', 'Not set yet. Kept encrypted, never shown again.'),
 ('sftp.secretnotset', 'de', 'Noch nicht gesetzt. Verschlüsselt gespeichert, nie wieder angezeigt.'),
 ('sftp.folder.out', 'en', 'Folder to write to'),
 ('sftp.folder.out', 'de', 'Zielordner'),
 ('sftp.folder.in', 'en', 'Folder to collect from'),
 ('sftp.folder.in', 'de', 'Ordner zum Abholen'),
 ('sftp.filename', 'en', 'File name'),
 ('sftp.filename', 'de', 'Dateiname'),
 ('sftp.filenamehint', 'en', 'From {invoiceNumber}, {invoiceId}, {date} and {ext}'),
 ('sftp.filenamehint', 'de', 'Aus {invoiceNumber}, {invoiceId}, {date} und {ext}'),
 ('sftp.pattern', 'en', 'Files to collect'),
 ('sftp.pattern', 'de', 'Abzuholende Dateien'),
 ('sftp.patternhint', 'en', 'Such as *.xml. * collects every file.'),
 ('sftp.patternhint', 'de', 'Etwa *.xml. * holt jede Datei ab.'),
 ('sftp.donefolder', 'en', 'Move collected files to'),
 ('sftp.donefolder', 'de', 'Abgeholte Dateien verschieben nach'),
 ('sftp.donefolderhint', 'en', 'A folder within the folder, or a path from the root. Made if it is not there.'),
 ('sftp.donefolderhint', 'de', 'Ein Ordner im Ordner oder ein Pfad ab dem Stamm. Wird angelegt, falls er fehlt.'),
 ('sftp.test', 'en', 'Test connection'),
 ('sftp.test', 'de', 'Verbindung testen'),
 ('sftp.testing', 'en', 'Signing in…'),
 ('sftp.testing', 'de', 'Anmeldung läuft…'),
 ('sftp.tested.ok', 'en', 'Signed in. {folder} holds {n} files.'),
 ('sftp.tested.ok', 'de', 'Angemeldet. {folder} enthält {n} Dateien.'),
 ('sftp.tested.kept', 'en', 'The server''s identity is kept: {key}'),
 ('sftp.tested.kept', 'de', 'Die Identität des Servers ist gespeichert: {key}'),
 ('sftp.tested.waiting', 'en', '{n} waiting to be collected.'),
 ('sftp.tested.waiting', 'de', '{n} warten auf Abholung.'),
 ('sftp.saved', 'en', 'Saved.'),
 ('sftp.saved', 'de', 'Gespeichert.'),
 ('sftp.savedforgot', 'en', 'Saved. The server changed, so its identity is forgotten: test the connection again.'),
 ('sftp.savedforgot', 'de', 'Gespeichert. Der Server hat sich geändert, seine Identität ist vergessen: Testen Sie die Verbindung erneut.'),
 ('sftp.identity.none', 'en', 'The server''s identity is not confirmed yet. Test the connection to confirm it: nothing is sent or collected before.'),
 ('sftp.identity.none', 'de', 'Die Identität des Servers ist noch nicht bestätigt. Testen Sie die Verbindung: Vorher wird nichts gesendet oder abgeholt.'),
 ('sftp.identity.kept', 'en', 'Server identity:'),
 ('sftp.identity.kept', 'de', 'Server-Identität:'),
 ('sftp.identity.forget', 'en', 'Forget'),
 ('sftp.identity.forget', 'de', 'Vergessen'),
 ('sftp.identity.changedhint', 'en', 'If the server''s owner says its key was changed, Forget the identity kept and test again. If not, do not: someone may be pretending to be the server.'),
 ('sftp.identity.changedhint', 'de', 'Wenn der Betreiber sagt, dass der Schlüssel geändert wurde, vergessen Sie die gespeicherte Identität und testen erneut. Sonst nicht: Jemand könnte sich als der Server ausgeben.'),
 ('sftp.checknow', 'en', 'Check now'),
 ('sftp.checknow', 'de', 'Jetzt prüfen'),
 ('sftp.checking', 'en', 'Collecting…'),
 ('sftp.checking', 'de', 'Wird abgeholt…'),
 ('sftp.collect.heading', 'en', 'Collect'),
 ('sftp.collect.heading', 'de', 'Abholen'),
 ('sftp.collect.hint', 'en', 'Up to ten files at a time. Each is moved to the done folder before it is read, so it is never taken twice.'),
 ('sftp.collect.hint', 'de', 'Bis zu zehn Dateien auf einmal. Jede wird vor dem Lesen in den Erledigt-Ordner verschoben, damit sie nie zweimal abgeholt wird.'),
 ('sftp.collect.summary', 'en', '{n} of {matching} waiting files taken.'),
 ('sftp.collect.summary', 'de', '{n} von {matching} wartenden Dateien abgeholt.'),
 ('sftp.collect.left', 'en', '{n} more are waiting: check again.'),
 ('sftp.collect.left', 'de', '{n} weitere warten: Bitte erneut prüfen.'),
 ('sftp.collect.movedto', 'en', 'Moved to {path}'),
 ('sftp.collect.movedto', 'de', 'Verschoben nach {path}'),
 ('sftp.collect.collected', 'en', 'Collected'),
 ('sftp.collect.collected', 'de', 'Abgeholt'),
 ('sftp.collect.unreadable', 'en', 'Not read'),
 ('sftp.collect.unreadable', 'de', 'Nicht gelesen'),
 ('sftp.collect.failed', 'en', 'Failed'),
 ('sftp.collect.failed', 'de', 'Fehlgeschlagen'),
 ('sftp.collect.skipped', 'en', 'Left'),
 ('sftp.collect.skipped', 'de', 'Belassen'),
 ('sftp.error.auth_failed', 'en', 'The server refused the user, password or key.'),
 ('sftp.error.auth_failed', 'de', 'Der Server hat Benutzer, Passwort oder Schlüssel abgelehnt.'),
 ('sftp.error.connect_failed', 'en', 'The server could not be reached.'),
 ('sftp.error.connect_failed', 'de', 'Der Server war nicht erreichbar.'),
 ('sftp.error.timeout', 'en', 'The server did not answer in time.'),
 ('sftp.error.timeout', 'de', 'Der Server hat nicht rechtzeitig geantwortet.'),
 ('sftp.error.host_key_changed', 'en', 'The server showed a different identity from the one kept. Nothing was sent.'),
 ('sftp.error.host_key_changed', 'de', 'Der Server zeigte eine andere Identität als die gespeicherte. Es wurde nichts gesendet.'),
 ('sftp.error.permission_denied', 'en', 'The server does not let this user do that in the folder.'),
 ('sftp.error.permission_denied', 'de', 'Der Server erlaubt diesem Benutzer das in diesem Ordner nicht.'),
 ('sftp.error.not_found', 'en', 'The folder is not there.'),
 ('sftp.error.not_found', 'de', 'Der Ordner ist nicht vorhanden.'),
 ('sftp.error.not_tested', 'en', 'Test the connection first, to confirm the server''s identity.'),
 ('sftp.error.not_tested', 'de', 'Testen Sie zuerst die Verbindung, um die Identität des Servers zu bestätigen.'),
 ('sftp.error.secret_missing', 'en', 'Give the password or private key first.'),
 ('sftp.error.secret_missing', 'de', 'Geben Sie zuerst das Passwort oder den privaten Schlüssel an.'),
 ('sftp.error.not_set_up', 'en', 'Give the server and user first.'),
 ('sftp.error.not_set_up', 'de', 'Geben Sie zuerst Server und Benutzer an.'),
 ('sftp.error.runner_unavailable', 'en', 'SFTP is not set up for this environment yet.'),
 ('sftp.error.runner_unavailable', 'de', 'SFTP ist für diese Umgebung noch nicht eingerichtet.'),
 ('sftp.error.bad_key', 'en', 'The private key could not be read.'),
 ('sftp.error.bad_key', 'de', 'Der private Schlüssel konnte nicht gelesen werden.'),
 ('sftp.error.no_host', 'en', 'Name the server, such as sftp.example.com.'),
 ('sftp.error.no_host', 'de', 'Nennen Sie den Server, etwa sftp.example.com.'),
 ('sftp.error.bad_host', 'en', 'Give the server''s name alone, with no sftp://, user or folder.'),
 ('sftp.error.bad_host', 'de', 'Geben Sie nur den Namen des Servers an, ohne sftp://, Benutzer oder Ordner.'),
 ('sftp.error.bad_port', 'en', 'The port is a number from 1 to 65535, usually 22.'),
 ('sftp.error.bad_port', 'de', 'Der Port ist eine Zahl von 1 bis 65535, meist 22.'),
 ('sftp.error.no_username', 'en', 'Name the user to sign in as.'),
 ('sftp.error.no_username', 'de', 'Nennen Sie den Benutzer für die Anmeldung.'),
 ('sftp.error.bad_folder', 'en', 'A folder cannot climb out with ..'),
 ('sftp.error.bad_folder', 'de', 'Ein Ordner darf nicht mit .. nach oben führen.'),
 ('sftp.error.filename_not_unique', 'en', 'A file name needs {invoiceNumber} or {invoiceId}, so each invoice has its own file.'),
 ('sftp.error.filename_not_unique', 'de', 'Ein Dateiname braucht {invoiceNumber} oder {invoiceId}, damit jede Rechnung ihre eigene Datei hat.'),
 ('sftp.error.bad_filename', 'en', 'A file name has no folder in it, and at most 120 characters.'),
 ('sftp.error.bad_filename', 'de', 'Ein Dateiname enthält keinen Ordner und höchstens 120 Zeichen.'),
 ('sftp.error.bad_pattern', 'en', 'Name the files to collect with * or ?, such as *.xml, with no folder.'),
 ('sftp.error.bad_pattern', 'de', 'Benennen Sie die abzuholenden Dateien mit * oder ?, etwa *.xml, ohne Ordner.'),
 ('sftp.error.done_is_folder', 'en', 'Collected files are moved to another folder, so they are taken once.'),
 ('sftp.error.done_is_folder', 'de', 'Abgeholte Dateien werden in einen anderen Ordner verschoben, damit sie nur einmal abgeholt werden.'),
 ('sftp.error.bad_done_folder', 'en', 'The done folder cannot climb out with ..'),
 ('sftp.error.bad_done_folder', 'de', 'Der Erledigt-Ordner darf nicht mit .. nach oben führen.'),
 ('routemonitor.event.sftp_collected', 'en', 'Collected over SFTP'),
 ('routemonitor.event.sftp_collected', 'de', 'Über SFTP abgeholt');

-- The library's word for SFTP out said a daily batch, which it does not do.
UPDATE ui_strings SET value = 'Writes each invoice as a file into a folder on your SFTP server, where your ERP can pick it up.' WHERE key = 'connector.sftp-out.description' AND locale = 'en';
UPDATE ui_strings SET value = 'Schreibt jede Rechnung als Datei in einen Ordner auf Ihrem SFTP-Server, wo Ihr ERP sie abholen kann.' WHERE key = 'connector.sftp-out.description' AND locale = 'de';

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('sftp.out.heading','sftp.out.sub','sftp.in.heading','sftp.in.sub','sftp.settings','sftp.loading','sftp.failed','sftp.host','sftp.hosthint','sftp.port','sftp.username','sftp.authlabel','sftp.auth.password','sftp.auth.key','sftp.password','sftp.privatekey','sftp.privatekeyhint','sftp.secretset','sftp.secretnotset','sftp.folder.out','sftp.folder.in','sftp.filename','sftp.filenamehint','sftp.pattern','sftp.patternhint','sftp.donefolder','sftp.donefolderhint','sftp.test','sftp.testing','sftp.tested.ok','sftp.tested.kept','sftp.tested.waiting','sftp.saved','sftp.savedforgot','sftp.identity.none','sftp.identity.kept','sftp.identity.forget','sftp.identity.changedhint','sftp.checknow','sftp.checking','sftp.collect.heading','sftp.collect.hint','sftp.collect.summary','sftp.collect.left','sftp.collect.movedto','sftp.collect.collected','sftp.collect.unreadable','sftp.collect.failed','sftp.collect.skipped','sftp.error.auth_failed','sftp.error.connect_failed','sftp.error.timeout','sftp.error.host_key_changed','sftp.error.permission_denied','sftp.error.not_found','sftp.error.not_tested','sftp.error.secret_missing','sftp.error.not_set_up','sftp.error.runner_unavailable','sftp.error.bad_key','sftp.error.no_host','sftp.error.bad_host','sftp.error.bad_port','sftp.error.no_username','sftp.error.bad_folder','sftp.error.filename_not_unique','sftp.error.bad_filename','sftp.error.bad_pattern','sftp.error.done_is_folder','sftp.error.bad_done_folder','routemonitor.event.sftp_collected') == 142
-- ASSERT: SELECT count(*) FROM ui_strings WHERE key = 'connector.sftp-out.description' AND value LIKE '%batch%' == 0
