-- 0265_agents_strings.sql
-- Decision 0622 — Agents, slice 1: the Agents screen, its form and runs, the
-- reports and their columns, From agents on the task list, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.agents', 'en', 'Agents'),
 ('nav.agents', 'de', 'Agenten'),
 ('agents.subtitle', 'en', 'Reports you set up once, run on a schedule and delivered to your task list.'),
 ('agents.subtitle', 'de', 'Berichte, die Sie einmal einrichten, nach Zeitplan laufen und in Ihrer Aufgabenliste ankommen.'),
 ('agents.failed', 'en', 'This could not be done just now. Try again.'),
 ('agents.failed', 'de', 'Das ging gerade nicht. Bitte erneut versuchen.'),
 ('agents.loading', 'en', 'Loading…'),
 ('agents.loading', 'de', 'Wird geladen…'),
 ('agents.noruns', 'en', 'It has not run yet.'),
 ('agents.noruns', 'de', 'Er ist noch nicht gelaufen.'),
 ('agents.neverrun', 'en', 'Not run yet'),
 ('agents.neverrun', 'de', 'Noch nicht gelaufen'),
 ('agents.late', 'en', 'ran late'),
 ('agents.late', 'de', 'verspätet gelaufen'),
 ('agents.rows', 'en', '{n} rows'),
 ('agents.rows', 'de', '{n} Zeilen'),
 ('agents.status.active', 'en', 'Started'),
 ('agents.status.active', 'de', 'Gestartet'),
 ('agents.status.paused', 'en', 'Paused'),
 ('agents.status.paused', 'de', 'Pausiert'),
 ('agents.paused.author_access', 'en', 'Paused: its author no longer has access'),
 ('agents.paused.author_access', 'de', 'Pausiert: sein Autor hat keinen Zugriff mehr'),
 ('agents.paused.finished', 'en', 'Ran once, finished'),
 ('agents.paused.finished', 'de', 'Einmal gelaufen, beendet'),
 ('agents.run.delivered', 'en', 'Delivered'),
 ('agents.run.delivered', 'de', 'Zugestellt'),
 ('agents.run.nothing', 'en', 'Nothing to report'),
 ('agents.run.nothing', 'de', 'Nichts zu melden'),
 ('agents.run.failed', 'en', 'Failed'),
 ('agents.run.failed', 'de', 'Fehlgeschlagen'),
 ('agents.run.running', 'en', 'Running'),
 ('agents.run.running', 'de', 'Läuft'),
 ('agents.runerror.author_access', 'en', 'its author no longer has access to this report'),
 ('agents.runerror.author_access', 'de', 'sein Autor hat keinen Zugriff mehr auf diesen Bericht'),
 ('agents.runerror.report_unknown', 'en', 'this report no longer exists'),
 ('agents.runerror.report_unknown', 'de', 'diesen Bericht gibt es nicht mehr'),
 ('agents.trigger.schedule', 'en', 'On schedule'),
 ('agents.trigger.schedule', 'de', 'Nach Zeitplan'),
 ('agents.trigger.now', 'en', 'Run now'),
 ('agents.trigger.now', 'de', 'Jetzt ausgeführt'),
 ('agents.pause', 'en', 'Pause'),
 ('agents.pause', 'de', 'Pausieren'),
 ('agents.start', 'en', 'Start'),
 ('agents.start', 'de', 'Starten'),
 ('agents.runnow', 'en', 'Run now'),
 ('agents.runnow', 'de', 'Jetzt ausführen'),
 ('agents.ranow.delivered', 'en', 'Done: it is on your task list.'),
 ('agents.ranow.delivered', 'de', 'Erledigt: er ist in Ihrer Aufgabenliste.'),
 ('agents.ranow.nothing', 'en', 'It ran and found nothing to report, so nothing was sent.'),
 ('agents.ranow.nothing', 'de', 'Er ist gelaufen und hat nichts zu melden, also wurde nichts gesendet.'),
 ('agents.ranow.failed', 'en', 'It ran but failed. Open Runs to see why.'),
 ('agents.ranow.failed', 'de', 'Er ist gelaufen, aber fehlgeschlagen. Unter Läufe steht, warum.'),
 ('agents.edit', 'en', 'Edit'),
 ('agents.edit', 'de', 'Bearbeiten'),
 ('agents.runs', 'en', 'Runs'),
 ('agents.runs', 'de', 'Läufe'),
 ('agents.remove', 'en', 'Remove'),
 ('agents.remove', 'de', 'Entfernen'),
 ('agents.removeconfirm', 'en', 'Remove this agent? Its past runs stay.'),
 ('agents.removeconfirm', 'de', 'Diesen Agenten entfernen? Seine bisherigen Läufe bleiben.'),
 ('agents.cancel', 'en', 'Cancel'),
 ('agents.cancel', 'de', 'Abbrechen'),
 ('agents.when.day', 'en', 'Every day at {time}'),
 ('agents.when.day', 'de', 'Täglich um {time}'),
 ('agents.when.workday', 'en', 'Working days at {time}'),
 ('agents.when.workday', 'de', 'Werktags um {time}'),
 ('agents.when.week', 'en', 'Every {weekday} at {time}'),
 ('agents.when.week', 'de', 'Jeden {weekday} um {time}'),
 ('agents.when.month', 'en', 'On day {day} of each month at {time}'),
 ('agents.when.month', 'de', 'Am {day}. jedes Monats um {time}'),
 ('agents.when.monthlast', 'en', 'On the last day of each month at {time}'),
 ('agents.when.monthlast', 'de', 'Am letzten Tag jedes Monats um {time}'),
 ('agents.when.monthlastworking', 'en', 'On the last working day of each month at {time}'),
 ('agents.when.monthlastworking', 'de', 'Am letzten Werktag jedes Monats um {time}'),
 ('agents.when.once', 'en', 'Once, on {date} at {time}'),
 ('agents.when.once', 'de', 'Einmal, am {date} um {time}'),
 ('agents.weekday.1', 'en', 'Monday'),
 ('agents.weekday.1', 'de', 'Montag'),
 ('agents.weekday.2', 'en', 'Tuesday'),
 ('agents.weekday.2', 'de', 'Dienstag'),
 ('agents.weekday.3', 'en', 'Wednesday'),
 ('agents.weekday.3', 'de', 'Mittwoch'),
 ('agents.weekday.4', 'en', 'Thursday'),
 ('agents.weekday.4', 'de', 'Donnerstag'),
 ('agents.weekday.5', 'en', 'Friday'),
 ('agents.weekday.5', 'de', 'Freitag'),
 ('agents.weekday.6', 'en', 'Saturday'),
 ('agents.weekday.6', 'de', 'Samstag'),
 ('agents.weekday.7', 'en', 'Sunday'),
 ('agents.weekday.7', 'de', 'Sonntag'),
 ('agents.every.day', 'en', 'Every day'),
 ('agents.every.day', 'de', 'Täglich'),
 ('agents.every.workday', 'en', 'Working days'),
 ('agents.every.workday', 'de', 'Werktags'),
 ('agents.every.week', 'en', 'Weekly'),
 ('agents.every.week', 'de', 'Wöchentlich'),
 ('agents.every.month', 'en', 'Monthly'),
 ('agents.every.month', 'de', 'Monatlich'),
 ('agents.every.once', 'en', 'Once'),
 ('agents.every.once', 'de', 'Einmal'),
 ('agents.form.new', 'en', 'New agent'),
 ('agents.form.new', 'de', 'Neuer Agent'),
 ('agents.form.edit', 'en', 'Edit agent'),
 ('agents.form.edit', 'de', 'Agent bearbeiten'),
 ('agents.form.name', 'en', 'Name'),
 ('agents.form.name', 'de', 'Name'),
 ('agents.form.nameplaceholder', 'en', 'Outstanding payables by supplier'),
 ('agents.form.nameplaceholder', 'de', 'Offene Verbindlichkeiten nach Lieferant'),
 ('agents.form.report', 'en', 'Report'),
 ('agents.form.report', 'de', 'Bericht'),
 ('agents.form.orgs', 'en', 'Organisations'),
 ('agents.form.orgs', 'de', 'Organisationen'),
 ('agents.form.orgshint', 'en', 'Chosen now and kept. Only organisations where you can see this report are offered.'),
 ('agents.form.orgshint', 'de', 'Jetzt gewählt und beibehalten. Angeboten werden nur Organisationen, in denen Sie diesen Bericht sehen dürfen.'),
 ('agents.form.every', 'en', 'Runs'),
 ('agents.form.every', 'de', 'Läuft'),
 ('agents.form.time', 'en', 'At'),
 ('agents.form.time', 'de', 'Um'),
 ('agents.form.timehint', 'en', 'Times are in {zone}.'),
 ('agents.form.timehint', 'de', 'Zeiten in {zone}.'),
 ('agents.form.weekday', 'en', 'On'),
 ('agents.form.weekday', 'de', 'Am'),
 ('agents.form.day', 'en', 'Day of the month'),
 ('agents.form.day', 'de', 'Tag des Monats'),
 ('agents.form.lastday', 'en', 'Last day'),
 ('agents.form.lastday', 'de', 'Letzter Tag'),
 ('agents.form.lastworkingday', 'en', 'Last working day'),
 ('agents.form.lastworkingday', 'de', 'Letzter Werktag'),
 ('agents.form.date', 'en', 'Date'),
 ('agents.form.date', 'de', 'Datum'),
 ('agents.form.delivery', 'en', 'Each run arrives on your task list, under From agents. A run with nothing to report sends nothing.'),
 ('agents.form.delivery', 'de', 'Jeder Lauf kommt in Ihrer Aufgabenliste unter Von Agenten an. Ein Lauf ohne Ergebnis sendet nichts.'),
 ('agents.form.savepaused', 'en', 'Save, paused'),
 ('agents.form.savepaused', 'de', 'Speichern, pausiert'),
 ('agents.form.save', 'en', 'Save'),
 ('agents.form.save', 'de', 'Speichern'),
 ('agents.saved.new', 'en', 'Saved, paused. Start it when you are ready, or try it with Run now.'),
 ('agents.saved.new', 'de', 'Gespeichert, pausiert. Starten Sie ihn, wenn Sie bereit sind, oder testen Sie ihn mit Jetzt ausführen.'),
 ('agents.saved.edit', 'en', 'Saved.'),
 ('agents.saved.edit', 'de', 'Gespeichert.'),
 ('agents.report.outstanding_payables', 'en', 'Outstanding payables'),
 ('agents.report.outstanding_payables', 'de', 'Offene Verbindlichkeiten'),
 ('agents.report.overdue_not_eligible', 'en', 'Past due, not yet payment-eligible'),
 ('agents.report.overdue_not_eligible', 'de', 'Überfällig, noch nicht zahlungsbereit'),
 ('agents.report.accruals', 'en', 'Accruals by stage'),
 ('agents.report.accruals', 'de', 'Abgrenzungen nach Stufe'),
 ('agents.report.open_tasks', 'en', 'Open tasks by person'),
 ('agents.report.open_tasks', 'de', 'Offene Aufgaben nach Person'),
 ('agents.report.possible_duplicates', 'en', 'Possible duplicates'),
 ('agents.report.possible_duplicates', 'de', 'Mögliche Duplikate'),
 ('agents.reporthint.outstanding_payables', 'en', 'Payment-eligible invoices not yet delivered to the ERP, by supplier and currency, oldest due date first.'),
 ('agents.reporthint.outstanding_payables', 'de', 'Zahlungsbereite Rechnungen, die noch nicht an das ERP geliefert wurden, nach Lieferant und Währung, älteste Fälligkeit zuerst.'),
 ('agents.reporthint.overdue_not_eligible', 'en', 'Invoices whose due date has passed and that have not yet reached payment-eligible, by supplier.'),
 ('agents.reporthint.overdue_not_eligible', 'de', 'Rechnungen, deren Fälligkeit verstrichen ist und die noch nicht zahlungsbereit sind, nach Lieferant.'),
 ('agents.reporthint.accruals', 'en', 'Invoices received and not yet payment-eligible, by the stage they are at.'),
 ('agents.reporthint.accruals', 'de', 'Eingegangene, noch nicht zahlungsbereite Rechnungen, nach der Stufe, in der sie sind.'),
 ('agents.reporthint.open_tasks', 'en', 'How many open tasks each person has, and how many wait unclaimed.'),
 ('agents.reporthint.open_tasks', 'de', 'Wie viele offene Aufgaben jede Person hat und wie viele ungeclaimt warten.'),
 ('agents.reporthint.possible_duplicates', 'en', 'Invoices that look like another one already received. Needs the Fraud Prevention permission.'),
 ('agents.reporthint.possible_duplicates', 'de', 'Rechnungen, die einer bereits erhaltenen ähneln. Braucht die Berechtigung für Betrugsprävention.'),
 ('agents.limit', 'en', '{used} of {max} agents'),
 ('agents.limit', 'de', '{used} von {max} Agenten'),
 ('agents.zone', 'en', 'Times in {zone}'),
 ('agents.zone', 'de', 'Zeiten in {zone}'),
 ('agents.zonechange', 'en', 'Change'),
 ('agents.zonechange', 'de', 'Ändern'),
 ('agents.zonesave', 'en', 'Save time zone'),
 ('agents.zonesave', 'de', 'Zeitzone speichern'),
 ('agents.zonesaved', 'en', 'Time zone saved. Every started agent''s next run has moved with it.'),
 ('agents.zonesaved', 'de', 'Zeitzone gespeichert. Der nächste Lauf jedes gestarteten Agenten wurde angepasst.'),
 ('agents.showall', 'en', 'Everyone''s agents'),
 ('agents.showall', 'de', 'Agenten aller'),
 ('agents.showmine', 'en', 'My agents'),
 ('agents.showmine', 'de', 'Meine Agenten'),
 ('agents.new', 'en', 'New agent'),
 ('agents.new', 'de', 'Neuer Agent'),
 ('agents.empty', 'en', 'No agents yet. New agent sets up a report that comes to your task list on its own.'),
 ('agents.empty', 'de', 'Noch keine Agenten. Mit Neuer Agent richten Sie einen Bericht ein, der von selbst in Ihre Aufgabenliste kommt.'),
 ('agents.emptyadmin', 'en', 'Nobody here has made an agent yet.'),
 ('agents.emptyadmin', 'de', 'Hier hat noch niemand einen Agenten angelegt.'),
 ('agents.col.agent', 'en', 'Agent'),
 ('agents.col.agent', 'de', 'Agent'),
 ('agents.col.orgs', 'en', 'Organisations'),
 ('agents.col.orgs', 'de', 'Organisationen'),
 ('agents.col.when', 'en', 'When'),
 ('agents.col.when', 'de', 'Wann'),
 ('agents.col.lastrun', 'en', 'Last run'),
 ('agents.col.lastrun', 'de', 'Letzter Lauf'),
 ('agents.col.next', 'en', 'Next'),
 ('agents.col.next', 'de', 'Nächster'),
 ('agents.col.org', 'en', 'Organisation'),
 ('agents.col.org', 'de', 'Organisation'),
 ('agents.col.supplier', 'en', 'Supplier'),
 ('agents.col.supplier', 'de', 'Lieferant'),
 ('agents.col.invoices', 'en', 'Invoices'),
 ('agents.col.invoices', 'de', 'Rechnungen'),
 ('agents.col.total', 'en', 'Total'),
 ('agents.col.total', 'de', 'Summe'),
 ('agents.col.currency', 'en', 'Currency'),
 ('agents.col.currency', 'de', 'Währung'),
 ('agents.col.oldestdue', 'en', 'Oldest due'),
 ('agents.col.oldestdue', 'de', 'Älteste Fälligkeit'),
 ('agents.col.dayspastdue', 'en', 'Days past due'),
 ('agents.col.dayspastdue', 'de', 'Tage überfällig'),
 ('agents.col.stage', 'en', 'Stage'),
 ('agents.col.stage', 'de', 'Stufe'),
 ('agents.col.person', 'en', 'Person'),
 ('agents.col.person', 'de', 'Person'),
 ('agents.col.open', 'en', 'Open tasks'),
 ('agents.col.open', 'de', 'Offene Aufgaben'),
 ('agents.col.invoice', 'en', 'Invoice'),
 ('agents.col.invoice', 'de', 'Rechnung'),
 ('agents.col.issued', 'en', 'Issued'),
 ('agents.col.issued', 'de', 'Ausgestellt'),
 ('agents.col.confidence', 'en', 'Likeness'),
 ('agents.col.confidence', 'de', 'Ähnlichkeit'),
 ('agents.error.name_missing', 'en', 'Give the agent a name.'),
 ('agents.error.name_missing', 'de', 'Geben Sie dem Agenten einen Namen.'),
 ('agents.error.name_too_long', 'en', 'A name is at most 80 characters.'),
 ('agents.error.name_too_long', 'de', 'Ein Name hat höchstens 80 Zeichen.'),
 ('agents.error.report_unknown', 'en', 'Choose one of the reports.'),
 ('agents.error.report_unknown', 'de', 'Wählen Sie einen der Berichte.'),
 ('agents.error.orgs_missing', 'en', 'Choose at least one organisation.'),
 ('agents.error.orgs_missing', 'de', 'Wählen Sie mindestens eine Organisation.'),
 ('agents.error.org_unknown', 'en', 'An organisation chosen no longer exists.'),
 ('agents.error.org_unknown', 'de', 'Eine gewählte Organisation gibt es nicht mehr.'),
 ('agents.error.org_not_permitted', 'en', 'You cannot see this report for every organisation chosen. Untick the ones you cannot see.'),
 ('agents.error.org_not_permitted', 'de', 'Sie dürfen diesen Bericht nicht für alle gewählten Organisationen sehen. Entfernen Sie die Häkchen bei denen, die Sie nicht sehen dürfen.'),
 ('agents.error.schedule_missing', 'en', 'Say when it runs.'),
 ('agents.error.schedule_missing', 'de', 'Geben Sie an, wann er läuft.'),
 ('agents.error.time_invalid', 'en', 'Give a time, such as 08:00.'),
 ('agents.error.time_invalid', 'de', 'Geben Sie eine Uhrzeit an, zum Beispiel 08:00.'),
 ('agents.error.every_invalid', 'en', 'Choose how often it runs.'),
 ('agents.error.every_invalid', 'de', 'Wählen Sie, wie oft er läuft.'),
 ('agents.error.weekday_invalid', 'en', 'Choose a day of the week.'),
 ('agents.error.weekday_invalid', 'de', 'Wählen Sie einen Wochentag.'),
 ('agents.error.day_invalid', 'en', 'Choose a day of the month from 1 to 28, or the last day.'),
 ('agents.error.day_invalid', 'de', 'Wählen Sie einen Tag des Monats von 1 bis 28 oder den letzten Tag.'),
 ('agents.error.date_invalid', 'en', 'Give a date.'),
 ('agents.error.date_invalid', 'de', 'Geben Sie ein Datum an.'),
 ('agents.error.limit_reached', 'en', 'Your licence allows {n} agents. Remove one, or ask about a larger plan.'),
 ('agents.error.limit_reached', 'de', 'Ihre Lizenz erlaubt {n} Agenten. Entfernen Sie einen oder fragen Sie nach einem größeren Plan.'),
 ('agents.error.once_past', 'en', 'That time has already passed. Choose a later date.'),
 ('agents.error.once_past', 'de', 'Dieser Zeitpunkt ist schon vorbei. Wählen Sie ein späteres Datum.'),
 ('agents.error.not_author', 'en', 'Only its author can change this agent.'),
 ('agents.error.not_author', 'de', 'Nur sein Autor kann diesen Agenten ändern.'),
 ('agents.error.not_found', 'en', 'This agent no longer exists.'),
 ('agents.error.not_found', 'de', 'Diesen Agenten gibt es nicht mehr.'),
 ('agents.error.time_zone_invalid', 'en', 'That is not a time zone this system knows.'),
 ('agents.error.time_zone_invalid', 'de', 'Diese Zeitzone kennt das System nicht.'),
 ('agents.notes.heading', 'en', 'From agents'),
 ('agents.notes.heading', 'de', 'Von Agenten'),
 ('agents.notes.sub', 'en', 'Reports your agents delivered. They are not tasks: mark each done when you have read it.'),
 ('agents.notes.sub', 'de', 'Berichte, die Ihre Agenten geliefert haben. Es sind keine Aufgaben: markieren Sie jeden als erledigt, wenn Sie ihn gelesen haben.'),
 ('agents.notes.tag', 'en', 'From an agent'),
 ('agents.notes.tag', 'de', 'Von einem Agenten'),
 ('agents.notes.open', 'en', 'Open'),
 ('agents.notes.open', 'de', 'Öffnen'),
 ('agents.notes.done', 'en', 'Done'),
 ('agents.notes.done', 'de', 'Erledigt'),
 ('agents.notes.total', 'en', 'Total:'),
 ('agents.notes.total', 'de', 'Summe:'),
 ('agents.notes.invoices', 'en', '{n} invoices'),
 ('agents.notes.invoices', 'de', '{n} Rechnungen'),
 ('agents.notes.items', 'en', '{n} in all'),
 ('agents.notes.items', 'de', '{n} insgesamt'),
 ('agents.notes.skipped', 'en', 'Left out, as the agent''s author can no longer see them: {orgs}.'),
 ('agents.notes.skipped', 'de', 'Ausgelassen, da der Autor des Agenten sie nicht mehr sehen darf: {orgs}.'),
 ('agents.notes.unclaimed', 'en', 'Unclaimed, waiting'),
 ('agents.notes.unclaimed', 'de', 'Ungeclaimt, wartend'),
 ('help.screen.agents', 'en', 'An agent is a report you set up once. It runs on its own, on the schedule you choose, and lands on your task list under From agents.'),
 ('help.screen.agents', 'de', 'Ein Agent ist ein Bericht, den Sie einmal einrichten. Er läuft von selbst nach dem gewählten Zeitplan und landet in Ihrer Aufgabenliste unter Von Agenten.'),
 ('help.screen.agents.2', 'en', '## Making one'),
 ('help.screen.agents.2', 'de', '## Einen anlegen'),
 ('help.screen.agents.3', 'en', '- New agent: give it a name, choose a report and the organisations it covers, and say when it runs. It is saved paused.'),
 ('help.screen.agents.3', 'de', '- Neuer Agent: Namen geben, Bericht und Organisationen wählen und angeben, wann er läuft. Er wird pausiert gespeichert.'),
 ('help.screen.agents.4', 'en', '- Run now tries it once and delivers to you alone. Start it when it shows what you want.'),
 ('help.screen.agents.4', 'de', '- Jetzt ausführen testet ihn einmal und liefert nur an Sie. Starten Sie ihn, wenn er zeigt, was Sie wollen.'),
 ('help.screen.agents.5', 'en', '## What it can see'),
 ('help.screen.agents.5', 'de', '## Was er sehen darf'),
 ('help.screen.agents.6', 'en', '- An agent sees what you see. Each run checks again: an organisation you can no longer see is left out and named, and if you lose access altogether the agent pauses itself.'),
 ('help.screen.agents.6', 'de', '- Ein Agent sieht, was Sie sehen. Jeder Lauf prüft erneut: eine Organisation, die Sie nicht mehr sehen dürfen, wird ausgelassen und genannt, und verlieren Sie den Zugriff ganz, pausiert sich der Agent selbst.'),
 ('help.screen.agents.7', 'en', '- Outstanding payables are payment-eligible invoices not yet delivered to the ERP. Once the ERP has an invoice, it leaves the report.'),
 ('help.screen.agents.7', 'de', '- Offene Verbindlichkeiten sind zahlungsbereite Rechnungen, die noch nicht an das ERP geliefert wurden. Sobald das ERP eine Rechnung hat, verlässt sie den Bericht.'),
 ('help.screen.agents.8', 'en', '## When it runs'),
 ('help.screen.agents.8', 'de', '## Wann er läuft'),
 ('help.screen.agents.9', 'en', '- Times are in the environment''s time zone, shown at the top. A run missed while the system was not running happens once, late, and says so.'),
 ('help.screen.agents.9', 'de', '- Zeiten gelten in der Zeitzone der Umgebung, oben angezeigt. Ein verpasster Lauf wird einmal verspätet nachgeholt und als verspätet angezeigt.'),
 ('help.screen.agents.10', 'en', '- Your licence sets how many agents this environment may have. Removing one frees its place, and its past runs stay.'),
 ('help.screen.agents.10', 'de', '- Ihre Lizenz legt fest, wie viele Agenten diese Umgebung haben darf. Ein entfernter Agent gibt seinen Platz frei, und seine bisherigen Läufe bleiben.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key LIKE 'agents.%' OR key = 'nav.agents' OR key LIKE 'help.screen.agents%' == 290
