-- 0266_agent_email_strings.sql
-- Decision 0623 — Agents, slice 2: how and to whom an agent is delivered, its
-- runs' deliveries, Stop sending me this, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.deliver.how', 'en', 'Delivered'),
 ('agents.deliver.how', 'de', 'Zustellung'),
 ('agents.deliver.task', 'en', 'On the task list'),
 ('agents.deliver.task', 'de', 'In der Aufgabenliste'),
 ('agents.deliver.email', 'en', 'By email'),
 ('agents.deliver.email', 'de', 'Per E-Mail'),
 ('agents.deliver.both', 'en', 'Task list and email'),
 ('agents.deliver.both', 'de', 'Aufgabenliste und E-Mail'),
 ('agents.deliver.hint', 'en', 'An email carries the table and the full report as a CSV file.'),
 ('agents.deliver.hint', 'de', 'Eine E-Mail enthält die Tabelle und den ganzen Bericht als CSV-Datei.'),
 ('agents.deliver.noemailsetup', 'en', 'Email is not set up for this environment yet. Ask your administrator.'),
 ('agents.deliver.noemailsetup', 'de', 'E-Mail ist für diese Umgebung noch nicht eingerichtet. Fragen Sie Ihre Administration.'),
 ('agents.deliver.who', 'en', 'Also send to'),
 ('agents.deliver.who', 'de', 'Auch senden an'),
 ('agents.deliver.whohint', 'en', 'You always get it. Each person sees only the organisations they may see, in their own language.'),
 ('agents.deliver.whohint', 'de', 'Sie erhalten ihn immer. Jede Person sieht nur die Organisationen, die sie sehen darf, in ihrer eigenen Sprache.'),
 ('agents.deliver.noemail', 'en', 'no email address'),
 ('agents.deliver.noemail', 'de', 'keine E-Mail-Adresse'),
 ('agents.deliver.nomanagers', 'en', 'Nobody else holds the AP Manager permission yet.'),
 ('agents.deliver.nomanagers', 'de', 'Noch niemand sonst hat die Berechtigung AP-Manager.'),
 ('agents.deliver.stopped', 'en', 'stopped'),
 ('agents.deliver.stopped', 'de', 'abbestellt'),
 ('agents.channel.task', 'en', 'on the task list'),
 ('agents.channel.task', 'de', 'in der Aufgabenliste'),
 ('agents.channel.email', 'en', 'by email'),
 ('agents.channel.email', 'de', 'per E-Mail'),
 ('agents.runerror.email_not_configured', 'en', 'email is not set up here'),
 ('agents.runerror.email_not_configured', 'de', 'E-Mail ist hier nicht eingerichtet'),
 ('agents.runerror.no_email_address', 'en', 'no email address'),
 ('agents.runerror.no_email_address', 'de', 'keine E-Mail-Adresse'),
 ('agents.error.deliver_missing', 'en', 'Choose the task list, email, or both.'),
 ('agents.error.deliver_missing', 'de', 'Wählen Sie die Aufgabenliste, E-Mail oder beides.'),
 ('agents.error.recipient_not_manager', 'en', 'An agent goes only to you and people with the AP Manager permission.'),
 ('agents.error.recipient_not_manager', 'de', 'Ein Agent geht nur an Sie und an Personen mit der Berechtigung AP-Manager.'),
 ('agents.error.author_cannot_stop', 'en', 'You made this agent. Pause or remove it on the Agents screen instead.'),
 ('agents.error.author_cannot_stop', 'de', 'Sie haben diesen Agenten angelegt. Pausieren oder entfernen Sie ihn stattdessen auf der Seite Agenten.'),
 ('agents.notes.stop', 'en', 'Stop sending me this'),
 ('agents.notes.stop', 'de', 'Nicht mehr an mich senden'),
 ('agents.notes.stopped', 'en', 'you will not get this again'),
 ('agents.notes.stopped', 'de', 'Sie erhalten dies nicht mehr'),
 ('agents.notes.stoppedlink', 'en', 'You will no longer get “{name}”.'),
 ('agents.notes.stoppedlink', 'de', 'Sie erhalten „{name}“ nicht mehr.'),
 ('agents.notes.stopfailed', 'en', 'That agent could not be stopped for you. It may have been removed, or belong to another environment.'),
 ('agents.notes.stopfailed', 'de', 'Dieser Agent konnte für Sie nicht abbestellt werden. Vielleicht wurde er entfernt oder gehört zu einer anderen Umgebung.'),
 ('help.screen.agents.11', 'en', '## Who gets it'),
 ('help.screen.agents.11', 'de', '## Wer ihn erhält'),
 ('help.screen.agents.12', 'en', '- An agent goes to you and any AP Managers you choose, on the task list, by email, or both. Each person''s copy covers only the organisations they may see, in their own language.'),
 ('help.screen.agents.12', 'de', '- Ein Agent geht an Sie und an gewählte AP-Manager, in die Aufgabenliste, per E-Mail oder beides. Jede Kopie umfasst nur die Organisationen, die die Person sehen darf, in ihrer eigenen Sprache.'),
 ('help.screen.agents.13', 'en', '- Anyone but you can choose Stop sending me this, on the note or in the email. You see who has stopped it beside the agent.'),
 ('help.screen.agents.13', 'de', '- Jede Person außer Ihnen kann Nicht mehr an mich senden wählen, an der Notiz oder in der E-Mail. Neben dem Agenten sehen Sie, wer ihn abbestellt hat.'),
 ('help.screen.agents.14', 'en', '- What was sent is kept for 13 months, then removed.'),
 ('help.screen.agents.14', 'de', '- Was gesendet wurde, wird 13 Monate aufbewahrt und dann entfernt.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.deliver.how', 'agents.deliver.task', 'agents.deliver.email', 'agents.deliver.both', 'agents.deliver.hint', 'agents.deliver.noemailsetup', 'agents.deliver.who', 'agents.deliver.whohint', 'agents.deliver.noemail', 'agents.deliver.nomanagers', 'agents.deliver.stopped', 'agents.channel.task', 'agents.channel.email', 'agents.runerror.email_not_configured', 'agents.runerror.no_email_address', 'agents.error.deliver_missing', 'agents.error.recipient_not_manager', 'agents.error.author_cannot_stop', 'agents.notes.stop', 'agents.notes.stopped', 'agents.notes.stoppedlink', 'agents.notes.stopfailed', 'help.screen.agents.11', 'help.screen.agents.12', 'help.screen.agents.13', 'help.screen.agents.14') == 52
