-- 0267_agent_options_strings.sql
-- Decision 0624 — Agents, slice 3: two new reports, the ageing columns, each
-- report's options, the comparison with the last report, highlights, the
-- Run now hint, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.report.due_soon_not_eligible', 'en', 'Due soon, not yet payment-eligible'),
 ('agents.report.due_soon_not_eligible', 'de', 'Bald fällig, noch nicht zahlungsbereit'),
 ('agents.report.stuck_work', 'en', 'Stuck work'),
 ('agents.report.stuck_work', 'de', 'Festhängende Arbeit'),
 ('agents.reporthint.due_soon_not_eligible', 'en', 'Invoices not yet payment-eligible whose due date falls in the next few days, soonest first, so they can be pushed through in time.'),
 ('agents.reporthint.due_soon_not_eligible', 'de', 'Noch nicht zahlungsbereite Rechnungen, die in den nächsten Tagen fällig werden, die nächsten zuerst, damit sie rechtzeitig durchlaufen.'),
 ('agents.reporthint.stuck_work', 'en', 'Tasks open longer than the days you choose, by stage and who has them, oldest first.'),
 ('agents.reporthint.stuck_work', 'de', 'Aufgaben, die länger als die gewählten Tage offen sind, nach Stufe und wer sie hat, die ältesten zuerst.'),
 ('agents.col.notdue', 'en', 'Not yet due'),
 ('agents.col.notdue', 'de', 'Noch nicht fällig'),
 ('agents.col.d30', 'en', '1–30 days'),
 ('agents.col.d30', 'de', '1–30 Tage'),
 ('agents.col.d60', 'en', '31–60 days'),
 ('agents.col.d60', 'de', '31–60 Tage'),
 ('agents.col.d90', 'en', '61–90 days'),
 ('agents.col.d90', 'de', '61–90 Tage'),
 ('agents.col.d90plus', 'en', 'Over 90 days'),
 ('agents.col.d90plus', 'de', 'Über 90 Tage'),
 ('agents.col.due', 'en', 'Due'),
 ('agents.col.due', 'de', 'Fällig'),
 ('agents.col.daystodue', 'en', 'Days to due'),
 ('agents.col.daystodue', 'de', 'Tage bis fällig'),
 ('agents.col.stuck', 'en', 'Open tasks'),
 ('agents.col.stuck', 'de', 'Offene Aufgaben'),
 ('agents.col.oldestdays', 'en', 'Oldest, days'),
 ('agents.col.oldestdays', 'de', 'Älteste, Tage'),
 ('agents.option.mintotal', 'en', 'Only suppliers owing at least'),
 ('agents.option.mintotal', 'de', 'Nur Lieferanten mit offenen Beträgen ab'),
 ('agents.option.mintotal.hint', 'en', 'In each supplier''s own currency. Leave empty for all.'),
 ('agents.option.mintotal.hint', 'de', 'In der Währung des Lieferanten. Leer lassen für alle.'),
 ('agents.option.mintotal.placeholder', 'en', 'Any amount'),
 ('agents.option.mintotal.placeholder', 'de', 'Jeder Betrag'),
 ('agents.option.highlightdays', 'en', 'Highlight when the oldest is past due by more than'),
 ('agents.option.highlightdays', 'de', 'Hervorheben, wenn die älteste mehr Tage überfällig ist als'),
 ('agents.option.highlightdays.hint', 'en', 'Days. 60 unless you change it.'),
 ('agents.option.highlightdays.hint', 'de', 'Tage. 60, wenn Sie nichts ändern.'),
 ('agents.option.withindays', 'en', 'Due within'),
 ('agents.option.withindays', 'de', 'Fällig innerhalb von'),
 ('agents.option.withindays.hint', 'en', 'Days from today, 1 to 90. Within two days is highlighted.'),
 ('agents.option.withindays.hint', 'de', 'Tage ab heute, 1 bis 90. Innerhalb von zwei Tagen wird hervorgehoben.'),
 ('agents.option.olderthandays', 'en', 'Open longer than'),
 ('agents.option.olderthandays', 'de', 'Offen länger als'),
 ('agents.option.olderthandays.hint', 'en', 'Days, 1 to 365. Twice as long is highlighted.'),
 ('agents.option.olderthandays.hint', 'de', 'Tage, 1 bis 365. Doppelt so lange wird hervorgehoben.'),
 ('agents.error.option_invalid_mintotal', 'en', 'The amount must be 0 or more.'),
 ('agents.error.option_invalid_mintotal', 'de', 'Der Betrag muss 0 oder mehr sein.'),
 ('agents.error.option_invalid_highlightdays', 'en', 'Give a whole number of days from 1 to 365.'),
 ('agents.error.option_invalid_highlightdays', 'de', 'Geben Sie eine ganze Zahl von Tagen zwischen 1 und 365 an.'),
 ('agents.error.option_invalid_withindays', 'en', 'Give a whole number of days from 1 to 90.'),
 ('agents.error.option_invalid_withindays', 'de', 'Geben Sie eine ganze Zahl von Tagen zwischen 1 und 90 an.'),
 ('agents.error.option_invalid_olderthandays', 'en', 'Give a whole number of days from 1 to 365.'),
 ('agents.error.option_invalid_olderthandays', 'de', 'Geben Sie eine ganze Zahl von Tagen zwischen 1 und 365 an.'),
 ('agents.runnowhint', 'en', 'Run now sends only to you, to try an agent. Everyone else gets theirs on the schedule.'),
 ('agents.runnowhint', 'de', 'Jetzt ausführen sendet nur an Sie, um einen Agenten zu testen. Alle anderen erhalten ihn nach Zeitplan.'),
 ('agents.notes.up', 'en', 'up {n} since the last report'),
 ('agents.notes.up', 'de', '{n} mehr als im letzten Bericht'),
 ('agents.notes.down', 'en', 'down {n} since the last report'),
 ('agents.notes.down', 'de', '{n} weniger als im letzten Bericht'),
 ('agents.notes.same', 'en', 'no change since the last report'),
 ('agents.notes.same', 'de', 'unverändert seit dem letzten Bericht'),
 ('agents.notes.mintotal', 'en', 'Only suppliers owing at least {n}.'),
 ('agents.notes.mintotal', 'de', 'Nur Lieferanten mit offenen Beträgen ab {n}.'),
 ('agents.notes.highlighted', 'en', 'Highlighted: {why}.'),
 ('agents.notes.highlighted', 'de', 'Hervorgehoben: {why}.'),
 ('agents.notes.why.outstanding_payables', 'en', 'oldest more than {n} days past due'),
 ('agents.notes.why.outstanding_payables', 'de', 'älteste mehr als {n} Tage überfällig'),
 ('agents.notes.why.due_soon_not_eligible', 'en', 'due within two days'),
 ('agents.notes.why.due_soon_not_eligible', 'de', 'fällig innerhalb von zwei Tagen'),
 ('agents.notes.why.stuck_work', 'en', 'open {n} days or more'),
 ('agents.notes.why.stuck_work', 'de', 'seit {n} Tagen oder länger offen'),
 ('help.screen.agents.15', 'en', '## Narrowing and comparing'),
 ('help.screen.agents.15', 'de', '## Eingrenzen und vergleichen'),
 ('help.screen.agents.16', 'en', '- Outstanding payables split each supplier''s amount by days past due: not yet due, 1–30, 31–60, 61–90 and over 90. You can keep only suppliers owing at least an amount, and choose when a row is highlighted.'),
 ('help.screen.agents.16', 'de', '- Offene Verbindlichkeiten teilen den Betrag je Lieferant nach Tagen überfällig auf: noch nicht fällig, 1–30, 31–60, 61–90 und über 90. Sie können nur Lieferanten ab einem Betrag behalten und wählen, wann eine Zeile hervorgehoben wird.'),
 ('help.screen.agents.17', 'en', '- Each report''s totals are compared with what you were last sent: up, down, or no change.'),
 ('help.screen.agents.17', 'de', '- Die Summen jedes Berichts werden mit dem verglichen, was Sie zuletzt erhalten haben: mehr, weniger oder unverändert.');

UPDATE ui_strings SET value = 'Payment-eligible invoices not yet delivered to the ERP, by supplier, split by days past due, oldest first.' WHERE key = 'agents.reporthint.outstanding_payables' AND locale = 'en';
UPDATE ui_strings SET value = 'Zahlungsbereite Rechnungen, die noch nicht an das ERP geliefert wurden, nach Lieferant, aufgeteilt nach Tagen überfällig, die ältesten zuerst.' WHERE key = 'agents.reporthint.outstanding_payables' AND locale = 'de';

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.report.due_soon_not_eligible', 'agents.report.stuck_work', 'agents.reporthint.due_soon_not_eligible', 'agents.reporthint.stuck_work', 'agents.col.notdue', 'agents.col.d30', 'agents.col.d60', 'agents.col.d90', 'agents.col.d90plus', 'agents.col.due', 'agents.col.daystodue', 'agents.col.stuck', 'agents.col.oldestdays', 'agents.option.mintotal', 'agents.option.mintotal.hint', 'agents.option.mintotal.placeholder', 'agents.option.highlightdays', 'agents.option.highlightdays.hint', 'agents.option.withindays', 'agents.option.withindays.hint', 'agents.option.olderthandays', 'agents.option.olderthandays.hint', 'agents.error.option_invalid_mintotal', 'agents.error.option_invalid_highlightdays', 'agents.error.option_invalid_withindays', 'agents.error.option_invalid_olderthandays', 'agents.runnowhint', 'agents.notes.up', 'agents.notes.down', 'agents.notes.same', 'agents.notes.mintotal', 'agents.notes.highlighted', 'agents.notes.why.outstanding_payables', 'agents.notes.why.due_soon_not_eligible', 'agents.notes.why.stuck_work', 'help.screen.agents.15', 'help.screen.agents.16', 'help.screen.agents.17') == 76
-- ASSERT: SELECT count(*) FROM ui_strings WHERE key = 'agents.reporthint.outstanding_payables' AND value LIKE '%days past due%' == 1
