-- 0268_agent_plain_words_strings.sql
-- Decision 0625 — Agents, slice 4: Describe it, Understand, the plan in plain
-- words, what an agent cannot do, Edit steps, plan versions, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.describe.label', 'en', 'Describe it'),
 ('agents.describe.label', 'de', 'Beschreiben'),
 ('agents.describe.placeholder', 'en', 'Every Monday at 8am, send me and Priya the outstanding payables over 1,000 for UK Ltd, by email'),
 ('agents.describe.placeholder', 'de', 'Jeden Montag um 8 Uhr mir und Priya die offenen Verbindlichkeiten über 1.000 für UK Ltd per E-Mail senden'),
 ('agents.describe.hint', 'en', 'Say what to report, for which organisations, when, and to whom. The plan below is filled in for you to check.'),
 ('agents.describe.hint', 'de', 'Sagen Sie, was berichtet werden soll, für welche Organisationen, wann und an wen. Der Plan darunter wird zum Prüfen ausgefüllt.'),
 ('agents.understand', 'en', 'Understand'),
 ('agents.understand', 'de', 'Verstehen'),
 ('agents.understanding', 'en', 'Understanding…'),
 ('agents.understanding', 'de', 'Wird verstanden…'),
 ('agents.editsteps', 'en', 'Edit steps'),
 ('agents.editsteps', 'de', 'Schritte bearbeiten'),
 ('agents.plan.heading', 'en', 'The plan'),
 ('agents.plan.heading', 'de', 'Der Plan'),
 ('agents.plan.when', 'en', 'When'),
 ('agents.plan.when', 'de', 'Wann'),
 ('agents.plan.gather', 'en', 'Report'),
 ('agents.plan.gather', 'de', 'Bericht'),
 ('agents.plan.shape', 'en', 'Narrowed'),
 ('agents.plan.shape', 'de', 'Eingegrenzt'),
 ('agents.plan.deliver', 'en', 'Delivered'),
 ('agents.plan.deliver', 'de', 'Zustellung'),
 ('agents.plan.shape.none', 'en', 'Nothing narrowed'),
 ('agents.plan.shape.none', 'de', 'Nicht eingegrenzt'),
 ('agents.plan.mintotal', 'en', 'only suppliers owing at least {n}'),
 ('agents.plan.mintotal', 'de', 'nur Lieferanten mit offenen Beträgen ab {n}'),
 ('agents.plan.highlightdays', 'en', 'highlighted past {n} days'),
 ('agents.plan.highlightdays', 'de', 'hervorgehoben ab {n} Tagen'),
 ('agents.plan.withindays', 'en', 'due within {n} days'),
 ('agents.plan.withindays', 'de', 'fällig innerhalb von {n} Tagen'),
 ('agents.plan.olderthandays', 'en', 'open longer than {n} days'),
 ('agents.plan.olderthandays', 'de', 'länger als {n} Tage offen'),
 ('agents.plan.toyou', 'en', 'to you'),
 ('agents.plan.toyou', 'de', 'an Sie'),
 ('agents.plan.toyouand', 'en', 'to you and {names}'),
 ('agents.plan.toyouand', 'de', 'an Sie und {names}'),
 ('agents.plan.missing.report', 'en', 'Not understood yet: choose a report in Edit steps.'),
 ('agents.plan.missing.report', 'de', 'Noch nicht verstanden: wählen Sie einen Bericht unter Schritte bearbeiten.'),
 ('agents.plan.missing.orgs', 'en', 'Not understood yet: choose organisations in Edit steps.'),
 ('agents.plan.missing.orgs', 'de', 'Noch nicht verstanden: wählen Sie Organisationen unter Schritte bearbeiten.'),
 ('agents.plan.missing.schedule', 'en', 'Not understood yet: say when in Edit steps.'),
 ('agents.plan.missing.schedule', 'de', 'Noch nicht verstanden: geben Sie unter Schritte bearbeiten an, wann.'),
 ('agents.plan.finish', 'en', 'Finish what is missing in Edit steps, then save.'),
 ('agents.plan.finish', 'de', 'Ergänzen Sie, was fehlt, unter Schritte bearbeiten und speichern Sie dann.'),
 ('agents.refusal.outside_address', 'en', 'Left out “{words}”: agents go only to people in VibeFinance. Forward it from your own email if you need to.'),
 ('agents.refusal.outside_address', 'de', 'Ausgelassen „{words}“: Agenten gehen nur an Personen in VibeFinance. Leiten Sie ihn bei Bedarf aus Ihrer eigenen E-Mail weiter.'),
 ('agents.refusal.cannot_act', 'en', 'Left out “{words}”: agents report. They cannot pay, approve or change invoices.'),
 ('agents.refusal.cannot_act', 'de', 'Ausgelassen „{words}“: Agenten berichten. Sie können Rechnungen nicht bezahlen, genehmigen oder ändern.'),
 ('agents.refusal.too_often', 'en', 'Left out “{words}”: an agent runs at most once a day.'),
 ('agents.refusal.too_often', 'de', 'Ausgelassen „{words}“: ein Agent läuft höchstens einmal am Tag.'),
 ('agents.refusal.unknown_report', 'en', '“{words}” is not a report an agent can run. Choose one in Edit steps.'),
 ('agents.refusal.unknown_report', 'de', '„{words}“ ist kein Bericht, den ein Agent ausführen kann. Wählen Sie einen unter Schritte bearbeiten.'),
 ('agents.refusal.unknown_org', 'en', '“{words}” is not an organisation you can choose for this report.'),
 ('agents.refusal.unknown_org', 'de', '„{words}“ ist keine Organisation, die Sie für diesen Bericht wählen können.'),
 ('agents.refusal.unknown_person', 'en', '“{words}” is not an AP Manager here, so it will not go to them.'),
 ('agents.refusal.unknown_person', 'de', '„{words}“ ist hier kein AP-Manager, daher geht er nicht an diese Person.'),
 ('agents.refusal.option_out_of_range', 'en', 'The number for “{words}” was out of range, so the usual one is used.'),
 ('agents.refusal.option_out_of_range', 'de', 'Die Zahl für „{words}“ lag außerhalb des Bereichs, daher wird der übliche Wert verwendet.'),
 ('agents.refusal.other', 'en', 'Left out “{words}”: an agent cannot do that.'),
 ('agents.refusal.other', 'de', 'Ausgelassen „{words}“: das kann ein Agent nicht.'),
 ('agents.error.text_missing', 'en', 'Say what the agent should do.'),
 ('agents.error.text_missing', 'de', 'Sagen Sie, was der Agent tun soll.'),
 ('agents.error.text_too_long', 'en', 'Keep it to 600 characters.'),
 ('agents.error.text_too_long', 'de', 'Höchstens 600 Zeichen.'),
 ('agents.error.not_understood', 'en', 'That could not be understood. Try saying it another way, or use Edit steps.'),
 ('agents.error.not_understood', 'de', 'Das wurde nicht verstanden. Formulieren Sie es anders oder nutzen Sie Schritte bearbeiten.'),
 ('agents.error.ai_unavailable', 'en', 'The AI could not be reached just now. Try again, or use Edit steps.'),
 ('agents.error.ai_unavailable', 'de', 'Die KI war gerade nicht erreichbar. Versuchen Sie es erneut oder nutzen Sie Schritte bearbeiten.'),
 ('agents.planv', 'en', 'plan v{n}'),
 ('agents.planv', 'de', 'Plan v{n}'),
 ('help.screen.agents.18', 'en', '## Describing it in plain words'),
 ('help.screen.agents.18', 'de', '## In einfachen Worten beschreiben'),
 ('help.screen.agents.19', 'en', '- Write what you want, such as every Monday at 8am send me and Priya the outstanding payables over 1,000 for UK Ltd, and choose Understand. The plan is filled in for you to check, and anything an agent cannot do is said.'),
 ('help.screen.agents.19', 'de', '- Schreiben Sie, was Sie wollen, etwa jeden Montag um 8 Uhr mir und Priya die offenen Verbindlichkeiten über 1.000 für UK Ltd senden, und wählen Sie Verstehen. Der Plan wird zum Prüfen ausgefüllt, und was ein Agent nicht kann, wird gesagt.'),
 ('help.screen.agents.20', 'en', '- Change any part in Edit steps. Each change to what it reports, where, when or to whom is kept as a new plan version, and each run says which version it ran.'),
 ('help.screen.agents.20', 'de', '- Ändern Sie jeden Teil unter Schritte bearbeiten. Jede Änderung daran, was, wo, wann oder an wen berichtet wird, wird als neue Planversion gespeichert, und jeder Lauf zeigt, welche Version lief.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.describe.label', 'agents.describe.placeholder', 'agents.describe.hint', 'agents.understand', 'agents.understanding', 'agents.editsteps', 'agents.plan.heading', 'agents.plan.when', 'agents.plan.gather', 'agents.plan.shape', 'agents.plan.deliver', 'agents.plan.shape.none', 'agents.plan.mintotal', 'agents.plan.highlightdays', 'agents.plan.withindays', 'agents.plan.olderthandays', 'agents.plan.toyou', 'agents.plan.toyouand', 'agents.plan.missing.report', 'agents.plan.missing.orgs', 'agents.plan.missing.schedule', 'agents.plan.finish', 'agents.refusal.outside_address', 'agents.refusal.cannot_act', 'agents.refusal.too_often', 'agents.refusal.unknown_report', 'agents.refusal.unknown_org', 'agents.refusal.unknown_person', 'agents.refusal.option_out_of_range', 'agents.refusal.other', 'agents.error.text_missing', 'agents.error.text_too_long', 'agents.error.not_understood', 'agents.error.ai_unavailable', 'agents.planv', 'help.screen.agents.18', 'help.screen.agents.19', 'help.screen.agents.20') == 76
