-- 0271_agent_care_strings.sql
-- Decision 0627 — Agents, slice 6: the agent page, run steps, plan versions,
-- who gets it, the agent log, failure notes, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.page.back', 'en', 'All agents'),
 ('agents.page.back', 'de', 'Alle Agenten'),
 ('agents.page.subtitle', 'en', 'Its runs, every version of its plan, who gets it, and what was changed'),
 ('agents.page.subtitle', 'de', 'Läufe, jede Planversion, wer ihn erhält und was geändert wurde'),
 ('agents.page.runs', 'en', 'Runs'),
 ('agents.page.runs', 'de', 'Läufe'),
 ('agents.page.versions', 'en', 'Plan versions'),
 ('agents.page.versions', 'de', 'Planversionen'),
 ('agents.page.recipients', 'en', 'Who gets it'),
 ('agents.page.recipients', 'de', 'Wer ihn erhält'),
 ('agents.page.history', 'en', 'What was changed'),
 ('agents.page.history', 'de', 'Was geändert wurde'),
 ('agents.page.current', 'en', 'current'),
 ('agents.page.current', 'de', 'aktuell'),
 ('agents.page.changed', 'en', 'Changed: {steps}'),
 ('agents.page.changed', 'de', 'Geändert: {steps}'),
 ('agents.page.author', 'en', 'made it'),
 ('agents.page.author', 'de', 'hat ihn erstellt'),
 ('agents.page.stoppedon', 'en', 'stopped receiving it {when}'),
 ('agents.page.stoppedon', 'de', 'erhält ihn nicht mehr seit {when}'),
 ('agents.page.step.late', 'en', 'Ran late, after a missed time'),
 ('agents.page.step.late', 'de', 'Lief verspätet, nach einem verpassten Zeitpunkt'),
 ('agents.page.step.gathered', 'en', 'Gathered {n} rows'),
 ('agents.page.step.gathered', 'de', '{n} Zeilen gesammelt'),
 ('agents.page.step.nothing', 'en', 'Nothing to report, so nothing was sent'),
 ('agents.page.step.nothing', 'de', 'Nichts zu berichten, daher wurde nichts gesendet'),
 ('agents.page.step.sent', 'en', 'sent'),
 ('agents.page.step.sent', 'de', 'gesendet'),
 ('agents.event.byvibefinance', 'en', 'VibeFinance'),
 ('agents.event.byvibefinance', 'de', 'VibeFinance'),
 ('agents.event.created', 'en', '{by} made it (plan v{version})'),
 ('agents.event.created', 'de', '{by} hat ihn erstellt (Plan v{version})'),
 ('agents.event.changed', 'en', '{by} changed the plan to v{version}'),
 ('agents.event.changed', 'de', '{by} hat den Plan auf v{version} geändert'),
 ('agents.event.renamed', 'en', '{by} renamed it from “{from}” to “{to}”'),
 ('agents.event.renamed', 'de', '{by} hat ihn von „{from}“ in „{to}“ umbenannt'),
 ('agents.event.started', 'en', '{by} started it'),
 ('agents.event.started', 'de', '{by} hat ihn gestartet'),
 ('agents.event.paused', 'en', '{by} paused it'),
 ('agents.event.paused', 'de', '{by} hat ihn pausiert'),
 ('agents.event.paused_access', 'en', '{by} paused it: its author can no longer see its report'),
 ('agents.event.paused_access', 'de', '{by} hat ihn pausiert: sein Autor kann den Bericht nicht mehr sehen'),
 ('agents.event.removed', 'en', '{by} removed it'),
 ('agents.event.removed', 'de', '{by} hat ihn entfernt'),
 ('agents.event.stopped_receiving', 'en', '{by} stopped receiving it'),
 ('agents.event.stopped_receiving', 'de', '{by} erhält ihn nicht mehr'),
 ('agents.log.heading', 'en', 'Agent log'),
 ('agents.log.heading', 'de', 'Agentenprotokoll'),
 ('agents.log.sub', 'en', 'Every change to an agent, by whom and when. Runs are on each agent''s own page.'),
 ('agents.log.sub', 'de', 'Jede Änderung an einem Agenten, von wem und wann. Läufe stehen auf der Seite des Agenten.'),
 ('agents.log.show', 'en', 'Show the log'),
 ('agents.log.show', 'de', 'Protokoll anzeigen'),
 ('agents.log.hide', 'en', 'Hide the log'),
 ('agents.log.hide', 'de', 'Protokoll ausblenden'),
 ('agents.log.empty', 'en', 'No changes yet.'),
 ('agents.log.empty', 'de', 'Noch keine Änderungen.'),
 ('agents.status.removed', 'en', 'Removed'),
 ('agents.status.removed', 'de', 'Entfernt'),
 ('agents.notes.failedtag', 'en', 'Failing'),
 ('agents.notes.failedtag', 'de', 'Fehlgeschlagen'),
 ('agents.notes.failure.failed', 'en', 'Its last run failed'),
 ('agents.notes.failure.failed', 'de', 'Sein letzter Lauf ist fehlgeschlagen'),
 ('agents.notes.failure.partial', 'en', 'Some copies could not be sent'),
 ('agents.notes.failure.partial', 'de', 'Einige Kopien konnten nicht gesendet werden'),
 ('agents.notes.failure.times', 'en', 'Failed {n} times since {since}'),
 ('agents.notes.failure.times', 'de', '{n}-mal fehlgeschlagen seit {since}'),
 ('agents.notes.openagent', 'en', 'Open the agent'),
 ('agents.notes.openagent', 'de', 'Agent öffnen'),
 ('help.screen.agents.24', 'en', '## When something goes wrong'),
 ('help.screen.agents.24', 'de', '## Wenn etwas schiefgeht'),
 ('help.screen.agents.25', 'en', '- If a scheduled run fails, or some copies cannot be sent, its author gets one note on their task list saying why, kept up to date while it keeps failing and marked done by itself when a run succeeds.'),
 ('help.screen.agents.25', 'de', '- Schlägt ein geplanter Lauf fehl oder können einige Kopien nicht gesendet werden, erhält der Autor eine Notiz in seiner Aufgabenliste mit dem Grund. Sie wird aktualisiert, solange es weiter fehlschlägt, und von selbst erledigt, wenn ein Lauf gelingt.'),
 ('help.screen.agents.26', 'en', '- Choose an agent''s name to see its own page: every run step by step, every version of its plan and what changed, who gets it and who stopped, and what was changed by whom. Administrators also see the agent log of every change.'),
 ('help.screen.agents.26', 'de', '- Wählen Sie den Namen eines Agenten, um seine Seite zu sehen: jeden Lauf Schritt für Schritt, jede Planversion und was sich geändert hat, wer ihn erhält und wer ihn abbestellt hat, und was von wem geändert wurde. Administratoren sehen auch das Agentenprotokoll aller Änderungen.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.page.back', 'agents.page.subtitle', 'agents.page.runs', 'agents.page.versions', 'agents.page.recipients', 'agents.page.history', 'agents.page.current', 'agents.page.changed', 'agents.page.author', 'agents.page.stoppedon', 'agents.page.step.late', 'agents.page.step.gathered', 'agents.page.step.nothing', 'agents.page.step.sent', 'agents.event.byvibefinance', 'agents.event.created', 'agents.event.changed', 'agents.event.renamed', 'agents.event.started', 'agents.event.paused', 'agents.event.paused_access', 'agents.event.removed', 'agents.event.stopped_receiving', 'agents.log.heading', 'agents.log.sub', 'agents.log.show', 'agents.log.hide', 'agents.log.empty', 'agents.status.removed', 'agents.notes.failedtag', 'agents.notes.failure.failed', 'agents.notes.failure.partial', 'agents.notes.failure.times', 'agents.notes.openagent', 'help.screen.agents.24', 'help.screen.agents.25', 'help.screen.agents.26') == 74
