-- 0272_agent_examples_strings.sql
-- Decision 0628 — Agents phase 2, slice 1: ready-made agents, their names and
-- words in English and German, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.examples', 'en', 'Ready-made'),
 ('agents.examples', 'de', 'Vorlagen'),
 ('agents.examples.heading', 'en', 'Ready-made agents'),
 ('agents.examples.heading', 'de', 'Fertige Agenten'),
 ('agents.examples.sub', 'en', 'Choose one to fill in a new agent. Check it, change anything, and save it: it is saved paused, like any new agent.'),
 ('agents.examples.sub', 'de', 'Wählen Sie einen, um einen neuen Agenten auszufüllen. Prüfen und ändern Sie ihn und speichern Sie ihn: er wird pausiert gespeichert, wie jeder neue Agent.'),
 ('agents.examples.use', 'en', 'Use this'),
 ('agents.examples.use', 'de', 'Verwenden'),
 ('agents.examples.none', 'en', 'None of the ready-made agents use a report you can see.'),
 ('agents.examples.none', 'de', 'Keiner der fertigen Agenten nutzt einen Bericht, den Sie sehen dürfen.'),
 ('agents.example.weekly_payables.name', 'en', 'Weekly outstanding payables'),
 ('agents.example.weekly_payables.name', 'de', 'Wöchentliche offene Verbindlichkeiten'),
 ('agents.example.weekly_payables.words', 'en', 'Every Monday at 8am, outstanding payables by supplier, aged by days past due, with anything more than 60 days past due highlighted, by email and on my task list.'),
 ('agents.example.weekly_payables.words', 'de', 'Jeden Montag um 8 Uhr offene Verbindlichkeiten nach Lieferant, nach Tagen überfällig gestaffelt, alles über 60 Tage hervorgehoben, per E-Mail und in meiner Aufgabenliste.'),
 ('agents.example.due_soon.name', 'en', 'Due soon, not yet payment-eligible'),
 ('agents.example.due_soon.name', 'de', 'Bald fällig, noch nicht zahlungsbereit'),
 ('agents.example.due_soon.words', 'en', 'Every working day at 7:30, invoices due in the next 7 days that are not yet payment-eligible, to protect early-payment discounts.'),
 ('agents.example.due_soon.words', 'de', 'Jeden Werktag um 7:30 Uhr Rechnungen, die in den nächsten 7 Tagen fällig und noch nicht zahlungsbereit sind, um Skonti zu sichern.'),
 ('agents.example.stuck_digest.name', 'en', 'Stuck work'),
 ('agents.example.stuck_digest.name', 'de', 'Festhängende Arbeit'),
 ('agents.example.stuck_digest.words', 'en', 'Every working day at 9am, tasks open more than 5 days, by stage and who has them.'),
 ('agents.example.stuck_digest.words', 'de', 'Jeden Werktag um 9 Uhr Aufgaben, die länger als 5 Tage offen sind, nach Schritt und Bearbeiter.'),
 ('agents.example.past_due.name', 'en', 'Past due, not yet payment-eligible'),
 ('agents.example.past_due.name', 'de', 'Überfällig, noch nicht zahlungsbereit'),
 ('agents.example.past_due.words', 'en', 'Every working day at 8am, invoices already past their due date that are not yet payment-eligible.'),
 ('agents.example.past_due.words', 'de', 'Jeden Werktag um 8 Uhr Rechnungen, die bereits überfällig und noch nicht zahlungsbereit sind.'),
 ('agents.example.month_end_accruals.name', 'en', 'Month-end accruals'),
 ('agents.example.month_end_accruals.name', 'de', 'Abgrenzungen zum Monatsende'),
 ('agents.example.month_end_accruals.words', 'en', 'On the last working day of each month at 4pm, invoices received but not yet released, by organisation and stage, by email.'),
 ('agents.example.month_end_accruals.words', 'de', 'Am letzten Werktag jedes Monats um 16 Uhr eingegangene, aber noch nicht freigegebene Rechnungen, nach Organisation und Schritt, per E-Mail.'),
 ('agents.example.team_workload.name', 'en', 'Team workload'),
 ('agents.example.team_workload.name', 'de', 'Arbeitslast im Team'),
 ('agents.example.team_workload.words', 'en', 'Every Friday at 3pm, open tasks by person, compared with the week before.'),
 ('agents.example.team_workload.words', 'de', 'Jeden Freitag um 15 Uhr offene Aufgaben nach Person, verglichen mit der Vorwoche.'),
 ('agents.example.fraud_watch.name', 'en', 'Fraud watch: possible duplicates'),
 ('agents.example.fraud_watch.name', 'de', 'Betrugsprüfung: mögliche Duplikate'),
 ('agents.example.fraud_watch.words', 'en', 'Every Monday at 8am, invoices that look like duplicates of another, by email.'),
 ('agents.example.fraud_watch.words', 'de', 'Jeden Montag um 8 Uhr Rechnungen, die wie Duplikate einer anderen aussehen, per E-Mail.'),
 ('help.screen.agents.27', 'en', '## Ready-made agents'),
 ('help.screen.agents.27', 'de', '## Fertige Agenten'),
 ('help.screen.agents.28', 'en', '- Choose Ready-made to see agents set up for common needs, such as weekly outstanding payables or month-end accruals. Use this fills in a new agent with everything chosen, for every organisation you can see the report for. Change anything before saving it.'),
 ('help.screen.agents.28', 'de', '- Wählen Sie Vorlagen, um Agenten für häufige Aufgaben zu sehen, etwa wöchentliche offene Verbindlichkeiten oder Abgrenzungen zum Monatsende. Verwenden füllt einen neuen Agenten mit allem aus, für jede Organisation, für die Sie den Bericht sehen dürfen. Ändern Sie alles Nötige vor dem Speichern.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.examples', 'agents.examples.heading', 'agents.examples.sub', 'agents.examples.use', 'agents.examples.none', 'agents.example.weekly_payables.name', 'agents.example.weekly_payables.words', 'agents.example.due_soon.name', 'agents.example.due_soon.words', 'agents.example.stuck_digest.name', 'agents.example.stuck_digest.words', 'agents.example.past_due.name', 'agents.example.past_due.words', 'agents.example.month_end_accruals.name', 'agents.example.month_end_accruals.words', 'agents.example.team_workload.name', 'agents.example.team_workload.words', 'agents.example.fraud_watch.name', 'agents.example.fraud_watch.words', 'help.screen.agents.27', 'help.screen.agents.28') == 42
