-- 0274_agent_event_strings.sql
-- Decision 0630 — Agents phase 2, slice 3: agents started by an event, their
-- reports, columns, ready-made agents, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.report.event_stuck', 'en', 'When an invoice is stuck at a stage'),
 ('agents.report.event_stuck', 'de', 'Wenn eine Rechnung in einem Schritt festhängt'),
 ('agents.report.event_duplicate', 'en', 'When a possible duplicate arrives'),
 ('agents.report.event_duplicate', 'de', 'Wenn ein mögliches Duplikat eingeht'),
 ('agents.report.event_unapproved_supplier', 'en', 'When an invoice comes from an unapproved supplier'),
 ('agents.report.event_unapproved_supplier', 'de', 'Wenn eine Rechnung von einem nicht freigegebenen Lieferanten kommt'),
 ('agents.report.event_file_failed', 'en', 'When a supplier file cannot be read'),
 ('agents.report.event_file_failed', 'de', 'Wenn eine Lieferantendatei nicht gelesen werden kann'),
 ('agents.reporthint.event_stuck', 'en', 'Each invoice at one stage longer than the days chosen, told once per stay at that stage.'),
 ('agents.reporthint.event_stuck', 'de', 'Jede Rechnung, die länger als die gewählten Tage in einem Schritt liegt, einmal je Aufenthalt gemeldet.'),
 ('agents.reporthint.event_duplicate', 'en', 'Each invoice that looks like a duplicate of another, told once.'),
 ('agents.reporthint.event_duplicate', 'de', 'Jede Rechnung, die wie ein Duplikat einer anderen aussieht, einmal gemeldet.'),
 ('agents.reporthint.event_unapproved_supplier', 'en', 'Each invoice from a supplier not on file, or on hold, told once.'),
 ('agents.reporthint.event_unapproved_supplier', 'de', 'Jede Rechnung von einem nicht angelegten oder gesperrten Lieferanten, einmal gemeldet.'),
 ('agents.reporthint.event_file_failed', 'en', 'Each received file the Route monitor shows as failed or partly read in the last two weeks, told once. Needs access to the Route monitor.'),
 ('agents.reporthint.event_file_failed', 'de', 'Jede eingegangene Datei, die der Routenmonitor in den letzten zwei Wochen als fehlgeschlagen oder teilweise gelesen zeigt, einmal gemeldet. Erfordert Zugriff auf den Routenmonitor.'),
 ('agents.col.daysatstage', 'en', 'Days at stage'),
 ('agents.col.daysatstage', 'de', 'Tage im Schritt'),
 ('agents.col.reason', 'en', 'Why'),
 ('agents.col.reason', 'de', 'Grund'),
 ('agents.col.received', 'en', 'Received'),
 ('agents.col.received', 'de', 'Eingegangen'),
 ('agents.col.from', 'en', 'From'),
 ('agents.col.from', 'de', 'Von'),
 ('agents.col.subject', 'en', 'Subject'),
 ('agents.col.subject', 'de', 'Betreff'),
 ('agents.col.problem', 'en', 'What went wrong'),
 ('agents.col.problem', 'de', 'Was schiefging'),
 ('agents.reason.notonfile', 'en', 'Supplier not on file'),
 ('agents.reason.notonfile', 'de', 'Lieferant nicht angelegt'),
 ('agents.reason.onhold', 'en', 'Supplier on hold'),
 ('agents.reason.onhold', 'de', 'Lieferant gesperrt'),
 ('agents.when.hour', 'en', 'Every hour, when there is something new'),
 ('agents.when.hour', 'de', 'Stündlich, wenn es etwas Neues gibt'),
 ('agents.event.hint', 'en', 'It looks every hour and sends each person only what they have not been sent. The first time, it sends what there is now. An hour with nothing new sends nothing.'),
 ('agents.event.hint', 'de', 'Er prüft stündlich und sendet jeder Person nur, was sie noch nicht erhalten hat. Beim ersten Mal sendet er, was es jetzt gibt. Eine Stunde ohne Neues sendet nichts.'),
 ('agents.option.stagedays', 'en', 'At one stage longer than (days)'),
 ('agents.option.stagedays', 'de', 'Länger als (Tage) in einem Schritt'),
 ('agents.option.stagedays.hint', 'en', 'From 1 to 90. Usually 3.'),
 ('agents.option.stagedays.hint', 'de', 'Von 1 bis 90. Üblich sind 3.'),
 ('agents.example.stuck_alert.name', 'en', 'Tell me when an invoice is stuck'),
 ('agents.example.stuck_alert.name', 'de', 'Melden, wenn eine Rechnung festhängt'),
 ('agents.example.stuck_alert.words', 'en', 'As soon as an invoice has been at one stage for more than 3 days, by email and on my task list.'),
 ('agents.example.stuck_alert.words', 'de', 'Sobald eine Rechnung länger als 3 Tage in einem Schritt liegt, per E-Mail und in meiner Aufgabenliste.'),
 ('agents.example.duplicate_alert.name', 'en', 'Tell me about possible duplicates'),
 ('agents.example.duplicate_alert.name', 'de', 'Mögliche Duplikate melden'),
 ('agents.example.duplicate_alert.words', 'en', 'As soon as an invoice looks like a duplicate of another, by email and on my task list.'),
 ('agents.example.duplicate_alert.words', 'de', 'Sobald eine Rechnung wie ein Duplikat einer anderen aussieht, per E-Mail und in meiner Aufgabenliste.'),
 ('agents.example.failed_files.name', 'en', 'Tell me when a supplier file fails'),
 ('agents.example.failed_files.name', 'de', 'Melden, wenn eine Lieferantendatei fehlschlägt'),
 ('agents.example.failed_files.words', 'en', 'As soon as a supplier file cannot be read, by email and on my task list.'),
 ('agents.example.failed_files.words', 'de', 'Sobald eine Lieferantendatei nicht gelesen werden kann, per E-Mail und in meiner Aufgabenliste.'),
 ('help.screen.agents.31', 'en', '## Agents started by an event'),
 ('help.screen.agents.31', 'de', '## Durch ein Ereignis gestartete Agenten'),
 ('help.screen.agents.32', 'en', '- Four reports start when something happens rather than at a time: an invoice stuck at a stage, a possible duplicate, an invoice from an unapproved supplier, and a supplier file that cannot be read. Such an agent looks every hour and sends each person only what they have not been sent, so a burst of thirty is one message.'),
 ('help.screen.agents.32', 'de', '- Vier Berichte starten, wenn etwas geschieht, statt zu einer Uhrzeit: eine Rechnung, die in einem Schritt festhängt, ein mögliches Duplikat, eine Rechnung von einem nicht freigegebenen Lieferanten und eine Lieferantendatei, die nicht gelesen werden kann. Ein solcher Agent prüft stündlich und sendet jeder Person nur, was sie noch nicht erhalten hat, sodass dreißig auf einmal eine Nachricht sind.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.report.event_stuck', 'agents.report.event_duplicate', 'agents.report.event_unapproved_supplier', 'agents.report.event_file_failed', 'agents.reporthint.event_stuck', 'agents.reporthint.event_duplicate', 'agents.reporthint.event_unapproved_supplier', 'agents.reporthint.event_file_failed', 'agents.col.daysatstage', 'agents.col.reason', 'agents.col.received', 'agents.col.from', 'agents.col.subject', 'agents.col.problem', 'agents.reason.notonfile', 'agents.reason.onhold', 'agents.when.hour', 'agents.event.hint', 'agents.option.stagedays', 'agents.option.stagedays.hint', 'agents.example.stuck_alert.name', 'agents.example.stuck_alert.words', 'agents.example.duplicate_alert.name', 'agents.example.duplicate_alert.words', 'agents.example.failed_files.name', 'agents.example.failed_files.words', 'help.screen.agents.31', 'help.screen.agents.32') == 56
