-- 0276_agent_actions_strings.sql
-- Decision 0631 — Agents phase 3, slice 1: prepared actions, For your
-- approval, reminding a task holder, the switch, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.action.label', 'en', 'Also prepare'),
 ('agents.action.label', 'de', 'Außerdem vorbereiten'),
 ('agents.action.none', 'en', 'Nothing'),
 ('agents.action.none', 'de', 'Nichts'),
 ('agents.action.remind_holder', 'en', 'A reminder to whoever holds each stuck task'),
 ('agents.action.remind_holder', 'de', 'Eine Erinnerung an jeden, der eine festhängende Aufgabe hat'),
 ('agents.action.none.hint', 'en', 'It only reports.'),
 ('agents.action.none.hint', 'de', 'Er berichtet nur.'),
 ('agents.action.remind_holder.hint', 'en', 'After each run it prepares a reminder for each stuck task someone holds. Nothing is sent until a person who may manage tasks approves it on Tasks.'),
 ('agents.action.remind_holder.hint', 'de', 'Nach jedem Lauf bereitet er für jede festhängende Aufgabe, die jemand hat, eine Erinnerung vor. Nichts wird gesendet, bis eine Person, die Aufgaben verwalten darf, sie unter Aufgaben freigibt.'),
 ('agents.action.offlicence', 'en', 'Your licence does not include prepared actions.'),
 ('agents.action.offlicence', 'de', 'Ihre Lizenz enthält keine vorbereiteten Aktionen.'),
 ('agents.action.offenvironment', 'en', 'Prepared actions are turned off here, so nothing will be prepared until an administrator turns them on.'),
 ('agents.action.offenvironment', 'de', 'Vorbereitete Aktionen sind hier ausgeschaltet. Bis ein Administrator sie einschaltet, wird nichts vorbereitet.'),
 ('agents.plan.act', 'en', 'Prepares'),
 ('agents.plan.act', 'de', 'Bereitet vor'),
 ('agents.plan.act.remind_holder', 'en', 'A reminder to whoever holds each stuck task, for approval'),
 ('agents.plan.act.remind_holder', 'de', 'Eine Erinnerung an jeden, der eine festhängende Aufgabe hat, zur Freigabe'),
 ('agents.actions.areon', 'en', 'Prepared actions are on.'),
 ('agents.actions.areon', 'de', 'Vorbereitete Aktionen sind eingeschaltet.'),
 ('agents.actions.areoff', 'en', 'Prepared actions are off.'),
 ('agents.actions.areoff', 'de', 'Vorbereitete Aktionen sind ausgeschaltet.'),
 ('agents.actions.turnon', 'en', 'Turn on'),
 ('agents.actions.turnon', 'de', 'Einschalten'),
 ('agents.actions.turnoff', 'en', 'Turn off'),
 ('agents.actions.turnoff', 'de', 'Ausschalten'),
 ('agents.actions.remind_holder.title', 'en', 'Remind {holder} about invoice {invoice}'),
 ('agents.actions.remind_holder.title', 'de', '{holder} an Rechnung {invoice} erinnern'),
 ('agents.actions.remind_holder.detail', 'en', '{supplier} · at {stage} for {days} days'),
 ('agents.actions.remind_holder.detail', 'de', '{supplier} · seit {days} Tagen im Schritt {stage}'),
 ('agents.actions.by', 'en', 'by {name}'),
 ('agents.actions.by', 'de', 'von {name}'),
 ('agents.actions.heading', 'en', 'For your approval'),
 ('agents.actions.heading', 'de', 'Zur Freigabe'),
 ('agents.actions.sub', 'en', 'Agents prepared these. Nothing is done until you approve, and it is checked again then.'),
 ('agents.actions.sub', 'de', 'Agenten haben dies vorbereitet. Nichts geschieht, bevor Sie freigeben, und dann wird erneut geprüft.'),
 ('agents.actions.tag', 'en', 'Prepared'),
 ('agents.actions.tag', 'de', 'Vorbereitet'),
 ('agents.actions.from', 'en', 'From the agent “{agent}” by {author} · lapses {when}'),
 ('agents.actions.from', 'de', 'Vom Agenten „{agent}“ von {author} · verfällt {when}'),
 ('agents.actions.approve', 'en', 'Approve'),
 ('agents.actions.approve', 'de', 'Freigeben'),
 ('agents.actions.reject', 'en', 'Reject'),
 ('agents.actions.reject', 'de', 'Ablehnen'),
 ('agents.actions.noteplaceholder', 'en', 'A note to add (optional)'),
 ('agents.actions.noteplaceholder', 'de', 'Ein Hinweis (optional)'),
 ('agents.actions.done', 'en', 'Done: {holder} has been reminded by email.'),
 ('agents.actions.done', 'de', 'Erledigt: {holder} wurde per E-Mail erinnert.'),
 ('agents.actions.donenoemail', 'en', 'Done, and shown on the invoice, but no email could be sent to {holder}.'),
 ('agents.actions.donenoemail', 'de', 'Erledigt und an der Rechnung vermerkt, aber an {holder} konnte keine E-Mail gesendet werden.'),
 ('agents.actions.rejected', 'en', 'Rejected. Nothing was done.'),
 ('agents.actions.rejected', 'de', 'Abgelehnt. Es wurde nichts getan.'),
 ('agents.actionstatus.waiting', 'en', 'waiting for approval'),
 ('agents.actionstatus.waiting', 'de', 'wartet auf Freigabe'),
 ('agents.actionstatus.done', 'en', 'done'),
 ('agents.actionstatus.done', 'de', 'erledigt'),
 ('agents.actionstatus.failed', 'en', 'not done'),
 ('agents.actionstatus.failed', 'de', 'nicht erledigt'),
 ('agents.actionstatus.rejected', 'en', 'rejected'),
 ('agents.actionstatus.rejected', 'de', 'abgelehnt'),
 ('agents.actionstatus.expired', 'en', 'lapsed'),
 ('agents.actionstatus.expired', 'de', 'verfallen'),
 ('agents.actionreason.changed', 'en', 'The task moved on since this was prepared, so nothing was done.'),
 ('agents.actionreason.changed', 'de', 'Die Aufgabe hat sich seit der Vorbereitung geändert, daher wurde nichts getan.'),
 ('agents.actionreason.already_done', 'en', 'Someone already approved this.'),
 ('agents.actionreason.already_done', 'de', 'Jemand hat dies bereits freigegeben.'),
 ('agents.actionreason.already_rejected', 'en', 'Someone already rejected this.'),
 ('agents.actionreason.already_rejected', 'de', 'Jemand hat dies bereits abgelehnt.'),
 ('agents.actionreason.already_failed', 'en', 'This could not be done when it was approved.'),
 ('agents.actionreason.already_failed', 'de', 'Dies konnte bei der Freigabe nicht erledigt werden.'),
 ('agents.actionreason.already_expired', 'en', 'This lapsed before anyone approved it.'),
 ('agents.actionreason.already_expired', 'de', 'Dies ist verfallen, bevor es jemand freigegeben hat.'),
 ('agents.actionreason.already_decided', 'en', 'Someone decided this a moment ago.'),
 ('agents.actionreason.already_decided', 'de', 'Jemand hat dies gerade entschieden.'),
 ('agents.actionreason.actions_off', 'en', 'Prepared actions are turned off.'),
 ('agents.actionreason.actions_off', 'de', 'Vorbereitete Aktionen sind ausgeschaltet.'),
 ('agents.actionreason.not_permitted', 'en', 'You cannot decide this one.'),
 ('agents.actionreason.not_permitted', 'de', 'Darüber können Sie nicht entscheiden.'),
 ('agents.actionreason.failed', 'en', 'That did not work. Try again.'),
 ('agents.actionreason.failed', 'de', 'Das hat nicht geklappt. Versuchen Sie es erneut.'),
 ('agents.page.actions', 'en', 'What it prepared'),
 ('agents.page.actions', 'de', 'Was er vorbereitet hat'),
 ('agents.error.action_unknown', 'en', 'That is not an action an agent can prepare.'),
 ('agents.error.action_unknown', 'de', 'Diese Aktion kann ein Agent nicht vorbereiten.'),
 ('agents.error.action_not_for_report', 'en', 'This report cannot prepare that action.'),
 ('agents.error.action_not_for_report', 'de', 'Dieser Bericht kann diese Aktion nicht vorbereiten.'),
 ('agents.error.actions_invalid', 'en', 'Choose on or off.'),
 ('agents.error.actions_invalid', 'de', 'Wählen Sie ein oder aus.'),
 ('activity.reminded', 'en', '{who} reminded {target}, as an agent prepared'),
 ('activity.reminded', 'de', '{who} hat {target} erinnert, wie ein Agent es vorbereitet hat'),
 ('help.screen.agents.33', 'en', '## Prepared actions'),
 ('help.screen.agents.33', 'de', '## Vorbereitete Aktionen'),
 ('help.screen.agents.34', 'en', '- A stuck work agent can also prepare a reminder to whoever holds each stuck task. It waits under For your approval on Tasks for anyone who may manage tasks where the invoice is, the agent''s author included. Nothing is sent until someone approves it, and it is checked again then: if the task has moved on, nothing is done.'),
 ('help.screen.agents.34', 'de', '- Ein Agent für festhängende Arbeit kann außerdem eine Erinnerung an jeden vorbereiten, der eine festhängende Aufgabe hat. Sie wartet unter Zur Freigabe in Aufgaben auf jemanden, der dort, wo die Rechnung ist, Aufgaben verwalten darf, auch auf den Autor des Agenten. Nichts wird gesendet, bevor jemand freigibt, und dann wird erneut geprüft: hat sich die Aufgabe geändert, geschieht nichts.'),
 ('help.screen.agents.35', 'en', '- A prepared action lapses after 5 working days, the same task is not reminded about again within a week, and the invoice''s Timeline says who reminded whom. An administrator can turn prepared actions off for the whole environment.'),
 ('help.screen.agents.35', 'de', '- Eine vorbereitete Aktion verfällt nach 5 Werktagen, an dieselbe Aufgabe wird innerhalb einer Woche nicht erneut erinnert, und der Verlauf der Rechnung zeigt, wer wen erinnert hat. Ein Administrator kann vorbereitete Aktionen für die ganze Umgebung ausschalten.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.action.label', 'agents.action.none', 'agents.action.remind_holder', 'agents.action.none.hint', 'agents.action.remind_holder.hint', 'agents.action.offlicence', 'agents.action.offenvironment', 'agents.plan.act', 'agents.plan.act.remind_holder', 'agents.actions.areon', 'agents.actions.areoff', 'agents.actions.turnon', 'agents.actions.turnoff', 'agents.actions.remind_holder.title', 'agents.actions.remind_holder.detail', 'agents.actions.by', 'agents.actions.heading', 'agents.actions.sub', 'agents.actions.tag', 'agents.actions.from', 'agents.actions.approve', 'agents.actions.reject', 'agents.actions.noteplaceholder', 'agents.actions.done', 'agents.actions.donenoemail', 'agents.actions.rejected', 'agents.actionstatus.waiting', 'agents.actionstatus.done', 'agents.actionstatus.failed', 'agents.actionstatus.rejected', 'agents.actionstatus.expired', 'agents.actionreason.changed', 'agents.actionreason.already_done', 'agents.actionreason.already_rejected', 'agents.actionreason.already_failed', 'agents.actionreason.already_expired', 'agents.actionreason.already_decided', 'agents.actionreason.actions_off', 'agents.actionreason.not_permitted', 'agents.actionreason.failed', 'agents.page.actions', 'agents.error.action_unknown', 'agents.error.action_not_for_report', 'agents.error.actions_invalid', 'activity.reminded', 'help.screen.agents.33', 'help.screen.agents.34', 'help.screen.agents.35') == 96
