-- 0277_agent_chase_strings.sql
-- Decision 0632 — Agents phase 3, slice 2: returned with no reply, chasing
-- the supplier, the letter on Tasks, the Timeline, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.report.returned_no_reply', 'en', 'Returned to the supplier, no corrected invoice yet'),
 ('agents.report.returned_no_reply', 'de', 'An den Lieferanten zurückgesandt, noch keine korrigierte Rechnung'),
 ('agents.reporthint.returned_no_reply', 'en', 'Invoices returned to their supplier more than the days chosen ago, in the last 90 days, with no later invoice of the same number from them.'),
 ('agents.reporthint.returned_no_reply', 'de', 'Rechnungen, die vor mehr als den gewählten Tagen in den letzten 90 Tagen an den Lieferanten zurückgingen und zu denen keine spätere Rechnung mit derselben Nummer kam.'),
 ('agents.col.returned', 'en', 'Returned'),
 ('agents.col.returned', 'de', 'Zurückgesandt'),
 ('agents.col.dayssince', 'en', 'Days since'),
 ('agents.col.dayssince', 'de', 'Tage seither'),
 ('agents.col.returnreason', 'en', 'Why returned'),
 ('agents.col.returnreason', 'de', 'Grund der Rücksendung'),
 ('agents.option.waitdays', 'en', 'Returned more than (days) ago'),
 ('agents.option.waitdays', 'de', 'Zurückgesandt vor mehr als (Tagen)'),
 ('agents.option.waitdays.hint', 'en', 'From 1 to 90. Usually 7.'),
 ('agents.option.waitdays.hint', 'de', 'Von 1 bis 90. Üblich sind 7.'),
 ('agents.action.chase_supplier', 'en', 'A letter chasing the supplier for each return'),
 ('agents.action.chase_supplier', 'de', 'Ein Nachfassschreiben an den Lieferanten zu jeder Rücksendung'),
 ('agents.action.chase_supplier.hint', 'en', 'After each run it drafts a letter to the supplier in their language, to the address on file. Nothing is sent until someone who may return invoices to suppliers approves it on Tasks.'),
 ('agents.action.chase_supplier.hint', 'de', 'Nach jedem Lauf entwirft er ein Schreiben an den Lieferanten in dessen Sprache, an die hinterlegte Adresse. Nichts wird gesendet, bis jemand, der Rechnungen an Lieferanten zurücksenden darf, es unter Aufgaben freigibt.'),
 ('agents.plan.act.chase_supplier', 'en', 'A letter chasing the supplier for each return, for approval'),
 ('agents.plan.act.chase_supplier', 'de', 'Ein Nachfassschreiben an den Lieferanten zu jeder Rücksendung, zur Freigabe'),
 ('agents.actions.chase_supplier.title', 'en', 'Chase {supplier} about invoice {invoice}'),
 ('agents.actions.chase_supplier.title', 'de', '{supplier} zur Rechnung {invoice} nachfassen'),
 ('agents.actions.chase_supplier.detail', 'en', 'Returned for: {reason} · {days} days without a corrected invoice'),
 ('agents.actions.chase_supplier.detail', 'de', 'Zurückgesandt wegen: {reason} · seit {days} Tagen ohne korrigierte Rechnung'),
 ('agents.actions.chase.send', 'en', 'Approve and send'),
 ('agents.actions.chase.send', 'de', 'Freigeben und senden'),
 ('agents.actions.chase.to', 'en', 'To'),
 ('agents.actions.chase.to', 'de', 'An'),
 ('agents.actions.chase.cc', 'en', 'Copy'),
 ('agents.actions.chase.cc', 'de', 'Kopie'),
 ('agents.actions.chase.subject', 'en', 'Subject'),
 ('agents.actions.chase.subject', 'de', 'Betreff'),
 ('agents.actions.chase.body', 'en', 'Letter'),
 ('agents.actions.chase.body', 'de', 'Schreiben'),
 ('agents.actions.chase.draftedai', 'en', 'Worded by AI around the invoice''s own facts, which VibeFinance filled in. Change the words as you like. Any number must be the invoice''s.'),
 ('agents.actions.chase.draftedai', 'de', 'Von KI um die Fakten der Rechnung formuliert, die VibeFinance eingesetzt hat. Ändern Sie den Text nach Belieben. Jede Zahl muss die der Rechnung sein.'),
 ('agents.actions.chase.draftedours', 'en', 'Written from the invoice''s own facts. Change the words as you like. Any number must be the invoice''s.'),
 ('agents.actions.chase.draftedours', 'de', 'Aus den Fakten der Rechnung geschrieben. Ändern Sie den Text nach Belieben. Jede Zahl muss die der Rechnung sein.'),
 ('agents.actions.chase.sent', 'en', 'Sent to {to}, and shown on the invoice.'),
 ('agents.actions.chase.sent', 'de', 'An {to} gesendet und an der Rechnung vermerkt.'),
 ('agents.actionreason.number_not_on_invoice', 'en', '{stray} is not a number on this invoice. Change it, then send.'),
 ('agents.actionreason.number_not_on_invoice', 'de', '{stray} ist keine Zahl dieser Rechnung. Bitte ändern und dann senden.'),
 ('agents.actionreason.chase_address_in_text', 'en', 'The letter may not carry email addresses or links.'),
 ('agents.actionreason.chase_address_in_text', 'de', 'Das Schreiben darf keine E-Mail-Adressen oder Links enthalten.'),
 ('agents.actionreason.replied', 'en', 'A corrected invoice arrived since this was prepared, so nothing was sent.'),
 ('agents.actionreason.replied', 'de', 'Seit der Vorbereitung ist eine korrigierte Rechnung eingegangen, daher wurde nichts gesendet.'),
 ('agents.actionreason.address_changed', 'en', 'The supplier''s address changed since this was prepared, so nothing was sent.'),
 ('agents.actionreason.address_changed', 'de', 'Die Adresse des Lieferanten hat sich seit der Vorbereitung geändert, daher wurde nichts gesendet.'),
 ('agents.actionreason.email_not_configured', 'en', 'Email is not set up here, so this cannot be sent yet.'),
 ('agents.actionreason.email_not_configured', 'de', 'E-Mail ist hier nicht eingerichtet, daher kann dies noch nicht gesendet werden.'),
 ('agents.actionreason.send_failed', 'en', 'The email could not be sent.'),
 ('agents.actionreason.send_failed', 'de', 'Die E-Mail konnte nicht gesendet werden.'),
 ('agents.example.chase_returns.name', 'en', 'Chase returned invoices'),
 ('agents.example.chase_returns.name', 'de', 'Bei zurückgesandten Rechnungen nachfassen'),
 ('agents.example.chase_returns.words', 'en', 'Every working day at 9am, invoices returned to the supplier more than 7 days ago with no corrected invoice, and a letter chasing each one for approval.'),
 ('agents.example.chase_returns.words', 'de', 'Jeden Werktag um 9 Uhr Rechnungen, die vor mehr als 7 Tagen an den Lieferanten zurückgingen und noch nicht korrigiert kamen, mit einem Nachfassschreiben zu jeder zur Freigabe.'),
 ('activity.chased', 'en', '{who} chased {target}, as an agent prepared'),
 ('activity.chased', 'de', '{who} hat bei {target} nachgefasst, wie ein Agent es vorbereitet hat'),
 ('help.screen.agents.36', 'en', '- An agent on returned invoices with no reply can also draft a letter chasing each supplier, in their language, to the address on file and copied to your AP team address. The invoice number, dates, total and reason come from VibeFinance, and the AI only words the letter around them.'),
 ('help.screen.agents.36', 'de', '- Ein Agent für zurückgesandte Rechnungen ohne Antwort kann außerdem ein Nachfassschreiben an jeden Lieferanten entwerfen, in dessen Sprache, an die hinterlegte Adresse und in Kopie an Ihre Kreditoren-Adresse. Rechnungsnummer, Daten, Betrag und Grund stammen aus VibeFinance, und die KI formuliert nur den Text darum herum.'),
 ('help.screen.agents.37', 'en', '- You can change the letter before sending it, but any number in it must be the invoice''s own, and it may not carry addresses or links. If a corrected invoice has arrived or the supplier''s address changed since it was drafted, nothing is sent.'),
 ('help.screen.agents.37', 'de', '- Sie können das Schreiben vor dem Senden ändern, aber jede Zahl darin muss die der Rechnung sein, und es darf keine Adressen oder Links enthalten. Ist inzwischen eine korrigierte Rechnung eingegangen oder hat sich die Adresse des Lieferanten geändert, wird nichts gesendet.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.report.returned_no_reply', 'agents.reporthint.returned_no_reply', 'agents.col.returned', 'agents.col.dayssince', 'agents.col.returnreason', 'agents.option.waitdays', 'agents.option.waitdays.hint', 'agents.action.chase_supplier', 'agents.action.chase_supplier.hint', 'agents.plan.act.chase_supplier', 'agents.actions.chase_supplier.title', 'agents.actions.chase_supplier.detail', 'agents.actions.chase.send', 'agents.actions.chase.to', 'agents.actions.chase.cc', 'agents.actions.chase.subject', 'agents.actions.chase.body', 'agents.actions.chase.draftedai', 'agents.actions.chase.draftedours', 'agents.actions.chase.sent', 'agents.actionreason.number_not_on_invoice', 'agents.actionreason.chase_address_in_text', 'agents.actionreason.replied', 'agents.actionreason.address_changed', 'agents.actionreason.email_not_configured', 'agents.actionreason.send_failed', 'agents.example.chase_returns.name', 'agents.example.chase_returns.words', 'activity.chased', 'help.screen.agents.36', 'help.screen.agents.37') == 62
