-- 0278_agent_query_strings.sql
-- Decision 0633 — Agents: asking the data, slice 1: the agent's own
-- question, its columns, values and the cut-short note.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.report.query', 'en', 'Your own question'),
 ('agents.report.query', 'de', 'Ihre eigene Abfrage'),
 ('agents.reporthint.query', 'en', 'A question of its own about invoices or tasks, checked against what may be asked and run with each reader''s own access.'),
 ('agents.reporthint.query', 'de', 'Eine eigene Abfrage zu Rechnungen oder Aufgaben, geprüft gegen das, was abgefragt werden darf, und mit dem Zugriff jedes Empfängers ausgeführt.'),
 ('agents.dataset.invoices', 'en', 'Invoices'),
 ('agents.dataset.invoices', 'de', 'Rechnungen'),
 ('agents.dataset.tasks', 'en', 'Tasks'),
 ('agents.dataset.tasks', 'de', 'Aufgaben'),
 ('agents.notes.cutshort', 'en', 'Only the first {n} rows are here. Narrow the question to see the rest.'),
 ('agents.notes.cutshort', 'de', 'Hier stehen nur die ersten {n} Zeilen. Grenzen Sie die Abfrage ein, um den Rest zu sehen.'),
 ('agents.col.country', 'en', 'Supplier country'),
 ('agents.col.country', 'de', 'Land des Lieferanten'),
 ('agents.col.net', 'en', 'Net'),
 ('agents.col.net', 'de', 'Netto'),
 ('agents.col.vat', 'en', 'VAT'),
 ('agents.col.vat', 'de', 'USt.'),
 ('agents.col.buyerref', 'en', 'Buyer reference'),
 ('agents.col.buyerref', 'de', 'Käuferreferenz'),
 ('agents.col.ponumber', 'en', 'Purchase order'),
 ('agents.col.ponumber', 'de', 'Bestellung'),
 ('agents.col.status', 'en', 'Status'),
 ('agents.col.status', 'de', 'Status'),
 ('agents.col.delivered', 'en', 'At the ERP'),
 ('agents.col.delivered', 'de', 'Im ERP'),
 ('agents.col.team', 'en', 'Team'),
 ('agents.col.team', 'de', 'Team'),
 ('agents.col.taskstatus', 'en', 'Task status'),
 ('agents.col.taskstatus', 'de', 'Aufgabenstatus'),
 ('agents.col.created', 'en', 'Created'),
 ('agents.col.created', 'de', 'Erstellt'),
 ('agents.col.agedays', 'en', 'Age, days'),
 ('agents.col.agedays', 'de', 'Alter, Tage'),
 ('agents.col.claimed', 'en', 'Claimed'),
 ('agents.col.claimed', 'de', 'Übernommen'),
 ('agents.col.ended', 'en', 'Ended'),
 ('agents.col.ended', 'de', 'Beendet'),
 ('agents.col.m.count', 'en', 'Count'),
 ('agents.col.m.count', 'de', 'Anzahl'),
 ('agents.col.m.sum', 'en', '{field}, added up'),
 ('agents.col.m.sum', 'de', '{field}, zusammen'),
 ('agents.col.m.avg', 'en', '{field}, average'),
 ('agents.col.m.avg', 'de', '{field}, Durchschnitt'),
 ('agents.col.m.min', 'en', '{field}, lowest'),
 ('agents.col.m.min', 'de', '{field}, kleinster Wert'),
 ('agents.col.m.max', 'en', '{field}, highest'),
 ('agents.col.m.max', 'de', '{field}, größter Wert'),
 ('agents.col.m.first', 'en', '{field}, earliest'),
 ('agents.col.m.first', 'de', '{field}, frühestens'),
 ('agents.col.m.last', 'en', '{field}, latest'),
 ('agents.col.m.last', 'de', '{field}, spätestens'),
 ('agents.qstatus.in_progress', 'en', 'In process'),
 ('agents.qstatus.in_progress', 'de', 'In Bearbeitung'),
 ('agents.qstatus.completed', 'en', 'Through the process'),
 ('agents.qstatus.completed', 'de', 'Prozess durchlaufen'),
 ('agents.qstatus.returned_manually', 'en', 'Returned to the supplier'),
 ('agents.qstatus.returned_manually', 'de', 'An den Lieferanten zurückgesandt'),
 ('agents.qstatus.archived', 'en', 'Archived'),
 ('agents.qstatus.archived', 'de', 'Archiviert'),
 ('agents.qstatus.none', 'en', 'Not in a process'),
 ('agents.qstatus.none', 'de', 'In keinem Prozess'),
 ('agents.qtaskstatus.open', 'en', 'Open'),
 ('agents.qtaskstatus.open', 'de', 'Offen'),
 ('agents.qtaskstatus.completed', 'en', 'Completed'),
 ('agents.qtaskstatus.completed', 'de', 'Erledigt'),
 ('agents.qtaskstatus.returned', 'en', 'Returned'),
 ('agents.qtaskstatus.returned', 'de', 'Zurückgegeben'),
 ('agents.qtaskstatus.cancelled', 'en', 'Cancelled'),
 ('agents.qtaskstatus.cancelled', 'de', 'Abgebrochen'),
 ('agents.qyesno.yes', 'en', 'Yes'),
 ('agents.qyesno.yes', 'de', 'Ja'),
 ('agents.qyesno.no', 'en', 'No'),
 ('agents.qyesno.no', 'de', 'Nein');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.report.query', 'agents.reporthint.query', 'agents.dataset.invoices', 'agents.dataset.tasks', 'agents.notes.cutshort', 'agents.col.country', 'agents.col.net', 'agents.col.vat', 'agents.col.buyerref', 'agents.col.ponumber', 'agents.col.status', 'agents.col.delivered', 'agents.col.team', 'agents.col.taskstatus', 'agents.col.created', 'agents.col.agedays', 'agents.col.claimed', 'agents.col.ended', 'agents.col.m.count', 'agents.col.m.sum', 'agents.col.m.avg', 'agents.col.m.min', 'agents.col.m.max', 'agents.col.m.first', 'agents.col.m.last', 'agents.qstatus.in_progress', 'agents.qstatus.completed', 'agents.qstatus.returned_manually', 'agents.qstatus.archived', 'agents.qstatus.none', 'agents.qtaskstatus.open', 'agents.qtaskstatus.completed', 'agents.qtaskstatus.returned', 'agents.qtaskstatus.cancelled', 'agents.qyesno.yes', 'agents.qyesno.no') == 72
