-- 0279_agent_query_words_strings.sql
-- Decision 0634 — Agents: asking the data, slice 2: plain words write the
-- question, the question in words, (usual), refusals and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.plan.usual', 'en', '(usual)'),
 ('agents.plan.usual', 'de', '(üblich)'),
 ('agents.plan.q.where', 'en', '{dataset} where {filters}'),
 ('agents.plan.q.where', 'de', '{dataset}, bei denen {filters}'),
 ('agents.plan.q.all', 'en', '{dataset}, all of them'),
 ('agents.plan.q.all', 'de', '{dataset}, alle'),
 ('agents.plan.q.and', 'en', 'and'),
 ('agents.plan.q.and', 'de', 'und'),
 ('agents.plan.q.since.last_run', 'en', 'only what is new since the last run'),
 ('agents.plan.q.since.last_run', 'de', 'nur, was seit dem letzten Lauf neu ist'),
 ('agents.plan.q.since.all', 'en', 'everything that matches'),
 ('agents.plan.q.since.all', 'de', 'alles, was passt'),
 ('agents.plan.q.show', 'en', 'showing {fields}'),
 ('agents.plan.q.show', 'de', 'mit {fields}'),
 ('agents.plan.q.group', 'en', 'by {fields}: {measures}'),
 ('agents.plan.q.group', 'de', 'nach {fields}: {measures}'),
 ('agents.plan.q.sort', 'en', '{field}, {dir}'),
 ('agents.plan.q.sort', 'de', '{field}, {dir}'),
 ('agents.plan.q.asc', 'en', 'smallest first'),
 ('agents.plan.q.asc', 'de', 'kleinste zuerst'),
 ('agents.plan.q.desc', 'en', 'largest first'),
 ('agents.plan.q.desc', 'de', 'größte zuerst'),
 ('agents.plan.q.limit', 'en', 'at most {n} rows'),
 ('agents.plan.q.limit', 'de', 'höchstens {n} Zeilen'),
 ('agents.qop.is', 'en', '{field} is {value}'),
 ('agents.qop.is', 'de', '{field} ist {value}'),
 ('agents.qop.is_not', 'en', '{field} is not {value}'),
 ('agents.qop.is_not', 'de', '{field} ist nicht {value}'),
 ('agents.qop.in', 'en', '{field} is one of {value}'),
 ('agents.qop.in', 'de', '{field} ist eines von {value}'),
 ('agents.qop.contains', 'en', '{field} contains “{value}”'),
 ('agents.qop.contains', 'de', '{field} enthält „{value}“'),
 ('agents.qop.is_empty', 'en', '{field} is empty'),
 ('agents.qop.is_empty', 'de', '{field} ist leer'),
 ('agents.qop.not_empty', 'en', '{field} is not empty'),
 ('agents.qop.not_empty', 'de', '{field} ist nicht leer'),
 ('agents.qop.over', 'en', '{field} is over {value}'),
 ('agents.qop.over', 'de', '{field} liegt über {value}'),
 ('agents.qop.under', 'en', '{field} is under {value}'),
 ('agents.qop.under', 'de', '{field} liegt unter {value}'),
 ('agents.qop.between', 'en', '{field} is between {a} and {b}'),
 ('agents.qop.between', 'de', '{field} liegt zwischen {a} und {b}'),
 ('agents.qop.in_last_days', 'en', '{field} in the last {value} days'),
 ('agents.qop.in_last_days', 'de', '{field} in den letzten {value} Tagen'),
 ('agents.qop.older_than_days', 'en', '{field} more than {value} days ago'),
 ('agents.qop.older_than_days', 'de', '{field} vor mehr als {value} Tagen'),
 ('agents.qop.before', 'en', '{field} before {value}'),
 ('agents.qop.before', 'de', '{field} vor dem {value}'),
 ('agents.qop.after', 'en', '{field} after {value}'),
 ('agents.qop.after', 'de', '{field} nach dem {value}'),
 ('agents.refusal.cannot_ask', 'en', 'Could not ask about “{words}”: it is not something an agent can ask about here.'),
 ('agents.refusal.cannot_ask', 'de', 'Zu „{words}“ kann nicht gefragt werden: Danach kann ein Agent hier nicht fragen.'),
 ('agents.refusal.approximate', 'en', '“{words}” can only be answered nearly. Check the plan before saving.'),
 ('agents.refusal.approximate', 'de', '„{words}“ lässt sich nur ungefähr beantworten. Prüfen Sie den Plan vor dem Speichern.'),
 ('agents.form.question', 'en', 'The question'),
 ('agents.form.question', 'de', 'Die Abfrage'),
 ('agents.form.question.hint', 'en', 'To change the question, change the words above and choose Understand again.'),
 ('agents.form.question.hint', 'de', 'Um die Abfrage zu ändern, ändern Sie den Text oben und wählen Sie erneut Verstehen.'),
 ('help.screen.agents.38', 'en', '- Describe what you want in your own words, such as invoices over £100,000 still in process, and the agent asks exactly that of the data, rather than the nearest ready-made report. The plan says each part in words, and marks with (usual) anything you did not say.'),
 ('help.screen.agents.38', 'de', '- Beschreiben Sie in eigenen Worten, was Sie möchten, etwa Rechnungen über 100.000 £, die noch in Bearbeitung sind, und der Agent fragt genau das ab, statt den nächstliegenden fertigen Bericht zu nehmen. Der Plan nennt jeden Teil in Worten und markiert mit (üblich), was Sie nicht gesagt haben.'),
 ('help.screen.agents.39', 'en', '- A question can only use what VibeFinance lets agents ask about, and each reader sees only the organisations they may see. Amounts are always in one currency. Anything it cannot ask is said, not guessed.'),
 ('help.screen.agents.39', 'de', '- Eine Abfrage kann nur nutzen, wonach Agenten in VibeFinance fragen dürfen, und jeder Empfänger sieht nur die Organisationen, die er sehen darf. Beträge gelten immer in einer Währung. Was nicht abgefragt werden kann, wird gesagt, nicht geraten.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.plan.usual', 'agents.plan.q.where', 'agents.plan.q.all', 'agents.plan.q.and', 'agents.plan.q.since.last_run', 'agents.plan.q.since.all', 'agents.plan.q.show', 'agents.plan.q.group', 'agents.plan.q.sort', 'agents.plan.q.asc', 'agents.plan.q.desc', 'agents.plan.q.limit', 'agents.qop.is', 'agents.qop.is_not', 'agents.qop.in', 'agents.qop.contains', 'agents.qop.is_empty', 'agents.qop.not_empty', 'agents.qop.over', 'agents.qop.under', 'agents.qop.between', 'agents.qop.in_last_days', 'agents.qop.older_than_days', 'agents.qop.before', 'agents.qop.after', 'agents.refusal.cannot_ask', 'agents.refusal.approximate', 'agents.form.question', 'agents.form.question.hint', 'help.screen.agents.38', 'help.screen.agents.39') == 62
