-- 0281_agent_question_builder_strings.sql
-- Decision 0636 — Agents ask the data, slice 3: the question builder in Edit
-- steps, Try it now, and the words when a question is refused.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.q.hint', 'en', 'Change it below, or change the words above and choose Understand again. Try it now runs it with your own access and saves nothing.'),
 ('agents.q.hint', 'de', 'Ändern Sie sie unten, oder ändern Sie den Text oben und wählen Sie erneut Verstehen. Jetzt ausprobieren führt sie mit Ihrem eigenen Zugriff aus und speichert nichts.'),
 ('agents.q.dataset', 'en', 'Ask about'),
 ('agents.q.dataset', 'de', 'Fragen nach'),
 ('agents.q.since', 'en', 'Which'),
 ('agents.q.since', 'de', 'Welche'),
 ('agents.q.where', 'en', 'Where'),
 ('agents.q.where', 'de', 'Bedingungen'),
 ('agents.q.addfilter', 'en', 'Add a condition'),
 ('agents.q.addfilter', 'de', 'Bedingung hinzufügen'),
 ('agents.q.remove', 'en', 'Remove'),
 ('agents.q.remove', 'de', 'Entfernen'),
 ('agents.q.currency', 'en', 'Currency'),
 ('agents.q.currency', 'de', 'Währung'),
 ('agents.q.commas', 'en', 'Separate with commas'),
 ('agents.q.commas', 'de', 'Durch Kommas getrennt'),
 ('agents.q.shape', 'en', 'Show'),
 ('agents.q.shape', 'de', 'Anzeigen'),
 ('agents.q.shape.rows', 'en', 'One row each'),
 ('agents.q.shape.rows', 'de', 'Eine Zeile je Eintrag'),
 ('agents.q.shape.group', 'en', 'Grouped, with totals'),
 ('agents.q.shape.group', 'de', 'Gruppiert, mit Summen'),
 ('agents.q.show', 'en', 'Columns'),
 ('agents.q.show', 'de', 'Spalten'),
 ('agents.q.groupby', 'en', 'Group by'),
 ('agents.q.groupby', 'de', 'Gruppieren nach'),
 ('agents.q.measures', 'en', 'For each group'),
 ('agents.q.measures', 'de', 'Je Gruppe'),
 ('agents.q.sort', 'en', 'Order'),
 ('agents.q.sort', 'de', 'Reihenfolge'),
 ('agents.q.limit', 'en', 'At most (rows)'),
 ('agents.q.limit', 'de', 'Höchstens (Zeilen)'),
 ('agents.q.none', 'en', 'None'),
 ('agents.q.none', 'de', 'Keine'),
 ('agents.q.try', 'en', 'Try it now'),
 ('agents.q.try', 'de', 'Jetzt ausprobieren'),
 ('agents.q.trying', 'en', 'Trying…'),
 ('agents.q.trying', 'de', 'Wird ausprobiert…'),
 ('agents.q.tried', 'en', '{n} rows with your own access. The first {shown} are shown.'),
 ('agents.q.tried', 'de', '{n} Zeilen mit Ihrem eigenen Zugriff. Die ersten {shown} werden gezeigt.'),
 ('agents.error.query_missing', 'en', 'Say what the question asks about.'),
 ('agents.error.query_missing', 'de', 'Geben Sie an, wonach die Abfrage fragt.'),
 ('agents.error.query_dataset_unknown', 'en', 'That cannot be asked about here.'),
 ('agents.error.query_dataset_unknown', 'de', 'Danach kann hier nicht gefragt werden.'),
 ('agents.error.query_field_unknown', 'en', 'A field in the question cannot be asked about here.'),
 ('agents.error.query_field_unknown', 'de', 'Ein Feld der Abfrage kann hier nicht abgefragt werden.'),
 ('agents.error.query_field_hidden', 'en', 'A field in the question is hidden here.'),
 ('agents.error.query_field_hidden', 'de', 'Ein Feld der Abfrage ist hier ausgeblendet.'),
 ('agents.error.query_filter_invalid', 'en', 'A condition is not complete.'),
 ('agents.error.query_filter_invalid', 'de', 'Eine Bedingung ist nicht vollständig.'),
 ('agents.error.query_op_invalid', 'en', 'A condition does not suit its field.'),
 ('agents.error.query_op_invalid', 'de', 'Eine Bedingung passt nicht zu ihrem Feld.'),
 ('agents.error.query_value_invalid', 'en', 'A condition''s value is missing or cannot be read.'),
 ('agents.error.query_value_invalid', 'de', 'Der Wert einer Bedingung fehlt oder lässt sich nicht lesen.'),
 ('agents.error.query_currency_missing', 'en', 'An amount needs its currency, such as GBP.'),
 ('agents.error.query_currency_missing', 'de', 'Ein Betrag braucht seine Währung, etwa GBP.'),
 ('agents.error.query_too_many_filters', 'en', 'At most 10 conditions.'),
 ('agents.error.query_too_many_filters', 'de', 'Höchstens 10 Bedingungen.'),
 ('agents.error.query_since_invalid', 'en', 'Choose everything, or only what is new.'),
 ('agents.error.query_since_invalid', 'de', 'Wählen Sie alles oder nur Neues.'),
 ('agents.error.query_group_invalid', 'en', 'Rows cannot be grouped by that.'),
 ('agents.error.query_group_invalid', 'de', 'Danach kann nicht gruppiert werden.'),
 ('agents.error.query_measure_invalid', 'en', 'That cannot be added up for each group.'),
 ('agents.error.query_measure_invalid', 'de', 'Das lässt sich je Gruppe nicht zusammenfassen.'),
 ('agents.error.query_measure_without_group', 'en', 'Totals need a grouping.'),
 ('agents.error.query_measure_without_group', 'de', 'Summen brauchen eine Gruppierung.'),
 ('agents.error.query_money_needs_currency', 'en', 'Amounts are added up by currency, so group by one field fewer.'),
 ('agents.error.query_money_needs_currency', 'de', 'Beträge werden je Währung zusammengefasst, gruppieren Sie daher nach einem Feld weniger.'),
 ('agents.error.query_show_missing', 'en', 'Choose at least one column.'),
 ('agents.error.query_show_missing', 'de', 'Wählen Sie mindestens eine Spalte.'),
 ('agents.error.query_show_invalid', 'en', 'Choose the columns again.'),
 ('agents.error.query_show_invalid', 'de', 'Wählen Sie die Spalten erneut.'),
 ('agents.error.query_show_too_many', 'en', 'At most 12 columns.'),
 ('agents.error.query_show_too_many', 'de', 'Höchstens 12 Spalten.'),
 ('agents.error.query_sort_invalid', 'en', 'The order must be by a column shown.'),
 ('agents.error.query_sort_invalid', 'de', 'Die Reihenfolge muss nach einer angezeigten Spalte gehen.'),
 ('agents.error.query_limit_invalid', 'en', 'At most from 1 to 500 rows.'),
 ('agents.error.query_limit_invalid', 'de', 'Höchstens 1 bis 500 Zeilen.'),
 ('agents.error.query_too_large', 'en', 'The question is too large. Narrow it, or choose fewer organisations or values.'),
 ('agents.error.query_too_large', 'de', 'Die Abfrage ist zu groß. Grenzen Sie sie ein oder wählen Sie weniger Organisationen oder Werte.'),
 ('help.screen.agents.40', 'en', '- In Edit steps you can change the question itself: what it asks about, its conditions, new or all, the columns or a grouping with totals, the order and how many rows. Try it now shows what it finds with your own access, before you save.'),
 ('help.screen.agents.40', 'de', '- Unter Schritte bearbeiten können Sie die Abfrage selbst ändern: wonach sie fragt, ihre Bedingungen, neu oder alles, die Spalten oder eine Gruppierung mit Summen, die Reihenfolge und wie viele Zeilen. Jetzt ausprobieren zeigt vor dem Speichern, was sie mit Ihrem eigenen Zugriff findet.'),
 ('agents.q.op.is', 'en', 'is'),
 ('agents.q.op.is', 'de', 'ist'),
 ('agents.q.op.is_not', 'en', 'is not'),
 ('agents.q.op.is_not', 'de', 'ist nicht'),
 ('agents.q.op.in', 'en', 'is one of'),
 ('agents.q.op.in', 'de', 'ist eines von'),
 ('agents.q.op.contains', 'en', 'contains'),
 ('agents.q.op.contains', 'de', 'enthält'),
 ('agents.q.op.is_empty', 'en', 'is empty'),
 ('agents.q.op.is_empty', 'de', 'ist leer'),
 ('agents.q.op.not_empty', 'en', 'is not empty'),
 ('agents.q.op.not_empty', 'de', 'ist nicht leer'),
 ('agents.q.op.over', 'en', 'is over'),
 ('agents.q.op.over', 'de', 'liegt über'),
 ('agents.q.op.under', 'en', 'is under'),
 ('agents.q.op.under', 'de', 'liegt unter'),
 ('agents.q.op.between', 'en', 'is between'),
 ('agents.q.op.between', 'de', 'liegt zwischen'),
 ('agents.q.op.in_last_days', 'en', 'in the last (days)'),
 ('agents.q.op.in_last_days', 'de', 'in den letzten (Tagen)'),
 ('agents.q.op.older_than_days', 'en', 'more than (days) ago'),
 ('agents.q.op.older_than_days', 'de', 'vor mehr als (Tagen)'),
 ('agents.q.op.before', 'en', 'before'),
 ('agents.q.op.before', 'de', 'vor dem'),
 ('agents.q.op.after', 'en', 'after'),
 ('agents.q.op.after', 'de', 'nach dem');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.q.hint', 'agents.q.dataset', 'agents.q.since', 'agents.q.where', 'agents.q.addfilter', 'agents.q.remove', 'agents.q.currency', 'agents.q.commas', 'agents.q.shape', 'agents.q.shape.rows', 'agents.q.shape.group', 'agents.q.show', 'agents.q.groupby', 'agents.q.measures', 'agents.q.sort', 'agents.q.limit', 'agents.q.none', 'agents.q.try', 'agents.q.trying', 'agents.q.tried', 'agents.error.query_missing', 'agents.error.query_dataset_unknown', 'agents.error.query_field_unknown', 'agents.error.query_field_hidden', 'agents.error.query_filter_invalid', 'agents.error.query_op_invalid', 'agents.error.query_value_invalid', 'agents.error.query_currency_missing', 'agents.error.query_too_many_filters', 'agents.error.query_since_invalid', 'agents.error.query_group_invalid', 'agents.error.query_measure_invalid', 'agents.error.query_measure_without_group', 'agents.error.query_money_needs_currency', 'agents.error.query_show_missing', 'agents.error.query_show_invalid', 'agents.error.query_show_too_many', 'agents.error.query_sort_invalid', 'agents.error.query_limit_invalid', 'agents.error.query_too_large', 'help.screen.agents.40', 'agents.q.op.is', 'agents.q.op.is_not', 'agents.q.op.in', 'agents.q.op.contains', 'agents.q.op.is_empty', 'agents.q.op.not_empty', 'agents.q.op.over', 'agents.q.op.under', 'agents.q.op.between', 'agents.q.op.in_last_days', 'agents.q.op.older_than_days', 'agents.q.op.before', 'agents.q.op.after') == 108
