-- 0285_absence_strings.sql
-- Decision 0641 — Absence and cover: the Absence screen, its states,
-- what became of the tasks, refusals, and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.absence', 'en', 'Absence'),
 ('nav.absence', 'de', 'Abwesenheit'),
 ('absence.subtitle', 'en', 'When you are away, and who covers your tasks.'),
 ('absence.subtitle', 'de', 'Wann Sie abwesend sind und wer Ihre Aufgaben übernimmt.'),
 ('absence.failed', 'en', 'Absences could not be loaded just now.'),
 ('absence.failed', 'de', 'Abwesenheiten konnten gerade nicht geladen werden.'),
 ('absence.zone', 'en', 'Dates in {zone}'),
 ('absence.zone', 'de', 'Daten in {zone}'),
 ('absence.new', 'en', 'I will be away'),
 ('absence.new', 'de', 'Ich bin abwesend'),
 ('absence.newfor', 'en', 'For someone in my team'),
 ('absence.newfor', 'de', 'Für jemanden in meinem Team'),
 ('absence.me', 'en', 'Me'),
 ('absence.me', 'de', 'Ich'),
 ('absence.covering', 'en', 'You are covering for {who}. Their tasks are on your task list.'),
 ('absence.covering', 'de', 'Sie vertreten {who}. Deren Aufgaben stehen in Ihrer Aufgabenliste.'),
 ('absence.coveringone', 'en', '{name} until {day}'),
 ('absence.coveringone', 'de', '{name} bis {day}'),
 ('absence.mine', 'en', 'My absences'),
 ('absence.mine', 'de', 'Meine Abwesenheiten'),
 ('absence.mine.empty', 'en', 'No absence planned.'),
 ('absence.mine.empty', 'de', 'Keine Abwesenheit geplant.'),
 ('absence.team', 'en', 'My team'),
 ('absence.team', 'de', 'Mein Team'),
 ('absence.team.hint', 'en', 'Everyone who shares a team with you, or reports to you, who is away now or will be.'),
 ('absence.team.hint', 'de', 'Alle, die mit Ihnen ein Team teilen oder an Sie berichten und jetzt oder künftig abwesend sind.'),
 ('absence.team.empty', 'en', 'Nobody in your team is away now or planning to be.'),
 ('absence.team.empty', 'de', 'Niemand in Ihrem Team ist jetzt oder künftig abwesend.'),
 ('absence.col.who', 'en', 'Who'),
 ('absence.col.who', 'de', 'Wer'),
 ('absence.col.when', 'en', 'When'),
 ('absence.col.when', 'de', 'Wann'),
 ('absence.col.state', 'en', 'State'),
 ('absence.col.state', 'de', 'Stand'),
 ('absence.col.cover', 'en', 'Cover'),
 ('absence.col.cover', 'de', 'Vertretung'),
 ('absence.col.tasks', 'en', 'Their tasks'),
 ('absence.col.tasks', 'de', 'Ihre Aufgaben'),
 ('absence.backon', 'en', 'Back on {day}'),
 ('absence.backon', 'de', 'Zurück am {day}'),
 ('absence.state.planned', 'en', 'Planned'),
 ('absence.state.planned', 'de', 'Geplant'),
 ('absence.state.away', 'en', 'Away now'),
 ('absence.state.away', 'de', 'Jetzt abwesend'),
 ('absence.state.back', 'en', 'Back'),
 ('absence.state.back', 'de', 'Zurück'),
 ('absence.state.cancelled', 'en', 'Cancelled'),
 ('absence.state.cancelled', 'de', 'Abgesagt'),
 ('absence.tasks.kept', 'en', 'Kept, not passed on'),
 ('absence.tasks.kept', 'de', 'Behalten, nicht weitergegeben'),
 ('absence.tasks.willpass', 'en', 'Will pass to {cover}'),
 ('absence.tasks.willpass', 'de', 'Gehen an {cover}'),
 ('absence.tasks.moved', 'en', '{n} with {cover}'),
 ('absence.tasks.moved', 'de', '{n} bei {cover}'),
 ('absence.tasks.returned', 'en', '{n} handed back'),
 ('absence.tasks.returned', 'de', '{n} zurückgegeben'),
 ('absence.tasks.none', 'en', 'None held'),
 ('absence.tasks.none', 'de', 'Keine offen'),
 ('absence.tasks.kept.permission', 'en', '{n} stayed: {cover} does not hold {what} there'),
 ('absence.tasks.kept.permission', 'de', '{n} geblieben: {cover} hat dort nicht {what}'),
 ('absence.tasks.kept.limit', 'en', '{n} stayed: above {cover}''s approval limit in {what}'),
 ('absence.tasks.kept.limit', 'de', '{n} geblieben: über dem Freigabelimit von {cover} in {what}'),
 ('absence.amend', 'en', 'Amend'),
 ('absence.amend', 'de', 'Ändern'),
 ('absence.cancel', 'en', 'Cancel absence'),
 ('absence.cancel', 'de', 'Abwesenheit absagen'),
 ('absence.cancelform', 'en', 'Cancel'),
 ('absence.cancelform', 'de', 'Abbrechen'),
 ('absence.save', 'en', 'Save'),
 ('absence.save', 'de', 'Speichern'),
 ('absence.saved.new', 'en', 'Saved. Tasks pass to the cover on the first day away.'),
 ('absence.saved.new', 'de', 'Gespeichert. Die Aufgaben gehen am ersten Abwesenheitstag an die Vertretung.'),
 ('absence.saved.edit', 'en', 'Saved.'),
 ('absence.saved.edit', 'de', 'Gespeichert.'),
 ('absence.saved.cancelled', 'en', 'Cancelled. Anything passed on has been handed back.'),
 ('absence.saved.cancelled', 'de', 'Abgesagt. Weitergegebenes wurde zurückgegeben.'),
 ('absence.form.new', 'en', 'I will be away'),
 ('absence.form.new', 'de', 'Ich bin abwesend'),
 ('absence.form.newfor', 'en', 'Someone in my team will be away'),
 ('absence.form.newfor', 'de', 'Jemand aus meinem Team ist abwesend'),
 ('absence.form.edit', 'en', 'Amend the absence'),
 ('absence.form.edit', 'de', 'Abwesenheit ändern'),
 ('absence.form.who', 'en', 'Who'),
 ('absence.form.who', 'de', 'Wer'),
 ('absence.form.starts', 'en', 'First day away'),
 ('absence.form.starts', 'de', 'Erster Abwesenheitstag'),
 ('absence.form.returns', 'en', 'Back on'),
 ('absence.form.returns', 'de', 'Zurück am'),
 ('absence.form.returnshint', 'en', 'The first day back at work.'),
 ('absence.form.returnshint', 'de', 'Der erste Tag zurück bei der Arbeit.'),
 ('absence.form.cover', 'en', 'Who covers'),
 ('absence.form.cover', 'de', 'Vertretung'),
 ('absence.form.nocover', 'en', 'Nobody'),
 ('absence.form.nocover', 'de', 'Niemand'),
 ('absence.form.coverhint', 'en', 'Someone who shares a team with them, or their manager. They take only the tasks they may do.'),
 ('absence.form.coverhint', 'de', 'Jemand aus einem gemeinsamen Team oder die Führungskraft. Übernommen wird nur, was sie erledigen dürfen.'),
 ('absence.form.pass', 'en', 'Pass open tasks to the cover while away'),
 ('absence.form.pass', 'de', 'Offene Aufgaben während der Abwesenheit an die Vertretung geben'),
 ('absence.form.back', 'en', 'Hand back what is still open on return'),
 ('absence.form.back', 'de', 'Noch Offenes bei Rückkehr zurückgeben'),
 ('absence.form.note', 'en', 'Note (optional)'),
 ('absence.form.note', 'de', 'Notiz (optional)'),
 ('absence.error.not_yours', 'en', 'Only the person, or an AP Manager for their team, may arrange their absence.'),
 ('absence.error.not_yours', 'de', 'Nur die Person selbst oder eine AP-Leitung ihres Teams kann die Abwesenheit eintragen.'),
 ('absence.error.dates_invalid', 'en', 'Give the first day away and the day back.'),
 ('absence.error.dates_invalid', 'de', 'Geben Sie den ersten Abwesenheitstag und den Tag der Rückkehr an.'),
 ('absence.error.dates_order', 'en', 'The day back must be after the first day away.'),
 ('absence.error.dates_order', 'de', 'Der Tag der Rückkehr muss nach dem ersten Abwesenheitstag liegen.'),
 ('absence.error.starts_in_past', 'en', 'The first day away cannot be in the past.'),
 ('absence.error.starts_in_past', 'de', 'Der erste Abwesenheitstag darf nicht in der Vergangenheit liegen.'),
 ('absence.error.returns_in_past', 'en', 'The day back must be after today.'),
 ('absence.error.returns_in_past', 'de', 'Der Tag der Rückkehr muss nach heute liegen.'),
 ('absence.error.cover_self', 'en', 'Someone else must cover.'),
 ('absence.error.cover_self', 'de', 'Jemand anderes muss vertreten.'),
 ('absence.error.cover_not_allowed', 'en', 'The cover must share a team with them, or be their manager.'),
 ('absence.error.cover_not_allowed', 'de', 'Die Vertretung muss ein Team mit der Person teilen oder ihre Führungskraft sein.'),
 ('absence.error.cover_away', 'en', 'The cover is away for some of that time.'),
 ('absence.error.cover_away', 'de', 'Die Vertretung ist in dieser Zeit teilweise selbst abwesend.'),
 ('absence.error.overlaps', 'en', 'They are already away for some of that time.'),
 ('absence.error.overlaps', 'de', 'Für einen Teil dieser Zeit ist bereits eine Abwesenheit eingetragen.'),
 ('absence.error.cover_missing', 'en', 'Choose who covers, or keep the tasks.'),
 ('absence.error.cover_missing', 'de', 'Wählen Sie eine Vertretung oder behalten Sie die Aufgaben.'),
 ('absence.error.over', 'en', 'That absence is over.'),
 ('absence.error.over', 'de', 'Diese Abwesenheit ist vorbei.'),
 ('absence.error.not_found', 'en', 'That absence no longer exists.'),
 ('absence.error.not_found', 'de', 'Diese Abwesenheit gibt es nicht mehr.'),
 ('help.screen.absence', 'en', 'Mark when you will be away, and who covers. While you are away, your open tasks pass to them, and they come back when you return.'),
 ('help.screen.absence', 'de', 'Tragen Sie ein, wann Sie abwesend sind und wer vertritt. Während Ihrer Abwesenheit gehen Ihre offenen Aufgaben an die Vertretung und kommen bei Ihrer Rückkehr zurück.'),
 ('help.screen.absence.2', 'en', '- Your cover takes only the tasks they may do: they need the task''s permission where the invoice is, and for an approval, a limit that covers the invoice. Anything else stays with you, and the screen says why.'),
 ('help.screen.absence.2', 'de', '- Ihre Vertretung übernimmt nur Aufgaben, die sie erledigen darf: Sie braucht die Berechtigung der Aufgabe dort, wo die Rechnung ist, und bei einer Freigabe ein ausreichendes Limit. Alles andere bleibt bei Ihnen, und die Ansicht sagt, warum.'),
 ('help.screen.absence.3', 'en', '- An AP Manager sees everyone in their team who is away or will be, and may arrange, amend or cancel their absence. Every task passed or handed back shows on the invoice''s Timeline.'),
 ('help.screen.absence.3', 'de', '- Eine AP-Leitung sieht alle aus ihrem Team, die abwesend sind oder sein werden, und kann deren Abwesenheit eintragen, ändern oder absagen. Jede weitergegebene oder zurückgegebene Aufgabe steht in der Timeline der Rechnung.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.absence', 'absence.subtitle', 'absence.failed', 'absence.zone', 'absence.new', 'absence.newfor', 'absence.me', 'absence.covering', 'absence.coveringone', 'absence.mine', 'absence.mine.empty', 'absence.team', 'absence.team.hint', 'absence.team.empty', 'absence.col.who', 'absence.col.when', 'absence.col.state', 'absence.col.cover', 'absence.col.tasks', 'absence.backon', 'absence.state.planned', 'absence.state.away', 'absence.state.back', 'absence.state.cancelled', 'absence.tasks.kept', 'absence.tasks.willpass', 'absence.tasks.moved', 'absence.tasks.returned', 'absence.tasks.none', 'absence.tasks.kept.permission', 'absence.tasks.kept.limit', 'absence.amend', 'absence.cancel', 'absence.cancelform', 'absence.save', 'absence.saved.new', 'absence.saved.edit', 'absence.saved.cancelled', 'absence.form.new', 'absence.form.newfor', 'absence.form.edit', 'absence.form.who', 'absence.form.starts', 'absence.form.returns', 'absence.form.returnshint', 'absence.form.cover', 'absence.form.nocover', 'absence.form.coverhint', 'absence.form.pass', 'absence.form.back', 'absence.form.note', 'absence.error.not_yours', 'absence.error.dates_invalid', 'absence.error.dates_order', 'absence.error.starts_in_past', 'absence.error.returns_in_past', 'absence.error.cover_self', 'absence.error.cover_not_allowed', 'absence.error.cover_away', 'absence.error.overlaps', 'absence.error.cover_missing', 'absence.error.over', 'absence.error.not_found', 'help.screen.absence', 'help.screen.absence.2', 'help.screen.absence.3') == 132
