-- 0288_goods_receipts_strings.sql
-- Decision 0645 — Goods receipts, slice 3: the Goods Receipts screen, recording
-- a receipt or a return, the figures, refusals and help.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('nav.goodsreceipts', 'en', 'Goods Receipts'),
 ('nav.goodsreceipts', 'de', 'Wareneingänge'),
 ('receipts.subtitle', 'en', 'What arrived and what went back, against purchase orders.'),
 ('receipts.subtitle', 'de', 'Was angekommen und was zurückgegangen ist, zu den Bestellungen.'),
 ('receipts.failed', 'en', 'Goods receipts could not be loaded just now.'),
 ('receipts.failed', 'de', 'Wareneingänge konnten gerade nicht geladen werden.'),
 ('receipts.readonly', 'en', 'You can see receipts here. Recording them needs AP.Receive.'),
 ('receipts.readonly', 'de', 'Sie sehen hier Wareneingänge. Zum Erfassen ist AP.Receive nötig.'),
 ('receipts.loadheading', 'en', 'Load receipts'),
 ('receipts.loadheading', 'de', 'Wareneingänge laden'),
 ('receipts.loadhelp', 'en', 'A CSV from your warehouse system, one row per receipt line. Loading the same file again changes nothing.'),
 ('receipts.loadhelp', 'de', 'Eine CSV aus Ihrem Lagersystem, eine Zeile je Wareneingangsposition. Dieselbe Datei erneut zu laden ändert nichts.'),
 ('receipts.loadfailed', 'en', 'The file could not be loaded just now.'),
 ('receipts.loadfailed', 'de', 'Die Datei konnte gerade nicht geladen werden.'),
 ('receipts.meaning', 'en', 'Meaning'),
 ('receipts.meaning', 'de', 'Bedeutung'),
 ('receipts.required.yes', 'en', 'Required'),
 ('receipts.required.yes', 'de', 'Pflicht'),
 ('receipts.required.no', 'en', '—'),
 ('receipts.required.no', 'de', '—'),
 ('receipts.required.for_returns', 'en', 'For returns'),
 ('receipts.required.for_returns', 'de', 'Bei Rücksendungen'),
 ('receipts.loaded', 'en', '{lines} lines loaded, {receipts} new receipts.'),
 ('receipts.loaded', 'de', '{lines} Positionen geladen, {receipts} neue Wareneingänge.'),
 ('receipts.skipped', 'en', '{n} lines were already loaded and were left as they are.'),
 ('receipts.skipped', 'de', '{n} Positionen waren schon geladen und bleiben unverändert.'),
 ('receipts.refusedheading', 'en', 'Not loaded'),
 ('receipts.refusedheading', 'de', 'Nicht geladen'),
 ('receipts.refusedrow', 'en', 'Row {row}: {why}'),
 ('receipts.refusedrow', 'de', 'Zeile {row}: {why}'),
 ('receipts.overrow', 'en', 'Row {row}: {order} line {line} now holds {held}, more than the {ordered} ordered.'),
 ('receipts.overrow', 'de', 'Zeile {row}: {order} Position {line} hat jetzt {held}, mehr als die bestellten {ordered}.'),
 ('receipts.overline', 'en', '{order} line {line} now holds {held}, more than the {ordered} ordered.'),
 ('receipts.overline', 'de', '{order} Position {line} hat jetzt {held}, mehr als die bestellten {ordered}.'),
 ('receipts.chartheading', 'en', 'Orders by receipt'),
 ('receipts.chartheading', 'de', 'Bestellungen nach Wareneingang'),
 ('receipts.charthint', 'en', 'Orders not closed whose supplier needs receipting, or that have a receipt.'),
 ('receipts.charthint', 'de', 'Nicht abgeschlossene Bestellungen, deren Lieferant Wareneingang erfordert oder die einen Wareneingang haben.'),
 ('receipts.nochart', 'en', 'No orders to show yet.'),
 ('receipts.nochart', 'de', 'Noch keine Bestellungen anzuzeigen.'),
 ('receipts.creditorders', 'en', '{n} orders expect a credit note for goods returned after invoicing.'),
 ('receipts.creditorders', 'de', '{n} Bestellungen erwarten eine Gutschrift für nach der Rechnung zurückgesandte Ware.'),
 ('receipts.creditexpected', 'en', 'Credit expected'),
 ('receipts.creditexpected', 'de', 'Gutschrift erwartet'),
 ('receipts.creditexpectedn', 'en', 'Credit expected {n}'),
 ('receipts.creditexpectedn', 'de', 'Gutschrift erwartet {n}'),
 ('receipts.state.not_received', 'en', 'Not received'),
 ('receipts.state.not_received', 'de', 'Nicht eingegangen'),
 ('receipts.state.partially_received', 'en', 'Partially received'),
 ('receipts.state.partially_received', 'de', 'Teilweise eingegangen'),
 ('receipts.state.fully_received', 'en', 'Fully received'),
 ('receipts.state.fully_received', 'de', 'Vollständig eingegangen'),
 ('receipts.state.over_received', 'en', 'Over-received'),
 ('receipts.state.over_received', 'de', 'Mehr eingegangen'),
 ('receipts.movement.received', 'en', 'Receipt'),
 ('receipts.movement.received', 'de', 'Eingang'),
 ('receipts.movement.returned', 'en', 'Return'),
 ('receipts.movement.returned', 'de', 'Rücksendung'),
 ('receipts.cancelled', 'en', 'Cancelled'),
 ('receipts.cancelled', 'de', 'Storniert'),
 ('receipts.listheading', 'en', 'Receipts and returns'),
 ('receipts.listheading', 'de', 'Eingänge und Rücksendungen'),
 ('receipts.recordreceipt', 'en', 'Record a receipt'),
 ('receipts.recordreceipt', 'de', 'Eingang erfassen'),
 ('receipts.recordreturn', 'en', 'Record a return'),
 ('receipts.recordreturn', 'de', 'Rücksendung erfassen'),
 ('receipts.searchplaceholder', 'en', 'Search receipt, order, delivery note, item or supplier…'),
 ('receipts.searchplaceholder', 'de', 'Eingang, Bestellung, Lieferschein, Artikel oder Lieferant suchen…'),
 ('receipts.kind.all', 'en', 'All'),
 ('receipts.kind.all', 'de', 'Alle'),
 ('receipts.kind.received', 'en', 'Receipts'),
 ('receipts.kind.received', 'de', 'Eingänge'),
 ('receipts.kind.returned', 'en', 'Returns'),
 ('receipts.kind.returned', 'de', 'Rücksendungen'),
 ('receipts.kind.cancelled', 'en', 'Cancelled'),
 ('receipts.kind.cancelled', 'de', 'Storniert'),
 ('receipts.none', 'en', 'No receipts recorded yet.'),
 ('receipts.none', 'de', 'Noch keine Wareneingänge erfasst.'),
 ('receipts.nomatches', 'en', 'Nothing matches that.'),
 ('receipts.nomatches', 'de', 'Dazu passt nichts.'),
 ('receipts.col.receipt', 'en', 'Receipt'),
 ('receipts.col.receipt', 'de', 'Eingang'),
 ('receipts.col.date', 'en', 'Date'),
 ('receipts.col.date', 'de', 'Datum'),
 ('receipts.col.orders', 'en', 'Order'),
 ('receipts.col.orders', 'de', 'Bestellung'),
 ('receipts.col.order', 'en', 'Order / line'),
 ('receipts.col.order', 'de', 'Bestellung / Position'),
 ('receipts.col.supplier', 'en', 'Supplier'),
 ('receipts.col.supplier', 'de', 'Lieferant'),
 ('receipts.col.lines', 'en', 'Lines'),
 ('receipts.col.lines', 'de', 'Positionen'),
 ('receipts.col.kind', 'en', 'Kind'),
 ('receipts.col.kind', 'de', 'Art'),
 ('receipts.col.ordernow', 'en', 'Order now'),
 ('receipts.col.ordernow', 'de', 'Bestellung jetzt'),
 ('receipts.col.by', 'en', 'Recorded by'),
 ('receipts.col.by', 'de', 'Erfasst von'),
 ('receipts.col.line', 'en', 'Line'),
 ('receipts.col.line', 'de', 'Position'),
 ('receipts.col.item', 'en', 'Item'),
 ('receipts.col.item', 'de', 'Artikel'),
 ('receipts.col.ordered', 'en', 'Ordered'),
 ('receipts.col.ordered', 'de', 'Bestellt'),
 ('receipts.col.received', 'en', 'Received'),
 ('receipts.col.received', 'de', 'Eingegangen'),
 ('receipts.col.returned', 'en', 'Returned'),
 ('receipts.col.returned', 'de', 'Zurück'),
 ('receipts.col.net', 'en', 'Net'),
 ('receipts.col.net', 'de', 'Netto'),
 ('receipts.col.invoiced', 'en', 'Invoiced'),
 ('receipts.col.invoiced', 'de', 'Berechnet'),
 ('receipts.col.state', 'en', 'State'),
 ('receipts.col.state', 'de', 'Stand'),
 ('receipts.col.quantity', 'en', 'Quantity'),
 ('receipts.col.quantity', 'de', 'Menge'),
 ('receipts.reason', 'en', 'Reason'),
 ('receipts.reason', 'de', 'Grund'),
 ('receipts.deliverynote', 'en', 'Supplier''s delivery note'),
 ('receipts.deliverynote', 'de', 'Lieferschein des Lieferanten'),
 ('receipts.note', 'en', 'Note'),
 ('receipts.note', 'de', 'Notiz'),
 ('receipts.source.csv', 'en', 'loaded by CSV'),
 ('receipts.source.csv', 'de', 'per CSV geladen'),
 ('receipts.source.screen', 'en', 'on screen'),
 ('receipts.source.screen', 'de', 'am Bildschirm'),
 ('receipts.notonorder', 'en', 'No longer on the order'),
 ('receipts.notonorder', 'de', 'Nicht mehr in der Bestellung'),
 ('receipts.ordersnow', 'en', 'Where the order stands now'),
 ('receipts.ordersnow', 'de', 'Wo die Bestellung jetzt steht'),
 ('receipts.detailfailed', 'en', 'That receipt could not be opened just now.'),
 ('receipts.detailfailed', 'de', 'Dieser Wareneingang konnte gerade nicht geöffnet werden.'),
 ('receipts.cancelreceipt', 'en', 'Cancel receipt'),
 ('receipts.cancelreceipt', 'de', 'Eingang stornieren'),
 ('receipts.cancelprompt', 'en', 'Why is it cancelled? It stays on file, marked, and counts for nothing.'),
 ('receipts.cancelprompt', 'de', 'Warum wird storniert? Er bleibt gespeichert, markiert, und zählt nicht mehr.'),
 ('receipts.cancelwhy', 'en', 'For example: entered against the wrong order'),
 ('receipts.cancelwhy', 'de', 'Zum Beispiel: gegen die falsche Bestellung erfasst'),
 ('receipts.cancelconfirm', 'en', 'Cancel it'),
 ('receipts.cancelconfirm', 'de', 'Stornieren'),
 ('receipts.cancelfailed', 'en', 'It could not be cancelled just now.'),
 ('receipts.cancelfailed', 'de', 'Er konnte gerade nicht storniert werden.'),
 ('receipts.cancelled.done', 'en', '{number} is cancelled.'),
 ('receipts.cancelled.done', 'de', '{number} ist storniert.'),
 ('receipts.cancelledby', 'en', 'Cancelled by {who}: {why}'),
 ('receipts.cancelledby', 'de', 'Storniert von {who}: {why}'),
 ('receipts.form.receiptheading', 'en', 'Record a receipt'),
 ('receipts.form.receiptheading', 'de', 'Eingang erfassen'),
 ('receipts.form.returnheading', 'en', 'Record a return'),
 ('receipts.form.returnheading', 'de', 'Rücksendung erfassen'),
 ('receipts.form.order', 'en', 'Purchase order'),
 ('receipts.form.order', 'de', 'Bestellung'),
 ('receipts.form.orderhint', 'en', 'Order number'),
 ('receipts.form.orderhint', 'de', 'Bestellnummer'),
 ('receipts.form.find', 'en', 'Find'),
 ('receipts.form.find', 'de', 'Suchen'),
 ('receipts.form.findfirst', 'en', 'Find the purchase order first.'),
 ('receipts.form.findfirst', 'de', 'Suchen Sie zuerst die Bestellung.'),
 ('receipts.form.number', 'en', 'Receipt number'),
 ('receipts.form.number', 'de', 'Eingangsnummer'),
 ('receipts.form.returnnumber', 'en', 'Return number'),
 ('receipts.form.returnnumber', 'de', 'Rücksendenummer'),
 ('receipts.form.receivedon', 'en', 'Received on'),
 ('receipts.form.receivedon', 'de', 'Eingegangen am'),
 ('receipts.form.returnedon', 'en', 'Returned on'),
 ('receipts.form.returnedon', 'de', 'Zurückgesandt am'),
 ('receipts.form.receivednow', 'en', 'Received now'),
 ('receipts.form.receivednow', 'de', 'Jetzt eingegangen'),
 ('receipts.form.returnednow', 'en', 'Returned now'),
 ('receipts.form.returnednow', 'de', 'Jetzt zurück'),
 ('receipts.form.choosereason', 'en', 'Choose a reason'),
 ('receipts.form.choosereason', 'de', 'Grund wählen'),
 ('receipts.form.willover', 'en', 'That makes {held}, more than the {ordered} ordered. It will be saved, and the line shows over-received.'),
 ('receipts.form.willover', 'de', 'Das ergibt {held}, mehr als die bestellten {ordered}. Es wird gespeichert, und die Position zeigt Mehreingang.'),
 ('receipts.form.nothing', 'en', 'Enter a quantity on at least one line.'),
 ('receipts.form.nothing', 'de', 'Geben Sie für mindestens eine Position eine Menge ein.'),
 ('receipts.saved.receipt', 'en', 'Receipt {number} recorded.'),
 ('receipts.saved.receipt', 'de', 'Eingang {number} erfasst.'),
 ('receipts.saved.return', 'en', 'Return {number} recorded.'),
 ('receipts.saved.return', 'de', 'Rücksendung {number} erfasst.'),
 ('receipts.savefailed', 'en', 'It could not be saved just now.'),
 ('receipts.savefailed', 'de', 'Es konnte gerade nicht gespeichert werden.'),
 ('receipts.error.online', 'en', 'Line {line}: {why}'),
 ('receipts.error.online', 'de', 'Position {line}: {why}'),
 ('receipts.error.number_missing', 'en', 'Give the receipt a number.'),
 ('receipts.error.number_missing', 'de', 'Geben Sie eine Eingangsnummer an.'),
 ('receipts.error.date_invalid', 'en', 'The date must be a real date (YYYY-MM-DD).'),
 ('receipts.error.date_invalid', 'de', 'Das Datum muss ein echtes Datum sein (JJJJ-MM-TT).'),
 ('receipts.error.no_lines', 'en', 'Enter a quantity on at least one line.'),
 ('receipts.error.no_lines', 'de', 'Geben Sie für mindestens eine Position eine Menge ein.'),
 ('receipts.error.too_many_lines', 'en', 'At most 500 lines in one receipt.'),
 ('receipts.error.too_many_lines', 'de', 'Höchstens 500 Positionen je Eingang.'),
 ('receipts.error.receipt_exists', 'en', 'That receipt number is already used.'),
 ('receipts.error.receipt_exists', 'de', 'Diese Eingangsnummer ist schon vergeben.'),
 ('receipts.error.order_missing', 'en', 'No order number.'),
 ('receipts.error.order_missing', 'de', 'Keine Bestellnummer.'),
 ('receipts.error.order_line_missing', 'en', 'No order line number.'),
 ('receipts.error.order_line_missing', 'de', 'Keine Bestellposition.'),
 ('receipts.error.order_not_found', 'en', 'No purchase order with that number that you may receive against.'),
 ('receipts.error.order_not_found', 'de', 'Keine Bestellung mit dieser Nummer, für die Sie Eingänge erfassen dürfen.'),
 ('receipts.error.order_closed', 'en', 'That purchase order is closed.'),
 ('receipts.error.order_closed', 'de', 'Diese Bestellung ist abgeschlossen.'),
 ('receipts.error.order_line_not_found', 'en', 'The purchase order has no such line.'),
 ('receipts.error.order_line_not_found', 'de', 'Die Bestellung hat keine solche Position.'),
 ('receipts.error.quantity_invalid', 'en', 'The quantity must be a number above nought.'),
 ('receipts.error.quantity_invalid', 'de', 'Die Menge muss eine Zahl über null sein.'),
 ('receipts.error.movement_invalid', 'en', 'The movement must be received or returned.'),
 ('receipts.error.movement_invalid', 'de', 'Die Bewegung muss received oder returned sein.'),
 ('receipts.error.unit_mismatch', 'en', 'The unit is not the order line''s unit.'),
 ('receipts.error.unit_mismatch', 'de', 'Die Einheit ist nicht die der Bestellposition.'),
 ('receipts.error.return_reason_missing', 'en', 'A return needs a reason.'),
 ('receipts.error.return_reason_missing', 'de', 'Eine Rücksendung braucht einen Grund.'),
 ('receipts.error.return_reason_unknown', 'en', 'That is not a goods return reason.'),
 ('receipts.error.return_reason_unknown', 'de', 'Das ist kein Grund für Warenrücksendungen.'),
 ('receipts.error.return_exceeds_received', 'en', 'More than is held on that line.'),
 ('receipts.error.return_exceeds_received', 'de', 'Mehr als auf dieser Position vorhanden ist.'),
 ('receipts.error.receipt_line_missing', 'en', 'No receipt line number.'),
 ('receipts.error.receipt_line_missing', 'de', 'Keine Eingangsposition.'),
 ('receipts.error.receipt_cancelled', 'en', 'That receipt was cancelled.'),
 ('receipts.error.receipt_cancelled', 'de', 'Dieser Eingang wurde storniert.'),
 ('receipts.error.columns_missing', 'en', 'The file is missing a required column. Open the format for the list.'),
 ('receipts.error.columns_missing', 'de', 'Der Datei fehlt eine Pflichtspalte. Öffnen Sie das Format für die Liste.'),
 ('receipts.error.empty', 'en', 'The file needs a header row and at least one line.'),
 ('receipts.error.empty', 'de', 'Die Datei braucht eine Kopfzeile und mindestens eine Zeile.'),
 ('receipts.error.already_cancelled', 'en', 'That receipt is already cancelled.'),
 ('receipts.error.already_cancelled', 'de', 'Dieser Eingang ist schon storniert.'),
 ('receipts.error.cancel_reason_missing', 'en', 'Say why it is cancelled.'),
 ('receipts.error.cancel_reason_missing', 'de', 'Geben Sie an, warum storniert wird.'),
 ('receipts.error.returns_depend_on_it', 'en', 'Goods on this receipt were later returned. Cancel the return first.'),
 ('receipts.error.returns_depend_on_it', 'de', 'Ware aus diesem Eingang wurde später zurückgesandt. Stornieren Sie zuerst die Rücksendung.'),
 ('receipts.error.not_found', 'en', 'That receipt no longer exists.'),
 ('receipts.error.not_found', 'de', 'Diesen Eingang gibt es nicht mehr.'),
 ('help.screen.goodsreceipts', 'en', 'What arrived and what went back, against purchase order lines. Each order line shows what was ordered, received, returned and invoiced, and where it stands.'),
 ('help.screen.goodsreceipts', 'de', 'Was angekommen und was zurückgegangen ist, zu Bestellpositionen. Jede Position zeigt, was bestellt, eingegangen, zurückgesandt und berechnet ist, und wo sie steht.'),
 ('help.screen.goodsreceipts.2', 'en', '- Load a CSV from your warehouse system, or record a receipt or a return here. More than ordered is saved, with a warning. A return needs a reason, and reopens what it took back until a replacement arrives or the order is changed.'),
 ('help.screen.goodsreceipts.2', 'de', '- Laden Sie eine CSV aus Ihrem Lagersystem oder erfassen Sie hier einen Eingang oder eine Rücksendung. Mehr als bestellt wird mit Hinweis gespeichert. Eine Rücksendung braucht einen Grund und öffnet die Menge wieder, bis Ersatz kommt oder die Bestellung geändert wird.'),
 ('help.screen.goodsreceipts.3', 'en', '- Credit expected means goods were returned after they were invoiced. A receipt entered by mistake is cancelled, never deleted. Recording needs AP.Receive, and AP.Validate may look.'),
 ('help.screen.goodsreceipts.3', 'de', '- Gutschrift erwartet heißt: Ware wurde nach der Rechnung zurückgesandt. Ein irrtümlich erfasster Eingang wird storniert, nie gelöscht. Erfassen braucht AP.Receive, AP.Validate darf ansehen.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('nav.goodsreceipts', 'receipts.subtitle', 'receipts.failed', 'receipts.readonly', 'receipts.loadheading', 'receipts.loadhelp', 'receipts.loadfailed', 'receipts.meaning', 'receipts.required.yes', 'receipts.required.no', 'receipts.required.for_returns', 'receipts.loaded', 'receipts.skipped', 'receipts.refusedheading', 'receipts.refusedrow', 'receipts.overrow', 'receipts.overline', 'receipts.chartheading', 'receipts.charthint', 'receipts.nochart', 'receipts.creditorders', 'receipts.creditexpected', 'receipts.creditexpectedn', 'receipts.state.not_received', 'receipts.state.partially_received', 'receipts.state.fully_received', 'receipts.state.over_received', 'receipts.movement.received', 'receipts.movement.returned', 'receipts.cancelled', 'receipts.listheading', 'receipts.recordreceipt', 'receipts.recordreturn', 'receipts.searchplaceholder', 'receipts.kind.all', 'receipts.kind.received', 'receipts.kind.returned', 'receipts.kind.cancelled', 'receipts.none', 'receipts.nomatches', 'receipts.col.receipt', 'receipts.col.date', 'receipts.col.orders', 'receipts.col.order', 'receipts.col.supplier', 'receipts.col.lines', 'receipts.col.kind', 'receipts.col.ordernow', 'receipts.col.by', 'receipts.col.line', 'receipts.col.item', 'receipts.col.ordered', 'receipts.col.received', 'receipts.col.returned', 'receipts.col.net', 'receipts.col.invoiced', 'receipts.col.state', 'receipts.col.quantity', 'receipts.reason', 'receipts.deliverynote', 'receipts.note', 'receipts.source.csv', 'receipts.source.screen', 'receipts.notonorder', 'receipts.ordersnow', 'receipts.detailfailed', 'receipts.cancelreceipt', 'receipts.cancelprompt', 'receipts.cancelwhy', 'receipts.cancelconfirm', 'receipts.cancelfailed', 'receipts.cancelled.done', 'receipts.cancelledby', 'receipts.form.receiptheading', 'receipts.form.returnheading', 'receipts.form.order', 'receipts.form.orderhint', 'receipts.form.find', 'receipts.form.findfirst', 'receipts.form.number', 'receipts.form.returnnumber', 'receipts.form.receivedon', 'receipts.form.returnedon', 'receipts.form.receivednow', 'receipts.form.returnednow', 'receipts.form.choosereason', 'receipts.form.willover', 'receipts.form.nothing', 'receipts.saved.receipt', 'receipts.saved.return', 'receipts.savefailed', 'receipts.error.online', 'receipts.error.number_missing', 'receipts.error.date_invalid', 'receipts.error.no_lines', 'receipts.error.too_many_lines', 'receipts.error.receipt_exists', 'receipts.error.order_missing', 'receipts.error.order_line_missing', 'receipts.error.order_not_found', 'receipts.error.order_closed', 'receipts.error.order_line_not_found', 'receipts.error.quantity_invalid', 'receipts.error.movement_invalid', 'receipts.error.unit_mismatch', 'receipts.error.return_reason_missing', 'receipts.error.return_reason_unknown', 'receipts.error.return_exceeds_received', 'receipts.error.receipt_line_missing', 'receipts.error.receipt_cancelled', 'receipts.error.columns_missing', 'receipts.error.empty', 'receipts.error.already_cancelled', 'receipts.error.cancel_reason_missing', 'receipts.error.returns_depend_on_it', 'receipts.error.not_found', 'help.screen.goodsreceipts', 'help.screen.goodsreceipts.2', 'help.screen.goodsreceipts.3') == 238
