-- 0293_warehouse_receipts_strings.sql
-- Decision 0651 — Warehouse Receipts, slice 2: pending, registered and rejected
-- receipts, and the Warehouse Receipts process.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('receipts.kind.pending', 'en', 'Pending'),
 ('receipts.kind.pending', 'de', 'Ausstehend'),
 ('receipts.kind.rejected', 'en', 'Rejected'),
 ('receipts.kind.rejected', 'de', 'Abgelehnt'),
 ('receipts.status.pending', 'en', 'Pending'),
 ('receipts.status.pending', 'de', 'Ausstehend'),
 ('receipts.status.rejected', 'en', 'Rejected'),
 ('receipts.status.rejected', 'de', 'Abgelehnt'),
 ('receipts.registered', 'en', 'Registered'),
 ('receipts.registered', 'de', 'Erfasst'),
 ('receipts.pendingat', 'en', 'Pending at {stage} in {process}: it counts once registered.'),
 ('receipts.pendingat', 'de', 'Ausstehend in {stage} ({process}): Er zählt erst, wenn er erfasst ist.'),
 ('receipts.pendingnoprocess', 'en', 'Pending: it counts once registered.'),
 ('receipts.pendingnoprocess', 'de', 'Ausstehend: Er zählt erst, wenn er erfasst ist.'),
 ('receipts.rejectedby', 'en', 'Rejected by {who}: {why}'),
 ('receipts.rejectedby', 'de', 'Abgelehnt von {who}: {why}'),
 ('receipts.rejectreceipt', 'en', 'Reject receipt'),
 ('receipts.rejectreceipt', 'de', 'Wareneingang ablehnen'),
 ('receipts.rejectprompt', 'en', 'Why is it rejected? A rejected receipt never counts.'),
 ('receipts.rejectprompt', 'de', 'Warum wird er abgelehnt? Ein abgelehnter Wareneingang zählt nie.'),
 ('receipts.rejectwhy', 'en', 'Reason'),
 ('receipts.rejectwhy', 'de', 'Grund'),
 ('receipts.rejectconfirm', 'en', 'Reject it'),
 ('receipts.rejectconfirm', 'de', 'Ablehnen'),
 ('receipts.rejected.done', 'en', 'Receipt {number} rejected.'),
 ('receipts.rejected.done', 'de', 'Wareneingang {number} abgelehnt.'),
 ('receipts.rejectfailed', 'en', 'The receipt could not be rejected.'),
 ('receipts.rejectfailed', 'de', 'Der Wareneingang konnte nicht abgelehnt werden.'),
 ('receipts.error.receipt_pending', 'en', 'It is not registered yet: reject it instead.'),
 ('receipts.error.receipt_pending', 'de', 'Er ist noch nicht erfasst: Lehnen Sie ihn stattdessen ab.'),
 ('receipts.error.receipt_rejected', 'en', 'That receipt was rejected.'),
 ('receipts.error.receipt_rejected', 'de', 'Dieser Wareneingang wurde abgelehnt.'),
 ('receipts.error.receipt_registered', 'en', 'It is registered: cancel it instead.'),
 ('receipts.error.receipt_registered', 'de', 'Er ist erfasst: Stornieren Sie ihn stattdessen.'),
 ('receipts.error.already_rejected', 'en', 'It is already rejected.'),
 ('receipts.error.already_rejected', 'de', 'Er ist bereits abgelehnt.'),
 ('receipts.error.reject_reason_missing', 'en', 'Say why it is rejected.'),
 ('receipts.error.reject_reason_missing', 'de', 'Geben Sie an, warum er abgelehnt wird.'),
 ('receipts.error.process_id_taken', 'en', 'Another process already uses the id warehouse-receipts.'),
 ('receipts.error.process_id_taken', 'de', 'Ein anderer Prozess verwendet bereits die ID warehouse-receipts.'),
 ('receipts.sent', 'en', 'Sent through {process}. Registered: {registered}. Waiting: {waiting}.'),
 ('receipts.sent', 'de', 'Über {process} gesendet. Erfasst: {registered}. Wartend: {waiting}.'),
 ('receipts.process.direct', 'en', 'Receipts loaded here register at once.'),
 ('receipts.process.direct', 'de', 'Hier geladene Wareneingänge werden sofort erfasst.'),
 ('receipts.process.through', 'en', 'Receipts loaded here go through {process} and count once registered.'),
 ('receipts.process.through', 'de', 'Hier geladene Wareneingänge laufen über {process} und zählen, sobald sie erfasst sind.'),
 ('receipts.process.setup', 'en', 'Set up Warehouse Receipts'),
 ('receipts.process.setup', 'de', 'Lagereingänge einrichten'),
 ('receipts.process.name', 'en', 'Warehouse Receipts'),
 ('receipts.process.name', 'de', 'Lagereingänge'),
 ('receipts.process.stage.intake', 'en', 'Intake'),
 ('receipts.process.stage.intake', 'de', 'Eingang'),
 ('receipts.process.stage.matching', 'en', 'Matching'),
 ('receipts.process.stage.matching', 'de', 'Abgleich'),
 ('receipts.process.stage.complete', 'en', 'Complete'),
 ('receipts.process.stage.complete', 'de', 'Abgeschlossen'),
 ('receipts.process.done', 'en', '{process} is set up. Receipts loaded here now go through it.'),
 ('receipts.process.done', 'de', '{process} ist eingerichtet. Hier geladene Wareneingänge laufen jetzt darüber.'),
 ('receipts.process.failed', 'en', 'The process could not be set up.'),
 ('receipts.process.failed', 'de', 'Der Prozess konnte nicht eingerichtet werden.'),
 ('processroutes.subject.goods_receipt', 'en', 'Moves goods receipts'),
 ('processroutes.subject.goods_receipt', 'de', 'Bewegt Wareneingänge'),
 ('processroutes.subject.goods_receipt.note', 'en', 'Receipts reach this process from Goods Receipts. Invoice sources and destinations are not added here.'),
 ('processroutes.subject.goods_receipt.note', 'de', 'Wareneingänge erreichen diesen Prozess über Wareneingänge. Rechnungsquellen und -ziele werden hier nicht hinzugefügt.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('receipts.kind.pending', 'receipts.kind.rejected', 'receipts.status.pending', 'receipts.status.rejected', 'receipts.registered', 'receipts.pendingat', 'receipts.pendingnoprocess', 'receipts.rejectedby', 'receipts.rejectreceipt', 'receipts.rejectprompt', 'receipts.rejectwhy', 'receipts.rejectconfirm', 'receipts.rejected.done', 'receipts.rejectfailed', 'receipts.error.receipt_pending', 'receipts.error.receipt_rejected', 'receipts.error.receipt_registered', 'receipts.error.already_rejected', 'receipts.error.reject_reason_missing', 'receipts.error.process_id_taken', 'receipts.sent', 'receipts.process.direct', 'receipts.process.through', 'receipts.process.setup', 'receipts.process.name', 'receipts.process.stage.intake', 'receipts.process.stage.matching', 'receipts.process.stage.complete', 'receipts.process.done', 'receipts.process.failed', 'processroutes.subject.goods_receipt', 'processroutes.subject.goods_receipt.note') == 64
