-- 0294_receipt_matching_strings.sql
-- Decision 0652 — Warehouse Receipts, slice 3a: the Matching check, the AP
-- Receiving task, and fixing the lines of a receipt.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('receipts.register', 'en', 'Register'),
 ('receipts.register', 'de', 'Erfassen'),
 ('receipts.registered.done', 'en', 'Receipt {number} registered.'),
 ('receipts.registered.done', 'de', 'Wareneingang {number} erfasst.'),
 ('receipts.registerfailed', 'en', 'The receipt could not be registered.'),
 ('receipts.registerfailed', 'de', 'Der Wareneingang konnte nicht erfasst werden.'),
 ('receipts.col.check', 'en', 'Check'),
 ('receipts.col.check', 'de', 'Prüfung'),
 ('receipts.check.matched', 'en', 'Matched'),
 ('receipts.check.matched', 'de', 'Abgeglichen'),
 ('receipts.check.rejected', 'en', 'Rejected'),
 ('receipts.check.rejected', 'de', 'Abgelehnt'),
 ('receipts.check.attention', 'en', 'Needs attention'),
 ('receipts.check.attention', 'de', 'Prüfen'),
 ('receipts.fix.order', 'en', 'Order'),
 ('receipts.fix.order', 'de', 'Bestellung'),
 ('receipts.fix.line', 'en', 'Order line'),
 ('receipts.fix.line', 'de', 'Bestellposition'),
 ('receipts.fix.change', 'en', 'Change'),
 ('receipts.fix.change', 'de', 'Ändern'),
 ('receipts.fix.rejectline', 'en', 'Reject line'),
 ('receipts.fix.rejectline', 'de', 'Position ablehnen'),
 ('receipts.fix.rejectprompt', 'en', 'Why is line {line} rejected? It will never count.'),
 ('receipts.fix.rejectprompt', 'de', 'Warum wird Position {line} abgelehnt? Sie zählt nie.'),
 ('receipts.fixfailed', 'en', 'The line could not be changed.'),
 ('receipts.fixfailed', 'de', 'Die Position konnte nicht geändert werden.'),
 ('receipts.error.lines_need_attention', 'en', 'Some lines still need attention: fix or reject them first.'),
 ('receipts.error.lines_need_attention', 'de', 'Einige Positionen sind noch zu prüfen: Korrigieren oder lehnen Sie sie zuerst ab.'),
 ('receipts.error.no_lines_left', 'en', 'Every line is rejected: reject the receipt instead.'),
 ('receipts.error.no_lines_left', 'de', 'Alle Positionen sind abgelehnt: Lehnen Sie stattdessen den Wareneingang ab.'),
 ('receipts.error.line_not_found', 'en', 'The receipt has no such line.'),
 ('receipts.error.line_not_found', 'de', 'Der Wareneingang hat keine solche Position.'),
 ('receipts.error.line_rejected', 'en', 'That line is rejected.'),
 ('receipts.error.line_rejected', 'de', 'Diese Position ist abgelehnt.'),
 ('receipts.error.register_receipt', 'en', 'Register the receipt from its pop-out.'),
 ('receipts.error.register_receipt', 'de', 'Erfassen Sie den Wareneingang in seinem Fenster.'),
 ('receipts.process.teamname', 'en', 'AP Receiving'),
 ('receipts.process.teamname', 'de', 'Kreditoren Wareneingang'),
 ('receipts.process.team', 'en', 'Matching''s tasks go to the {team} team. Members: {n}.'),
 ('receipts.process.team', 'de', 'Aufgaben aus dem Abgleich gehen an das Team {team}. Mitglieder: {n}.');

