-- 0295_create_goods_receipts_strings.sql
-- Decision 0653 — Warehouse Receipts, slice 3b: Create brings goods
-- receipts in.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('create.gr.subtitle', 'en', 'Bring goods receipts and returns in yourself. A CSV is previewed before it is sent.'),
 ('create.gr.subtitle', 'de', 'Wareneingänge und Rücksendungen selbst erfassen. Eine CSV wird vor dem Senden angezeigt.'),
 ('create.kind', 'en', 'What to create'),
 ('create.kind', 'de', 'Was erstellen'),
 ('create.kind.invoices', 'en', 'Invoices'),
 ('create.kind.invoices', 'de', 'Rechnungen'),
 ('create.kind.receipts', 'en', 'Goods receipts'),
 ('create.kind.receipts', 'de', 'Wareneingänge'),
 ('create.gr.upload', 'en', 'Upload receipts (CSV)'),
 ('create.gr.upload', 'de', 'Wareneingänge hochladen (CSV)'),
 ('create.gr.keyreceipt', 'en', 'Key a receipt'),
 ('create.gr.keyreceipt', 'de', 'Wareneingang erfassen'),
 ('create.gr.keyreturn', 'en', 'Key a return'),
 ('create.gr.keyreturn', 'de', 'Rücksendung erfassen'),
 ('create.gr.direct', 'en', 'Goods receipts, registered at once'),
 ('create.gr.direct', 'de', 'Wareneingänge, sofort erfasst'),
 ('create.gr.drop', 'en', 'Drop a receipt CSV here'),
 ('create.gr.drop', 'de', 'Wareneingangs-CSV hier ablegen'),
 ('create.gr.dropsub', 'en', 'One row per receipt line, from your warehouse system. You see what it holds before anything is sent.'),
 ('create.gr.dropsub', 'de', 'Eine Zeile je Eingangsposition, aus Ihrem Lagersystem. Sie sehen den Inhalt, bevor etwas gesendet wird.'),
 ('create.gr.status.ready', 'en', 'Ready'),
 ('create.gr.status.ready', 'de', 'Bereit'),
 ('create.gr.status.attention', 'en', 'Lines needing attention at Matching: {n}'),
 ('create.gr.status.attention', 'de', 'Im Abgleich zu prüfende Positionen: {n}'),
 ('create.gr.status.skipped', 'en', 'Already loaded, skipped'),
 ('create.gr.status.skipped', 'de', 'Bereits geladen, übersprungen'),
 ('create.gr.status.refused', 'en', 'Rows refused: {n}'),
 ('create.gr.status.refused', 'de', 'Abgelehnte Zeilen: {n}'),
 ('create.gr.status.registered', 'en', 'Registered'),
 ('create.gr.status.registered', 'de', 'Erfasst'),
 ('create.gr.status.pending', 'en', 'Waiting at {n}'),
 ('create.gr.status.pending', 'de', 'Wartet in {n}'),
 ('create.gr.count.ready', 'en', 'Ready: {n}'),
 ('create.gr.count.ready', 'de', 'Bereit: {n}'),
 ('create.gr.count.attention', 'en', 'Need attention: {n}'),
 ('create.gr.count.attention', 'de', 'Zu prüfen: {n}'),
 ('create.gr.count.skipped', 'en', 'Skipped: {n}'),
 ('create.gr.count.skipped', 'de', 'Übersprungen: {n}'),
 ('create.gr.count.refused', 'en', 'Refused: {n}'),
 ('create.gr.count.refused', 'de', 'Abgelehnt: {n}'),
 ('create.gr.previewmeta', 'en', '{file} · Receipts: {n}'),
 ('create.gr.previewmeta', 'de', '{file} · Wareneingänge: {n}'),
 ('create.gr.colreceipt', 'en', 'Receipt'),
 ('create.gr.colreceipt', 'de', 'Wareneingang'),
 ('create.gr.colorders', 'en', 'Orders'),
 ('create.gr.colorders', 'de', 'Bestellungen'),
 ('create.gr.lineneeds', 'en', 'Line {line}: {why}'),
 ('create.gr.lineneeds', 'de', 'Position {line}: {why}'),
 ('create.gr.addsto', 'en', 'Adds lines to a receipt already on file'),
 ('create.gr.addsto', 'de', 'Ergänzt Positionen eines vorhandenen Wareneingangs'),
 ('create.gr.attentionhint', 'en', 'A receipt with lines needing attention is still sent. It waits at Matching, where AP Receiving fixes or rejects those lines.'),
 ('create.gr.attentionhint', 'de', 'Ein Wareneingang mit zu prüfenden Positionen wird trotzdem gesendet. Er wartet im Abgleich, wo der Wareneingang diese Positionen korrigiert oder ablehnt.'),
 ('create.gr.sendone', 'en', 'Send 1 receipt'),
 ('create.gr.sendone', 'de', '1 Wareneingang senden'),
 ('create.gr.sendn', 'en', 'Send {n} receipts'),
 ('create.gr.sendn', 'de', '{n} Wareneingänge senden'),
 ('create.gr.thisupload', 'en', 'This upload'),
 ('create.gr.thisupload', 'de', 'Dieser Upload'),
 ('create.gr.keyedhint', 'en', 'A receipt or return keyed here is checked as it is typed and registered at once.'),
 ('create.gr.keyedhint', 'de', 'Ein hier erfasster Wareneingang oder eine Rücksendung wird bei der Eingabe geprüft und sofort erfasst.'),
 ('create.gr.nothingyet', 'en', 'Choose a CSV to see what it holds before anything is sent.'),
 ('create.gr.nothingyet', 'de', 'Wählen Sie eine CSV, um ihren Inhalt zu sehen, bevor etwas gesendet wird.'),
 ('receipts.uploadincreate', 'en', 'Upload receipts'),
 ('receipts.uploadincreate', 'de', 'Wareneingänge hochladen');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('create.kind', 'create.kind.invoices', 'create.kind.receipts', 'create.gr.upload', 'create.gr.keyreceipt', 'create.gr.keyreturn', 'create.gr.direct', 'create.gr.drop', 'create.gr.dropsub', 'create.gr.status.ready', 'create.gr.status.attention', 'create.gr.status.skipped', 'create.gr.status.refused', 'create.gr.status.registered', 'create.gr.status.pending', 'create.gr.count.ready', 'create.gr.count.attention', 'create.gr.count.skipped', 'create.gr.count.refused', 'create.gr.previewmeta', 'create.gr.colreceipt', 'create.gr.colorders', 'create.gr.lineneeds', 'create.gr.addsto', 'create.gr.attentionhint', 'create.gr.sendone', 'create.gr.sendn', 'create.gr.thisupload', 'create.gr.keyedhint', 'create.gr.nothingyet', 'receipts.uploadincreate') == 62
