-- 0298_receipts_agents_strings.sql
-- Decision 0656 — Warehouse Receipts, slice 6: receipts in questions and
-- agents.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('agents.dataset.receipts', 'en', 'Goods receipts'),
 ('agents.dataset.receipts', 'de', 'Wareneingänge'),
 ('agents.col.receiptstate', 'en', 'Received'),
 ('agents.col.receiptstate', 'de', 'Eingang'),
 ('agents.col.receipt', 'en', 'Receipt'),
 ('agents.col.receipt', 'de', 'Wareneingang'),
 ('agents.col.receiptdate', 'en', 'Receipt date'),
 ('agents.col.receiptdate', 'de', 'Eingangsdatum'),
 ('agents.col.dayssincereceipt', 'en', 'Days since receipt'),
 ('agents.col.dayssincereceipt', 'de', 'Tage seit Eingang'),
 ('agents.col.movement', 'en', 'Movement'),
 ('agents.col.movement', 'de', 'Bewegung'),
 ('agents.col.value', 'en', 'Value'),
 ('agents.col.value', 'de', 'Wert'),
 ('agents.col.receiptstatus', 'en', 'Receipt status'),
 ('agents.col.receiptstatus', 'de', 'Status des Eingangs'),
 ('agents.col.linestatus', 'en', 'Line'),
 ('agents.col.linestatus', 'de', 'Position'),
 ('agents.col.dayswaiting', 'en', 'Days waiting'),
 ('agents.col.dayswaiting', 'de', 'Tage wartend'),
 ('agents.col.deliverynote', 'en', 'Delivery note'),
 ('agents.col.deliverynote', 'de', 'Lieferschein'),
 ('agents.col.recordedby', 'en', 'Recorded by'),
 ('agents.col.recordedby', 'de', 'Erfasst von'),
 ('agents.col.orderline', 'en', 'Order line'),
 ('agents.col.orderline', 'de', 'Bestellposition'),
 ('agents.col.notinvoiced', 'en', 'Not invoiced'),
 ('agents.col.notinvoiced', 'de', 'Nicht berechnet'),
 ('agents.col.oldestreceipt', 'en', 'Oldest receipt'),
 ('agents.col.oldestreceipt', 'de', 'Ältester Eingang'),
 ('agents.col.creditqty', 'en', 'Credit expected'),
 ('agents.col.creditqty', 'de', 'Erwartete Gutschrift'),
 ('agents.col.lastreturn', 'en', 'Last return'),
 ('agents.col.lastreturn', 'de', 'Letzte Rücksendung'),
 ('agents.qreceipt.not_received', 'en', 'Not received'),
 ('agents.qreceipt.not_received', 'de', 'Nicht eingegangen'),
 ('agents.qreceipt.partially_received', 'en', 'Partially received'),
 ('agents.qreceipt.partially_received', 'de', 'Teilweise eingegangen'),
 ('agents.qreceipt.fully_received', 'en', 'Fully received'),
 ('agents.qreceipt.fully_received', 'de', 'Vollständig eingegangen'),
 ('agents.qreceipt.over_received', 'en', 'Over-received'),
 ('agents.qreceipt.over_received', 'de', 'Mehr eingegangen als bestellt'),
 ('agents.qmovement.received', 'en', 'Received'),
 ('agents.qmovement.received', 'de', 'Eingang'),
 ('agents.qmovement.returned', 'en', 'Returned'),
 ('agents.qmovement.returned', 'de', 'Rücksendung'),
 ('agents.qreceiptstatus.registered', 'en', 'Registered'),
 ('agents.qreceiptstatus.registered', 'de', 'Erfasst'),
 ('agents.qreceiptstatus.pending', 'en', 'Pending'),
 ('agents.qreceiptstatus.pending', 'de', 'Ausstehend'),
 ('agents.qreceiptstatus.rejected', 'en', 'Rejected'),
 ('agents.qreceiptstatus.rejected', 'de', 'Abgelehnt'),
 ('agents.qreceiptstatus.cancelled', 'en', 'Cancelled'),
 ('agents.qreceiptstatus.cancelled', 'de', 'Storniert'),
 ('agents.qreceiptline.counted', 'en', 'Counted'),
 ('agents.qreceiptline.counted', 'de', 'Gezählt'),
 ('agents.qreceiptline.waiting', 'en', 'Waiting for its order'),
 ('agents.qreceiptline.waiting', 'de', 'Wartet auf Bestellung'),
 ('agents.qreceiptline.needs_attention', 'en', 'Needs attention'),
 ('agents.qreceiptline.needs_attention', 'de', 'Zu prüfen'),
 ('agents.qreceiptline.rejected', 'en', 'Rejected'),
 ('agents.qreceiptline.rejected', 'de', 'Abgelehnt'),
 ('agents.report.waiting_on_receipt', 'en', 'Invoices waiting on goods received'),
 ('agents.report.waiting_on_receipt', 'de', 'Rechnungen, die auf den Wareneingang warten'),
 ('agents.reporthint.waiting_on_receipt', 'en', 'Invoices held at a stage by an Awaiting receipt or Credit expected task for at least the days chosen, oldest first.'),
 ('agents.reporthint.waiting_on_receipt', 'de', 'Rechnungen, die mindestens die gewählten Tage durch eine Aufgabe für fehlenden Wareneingang oder erwartete Gutschrift an einer Stufe stehen, die ältesten zuerst.'),
 ('agents.report.received_not_invoiced', 'en', 'Received, not invoiced'),
 ('agents.report.received_not_invoiced', 'de', 'Wareneingang ohne Rechnung'),
 ('agents.reporthint.received_not_invoiced', 'en', 'Order lines whose goods are in but not yet invoiced, older than the days chosen, by supplier and valued at the order''s price.'),
 ('agents.reporthint.received_not_invoiced', 'de', 'Bestellpositionen, deren Ware eingegangen, aber noch nicht berechnet ist, älter als die gewählten Tage, nach Lieferant und zum Bestellpreis bewertet.'),
 ('agents.report.credit_still_owed', 'en', 'Credit still owed for goods returned'),
 ('agents.report.credit_still_owed', 'de', 'Ausstehende Gutschriften für Rücksendungen'),
 ('agents.reporthint.credit_still_owed', 'en', 'Order lines where goods went back after being invoiced and no credit note has come yet, valued at the order''s price.'),
 ('agents.reporthint.credit_still_owed', 'de', 'Bestellpositionen, deren Ware nach der Berechnung zurückging und für die noch keine Gutschrift kam, zum Bestellpreis bewertet.'),
 ('agents.example.invoices_waiting_goods.name', 'en', 'Invoices waiting on goods'),
 ('agents.example.invoices_waiting_goods.name', 'de', 'Rechnungen, die auf Ware warten'),
 ('agents.example.invoices_waiting_goods.words', 'en', 'Every working day at 9am, invoices held for three days or more because the goods are not in yet.'),
 ('agents.example.invoices_waiting_goods.words', 'de', 'An jedem Arbeitstag um 9 Uhr Rechnungen, die seit drei Tagen oder länger stehen, weil die Ware noch nicht eingegangen ist.'),
 ('agents.example.grni_ageing.name', 'en', 'Goods received, not invoiced, over 30 days'),
 ('agents.example.grni_ageing.name', 'de', 'Ware eingegangen, nicht berechnet, über 30 Tage'),
 ('agents.example.grni_ageing.words', 'en', 'Every Monday at 8am, order lines received more than 30 days ago and not yet invoiced, by supplier.'),
 ('agents.example.grni_ageing.words', 'de', 'Jeden Montag um 8 Uhr Bestellpositionen, die vor mehr als 30 Tagen eingegangen und noch nicht berechnet sind, nach Lieferant.'),
 ('agents.example.credit_owed.name', 'en', 'Credit still owed'),
 ('agents.example.credit_owed.name', 'de', 'Ausstehende Gutschriften'),
 ('agents.example.credit_owed.words', 'en', 'Every Monday at 8am, goods returned after invoicing with no credit note yet.'),
 ('agents.example.credit_owed.words', 'de', 'Jeden Montag um 8 Uhr Ware, die nach der Berechnung zurückging und noch keine Gutschrift hat.'),
 ('agents.example.receipt_lines_waiting.name', 'en', 'Receipt lines waiting for their order'),
 ('agents.example.receipt_lines_waiting.name', 'de', 'Eingangspositionen, die auf ihre Bestellung warten'),
 ('agents.example.receipt_lines_waiting.words', 'en', 'Every working day at 9am, goods receipt lines waiting more than 7 days for their purchase order to be loaded.'),
 ('agents.example.receipt_lines_waiting.words', 'de', 'An jedem Arbeitstag um 9 Uhr Eingangspositionen, die seit mehr als 7 Tagen darauf warten, dass ihre Bestellung geladen wird.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('agents.dataset.receipts', 'agents.col.receiptstate', 'agents.col.receipt', 'agents.col.receiptdate', 'agents.col.dayssincereceipt', 'agents.col.movement', 'agents.col.value', 'agents.col.receiptstatus', 'agents.col.linestatus', 'agents.col.dayswaiting', 'agents.col.deliverynote', 'agents.col.recordedby', 'agents.col.orderline', 'agents.col.notinvoiced', 'agents.col.oldestreceipt', 'agents.col.creditqty', 'agents.col.lastreturn', 'agents.qreceipt.not_received', 'agents.qreceipt.partially_received', 'agents.qreceipt.fully_received', 'agents.qreceipt.over_received', 'agents.qmovement.received', 'agents.qmovement.returned', 'agents.qreceiptstatus.registered', 'agents.qreceiptstatus.pending', 'agents.qreceiptstatus.rejected', 'agents.qreceiptstatus.cancelled', 'agents.qreceiptline.counted', 'agents.qreceiptline.waiting', 'agents.qreceiptline.needs_attention', 'agents.qreceiptline.rejected', 'agents.report.waiting_on_receipt', 'agents.reporthint.waiting_on_receipt', 'agents.report.received_not_invoiced', 'agents.reporthint.received_not_invoiced', 'agents.report.credit_still_owed', 'agents.reporthint.credit_still_owed', 'agents.example.invoices_waiting_goods.name', 'agents.example.invoices_waiting_goods.words', 'agents.example.grni_ageing.name', 'agents.example.grni_ageing.words', 'agents.example.credit_owed.name', 'agents.example.credit_owed.words', 'agents.example.receipt_lines_waiting.name', 'agents.example.receipt_lines_waiting.words') == 90
