-- 0300_receipt_timeline_strings.sql
-- Decision 0658 — a goods receipt's Timeline and Chat, with the Warehouse.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('receipts.tl.heading', 'en', 'Timeline and conversation'),
 ('receipts.tl.heading', 'de', 'Verlauf und Unterhaltung'),
 ('receipts.tl.someone', 'en', 'Someone'),
 ('receipts.tl.someone', 'de', 'Jemand'),
 ('receipts.tl.aroute', 'en', 'a route'),
 ('receipts.tl.aroute', 'de', 'eine Route'),
 ('receipts.tl.received.file', 'en', '{by} loaded it from a file, {lines} lines.'),
 ('receipts.tl.received.file', 'de', '{by} hat ihn aus einer Datei geladen, {lines} Positionen.'),
 ('receipts.tl.received.screen', 'en', '{by} recorded it on the screen, {lines} lines.'),
 ('receipts.tl.received.screen', 'de', '{by} hat ihn am Bildschirm erfasst, {lines} Positionen.'),
 ('receipts.tl.received.message', 'en', 'It came in by {source}, message {message}, from {by}: {lines} lines.'),
 ('receipts.tl.received.message', 'de', 'Er kam über {source}, Nachricht {message}, von {by}: {lines} Positionen.'),
 ('receipts.tl.stopped', 'en', 'Stopped at {stage}: a task for {team} to check its lines.'),
 ('receipts.tl.stopped', 'de', 'Bei {stage} angehalten: eine Aufgabe für {team}, die Positionen zu prüfen.'),
 ('receipts.tl.claimed', 'en', '{by} claimed the task.'),
 ('receipts.tl.claimed', 'de', '{by} hat die Aufgabe übernommen.'),
 ('receipts.tl.released', 'en', '{by} released the task.'),
 ('receipts.tl.released', 'de', '{by} hat die Aufgabe freigegeben.'),
 ('receipts.tl.reassigned', 'en', '{by} reassigned the task.'),
 ('receipts.tl.reassigned', 'de', '{by} hat die Aufgabe neu zugewiesen.'),
 ('receipts.tl.linecorrected', 'en', '{by} corrected line {line} from {from} to {to}.'),
 ('receipts.tl.linecorrected', 'de', '{by} hat Position {line} von {from} auf {to} korrigiert.'),
 ('receipts.tl.linerepointed', 'en', '{by} pointed line {line} at order line {to}, from {from}.'),
 ('receipts.tl.linerepointed', 'de', '{by} hat Position {line} der Bestellposition {to} zugeordnet, vorher {from}.'),
 ('receipts.tl.linerejected', 'en', '{by} rejected line {line}: {reason}'),
 ('receipts.tl.linerejected', 'de', '{by} hat Position {line} abgelehnt: {reason}'),
 ('receipts.tl.linescounted', 'en', 'Held-back lines counted when {by} loaded {orders}: {lines}.'),
 ('receipts.tl.linescounted', 'de', 'Zurückgehaltene Positionen gezählt, als {by} {orders} geladen hat: {lines}.'),
 ('receipts.tl.linesmatched', 'en', 'Lines that found their order when {by} loaded {orders}: {lines}.'),
 ('receipts.tl.linesmatched', 'de', 'Positionen, die ihre Bestellung fanden, als {by} {orders} geladen hat: {lines}.'),
 ('receipts.tl.registered.register', 'en', '{by} registered it.'),
 ('receipts.tl.registered.register', 'de', '{by} hat ihn erfasst.'),
 ('receipts.tl.registered.order', 'en', 'Registered when {by} loaded {orders}.'),
 ('receipts.tl.registered.order', 'de', 'Erfasst, als {by} {orders} geladen hat.'),
 ('receipts.tl.registered.recorded', 'en', 'Registered when it was recorded.'),
 ('receipts.tl.registered.recorded', 'de', 'Beim Erfassen gebucht.'),
 ('receipts.tl.registered.matched', 'en', 'Registered: every line matched.'),
 ('receipts.tl.registered.matched', 'de', 'Erfasst: jede Position passte.'),
 ('receipts.tl.registered.partial', 'en', 'Lines waiting for their order stay held back.'),
 ('receipts.tl.registered.partial', 'de', 'Positionen, die auf ihre Bestellung warten, bleiben zurückgehalten.'),
 ('receipts.tl.rejected', 'en', '{by} rejected it: {reason}'),
 ('receipts.tl.rejected', 'de', '{by} hat ihn abgelehnt: {reason}'),
 ('receipts.tl.cancelled', 'en', '{by} cancelled it: {reason}'),
 ('receipts.tl.cancelled', 'de', '{by} hat ihn storniert: {reason}'),
 ('receipts.tl.added.user', 'en', '{by} added {name} to the conversation.'),
 ('receipts.tl.added.user', 'de', '{by} hat {name} zur Unterhaltung hinzugefügt.'),
 ('receipts.tl.added.team', 'en', '{by} added the team {name} to the conversation.'),
 ('receipts.tl.added.team', 'de', '{by} hat das Team {name} zur Unterhaltung hinzugefügt.'),
 ('receipts.tl.removed.user', 'en', '{by} removed {name} from the conversation.'),
 ('receipts.tl.removed.user', 'de', '{by} hat {name} aus der Unterhaltung entfernt.'),
 ('receipts.tl.removed.team', 'en', '{by} removed the team {name} from the conversation.'),
 ('receipts.tl.removed.team', 'de', '{by} hat das Team {name} aus der Unterhaltung entfernt.'),
 ('receipts.tl.placeholder', 'en', 'Write to everyone in this conversation. They are emailed.'),
 ('receipts.tl.placeholder', 'de', 'An alle in dieser Unterhaltung schreiben. Sie erhalten eine E-Mail.'),
 ('receipts.tl.post', 'en', 'Post'),
 ('receipts.tl.post', 'de', 'Senden'),
 ('receipts.tl.addpeople', 'en', 'Add a person or team'),
 ('receipts.tl.addpeople', 'de', 'Person oder Team hinzufügen'),
 ('receipts.tl.searchpeople', 'en', 'Search people and teams'),
 ('receipts.tl.searchpeople', 'de', 'Personen und Teams suchen'),
 ('receipts.tl.teammembers', 'en', 'Team, {n} people'),
 ('receipts.tl.teammembers', 'de', 'Team, {n} Personen'),
 ('receipts.tl.teamchip', 'en', '{name} (team, {n})'),
 ('receipts.tl.teamchip', 'de', '{name} (Team, {n})'),
 ('receipts.tl.needspermission', 'en', 'Needs Warehouse.Collaborate to open receipts'),
 ('receipts.tl.needspermission', 'de', 'Braucht Warehouse.Collaborate, um Wareneingänge zu öffnen'),
 ('receipts.tl.nomatches', 'en', 'Nobody matches.'),
 ('receipts.tl.nomatches', 'de', 'Keine Treffer.'),
 ('receipts.tl.remove', 'en', 'Remove'),
 ('receipts.tl.remove', 'de', 'Entfernen'),
 ('receipts.tl.nobody', 'en', 'Only AP is in this conversation.'),
 ('receipts.tl.nobody', 'de', 'Nur AP ist in dieser Unterhaltung.'),
 ('receipts.tl.nobodyhint', 'en', 'Add the Warehouse, or anyone else, to sort out what arrived.'),
 ('receipts.tl.nobodyhint', 'de', 'Fügen Sie das Lager oder andere hinzu, um zu klären, was eingegangen ist.'),
 ('receipts.tl.loading', 'en', 'Loading…'),
 ('receipts.tl.loading', 'de', 'Wird geladen …'),
 ('receipts.tl.empty', 'en', 'Nothing has happened yet.'),
 ('receipts.tl.empty', 'de', 'Noch ist nichts geschehen.'),
 ('receipts.tl.failed', 'en', 'The timeline could not be loaded.'),
 ('receipts.tl.failed', 'de', 'Der Verlauf konnte nicht geladen werden.'),
 ('receipts.tl.postfailed', 'en', 'The message could not be posted.'),
 ('receipts.tl.postfailed', 'de', 'Die Nachricht konnte nicht gesendet werden.'),
 ('receipts.tl.addfailed', 'en', 'They could not be added.'),
 ('receipts.tl.addfailed', 'de', 'Hinzufügen war nicht möglich.'),
 ('receipts.tl.removefailed', 'en', 'They could not be removed.'),
 ('receipts.tl.removefailed', 'de', 'Entfernen war nicht möglich.'),
 ('receipts.tl.emailed', 'en', 'Emailed: {n}.'),
 ('receipts.tl.emailed', 'de', 'Per E-Mail benachrichtigt: {n}.'),
 ('receipts.error.cannot_see', 'en', '{name} could not open this receipt. Give them Warehouse.Collaborate first.'),
 ('receipts.error.cannot_see', 'de', '{name} könnte diesen Wareneingang nicht öffnen. Geben Sie zuerst Warehouse.Collaborate.'),
 ('receipts.error.cannot_manage', 'en', 'Adding or removing people needs AP.Receive where this receipt''s orders are.'),
 ('receipts.error.cannot_manage', 'de', 'Personen hinzufügen oder entfernen braucht AP.Receive dort, wo die Bestellungen dieses Eingangs sind.'),
 ('receipts.error.comment_empty', 'en', 'Write something to post.'),
 ('receipts.error.comment_empty', 'de', 'Schreiben Sie etwas.'),
 ('receipts.error.comment_too_long', 'en', 'A message is at most 4000 characters.'),
 ('receipts.error.comment_too_long', 'de', 'Eine Nachricht hat höchstens 4000 Zeichen.'),
 ('receipts.conversations.subtitle', 'en', 'Goods receipts AP asked you to help with.'),
 ('receipts.conversations.subtitle', 'de', 'Wareneingänge, bei denen AP Sie um Hilfe gebeten hat.'),
 ('receipts.conversations.heading', 'en', 'Receipts you are in a conversation about'),
 ('receipts.conversations.heading', 'de', 'Wareneingänge, zu denen Sie in einer Unterhaltung sind'),
 ('receipts.conversations.help', 'en', 'AP added you, or a team you are in, to these receipts to help sort out what arrived. Open one to see what happened to it and to write to AP.'),
 ('receipts.conversations.help', 'de', 'AP hat Sie oder ein Team, in dem Sie sind, zu diesen Wareneingängen hinzugefügt, um zu klären, was eingegangen ist. Öffnen Sie einen, um zu sehen, was geschah, und AP zu schreiben.'),
 ('receipts.conversations.none', 'en', 'You have not been added to any receipt yet.'),
 ('receipts.conversations.none', 'de', 'Sie wurden noch zu keinem Wareneingang hinzugefügt.');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('receipts.tl.heading', 'receipts.tl.someone', 'receipts.tl.aroute', 'receipts.tl.received.file', 'receipts.tl.received.screen', 'receipts.tl.received.message', 'receipts.tl.stopped', 'receipts.tl.claimed', 'receipts.tl.released', 'receipts.tl.reassigned', 'receipts.tl.linecorrected', 'receipts.tl.linerepointed', 'receipts.tl.linerejected', 'receipts.tl.linescounted', 'receipts.tl.linesmatched', 'receipts.tl.registered.register', 'receipts.tl.registered.order', 'receipts.tl.registered.recorded', 'receipts.tl.registered.matched', 'receipts.tl.registered.partial', 'receipts.tl.rejected', 'receipts.tl.cancelled', 'receipts.tl.added.user', 'receipts.tl.added.team', 'receipts.tl.removed.user', 'receipts.tl.removed.team', 'receipts.tl.placeholder', 'receipts.tl.post', 'receipts.tl.addpeople', 'receipts.tl.searchpeople', 'receipts.tl.teammembers', 'receipts.tl.teamchip', 'receipts.tl.needspermission', 'receipts.tl.nomatches', 'receipts.tl.remove', 'receipts.tl.nobody', 'receipts.tl.nobodyhint', 'receipts.tl.loading', 'receipts.tl.empty', 'receipts.tl.failed', 'receipts.tl.postfailed', 'receipts.tl.addfailed', 'receipts.tl.removefailed', 'receipts.tl.emailed', 'receipts.error.cannot_see', 'receipts.error.cannot_manage', 'receipts.error.comment_empty', 'receipts.error.comment_too_long', 'receipts.conversations.subtitle', 'receipts.conversations.heading', 'receipts.conversations.help', 'receipts.conversations.none') == 104
