-- 0304_timeline_entry_labels.sql
-- Decision 0675 — the Timeline's system entries: each kind's bold label.

INSERT INTO ui_strings (key, locale, value) VALUES
 ('timeline.label.received', 'en', 'Received'),
 ('timeline.label.received', 'de', 'Eingegangen'),
 ('timeline.label.erp_export', 'en', 'Exported'),
 ('timeline.label.erp_export', 'de', 'Exportiert'),
 ('timeline.label.rule_fired', 'en', 'Rule fired'),
 ('timeline.label.rule_fired', 'de', 'Regel ausgelöst'),
 ('timeline.label.stopped', 'en', 'Needs checking'),
 ('timeline.label.stopped', 'de', 'Prüfung nötig'),
 ('timeline.label.return', 'en', 'Returned'),
 ('timeline.label.return', 'de', 'Zurückgegeben'),
 ('timeline.label.return_to_supplier', 'en', 'Returned to supplier'),
 ('timeline.label.return_to_supplier', 'de', 'An Lieferanten zurückgesandt'),
 ('timeline.label.chase', 'en', 'Chased'),
 ('timeline.label.chase', 'de', 'Nachgefasst'),
 ('timeline.label.remind', 'en', 'Reminder'),
 ('timeline.label.remind', 'de', 'Erinnerung'),
 ('timeline.label.erp_export_undone', 'en', 'Export undone'),
 ('timeline.label.erp_export_undone', 'de', 'Export rückgängig'),
 ('timeline.label.stage_completed', 'en', 'Stage completed'),
 ('timeline.label.stage_completed', 'de', 'Stufe abgeschlossen'),
 ('timeline.label.registered', 'en', 'Registered'),
 ('timeline.label.registered', 'de', 'Gebucht'),
 ('timeline.label.lines_released', 'en', 'Lines released'),
 ('timeline.label.lines_released', 'de', 'Positionen freigegeben'),
 ('timeline.label.receipt_closed', 'en', 'Goods arrived'),
 ('timeline.label.receipt_closed', 'de', 'Ware eingegangen'),
 ('timeline.label.email_failed', 'en', 'Email failed'),
 ('timeline.label.email_failed', 'de', 'E-Mail fehlgeschlagen'),
 ('timeline.label.discard', 'en', 'Discarded'),
 ('timeline.label.discard', 'de', 'Verworfen'),
 ('timeline.label.line_rejected', 'en', 'Line rejected'),
 ('timeline.label.line_rejected', 'de', 'Position abgelehnt'),
 ('timeline.label.rejected', 'en', 'Rejected'),
 ('timeline.label.rejected', 'de', 'Abgelehnt'),
 ('timeline.label.cancelled', 'en', 'Cancelled'),
 ('timeline.label.cancelled', 'de', 'Storniert'),
 ('timeline.label.claim', 'en', 'Claimed'),
 ('timeline.label.claim', 'de', 'Übernommen'),
 ('timeline.label.release', 'en', 'Released'),
 ('timeline.label.release', 'de', 'Freigegeben'),
 ('timeline.label.reassign', 'en', 'Reassigned'),
 ('timeline.label.reassign', 'de', 'Neu zugewiesen'),
 ('timeline.label.route_to_approver', 'en', 'Routed'),
 ('timeline.label.route_to_approver', 'de', 'Weitergeleitet'),
 ('timeline.label.po_link', 'en', 'Order linked'),
 ('timeline.label.po_link', 'de', 'Bestellung verknüpft'),
 ('timeline.label.po_pair', 'en', 'Line paired'),
 ('timeline.label.po_pair', 'de', 'Position zugeordnet'),
 ('timeline.label.line_corrected', 'en', 'Line corrected'),
 ('timeline.label.line_corrected', 'de', 'Position korrigiert'),
 ('timeline.label.line_repointed', 'en', 'Line moved'),
 ('timeline.label.line_repointed', 'de', 'Position umgehängt'),
 ('timeline.label.collaborator_added', 'en', 'Person added'),
 ('timeline.label.collaborator_added', 'de', 'Person hinzugefügt'),
 ('timeline.label.collaborator_removed', 'en', 'Person removed'),
 ('timeline.label.collaborator_removed', 'de', 'Person entfernt');

-- ASSERT: SELECT count(*) FROM ui_strings WHERE key IN ('timeline.label.received', 'timeline.label.erp_export', 'timeline.label.rule_fired', 'timeline.label.stopped', 'timeline.label.return', 'timeline.label.return_to_supplier', 'timeline.label.chase', 'timeline.label.remind', 'timeline.label.erp_export_undone', 'timeline.label.stage_completed', 'timeline.label.registered', 'timeline.label.lines_released', 'timeline.label.receipt_closed', 'timeline.label.email_failed', 'timeline.label.discard', 'timeline.label.line_rejected', 'timeline.label.rejected', 'timeline.label.cancelled', 'timeline.label.claim', 'timeline.label.release', 'timeline.label.reassign', 'timeline.label.route_to_approver', 'timeline.label.po_link', 'timeline.label.po_pair', 'timeline.label.line_corrected', 'timeline.label.line_repointed', 'timeline.label.collaborator_added', 'timeline.label.collaborator_removed') == 56
