#!/usr/bin/env python3
"""Regenerates the hybrid-PDF test fixtures for decision 0042.

Builds genuine PDF files (correct xref tables, real object structure,
real Flate compression) rather than hand-stubbed approximations — the
module under test parses actual PDF structure, so a fake would prove
nothing. The result is base64-encoded into a .ts module so the bytes
survive bundling, the same reason migrations are imported via ?raw.

    python3 scripts/build-pdf-fixtures.py

Requires nothing beyond the standard library.
"""
import base64
import os
import zlib

OUT_DIR = "workers/vf-app/test/fixtures"

UBL = b"""<?xml version="1.0" encoding="UTF-8"?>
<Invoice xmlns="urn:oasis:names:specification:ubl:schema:xsd:Invoice-2"
         xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2"
         xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2">
  <cbc:ID>ZUGFERD-2026-001</cbc:ID>
  <cbc:IssueDate>2026-09-02</cbc:IssueDate>
  <cbc:DocumentCurrencyCode>EUR</cbc:DocumentCurrencyCode>
  <cac:AccountingSupplierParty><cac:Party><cac:PartyTaxScheme>
    <cbc:CompanyID>DE900800700</cbc:CompanyID>
  </cac:PartyTaxScheme></cac:Party></cac:AccountingSupplierParty>
  <cac:LegalMonetaryTotal>
    <cbc:TaxInclusiveAmount currencyID="EUR">1190.00</cbc:TaxInclusiveAmount>
  </cac:LegalMonetaryTotal>
  <cac:InvoiceLine>
    <cbc:ID>1</cbc:ID>
    <cbc:InvoicedQuantity>2</cbc:InvoicedQuantity>
    <cbc:LineExtensionAmount currencyID="EUR">1000.00</cbc:LineExtensionAmount>
  </cac:InvoiceLine>
</Invoice>"""


def assemble(objs):
    out = bytearray(b"%PDF-1.7\n")
    offsets = []
    for i, body in enumerate(objs, start=1):
        offsets.append(len(out))
        out += f"{i} 0 obj\n".encode() + body + b"\nendobj\n"
    xref = len(out)
    out += f"xref\n0 {len(objs) + 1}\n".encode() + b"0000000000 65535 f \n"
    for off in offsets:
        out += f"{off:010d} 00000 n \n".encode()
    out += f"trailer\n<< /Size {len(objs) + 1} /Root 1 0 R >>\nstartxref\n{xref}\n%%EOF\n".encode()
    return bytes(out)


def with_attachment(name, payload, compress):
    data = zlib.compress(payload) if compress else payload
    filt = b"/Filter /FlateDecode " if compress else b""
    # PDF name escapes, exactly as real Factur-X producers emit them:
    # the filename never appears literally in the file.
    escaped = name.replace("-", r"\055").replace(".", r"\056").encode()
    return assemble([
        b"<< /Type /Catalog /Pages 2 0 R /Names << /EmbeddedFiles 5 0 R >> >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] >>",
        b"<< /Type /EmbeddedFile " + filt + b"/Length " + str(len(data)).encode()
        + b" >>\nstream\n" + data + b"\nendstream",
        b"<< /Names [ (" + escaped + b") << /Type /Filespec /F (" + escaped
        + b") /EF << /F 4 0 R >> >> ] >>",
    ])


def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    fixtures = {
        "facturx-plain.pdf": with_attachment("factur-x.xml", UBL, compress=False),
        "facturx-compressed.pdf": with_attachment("factur-x.xml", UBL, compress=True),
        "attachment-not-xml.pdf": with_attachment("readme.txt", b"just a note, not an invoice", compress=False),
        "plain-no-attachment.pdf": assemble([
            b"<< /Type /Catalog /Pages 2 0 R >>",
            b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
            b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] >>",
        ]),
    }

    lines = [
        "// Real PDF files, base64-encoded so the bytes survive bundling.",
        "// Generated by scripts/build-pdf-fixtures.py — do not hand-edit.",
        "",
    ]
    for filename, data in sorted(fixtures.items()):
        with open(os.path.join(OUT_DIR, filename), "wb") as fh:
            fh.write(data)
        const = filename.replace(".pdf", "").replace("-", "_").upper()
        b64 = base64.b64encode(data).decode()
        lines.append(f"export const {const}_B64 =")
        for i in range(0, len(b64), 100):
            lines.append(f'  "{b64[i:i + 100]}" +')
        lines[-1] = lines[-1][:-2] + ";"
        lines.append("")
    lines += [
        "export function decodePdf(b64: string): Uint8Array {",
        "  const binary = atob(b64);",
        "  const out = new Uint8Array(binary.length);",
        "  for (let i = 0; i < binary.length; i++) out[i] = binary.charCodeAt(i);",
        "  return out;",
        "}",
    ]
    with open(os.path.join(OUT_DIR, "pdf-fixtures.ts"), "w") as fh:
        fh.write("\n".join(lines) + "\n")
    print(f"wrote {len(fixtures)} fixtures + pdf-fixtures.ts to {OUT_DIR}")


if __name__ == "__main__":
    main()
