#!/usr/bin/env python3
"""Fixtures for decision 0683: reading an ordinary PDF.

Two genuine PDFs of the same small invoice:

- a **digital** one, as accounting software exports it, with a text layer
  (reportlab);
- a **scanned** one, a picture of the page and no text at all, as a
  scanner or phone app produces it (PIL draws the page, saves it as a
  JPEG-in-PDF).

Base64-encoded into a .ts module so the bytes survive bundling.

    python3 scripts/build-pdf-read-fixtures.py

Requires reportlab and Pillow.
"""
import base64, io
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from PIL import Image, ImageDraw, ImageFont

OUT = "workers/vf-app/test/fixtures/pdf-read-fixtures.ts"
LINES = [
    "Northwind Packaging Ltd",
    "VAT GB123456789",
    "INVOICE  INV-7781",
    "Issue date 2026-10-01   Due 2026-10-31",
    "Bill to: Acme UK Ltd",
    "Courier service, same-day     3 x 25.00     75.00",
    "Pallet wrap                    2 x 12.50     25.00",
    "Net 100.00   VAT 20.00   Total GBP 120.00",
]

def digital():
    buf = io.BytesIO()
    c = canvas.Canvas(buf, pagesize=A4)
    y = 800
    for line in LINES:
        c.drawString(60, y, line)
        y -= 24
    c.showPage(); c.save()
    return buf.getvalue()

def scanned():
    img = Image.new("L", (620, 420), 255)
    d = ImageDraw.Draw(img)
    try:
        font = ImageFont.truetype("DejaVuSans.ttf", 16)
    except OSError:
        font = ImageFont.load_default()
    y = 20
    for line in LINES:
        d.text((20, y), line, fill=0, font=font)
        y += 44
    buf = io.BytesIO()
    img.save(buf, "PDF", resolution=72, quality=70)
    return buf.getvalue()

def chunk(name, data):
    b = base64.b64encode(data).decode()
    parts = [b[i:i+100] for i in range(0, len(b), 100)]
    return f"export const {name} =\n  " + " +\n  ".join(f'"{p}"' for p in parts) + ";\n"

with open(OUT, "w") as fh:
    fh.write("// Real PDF files for decision 0683, base64-encoded so the bytes survive bundling.\n")
    fh.write("// Generated by scripts/build-pdf-read-fixtures.py — do not hand-edit.\n\n")
    fh.write(chunk("DIGITAL_INVOICE_PDF_B64", digital()) + "\n")
    fh.write(chunk("SCANNED_INVOICE_PDF_B64", scanned()))
print("wrote", OUT)
